### ISSUE TITLE
Indents Go Beyond Indent Guides When LaTeX-Workshop Is Enabled

### ISSUE THREAD

**Issue by Arszilla** [James-Yu/LaTeX-Workshop#1959] opened 2020-02-22 23:35 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: No

## Describe the bug [Required]

I have written majority of my LaTeX code in Vim and since then I have moved on to VSCode. Before installing the plugin, this is how my indents worked (for my `.tex`):

![EHBTbbGXYX](https://user-images.githubusercontent.com/22989170/75100752-21217780-55e3-11ea-8120-111f9c3b8d83.gif)

You can see that the piece of text I write matches the amount of indent guides. But when I have `LaTeX-Workshop` toggled on, this is what happens:

![5eADbw9f1S](https://user-images.githubusercontent.com/22989170/75100817-fc79cf80-55e3-11ea-82c3-2e92c53adc55.gif)

The indents don't match the document's overall look and goes beyond the actual amount of spaces. Do note that both `editor.insertSpaces` and `editor.detectIndentation` are set to true/enabled.

### To Reproduce
Just use the default VSCode settings (for everything) as well as default `LaTeX-Workshop`

### Expected behavior
Indents should match the document's overall behavior.

## Logs [Required]
N/A

### LaTeX Workshop Output [Required]

```
[01:44:00] Initializing LaTeX Workshop.
[01:44:00] Creating file watcher for .pdf files.
[01:44:00] Creating LaTeX Workshop http and websocket server.
[01:44:00] LaTeX Workshop initialized.
[01:44:00] Server created on 127.0.0.1:35025
[01:44:00] Snippet data loaded.
[01:44:00] LaTeX Workshop version: 8.7.2
[01:44:00] Found files that might be root, choose the first one: /home/arszilla/Documents/Mathematics/2019-2020/Spring/Diferansiyel Geometri II/Diferansiyel Geometri II.tex,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Fonksiyonel Analiz/Fonksiyonel Analiz.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Analiz III/Teori/Analiz III - Teori.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Analiz III/Uygulama/Analiz III - Uygulama.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Integral Calculus/Application/Integral Calculus - Application.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Introduction to Topology/Theory/Introduction to Topology - Theory.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Introduction to Topology/Application/Introduction to Topology - Application.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Differential Geometry I/Theory/Differential Geometry I - Theory.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Differential Geometry I/Application/Differential Geometry I - Application.tex,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Partial Differential Equations/Theory/Partial Differential Equations - Theory.tex,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Partial Differential Equations/Application/Partial Differential Equations - Application.tex,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Analiz IV/Teori/Analiz IV - Teori.tex,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Analiz IV/Uygulama/Analiz IV - Uygulama.tex
[01:44:00] Root file changed from: undefined to /home/arszilla/Documents/Mathematics/2019-2020/Spring/Diferansiyel Geometri II/Diferansiyel Geometri II.tex. Find all dependencies.
[01:44:00] Instantiating a new file watcher for /home/arszilla/Documents/Mathematics/2019-2020/Spring/Diferansiyel Geometri II/Diferansiyel Geometri II.tex
[01:44:00] Creating file watcher for .bib files.
[01:44:00] Parsing /home/arszilla/Documents/Mathematics/2019-2020/Spring/Diferansiyel Geometri II/Diferansiyel Geometri II.tex
[01:44:00] Adding /home/arszilla/Documents/Mathematics/2019-2020/Spring/Diferansiyel Geometri II/Diferansiyel Geometri II.tex to file watcher.
[01:44:02] Found root file from active editor: /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex
[01:44:02] Root file changed from: /home/arszilla/Documents/Mathematics/2019-2020/Spring/Diferansiyel Geometri II/Diferansiyel Geometri II.tex to /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex. Find all dependencies.
[01:44:02] Root file changed -> cleaning up old file watcher.
[01:44:02] Instantiating a new file watcher for /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex
[01:44:02] Parsing /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex
[01:44:02] Adding /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex to file watcher.
[01:44:58] File watcher: responding to change in /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex
[01:44:58] Parsing /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex
[01:44:58] /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex changed. Auto build project.
[01:44:58] BUILD command invoked.
[01:44:58] Building root file: /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex
[01:44:58] Build root file /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex
[01:44:58] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz
[01:44:58] LaTeX build process spawned. PID: 427367.
[01:44:58] LaTeX log parsed with 17 messages.
[01:44:58] Recipe of length 1 finished. PID: 427367.
[01:44:58] Successfully built /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex.
[01:44:58] No PDF viewer connected for /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.pdf
[01:44:58] Parse fls file.
[01:45:39] File watcher: /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex deleted.
[01:45:39] Deleted /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex was root - triggering root search
[01:45:39] Found files that might be root, choose the first one: /home/arszilla/Documents/Mathematics/2019-2020/Spring/Diferansiyel Geometri II/Diferansiyel Geometri II.tex,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Fonksiyonel Analiz/Fonksiyonel Analiz.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Analiz III/Uygulama/Analiz III - Uygulama.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Analiz III/Teori/Analiz III - Teori.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Introduction to Topology/Theory/Introduction to Topology - Theory.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Differential Geometry I/Theory/Differential Geometry I - Theory.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Integral Calculus/Application/Integral Calculus - Application.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Introduction to Topology/Application/Introduction to Topology - Application.tex,/home/arszilla/Documents/Mathematics/2019-2020/Fall/Differential Geometry I/Application/Differential Geometry I - Application.tex,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Partial Differential Equations/Theory/Partial Differential Equations - Theory.tex,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Analiz IV/Teori/Analiz IV - Teori.tex,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Partial Differential Equations/Application/Partial Differential Equations - Application.tex,/home/arszilla/Documents/Mathematics/2019-2020/Spring/Analiz IV/Uygulama/Analiz IV - Uygulama.tex
[01:45:39] Root file changed from: /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex to /home/arszilla/Documents/Mathematics/2019-2020/Spring/Diferansiyel Geometri II/Diferansiyel Geometri II.tex. Find all dependencies.
[01:45:39] Root file changed -> cleaning up old file watcher.
[01:45:39] Instantiating a new file watcher for /home/arszilla/Documents/Mathematics/2019-2020/Spring/Diferansiyel Geometri II/Diferansiyel Geometri II.tex
[01:45:39] Parsing /home/arszilla/Documents/Mathematics/2019-2020/Spring/Diferansiyel Geometri II/Diferansiyel Geometri II.tex
[01:45:39] Adding /home/arszilla/Documents/Mathematics/2019-2020/Spring/Diferansiyel Geometri II/Diferansiyel Geometri II.tex to file watcher.
[01:45:43] Found root file from active editor: /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex
[01:45:43] Found root file from active editor: /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex
[01:45:43] Root file changed from: /home/arszilla/Documents/Mathematics/2019-2020/Spring/Diferansiyel Geometri II/Diferansiyel Geometri II.tex to /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex. Find all dependencies.
[01:45:43] Root file changed -> cleaning up old file watcher.
[01:45:43] Instantiating a new file watcher for /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex
[01:45:43] Parsing /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex
[01:45:43] Root file remains unchanged from: /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex.
[01:45:43] Adding /home/arszilla/Documents/Mathematics/2019-2020/Spring/Reel Analiz/Reel Analiz.tex to file watcher.
[02:29:13] LOG command invoked.

```

### Developer Tools Console [Required]
N/A

## Desktop [Required]
 - OS: Kali Linux 2020.1
 - VS Code version: 1.42.1
 - Extension version: 8.7.2
 - TeX distribution version: TeX Live 2019

**Comment by jlelong** [comment] 2020-02-26 10:29
The extension changes indentation based on the `\begin` and `\end` keywords
https://github.com/James-Yu/LaTeX-Workshop/blob/c48365a3de08a4faa9b2ea99eba2e4cd8125cfd5/syntax/syntax.json#L26-L29

I cannot reproduce the issue and I do not think this is related to the extension.  Post a MWE if you believe it is.

**Comment by Arszilla** [comment] 2020-03-01 00:55
May I ask what MWE is? I can upload my plugins and their settings via Settings Sync and a sample of my LaTeX documents for you to try so you might be able to replicate it?

**Comment by jlelong** [comment] 2020-03-01 06:47
A MWE is a minimal working example to reproduce the issue. Can you upload a minimal `.tex` file to reproduce the issue? Your settings would also be helpful. I assume you tried to disable all other extensions and it did not change a thing. So no need of your other plugins.

**Comment by Arszilla** [comment] 2020-03-05 07:46
Weird, now on a newly generated `.tex`, I cannot replicate the issue. The issue persisted on all my previous `.tex`; despite when I deleted everything in the folder beside the `.tex`s. I'll try to replicate this issue again on my Windows later this weekend and submit a new reply with an update.

**Comment by jlelong** [comment] 2020-03-09 08:03
It may be related to the way VSCode detects indentation https://code.visualstudio.com/docs/editor/codebasics#_indentation.

I am closing this issue as it is most likely not related to the extension. Feel free to reopen if you have new information.

**Closed by jlelong** 2020-03-09 08:03 UTC
Labels: need more info
