### ISSUE TITLE
Using @( and tapping does not jump out of the \left( \right) properly

### ISSUE THREAD

**Issue by nijan18** [James-Yu/LaTeX-Workshop#1820] opened 2019-11-19 23:59 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes (but the problem is not about compiling)

## Describe the bug [Required]

When using the snippet @( in math mode and clicking tap you will jump inside \left( \right) which works fine. But when you are done, click tap, and want to jump out, you only jump right before the final parentheses  and not all the way out (see gif below). 
![bug](https://user-images.githubusercontent.com/45998209/69196511-02689c00-0b2f-11ea-8b79-c33d2d8d01ee.gif)

### To Reproduce

1. Create a LaTeX file
2. Go into math mode (I have tesed \begin{equation}, \begin{align} and $$)
3. Use the snippet @( and click tap
4. Write a expression, when done tap out.
5. See the bug

### Expected behavior

Expected to tap all the way out of "\left(   \right)"

## Logs [Required]

Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[00:47:09] Initializing LaTeX Workshop.
[00:47:09] Creating LaTeX Workshop http and websocket server.
[00:47:09] LaTeX Workshop initialized.
[00:47:09] Found root file from active editor: /Users/USER/Desktop/test/test/test.tex
[00:47:09] Root file changed from: undefined to /Users/USER/Desktop/test/test/test.tex. Find all dependencies.
[00:47:09] Instantiating a new file watcher for /Users/USER/Desktop/test/test/test.tex
[00:47:09] Creating file watcher for .bib files.
[00:47:09] Parsing /Users/USER/Desktop/test/test/test.tex
[00:47:09] Parsing /Users/USER/Documents/Skoleting/SDU/Latex/Template/preamble.tex
[00:47:09] Server created on 127.0.0.1:50682
[00:47:09] Adding /Users/USER/Desktop/test/test/test.tex to file watcher.
[00:47:09] Adding /Users/USER/Documents/Skoleting/SDU/Latex/Template/preamble.tex to file watcher.
[00:47:09] LaTeX Workshop version: 8.4.1
[00:47:09] Snippet data loaded.
[00:49:50] LOG command invoked.
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools. Paste anything suspicious.

[Paste the log here]
Nothing suspicious.



## Screenshots
See gif.




## Desktop [Required]
 - OS: macOS Catalina version 10.15.1
 - VS Code version: 1.40.1
 - Extension version: 8.4.1




## Additional questions

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 5.0.0]

### Additional context

Add any other context about the problem here.

**Comment by trevorgunn** [comment] 2019-11-20 00:26
This is a duplicate of #1423. There isn't anything we can do because the last `)` is provided by VSCode's auto-completion of bracket pairs and not by the snippet.

**Closed** 2019-11-20 05:28 UTC
