### ISSUE TITLE
sync tex view pdf does not hightlight the sentence

### ISSUE THREAD

**Issue by loneboy** [James-Yu/LaTeX-Workshop#324] opened 2017-11-21 06:21 UTC
### How to reproduce

1.  When I synctex the pdf viewer, it moves correctly, but it does not highlight the sentence. 
2. 
3. 

### Expected behavior

Many pdf view highlight the pdf text which correspond to the editor. 
This is perfect extension. but it is only problem.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

**Comment by James-Yu** [comment] 2017-11-21 07:11
Duplicate of #315

**Closed by James-Yu** 2017-11-21 07:11 UTC
