### ISSUE TITLE
[BUG or FEATURE] AutoCompletion for packages loaded from classes

### ISSUE THREAD

**Issue by funnym0nk3y** [James-Yu/LaTeX-Workshop#1982] opened 2020-03-08 02:16 UTC
I'm using version 8.7.2. 

My document structure consists of a class which loads most packages through the `\RequirePackage` macro. To give a concrete example: 
root-file -> class-file -> my graphics package -> subcaption

When I include the subcaption package directly via `\usepackage` the autocompletion suggests me the command `\DeclareCaptionLabelFormat`. But when I use the structure above no such suggestion is made. I don't know if that behavior is intentional or not, but I would be very happy if suggestions from `\RequirePackage` are included. Writing classes and own packages would be much easier.

**Comment by tamuratak** [comment] 2020-03-08 02:19
Fill out all the information required in the issue template. Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

Thank you for your cooperation.

**Comment by funnym0nk3y** [comment] 2020-03-08 13:37
Issue still exists when disabeling all other extensions. 
Starting a fresh instance of code gives following log:
```
[14:27:50] Initializing LaTeX Workshop.
[14:27:50] Creating file watcher for .pdf files.
[14:27:51] Creating LaTeX Workshop http and websocket server.
[14:27:51] LaTeX Workshop initialized.
[14:27:51] Linter for root file started.
[14:27:51] No root file found for linting.
[14:27:51] Found root file from active editor: c:\Users\Michael\Google Drive\Studium\Vorlagen\latex-package-example\thesis.tex
[14:27:51] Root file changed from: undefined to c:\Users\Michael\Google Drive\Studium\Vorlagen\latex-package-example\thesis.tex. Find all dependencies.
[14:27:51] Instantiating a new file watcher for c:\Users\Michael\Google Drive\Studium\Vorlagen\latex-package-example\thesis.tex
[14:27:51] Creating file watcher for .bib files.
[14:27:51] Parsing c:\Users\Michael\Google Drive\Studium\Vorlagen\latex-package-example\thesis.tex
[14:27:51] Server created on 127.0.0.1:49527
[14:27:51] Adding c:\Users\Michael\Google Drive\Studium\Vorlagen\latex-package-example\thesis.tex to file watcher.
[14:27:51] LaTeX Workshop version: 8.7.2
[14:27:51] Snippet data loaded.
[14:27:54] Linter for active file started.
[14:27:54] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m
```

I have read the wiki.

This is the behavior when including he package directly: 

![direct](https://user-images.githubusercontent.com/41870754/76163566-70b98480-6147-11ea-8aaa-d1352855bc8d.gif)

And the log-file:
```
[14:13:46] Linter for active file started.
[14:13:46] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:13:46] Found root file from active editor: c:\Users\Michael\Google Drive\Studium\Vorlagen\latex-package-example\thesis.tex
[14:13:46] Root file remains unchanged from: c:\Users\Michael\Google Drive\Studium\Vorlagen\latex-package-example\thesis.tex.
[14:13:47] Linter for active file successfully finished in 0s 777ms
[14:13:47] Linter log parsed with 0 messages.
[14:13:48] Linter for active file started.
[14:13:48] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:13:49] Linter for active file successfully finished in 0s 845ms
[14:13:49] Linter log parsed with 0 messages.
[14:13:50] Linter for active file started.
[14:13:50] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:13:50] Linter for active file successfully finished in 0s 745ms
[14:13:50] Linter log parsed with 1 messages.
[14:13:55] Linter for active file started.
[14:13:55] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:13:55] Cannot parse c:\Users\Michael\Google Drive\Studium\Vorlagen\latex-package-example\thesis.tex: Fall back to regex-based completion.
[14:13:55] Linter for active file successfully finished in 0s 729ms
[14:13:55] Linter log parsed with 2 messages.
```

When I remove all the `\usepackage` commands (the packages are included in the class file via `\RequirePackage`and delete all the auxilliary files, rebuild the project, the result is as follows: 

![indirect](https://user-images.githubusercontent.com/41870754/76163681-998e4980-6148-11ea-85ff-238553a3551e.gif)

And the log: 
```
[14:21:59] LOG command invoked.
[14:22:04] Linter for active file started.
[14:22:04] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:22:04] Found root file from active editor: c:\Users\Michael\Google Drive\Studium\Vorlagen\latex-package-example\thesis.tex
[14:22:04] Root file remains unchanged from: c:\Users\Michael\Google Drive\Studium\Vorlagen\latex-package-example\thesis.tex.
[14:22:05] Linter for active file successfully finished in 0s 633ms
[14:22:05] Linter log parsed with 0 messages.
[14:22:06] Linter for active file started.
[14:22:06] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:22:07] Linter for active file successfully finished in 0s 677ms
[14:22:07] Linter log parsed with 0 messages.
[14:22:07] Linter for active file started.
[14:22:07] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:22:08] Linter for active file successfully finished in 0s 665ms
[14:22:08] Linter log parsed with 1 messages.
[14:22:09] Linter for active file started.
[14:22:09] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:22:10] Linter for active file successfully finished in 0s 652ms
[14:22:10] Linter log parsed with 1 messages.
[14:22:13] Linter for active file started.
[14:22:13] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:22:14] Linter for active file successfully finished in 0s 656ms
[14:22:14] Linter log parsed with 1 messages.
[14:22:28] Linter for active file started.
[14:22:28] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:22:29] Linter for active file successfully finished in 0s 743ms
[14:22:29] Linter log parsed with 0 messages.
[14:22:34] Linter for active file started.
[14:22:34] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:22:35] Linter for active file successfully finished in 0s 733ms
[14:22:35] Linter log parsed with 1 messages.
[14:22:37] Linter for active file started.
[14:22:37] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n24,-I0,-f%f:%l:%c:%d:%k:%n:%m

[14:22:38] Linter for active file successfully finished in 0s 765ms
[14:22:38] Linter log parsed with 1 messages.
```

**Comment by jlelong** [comment] 2020-03-08 21:16
Duplicate of #1178.

**Closed by jlelong** 2020-03-08 21:16 UTC
Labels: need more info
