### ISSUE TITLE
"Cannot find LaTeX root file" error occurs - not importing anything

### ISSUE THREAD

**Issue by rkingan** [James-Yu/LaTeX-Workshop#2378] opened 2020-11-18 14:59 UTC
## Preliminary questions

I recently installed LaTeX Workshop in Visual Studio. I am on Windows 10 and have TeX Live installed. I cannot build any files - I consistently get the error message "Cannot find LaTeX root file". This is for a simple test file with no imports.

### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

As mentioned above - every build fails with "Cannot find LaTeX root file."

### To Reproduce

1. Go to 'TeX' menu
2. Click on 'Build LaTeX project' (any option)
3. See error "Cannot find LaTeX root file." 

### Expected behavior

For the option I have been using, pdflatex should be run on the file in the editor. I have also tried with latexmk and got the same result.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[09:46:02] Initializing LaTeX Workshop.
[09:46:02] Extension root: c:\Users\rkingan\.vscode\extensions\james-yu.latex-workshop-8.13.2
[09:46:02] Creating PDF file watcher.
[09:46:02] Creating LaTeX Workshop http and websocket server.
[09:46:02] LaTeX Workshop initialized.
[09:46:02] Current workspace folders: ["file:///c:/Users/rkingan/Documents/dev/doc/temp"]
[09:46:02] Current workspaceRootDir: c:\Users\rkingan\Documents\dev\doc\temp
[09:46:02] Server created on 127.0.0.1:53867
[09:46:02] Snippet data loaded.
[09:46:02] LaTeX Workshop version: 8.13.2
[09:46:29] RECIPES command invoked.
[09:46:29] BUILD command invoked.
[09:46:29] Current workspace folders: ["file:///c:/Users/rkingan/Documents/dev/doc/temp"]
[09:46:29] Current workspaceRootDir: c:\Users\rkingan\Documents\dev\doc\temp
[09:46:29] Found root file from active editor: c:\Users\rkingan\Documents\dev\doc\temp\test.ltx
[09:46:29] Root file changed: from undefined to c:\Users\rkingan\Documents\dev\doc\temp\test.ltx
[09:46:29] Start to find all dependencies.
[09:46:29] Instantiating a new file watcher for c:\Users\rkingan\Documents\dev\doc\temp\test.ltx
[09:46:29] Creating Bib file watcher.
[09:46:29] Parsing a file and its subfiles: c:\Users\rkingan\Documents\dev\doc\temp\test.ltx
[09:46:29] Parse fls file.
[09:46:29] Cannot find fls file: c:\Users\rkingan\Documents\dev\doc\temp\test.fls
[09:46:29] Cannot find LaTeX root file.
[09:46:29] Added to file watcher: c:\Users\rkingan\Documents\dev\doc\temp\test.ltx
[09:46:34] LOG command invoked.
[09:48:51] Current workspace folders: ["file:///c:/Users/rkingan/Documents/dev/doc/temp"]
[09:48:51] Current workspaceRootDir: c:\Users\rkingan\Documents\dev\doc\temp
[09:48:51] Found root file from active editor: c:\Users\rkingan\Documents\dev\doc\temp\test.ltx
[09:48:51] Keep using the same root file: c:\Users\rkingan\Documents\dev\doc\temp\test.ltx.
[09:51:17] Current workspace folders: ["file:///c:/Users/rkingan/Documents/dev/doc/temp"]
[09:51:17] Current workspaceRootDir: c:\Users\rkingan\Documents\dev\doc\temp
[09:51:17] Found root file from active editor: c:\Users\rkingan\Documents\dev\doc\temp\test.ltx
[09:51:17] Keep using the same root file: c:\Users\rkingan\Documents\dev\doc\temp\test.ltx.
[09:51:25] RECIPES command invoked.
[09:51:25] BUILD command invoked.
[09:51:25] Current workspace folders: ["file:///c:/Users/rkingan/Documents/dev/doc/temp"]
[09:51:25] Current workspaceRootDir: c:\Users\rkingan\Documents\dev\doc\temp
[09:51:25] Found root file from active editor: c:\Users\rkingan\Documents\dev\doc\temp\test.ltx
[09:51:25] Keep using the same root file: c:\Users\rkingan\Documents\dev\doc\temp\test.ltx.
[09:51:25] Cannot find LaTeX root file.
[09:53:56] RECIPES command invoked.
[09:53:56] BUILD command invoked.
[09:53:56] Current workspace folders: ["file:///c:/Users/rkingan/Documents/dev/doc/temp"]
[09:53:56] Current workspaceRootDir: c:\Users\rkingan\Documents\dev\doc\temp
[09:53:56] Found root file from active editor: c:\Users\rkingan\Documents\dev\doc\temp\test.ltx
[09:53:56] Keep using the same root file: c:\Users\rkingan\Documents\dev\doc\temp\test.ltx.
[09:53:56] Cannot find LaTeX root file.
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

(nothing there)
```

## Desktop [Required]
 - OS: Windows 10
 - VS Code version: 1.51.1
 - Extension version: 8.14.0
 - TeX distribution version: TeX Live 2020

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

I tried this with MikTeX before uninstalling it and replacing it with TeX Live and got the same error.

**Comment by jlelong** [comment] 2020-11-18 15:01
> `Found root file from active editor: c:\Users\rkingan\Documents\dev\doc\temp\test.ltx``

Use the `.tex` extension.

**Comment by jlelong** [comment] 2020-11-18 15:02
Duplicate of #2361.

**Closed by jlelong** 2020-11-18 15:02 UTC
