### ISSUE TITLE
Errors Aren't Displayed In The Problem Pane Anymore?

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#852] opened 2018-10-08 00:23 UTC
### Description

Compilation errors are no longer displayed in the problems pane view.
### Log messages
I couldn't find log messages for this. How can I troubleshoot/debug it?
<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce
1. Open LaTeX Directory anywhere on Windows 10
2. Compile any latex file with errors
3. Notice that errors aren't shown in the problems view 

### Expected behavior

Errors should appear in problems as it used to earlier. I think it's quite some time this is broken now.
### Actual behavior

![image](https://user-images.githubusercontent.com/32885386/46588753-f5920180-ca6e-11e8-8031-82d48a7d7473.png)

### Additional Information
I'm using Windows 10 and vscode insiders with the latest latex extension. 

cc @James-Yu 
cc @jlelong

**Comment by James-Yu** [comment] 2018-10-08 01:46
Mine works well 10 seconds ago. May you please share your log messages and/or project?

**Comment by Astrantia** [comment] 2018-10-08 01:56
@James-Yu 
I think this might be related with custom output dir again, let me test.

**Comment by Astrantia** [comment] 2018-10-08 01:57
Yeah, no need to debug and troubleshoot further. @James-Yu It doesn't respect custom output dir.

**Comment by Astrantia** [comment] 2018-10-08 02:03
```
"latex-workshop.latex.outputDir": "./dist"
"latex-workshop.latex.tools": [
    {
      "name": "latexmk",
      "command": "latexmk",
      "args": ["-synctex=1", "-interaction=nonstopmode", "-file-line-error", "-pdf", "%DOC%", "-output-directory=dist"]
    }
]
```

**Comment by Astrantia** [comment] 2018-10-08 05:33
@James-Yu Were you able to reproduce this?

**Comment by James-Yu** [comment] 2018-10-08 05:34
I'm yet to find a time to sit down and turn to this project. Soon (TM).

**Comment by James-Yu** [comment] 2018-10-08 06:06
Unfortunately, I cannot reproduce the problem given your settings above. I'm afraid a minimal working example is required for further debugging.

**Comment by jlelong** [comment] 2018-10-08 06:45
Can you post the LaTeX compiler output from the output pane? This might be related to item 3 [here](https://github.com/James-Yu/LaTeX-Workshop/issues/796#issuecomment-421534832).

**Comment by Astrantia** [comment] 2018-10-08 06:59
@jlelong 
<summary>
Latexmk: This is Latexmk, John Collins, 7 August 2018, version: 4.59.
Latexmk: making output directory 'dist'
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="dist"  "c:\Users\User\Desktop\Math\test\testnest\Week5\Week5.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6800 64-bit)
entering extended mode
(c:/Users/User/Desktop/Math/test/testnest/Week5/Week5.tex
LaTeX2e <2018-04-01> patch level 5

(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\scrartcl.
cls
Document Class: scrartcl 2018/03/30 v3.25 KOMA-Script document class (article)

(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\scrkbase.
sty
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\scrbase.s
ty ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\keyval.sty")
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\scrlfile.
sty)))
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\tocbasic.
sty)
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\scrsize11
pt.clo)
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\typearea.
sty)) ("C:\Program Files\MiKTeX 2.9\tex\latex\base\fontenc.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\t1enc.def"))
("C:\Program Files\MiKTeX 2.9\tex\generic\babel\babel.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\babel\switch.def")
*************************************
* Local config file bblopts.cfg used
*
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\arabi\bblopts.cfg)
("C:\Program Files\MiKTeX 2.9\tex\latex\babel-english\english.ldf"
("C:\Program Files\MiKTeX 2.9\tex\generic\babel\babel.def"
("C:\Program Files\MiKTeX 2.9\tex\generic\babel\txtbabel.def"))))
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsmath.sty"
For additional information on amsmath, use the `?' option.
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amstext.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsgen.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsbsy.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsopn.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\amscls\amsthm.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\amssymb.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\amsfonts.sty"))
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\doublestroke\dsfont.s
ty)
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\physics\physics.sty
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\l3packages\xparse\xpa
rse.sty
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\l3kernel\expl3.sty
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\l3kernel\expl3-code.t
ex)
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\l3kernel\l3pdfmode.de
f)))
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\big ' for the command '\@quantity' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\Big ' for the command '\@quantity' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\bigg ' for the command '\@quantity' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\Bigg ' for the command '\@quantity' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\big ' for the command '\@braces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\Big ' for the command '\@braces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\bigg ' for the command '\@braces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\Bigg ' for the command '\@braces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\big ' for the command '\fbraces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\Big ' for the command '\fbraces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\bigg ' for the command '\fbraces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\Bigg ' for the command '\fbraces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\ket ' for the command '\bra' should be a single
* character.
*************************************************
)
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\enumitem\enumitem.sty
) ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphicx.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphics.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\trig.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics-cfg\graphics.cfg")
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics-def\pdftex.def")))
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\cases\cases.sty)
("C:\Program Files\MiKTeX 2.9\tex\latex\geometry\geometry.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifpdf.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifvtex.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\ifxetex\ifxetex.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\geometry\geometry.cfg"))
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\sectsty\sectsty.sty)

Class scrartcl Warning: Usage of package `fancyhdr' together
(scrartcl)              with a KOMA-Script class is not recommended.
(scrartcl)              I'd suggest to use 
(scrartcl)              package `scrlayer' or `scrlayer-scrpage', because
(scrartcl)              they support KOMA-Script classes.
(scrartcl)              With `fancyhdr' several features of class `scrartcl'
(scrartcl)              like options `headsepline', `footsepline' or command
(scrartcl)              `\MakeMarkcase' and the commands `\setkomafont' and
(scrartcl)              `\addtokomafont' for the page style elements need
(scrartcl)              explicite user intervention to work.
(scrartcl)              Nevertheless, using requested
(scrartcl)              package `fancyhdr' on input line 13.


(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\fancyhdr\fancyhdr.sty
) (c:\Users\User\Desktop\Math\test\testnest\Week5\dist\Week5.aux)
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\context\base\supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) ("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\epstopdf-base.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\infwarerr.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\grfext.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\kvdefinekeys.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ltxcmds.sty")))
("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\kvoptions.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\kvsetkeys.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\etexcmds.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifluatex.sty"))))
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\pdftexcmds.sty"))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
("C:\Program Files\MiKTeX 2.9\tex\latex\base\t1cmss.fd")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\umsa.fd")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\umsb.fd") [1{C:/Users/User
/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]

Class scrartcl Warning: incompatible usage of \@ssect detected.
(scrartcl)              You've used the KOMA-Script implementation of \@ssect
(scrartcl)              from within a non compatible caller, that does not
(scrartcl)              \scr@s@ct@@nn@m@ locally.
(scrartcl)              This could result in several error messages on input li
ne 71.


Underfull \hbox (badness 10000) in paragraph at lines 75--76


Underfull \hbox (badness 10000) in paragraph at lines 78--79

[2]
Underfull \hbox (badness 10000) in paragraph at lines 152--153

[3]
Underfull \hbox (badness 10000) in paragraph at lines 196--198


Underfull \hbox (badness 10000) in paragraph at lines 196--198

[4]
Underfull \hbox (badness 10000) in paragraph at lines 217--218


Underfull \hbox (badness 10000) in paragraph at lines 223--224


(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\doublestroke\udsrom.f
d) [5] [6]
(c:\Users\User\Desktop\Math\test\testnest\Week5\dist\Week5.aux) )
(see the transcript file for additional information) <C:\Users\User\AppDa
ta\Local\MiKTeX\2.9\fonts\pk\ljfour\jknappen\ec\dpi600\ecbx1095.pk> <C:\Users\Q
er\AppData\Local\MiKTeX\2.9\fonts\pk\ljfour\jknappen\ec\dpi600\eccc1440.
pk> <C:\Users\User\AppData\Local\MiKTeX\2.9\fonts\pk\ljfour\jknappen\ec\d
pi600\ecrm1095.pk> <C:\Users\User\AppData\Local\MiKTeX\2.9\fonts\pk\ljfou
r\jknappen\ec\dpi600\ecrm1440.pk> <C:\Users\User\AppData\Local\MiKTeX\2.9
\fonts\pk\ljfour\jknappen\ec\dpi600\ecrm2074.pk> <C:\Users\User\AppData\L
ocal\MiKTeX\2.9\fonts\pk\ljfour\jknappen\ec\dpi600\eccc1095.pk><C:/Program File
s/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmex10.pfb><C:/Program Files/MiKTeX
 2.9/fonts/type1/public/amsfonts/cm/cmmi10.pfb><C:/Program Files/MiKTeX 2.9/fon
ts/type1/public/amsfonts/cm/cmmi6.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/
public/amsfonts/cm/cmmi8.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/am
sfonts/cm/cmr10.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm
/cmr6.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmr8.pfb>
<C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmsy10.pfb><C:/Prog
ram Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmsy8.pfb><C:/Users/usern
ion/AppData/Roaming/MiKTeX/2.9/fonts/type1/public/doublestroke/dsrom10.pfb><C:/
Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/symbols/msam10.pfb>
Output written on c:\Users\User\Desktop\Math\test\testnest\Week5\dist\
Week5.pdf (6 pages, 162390 bytes).
SyncTeX written on c:\Users\User\Desktop\Math\test\testnest\Week5\dist\Week5.synctex.gz.
Transcript written on c:\Users\User\Desktop\Math\test\testnest\Week5\d
ist\Week5.log.
Latexmk: Log file says output to 'dist/Week5.pdf'
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'dist/Week5.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="dist"  "c:\Users\User\Desktop\Math\test\testnest\Week5\Week5.tex"'
------------
=== TeX engine is 'pdfTeX'
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6800 64-bit)
entering extended mode
(c:/Users/User/Desktop/Math/test/testnest/Week5/Week5.tex
LaTeX2e <2018-04-01> patch level 5

(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\scrartcl.
cls
Document Class: scrartcl 2018/03/30 v3.25 KOMA-Script document class (article)

(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\scrkbase.
sty
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\scrbase.s
ty ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\keyval.sty")
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\scrlfile.
sty)))
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\tocbasic.
sty)
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\scrsize11
pt.clo)
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\koma-script\typearea.
sty)) ("C:\Program Files\MiKTeX 2.9\tex\latex\base\fontenc.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\t1enc.def"))
("C:\Program Files\MiKTeX 2.9\tex\generic\babel\babel.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\babel\switch.def")
*************************************
* Local config file bblopts.cfg used
*
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\arabi\bblopts.cfg)
("C:\Program Files\MiKTeX 2.9\tex\latex\babel-english\english.ldf"
("C:\Program Files\MiKTeX 2.9\tex\generic\babel\babel.def"
("C:\Program Files\MiKTeX 2.9\tex\generic\babel\txtbabel.def"))))
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsmath.sty"
For additional information on amsmath, use the `?' option.
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amstext.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsgen.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsbsy.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsmath\amsopn.sty"))
("C:\Program Files\MiKTeX 2.9\tex\latex\amscls\amsthm.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\amssymb.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\amsfonts.sty"))
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\doublestroke\dsfont.s
ty)
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\physics\physics.sty
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\l3packages\xparse\xpa
rse.sty
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\l3kernel\expl3.sty
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\l3kernel\expl3-code.t
ex)
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\l3kernel\l3pdfmode.de
f)))
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\big ' for the command '\@quantity' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\Big ' for the command '\@quantity' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\bigg ' for the command '\@quantity' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\Bigg ' for the command '\@quantity' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\big ' for the command '\@braces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\Big ' for the command '\@braces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\bigg ' for the command '\@braces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\Bigg ' for the command '\@braces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\big ' for the command '\fbraces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\Big ' for the command '\fbraces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\bigg ' for the command '\fbraces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\Bigg ' for the command '\fbraces' should be a single
* character.
*************************************************
*************************************************
* LaTeX warning: "xparse/not-single-char"
* 
* Argument delimiter '\ket ' for the command '\bra' should be a single
* character.
*************************************************
)
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\enumitem\enumitem.sty
) ("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphicx.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\graphics.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics\trig.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics-cfg\graphics.cfg")
("C:\Program Files\MiKTeX 2.9\tex\latex\graphics-def\pdftex.def")))
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\cases\cases.sty)
("C:\Program Files\MiKTeX 2.9\tex\latex\geometry\geometry.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifpdf.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifvtex.sty")
("C:\Program Files\MiKTeX 2.9\tex\generic\ifxetex\ifxetex.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\geometry\geometry.cfg"))
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\sectsty\sectsty.sty)

Class scrartcl Warning: Usage of package `fancyhdr' together
(scrartcl)              with a KOMA-Script class is not recommended.
(scrartcl)              I'd suggest to use 
(scrartcl)              package `scrlayer' or `scrlayer-scrpage', because
(scrartcl)              they support KOMA-Script classes.
(scrartcl)              With `fancyhdr' several features of class `scrartcl'
(scrartcl)              like options `headsepline', `footsepline' or command
(scrartcl)              `\MakeMarkcase' and the commands `\setkomafont' and
(scrartcl)              `\addtokomafont' for the page style elements need
(scrartcl)              explicite user intervention to work.
(scrartcl)              Nevertheless, using requested
(scrartcl)              package `fancyhdr' on input line 13.


(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\fancyhdr\fancyhdr.sty
) (c:\Users\User\Desktop\Math\test\testnest\Week5\dist\Week5.aux)
(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\context\base\supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) ("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\epstopdf-base.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\infwarerr.sty")
("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\grfext.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\kvdefinekeys.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ltxcmds.sty")))
("C:\Program Files\MiKTeX 2.9\tex\latex\oberdiek\kvoptions.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\kvsetkeys.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\etexcmds.sty"
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\ifluatex.sty"))))
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\pdftexcmds.sty"))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
("C:\Program Files\MiKTeX 2.9\tex\latex\base\t1cmss.fd")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\umsa.fd")
("C:\Program Files\MiKTeX 2.9\tex\latex\amsfonts\umsb.fd") [1{C:/Users/User
on/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]

Class scrartcl Warning: incompatible usage of \@ssect detected.
(scrartcl)              You've used the KOMA-Script implementation of \@ssect
(scrartcl)              from within a non compatible caller, that does not
(scrartcl)              \scr@s@ct@@nn@m@ locally.
(scrartcl)              This could result in several error messages on input li
ne 71.


Underfull \hbox (badness 10000) in paragraph at lines 75--76


Underfull \hbox (badness 10000) in paragraph at lines 78--79

[2]
Underfull \hbox (badness 10000) in paragraph at lines 152--153

[3]
Underfull \hbox (badness 10000) in paragraph at lines 196--198


Underfull \hbox (badness 10000) in paragraph at lines 196--198

[4]
Underfull \hbox (badness 10000) in paragraph at lines 217--218


Underfull \hbox (badness 10000) in paragraph at lines 223--224


(C:\Users\User\AppData\Roaming\MiKTeX\2.9\tex\latex\doublestroke\udsrom.f
d) [5] [6]
(c:\Users\User\Desktop\Math\test\testnest\Week5\dist\Week5.aux) )
(see the transcript file for additional information) <C:\Users\User\AppDa
ta\Local\MiKTeX\2.9\fonts\pk\ljfour\jknappen\ec\dpi600\ecbx1095.pk> <C:\Users\Q
er\AppData\Local\MiKTeX\2.9\fonts\pk\ljfour\jknappen\ec\dpi600\eccc1440.
pk> <C:\Users\User\AppData\Local\MiKTeX\2.9\fonts\pk\ljfour\jknappen\ec\d
pi600\ecrm1095.pk> <C:\Users\User\AppData\Local\MiKTeX\2.9\fonts\pk\ljfou
r\jknappen\ec\dpi600\ecrm1440.pk> <C:\Users\User\AppData\Local\MiKTeX\2.9
\fonts\pk\ljfour\jknappen\ec\dpi600\ecrm2074.pk> <C:\Users\User\AppData\L
ocal\MiKTeX\2.9\fonts\pk\ljfour\jknappen\ec\dpi600\eccc1095.pk><C:/Program File
s/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmex10.pfb><C:/Program Files/MiKTeX
 2.9/fonts/type1/public/amsfonts/cm/cmmi10.pfb><C:/Program Files/MiKTeX 2.9/fon
ts/type1/public/amsfonts/cm/cmmi6.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/
public/amsfonts/cm/cmmi8.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/am
sfonts/cm/cmr10.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm
/cmr6.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmr8.pfb>
<C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmsy10.pfb><C:/Prog
ram Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmsy8.pfb><C:/Users/usern
ion/AppData/Roaming/MiKTeX/2.9/fonts/type1/public/doublestroke/dsrom10.pfb><C:/
Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/symbols/msam10.pfb>
Output written on c:\Users\User\Desktop\Math\test\testnest\Week5\dist\
Week5.pdf (6 pages, 162390 bytes).
SyncTeX written on c:\Users\User\Desktop\Math\test\testnest\Week5\dist\Week5.synctex.gz.
Transcript written on c:\Users\User\Desktop\Math\test\testnest\Week5\d
ist\Week5.log.
Latexmk: Log file says output to 'dist/Week5.pdf'
=== TeX engine is 'pdfTeX'
Latexmk: All targets (dist/Week5.pdf) are up-to-date

</summary>

**Comment by Astrantia** [comment] 2018-10-08 07:04
The issue is only when I have custom output directory settings turned on. It works fine if the build path is just `./`

**Comment by jlelong** [comment] 2018-10-08 07:12
Your `latexmk` log is hard wrapped at 80 characters, which should not be. Can you just change the recipe to run `pdflatex --max_print_line=10000` and compare the output (this time, lines should not broken) and the problems pane?
Yet I don't understand why it works when the build path is `./`.

**Comment by jlelong** [comment] 2018-10-08 07:40
I would like to but the problem only occurs on Windows with some versions of Miktex and I am running OS X. So it is a bit tricky

@Astrantia, can you give the output of `pdflatex --version`?
@James-Yu, same question

I am thinking about going from the environment variable approach to the `--max-print-line` option for recent versions of Miktex. Need help to figure out the version in which it was changed.

**Comment by Astrantia** [comment] 2018-10-08 07:46
Thanks @jlelong 
Here's version
```
pdflatex: warning: running with administrator privileges
MiKTeX-pdfTeX 2.9.6668 (1.40.19) (MiKTeX 2.9.6800 64-bit)
Copyright (C) 1982 D. E. Knuth, (C) 1996-2018 Han The Thanh
TeX is a trademark of the American Mathematical Society.
using bzip2 version 1.0.6, 6-Sept-2010
compiled with curl version 7.56.1; using libcurl/7.56.1 WinSSL
compiled with expat version 2.2; using expat_2.2.0
compiled with jpeg version 9.2
compiled with liblzma version 50020032; using 50020032
compiled with libpng version 1.6.34; using 1.6.34
compiled with libressl version LibreSSL 2.5.3; using LibreSSL 2.5.3
compiled with MiKTeX Application Framework version 3.6802; using 3.6802
compiled with MiKTeX Core version 8.6811; using 8.6811
compiled with MiKTeX Archive Extractor version 1.6300; using 1.6300
compiled with MiKTeX Package Manager version 3.6810; using 3.6810
compiled with poppler version 0.60.1
compiled with uriparser version 0.8.4
compiled with zlib version 1.2.11; using 1.2.11
```

**Comment by James-Yu** [comment] 2018-10-08 08:52
I work with TeXLive even on Windows, tho @Astrantia seems gave a good demo of MikTeX.
```
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/W32TeX)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.29; using libpng 1.6.29
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 3.04
```

**Comment by jlelong** [comment] 2018-10-08 20:09
I have just made an attempt to fix.
@Astrantia and @James-Yu can you pull the [max-print-line](https://github.com/James-Yu/LaTeX-Workshop/tree/max-print-line) branch and test it?

**Comment by Astrantia** [comment] 2018-10-08 21:57
@jlelong Can't compile 
```
[5:55:49 PM] Starting compilation in watch mode...

src/components/builder.ts:230:21 - error TS2532: Object is possibly 'undefined'.

230                     step.args.unshift('--max-print-line=' + maxPrintLine)
                        ~~~~~~~~~


[5:55:51 PM] Found 1 error. Watching for file changes.
```

**Comment by jlelong** [comment] 2018-10-09 05:43
I have just fixed it. Hopefully! Can you give it a try?

**Comment by Astrantia** [comment] 2018-10-09 05:47
@jlelong works for me now, thanks!

**Comment by jlelong** [comment] 2018-10-09 06:32
This is merged into master.

**Closed by jlelong** 2018-10-09 06:32 UTC
