### ISSUE TITLE
Unwanted acquisition of focus from the Latex Sidebar

### ISSUE THREAD

**Issue by darius-sas** [James-Yu/LaTeX-Workshop#1012] opened 2018-11-23 09:00 UTC
More an annoying behaviour rather than a bug, this is why I post it as a bug report (and not as a Feature request).

**Describe the bug**
The sidebar of the extension, with the commands and the structure of the file, continues to open whenever I interact with the previewer. This is a very annoying behaviour and should be fixed or made optional.

**To Reproduce**
1. Have two-sided view with a `.tex` file opened in the editor on the left and `.pdf` file opened on the right in the previewer.
2. Close the sidebar, or set it to "Explorer" or "Git" pages.
3. Change focus from the TeX file to the previewer by clicking on the previewer (e.g. zoom).
4. The sidebar automatically opens, or changes to the "Latex" page.

This is very annoying and disrupts my workflow.

**Expected behavior**
The sidebar should not focus on "Latex" page automatically. Or there should be an option to disable this behaviour.

**Logs**
No logs are necessary.

**Desktop:**
 - OS: Linux (Ubuntu 16.04)
 - VS Code version: 1.29.1
 - Extension version: 5.17.2

Hope everything is clear.
Thank you!
Darius

**Comment by jlelong** [comment] 2018-11-23 09:01
Duplicate of #1011 and #1009. Will be fixed in next release.

**Closed by jlelong** 2018-11-23 09:01 UTC
