### ISSUE TITLE
Terminating compilation does not kill process on Ubuntu 19.04

### ISSUE THREAD

**Issue by Aryojaam** [James-Yu/LaTeX-Workshop#1748] opened 2019-10-13 19:25 UTC
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug**
Terminating an endless loop of compilation caused by using incorrect syntax does not kill the actual process on linux. 
In my case I just terminated it from the latex extension tab under `Build LaTeX Project` -> `Terminate current compilation`.
I was using the `tikz` library, and had incorrect syntax (a missing semicolon) with the `draw` function. (line 24 in the first screenshot below)
[
![Screenshot from 2019-10-13 20-54-27](https://user-images.githubusercontent.com/40788573/66720527-13224580-edfe-11e9-952f-369c091614d3.png)
](url)  
after hitting ctrl+s it started to compile and entered an endless loop, which you can see from the bar below. It got stuck on 7/10 pages. I had to terminate the compilation manually since it did not automatically throw an error because of wrong syntax (I am not sure if it had to) as it normally does from non-tikz environments.

This was repeated a couple of times. Then accidentally I went to htop to see all the running tasks and then I noticed that the process is not killed and it is taking CPU time.
![Screenshot from 2019-10-13 20-54-57](https://user-images.githubusercontent.com/40788573/66720626-7e204c00-edff-11e9-9e46-e7ec1dfc6a66.png)

**To Reproduce**
1. use the following code:
```
\usepackage{tikz}
\begin{document}

\usetikzlibrary{positioning}
\begin{tikzpicture}[node distance=2cm]

% nodes
\node (A) at (0, 3) {\lstinline{OnCreate()}};
\node (B) at (2, 2.5) {\lstinline{OnStart()}};
\node (C) at (4, 2) {\lstinline{OnResume()}};
\node (M) at (4.5, 2.14) {};
\node (D) at (6, 1.5) {\lstinline{OnPause()}};
\node (E) at (8, 1) {\lstinline{OnStop()}};
\node (F) at (10, 0.5) {\lstinline{OnDestroy()}};
\node (G) at (7, 2.5) {\lstinline{Foreground}};
\node (H) at (2, 1) {\lstinline{Foreground}};
\node (I) at (2, 1.75) {\lstinline{OnRestart()}};

% arrows
\draw[->, to path={-| (\tikztotarget)}]
(A) edge (B)
(B) edge (C)
(C) edge (D)
(D) edge (E)
(E) edge (F)
(D) edge (G)
(G) edge (M)
% a semicolon is missing here

\draw[->] (E) edge (H);
\draw[->] (H) edge (I);
\draw[->] (I) edge (B);

\end{tikzpicture}
\end{document}
```
2. compile it (the process does not end)
3. terminate current compilation
4. go to htop (task manager)
5. the process for compilation is still using CPU time

**Expected behavior**
Either should the wrong syntax stop the compilation automatically
or
terminating the compilation should also kill the process

preferably both :)

**Logs [Required]**
```
[21:10:22] Found root file from parent: /home/aryo/Praktikumsbericht/Praktikumsbericht-Vorlage.tex
[21:10:22] Root file remains unchanged from: /home/aryo/Praktikumsbericht/Praktikumsbericht-Vorlage.tex.
[21:10:28] Parsing /home/aryo/Praktikumsbericht/AndroidLifecycle.tex
[21:10:28] File watcher: responding to change in /home/aryo/Praktikumsbericht/AndroidLifecycle.tex
[21:10:28] /home/aryo/Praktikumsbericht/AndroidLifecycle.tex changed. Auto build project.
[21:10:28] BUILD command invoked.
[21:10:28] Building root file: /home/aryo/Praktikumsbericht/Praktikumsbericht-Vorlage.tex
[21:10:28] Build root file /home/aryo/Praktikumsbericht/Praktikumsbericht-Vorlage.tex
[21:10:28] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/home/aryo/Praktikumsbericht,/home/aryo/Praktikumsbericht/Praktikumsbericht-Vorlage
[21:10:28] LaTeX build process spawned. PID: 15784.
[21:10:34] KILL command invoked.
[21:10:34] Kill the current process. PID: 15784.
[21:10:34] Recipe returns with error: null/SIGTERM. PID: 15784. message: Latexmk: This is Latexmk, John Collins, 25 October 2018, version: 4.61.
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'AndroidLifecycle.tex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="/home/aryo/Praktikumsbericht"  "/home/aryo/Praktikumsbericht/Praktikumsbericht-Vorlage.tex"'
------------
.
[21:18:59] Found root file from active editor: /home/aryo/Praktikumsbericht/Praktikumsbericht-Vorlage.tex
[21:18:59] Found root file from active editor: /home/aryo/Praktikumsbericht/Praktikumsbericht-Vorlage.tex
[21:18:59] Root file remains unchanged from: /home/aryo/Praktikumsbericht/Praktikumsbericht-Vorlage.tex.
[21:18:59] Root file remains unchanged from: /home/aryo/Praktikumsbericht/Praktikumsbericht-Vorlage.tex.
[21:22:13] Found root file from parent: /home/aryo/Praktikumsbericht/Praktikumsbericht-Vorlage.tex
[21:22:13] Root file remains unchanged from: /home/aryo/Praktikumsbericht/Praktikumsbericht-Vorlage.tex.

```

**Desktop:**
 - OS: Ubuntu 19.04 disco dingo with kernel version 5.0.0-31-generic
 - VS Code version: 1.38.1
 - Extension version: 8.2.0

**Are you using LaTeX Workshop with VS Code Remote?**
No

**Comment by tamuratak** [comment] 2019-10-13 21:25
duplicate of #1680

**Closed by tamuratak** 2019-10-13 21:25 UTC
