### ISSUE TITLE
Properly handle custom document class

### ISSUE THREAD

**Issue by nafur** [James-Yu/LaTeX-Workshop#811] opened 2018-09-19 10:55 UTC
The plugin makes sure that whenever a file is saved, the document is rebuilt. This works fine for all files that are included via `\input{}` or `\include{}` (or so it seems). It does however not work for a custom `\documentclass{}`.
Writing a custom document class is common practice (at least for many people I know).

This unfortunately leads to the following pattern:

- Change document class
- Do some random change in some other file to trigger recompilation
- Change something else in the document class
- Do some other random change
- ...

### Expected behavior

I'd like the plugin to not only follow `\include{}` and `\input{}` to discover dependencies (or whatever the internal term is), but also `\documentclass{}`, if the respective document class is found within the workspace.

### Alternative

You could also change the whole discovery to be based on the latex output and retrieve all "local" files that have been used, this might catch other corner cases (includes that are hidden within macros?), but might have new problems (absolute paths for local files?).

**Comment by jlelong** [comment] 2018-09-19 11:14
Duplicate of #785 and related to #743.
It is sufficient to use magic comment to set the root file in the `.cls` and then trigger the build with `alt+ctrl+b`.

**Closed by jlelong** 2018-09-19 11:14 UTC

**Comment by rzippo** [comment] 2019-04-29 18:46
> 
> 
> Duplicate of #785 and related to #743.
> It is sufficient to use magic comment to set the root file in the `.cls` and then trigger the build with `alt+ctrl+b`.

Can you post a tutorial for this?
