### ISSUE TITLE
PDF Preview: "An error occurred while loading the PDF." resets a document position.

### ISSUE THREAD

**Issue by timfayz** [James-Yu/LaTeX-Workshop#2039] opened 2020-04-15 15:03 UTC
The main idea in the title. I'm having a problem with keeping PDF previewer on the same page after my project is recompiled and resulting pdf is successful updated. So the problem is that the position of the previewer is always discarded as soon as the project is recompiled. I do not use Workshop's building system (`"latex-workshop.latex.autoBuild.run": "never"`) and do builds manually instead (`latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdflua -pvc main_.tex`). This problem does not appear when I'm down shifting to "Hello world" document with little content. It seems the problem is related to a PDF previewer file watcher, timings of producing "complicated" PDF by the `latexmk` and when it is better to pick up the final change rather than picking intermediate ones. It was hard to produce the screenshot since it happens very quickly but here is it:

![Screenshot from 2020-04-15 17-15-30](https://user-images.githubusercontent.com/6209197/79351722-b258fe80-7f41-11ea-84c1-7a81e943b012.png)

It looks as following: (0) I save a file, the `latexmk` picks the file change and start recompilation (1) I see a pdf update (blink, position is kept), (2) an error above (blink again) and (3) the final blink with updated file at the first page. So, as you can guess, it became really annoying to scroll down where I ended on an every file change (you may not suggest `ctrl+alt+j`; unfortunately, it works only on a very simple "paragraph"-only files; as soon as the doc become more complex and with tables, synctex cannot locate things properly, at least for me). 

**Interestingly**, the problem does not happen in case of external previewer (Evince Reader) which I'm currently forced to use. It works just as expected.

### LaTeX Workshop Output [Required]
```
[17:06:59] Initializing LaTeX Workshop.
[17:06:59] Creating file watcher for .pdf files.
[17:06:59] Cannot run pdflatex to determine if we are using MiKTeX
[17:06:59] Creating LaTeX Workshop http and websocket server.
[17:06:59] LaTeX Workshop initialized.
[17:06:59] Found root file from active editor: /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.tex
[17:06:59] Root file changed from: undefined to /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.tex. Find all dependencies.
[17:06:59] Instantiating a new file watcher for /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.tex
[17:06:59] Creating file watcher for .bib files.
[17:06:59] Parsing /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.tex
[17:06:59] Parsing /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/port.tex
[17:06:59] Parse fls file.
[17:06:59] Cannot find fls file.
[17:06:59] Parsing /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/toc.tex
[17:06:59] Parse fls file.
[17:06:59] Cannot find fls file.
[17:06:59] Parse fls file.
[17:06:59] Server created on 127.0.0.1:43375
[17:07:00] Adding /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.tex to file watcher.
[17:07:00] Adding /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/port.tex to file watcher.
[17:07:00] Adding /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/toc.tex to file watcher.
[17:07:00] Adding /home/timfayz/.texlive2019/texmf-var/luatex-cache/generic-dev/fonts/otl/lmroman10-regular.luc to file watcher.
[17:07:00] Adding /home/timfayz/.texlive2019/texmf-var/luatex-cache/generic-dev/fonts/otl/lmroman10-bold.luc to file watcher.
[17:07:00] Adding /home/timfayz/.texlive2019/texmf-var/luatex-cache/generic-dev/fonts/otl/ptm55f.luc to file watcher.
[17:07:00] Adding /home/timfayz/.texlive2019/texmf-var/luatex-cache/generic-dev/fonts/otl/ptm75f.luc to file watcher.
[17:07:00] Adding /home/timfayz/.texlive2019/texmf-var/fonts/map/pdftex/updmap/pdftex.map to file watcher.
[17:07:00] Adding /home/timfayz/.texmf/fonts/type1/urw/garamond/ugmm8a.pfb to file watcher.
[17:07:00] Adding /home/timfayz/.texmf/fonts/type1/urw/garamond/ugmr8a.pfb to file watcher.
[17:07:00] Adding /home/timfayz/.texmf/fonts/type1/urw/garamond/ugmri8a.pfb to file watcher.
[17:07:00] Snippet data loaded.
[17:07:00] LaTeX Workshop version: 8.8.0
[17:07:03] Root file remains unchanged from: /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.tex.
[17:07:03] Root file remains unchanged from: /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.tex.
[17:08:02] Root file remains unchanged from: /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.tex.
[17:08:32] Root file remains unchanged from: /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.tex.
[17:08:37] File watcher: responding to change in /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/port.tex
[17:08:37] Parsing /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/port.tex
[17:08:37] Parse fls file.
[17:08:37] Cannot find fls file.
[17:08:43] Adding .pdf file /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.pdf to pdf file watcher.
[17:08:44] Root file remains unchanged from: /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.tex.
[17:08:44] PDF command invoked.
[17:08:44] Serving PDF file at http://localhost:43375/viewer.html?file=pdf..JTJGaG9tZSUyRnRpbWZheXolMkZEcm9wYm94JTJGUGhEJTJGV3JpdGluZ3MlMkZQcm9qZWN0UHJvcG9zYWwlMkZtYWluXy5wZGY
[17:08:44] The encoded path is /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.pdf
[17:08:44] Open PDF tab for /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.pdf
[17:08:44] Handle data type: open
[17:08:44] Preview PDF file: /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.pdf
[17:08:44] Handle data type: request_params
[17:08:45] Handle data type: loaded
[17:08:52] Root file remains unchanged from: /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.tex.
[17:08:54] File watcher: responding to change in /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/port.tex
[17:08:54] Parsing /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/port.tex
[17:08:54] Parse fls file.
[17:08:54] Cannot find fls file.
[17:08:57] PDF file watcher - responding to change in /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.pdf
[17:08:58] Preview PDF file: /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.pdf
[17:08:58] PDF file watcher - responding to change in /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.pdf
[17:08:58] Preview PDF file: /home/timfayz/Dropbox/PhD/Writings/ProjectProposal/main_.pdf
[17:08:59] Handle data type: loaded
[17:08:59] Handle data type: loaded
```

### Developer Tools Console [Required]
```
﻿extensionHost.ts:212 Extension Host
extensionHost.ts:213 /bin/sh: 1: pdflatex: not found
```

### Desktop [Required]
 - OS: Linux Mint 19 Cinnamon
 - VS Code version: 1.44.0
 - Extension version: 8.8.0
 - TeX distribution version: TeX 3.14159265 (TeX Live 2019), Latexmk version 4.67, LuaTeX, Version 1.10.0 (TeX Live 2019)

**Comment by jlelong** [comment] 2020-04-15 15:18
You can try to increase the pdf watching delay https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects#latex-workshoplatexpdfwatchdelay

**Comment by jlelong** [comment] 2020-04-15 15:19
Duplicate of #2017

**Closed by jlelong** 2020-04-15 15:19 UTC

**Comment by timfayz** [comment] 2020-04-15 18:25
Thank you a lot! :) It works now!
