### ISSUE TITLE
bad building performance compared to latexmk from command line

### ISSUE THREAD

**Issue by hexaeder** [James-Yu/LaTeX-Workshop#1933] opened 2020-02-05 11:59 UTC
There seems to be a very big time difference between building from the latex-workshop extension compared to bare command. I have a latex file which loads some packages but isn't extraordinary big. I don't have any other extensions running.

If i invoke the latexmk command through the recipe interface (normal out-of-the-box build process from latex-workshop) it takes around 20 seconds to build.
If i fire the same command
`latexmk -synctex=1 -interaction=nonestopmode -file-line-error -pdf [filename].tex`
from the system terminal it takes arround 5 seconds to build.
If i set this command as the external build command of the extension it's still slow. If i start the command through the terminal in vscode it's fast agin.
For all builds i tried with the same changes so i'm quite sure it has nothing to do with multiple vs single runs of pdflatex.

During the entire build process (invoked through the extension) the editor feels very sluggish, thats why i noticed in the first place.

As a workaround: is there any possibility to run an external command (for example latexmk in continuous mode from the system command line) and still trigger parsing the logs with latex-workshop to get the errors and warnings right?

#### output for recipe
```
[12:19:11] BUILD command invoked.
[12:19:11] Root file remains unchanged from: [path]/thesis.tex.
[12:19:11] Building root file: [path]/thesis.tex
[12:19:11] Build root file/thesis.tex
[12:19:11] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/ [path],-cd, [path]
[12:19:11] LaTeX build process spawned. PID: 46084.
[12:19:30] LaTeX log parsed with 1 messages.
[12:19:30] Recipe of length 1 finished. PID: 46084.
[12:19:30] Successfully built  [path]/thesis.tex.
[12:19:30] No PDF viewer connected for  [path]/thesis.pdf
[12:19:30] Parse fls file.
```

#### output for external command
```
[12:39:35] BUILD command invoked.
[12:39:35] Root file remains unchanged from: [path]/thesis.tex.
[12:39:35] Build using the external command: latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=%OUTDIR% %DOC%
[12:39:35] External build process spawned. PID: 48862.
[12:40:01] Successfully built. PID: 48862
[12:40:01] Successfully built [path]/thesis.tex.
[12:40:01] No PDF viewer connected for [path]/thesis.pdf
[12:40:01] Parse fls file.
```

## Desktop [Required]
 - OS: Fedora 31
 - VS Code version: 1.41.0
 - Extension version: 8.7.1
 - TeX distribution version: TeX Live 2019

**Comment by jlelong** [comment] 2020-02-05 12:43
I am very much surprised by tour experience. When compiling a LaTeX project through the extension, we basically do two things

1. Spawn the compiling command. In your case, `latexmk -synctex=1 -interaction=nonestopmode -file-line-error -pdf [filename].tex`
1. Parse the output of the compiling command

I cannot see why Step 1 would take longer when run though the extension.
Could you post a MWE?

**Comment by hexaeder** [comment] 2020-02-05 13:09
```
\documentclass[11pt]{scrartcl}
\usepackage{blindtext}
\begin{document}
\tableofcontents
\blinddocument
\end{document}
```
content of file thesis.tex. There is nothing else in the directory (no .aux and so on).
If i run the build command through the extension it takes ~4.7 s (time is shown after building in the status line of vscode).

if i run `time latexmk -synctex=1 -interaction=nonestopmode -file-line-error -pdf thesis.tex` in the directory the time command shows `1,61s user 0,17s system 97% cpu 1,829 total` (i deleted all of the temp-files again of course). So less then half...

Output of the extension:
```
[14:01:18] BUILD command invoked.
[14:01:18] Found root file from active editor: [path]/thesis.tex
[14:01:18] Root file remains unchanged from: [path]/thesis.tex.
[14:01:18] Building root file: [path]/thesis.tex
[14:01:18] Build root file [path]/thesis.tex
[14:01:18] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=[path],-cd,[path]/thesis
[14:01:18] LaTeX build process spawned. PID: 53954.
[14:01:23] LaTeX log parsed with 0 messages.
[14:01:23] Recipe of length 1 finished. PID: 53954.
[14:01:23] Successfully built [path]/thesis.tex.
[14:01:23] No PDF viewer connected for [path]/mve/thesis.pdf
[14:01:23] Parse fls file.
```

**Comment by jlelong** [comment] 2020-02-05 14:39
I cannot reproduce such a difference with your example.

- From the terminal `2.07s user 0.12s system 98% cpu 2.214 total`
- From the extension `2.4s`

**Comment by tamuratak** [comment] 2020-02-06 05:04
> I also compared the output of the latexmk command run in the terminal with the "LaTeX Compiler" output in vscode and there is no difference...

Even if there is no difference, please show us the log messages as requested in the issue template.

1. Please run latex commands in recipes without using `latexmk`. Make sure that it does not take a long time.
2. Run `latexmk` in recipes with the option `-diagnostics`, and show us the log messages of the compilation.

**Comment by hexaeder** [comment] 2020-02-06 14:39
After some more testing i don't think it's related to latexmk in particular. I tested the same with just pdflatex on different latex projects and the results are more or less the same: if the process is spawned by the extension i takes approx twice as long. At this point i don't think it's necessary to have a closer look at the latexmk output.

I guess it has something to do with the way the process is spawned, maybe this is OS depended? Since i get an noticeable lag in vscode during the build process it doesn't seem to be properly parallelized... maybe this is not related to the latex-workshop extension at all.

**Comment by tamuratak** [comment] 2020-02-06 23:38
Thank you.

There is a possibility that the progress bar and the compilation info panel cause this problem. We will add an option to disable them in a future release. Please try to turn it on.

https://github.com/James-Yu/LaTeX-Workshop/blob/2ee8c67379f805b77572380bd7366baf62e803b3/src/components/builder.ts#L265-L273

**Comment by tamuratak** [comment] 2020-02-07 00:05
@hexaeder Please see the output of `top` command during compilation and find what processes use CPU. If the utilization of CPU is low, the cause might not be the progress bar.

**Comment by jlelong** [comment] 2020-02-13 21:02
Do you still face this issue with version 8.7.2 ?
Can you try with `latex-workshop.progress.enabled: false`?

**Comment by hexaeder** [comment] 2020-02-15 18:09
Sorry for the long delay, i didn't find the time to respond.

I tried with version 8.7.2, same results. It doesn't matter whether the progress bar is turned on or off with `latex-workshop.progress.enabled`. Side note:  there is a minor bug, if the recipe fails (because there is no corresponding tool, i had a typo) the build icon will stay on the status line.

I had a look at the CPU usage during the build process as @tamuratak suggested.  The `pdflatex` process uses around 80-100% of a single core in both cases (spawned via vscode/ spawned via terminal). If i build through vscode, all of the cores go up to 80-100% because of the high CPU usage of several of the `code` processes during the complete build process.

**Comment by holdon1221** [comment] 2020-02-27 10:53
I don't think this comment would be helpful but I experienced the same problem. 

I'm using the Windows 10. It worked normally for the first month, but someday after(I don't remember when this problem started exactly), I experienced the very same problem.

I thought this is for the version, but it is not, I downloaded 8.7.0 8.7.1, but it has the same problem.

Can you suggest any other options I can try?

**Comment by tamuratak** [comment] 2020-02-27 11:17
- Use [VS Code Insiders](https://code.visualstudio.com/insiders/). VS Code Insiders ships with Electron 7 while VS Code ships with Electron 6. So the problem might be solved.
- Downgrade to VS Code 1.39, which shipped with Electron 4.

If these options solve the problem, please tell us. Thank you for your cooperation.

**Comment by holdon1221** [comment] 2020-03-02 00:03
It doesn't solve the problem sadly. Building the tex file still needs 80-almost 100% of CPU.

I think my information is not enough for solving it.

But I think this is not an OS-dependent one.

**Comment by holdon1221** [comment] 2020-03-02 00:04
Thank you for helping me and it is good to try something else I didn't realize.

But, It doesn't solve the problem sadly. Building the tex file still needs 80-almost 100% of CPU.

I think my information is not enough for solving it.

But I think this is not an OS-dependent one.

**Comment by tamuratak** [comment] 2020-03-02 00:31
Thank you. This problem might be related to microsoft/vscode/issues/24884. In the thread, they guess that antivirus software causes this problem.

**Comment by holdon1221** [comment] 2020-03-02 01:20
Thanks for informing me. 

I'm just using the very basic antivirus software, Window defends, which is given by Win10, initially.

If the idea of that thread is right, then it can be the things... from one of the Windows updates... then.

Thank you.

**Comment by tamuratak** [comment] 2020-03-02 11:38
If anyone encounters this problem, please disable all the other extensions except for LaTeX Workshop, then please tell us whether you still see this problem. Please change all the user settings of VSCode to the default ones, then please tell us whether you still see this issue.  Thank you for your cooperation.

**Comment by tamuratak** [comment] 2020-03-04 22:47
We can also profile the extension. See https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions.

**Comment by sqd** [comment] 2020-03-09 00:28
I think I am having the same issue. But what I feel like is a delay between pressing "save" and the build process actually starts. If I set my CPU usage monitor's polling interval to very high, there is a delay of about 3 seconds between my pressing "save", and the CPU peak appears (I also tried a while(1) loop and the peak appears immediately, so I don't think it's a problem with the CPU usage software I'm using)

This appeared fairly recently. Is there anything I can do to help confirm if this is the case?

**Comment by sqd** [comment] 2020-03-09 00:36
What API does LaTeX-Workshop use to spawn the latexmk process? I want to try printing out the system timestamp before spawning, and use a dummy program to print the timestamp again when it's run. So I can see if there's a unusual difference.

**Comment by jlelong** [comment] 2020-03-09 05:06
You are right. There is a delay, see #1949. It will be fixed and made configurable in the next release.

**Comment by jlelong** [comment] 2020-03-28 20:15
The issue does not contain enough information to investigate the problem. I am closing it until more information is provided.

**Closed by jlelong** 2020-03-28 20:15 UTC
Labels: can't reproduce, external, need more info
