### ISSUE TITLE
Warning: command 'latex-workshop.onEnterKey' not found

### ISSUE THREAD

**Issue by Anaeijon** [James-Yu/LaTeX-Workshop#2853] opened 2021-09-01 12:10 UTC
## Warning shows and Enter doesn't work on 8.20.2
Downgrade to 8.19.2 solves the problem. (little gear icon -> install another version)

Also TeX-Icon is not shown on the left, even when in TeX-File.

You still see this issue?: No, not on 8.19.2; Yes, on 8.20.2

You visited the wiki?: Yes

## Description
After the update to 8.20.2 this warning pops up every time I press Enter in a .tex file and .

I have removed all VSCode setting and addons, reinstalled VSCode. Enter works as expected on clean VS-Code install.
After installing latex-workshop Enter stops working in TeX-files. Downgrading solves the problem. Everything on clean installation

### To Reproduce

1. Install Code-OSS on Manjaro ( pacman -Sy code )
2. Open Code, go to Extensions, search LaTeX-Workshop, install
3. Reload VS Code
4. Open any .tex file
5. press Enter, Warning opens, Enter doesn't work

### Expected behavior

Enter should just work on the latest version.

## Logs [Required]

exthost-Log: 
```
[2021-09-01 14:00:24.798] [exthost] [info] extension host started
[2021-09-01 14:00:24.816] [exthost] [info] Lock '/home/anaeijon/.config/Code - OSS/User/workspaceStorage/6e08ea458c878d6fb6de81cc8d926a7a/vscode.lock': Lock acquired.
[2021-09-01 14:00:24.959] [exthost] [info] ExtensionService#_doActivateExtension James-Yu.latex-workshop {"startup":false,"extensionId":{"value":"James-Yu.latex-workshop","_lower":"james-yu.latex-workshop"},"activationEvent":"onLanguage:latex"}
[2021-09-01 14:00:24.959] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/anaeijon/.vscode-oss/extensions/james-yu.latex-workshop-8.20.2/out/src/main.js
[2021-09-01 14:00:24.960] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-09-01 14:00:24.960] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code/extensions/debug-auto-launch/dist/extension
[2021-09-01 14:00:24.963] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-09-01 14:00:24.964] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code/extensions/git/dist/main
[2021-09-01 14:00:25.000] [exthost] [error] Activating extension James-Yu.latex-workshop failed due to an error:
[2021-09-01 14:00:25.000] [exthost] [error] Error: Cannot find module '/home/anaeijon/.vscode-oss/extensions/james-yu.latex-workshop-8.20.2/out/src/main.js'
Require stack:
- /usr/lib/code/out/vs/loader.js
- /usr/lib/code/out/bootstrap-amd.js
- /usr/lib/code/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
	at Module._load (internal/modules/cjs/loader.js:732:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.s._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27800)
	at Function.b._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24471)
	at Function.l._load (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59004)
	at Module.require (internal/modules/cjs/loader.js:959:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (/usr/lib/code/out/vs/loader.js:5:101)
	at c._loadCommonJSModule (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:25877)
	at c._doActivateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12556)
	at c._activateExtension (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:11657)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
[2021-09-01 14:00:25.124] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-09-01 14:00:25.127] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code/extensions/github/dist/extension.js
[2021-09-01 14:00:25.455] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-09-01 14:00:25.455] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code/extensions/ms-vscode.js-debug/src/extension.js
[2021-09-01 14:00:25.615] [exthost] [info] eager extensions activated
[2021-09-01 14:00:25.669] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-09-01 14:00:25.669] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code/extensions/emmet/dist/node/emmetNodeMain
[2021-09-01 14:00:25.675] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-09-01 14:00:25.675] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code/extensions/merge-conflict/dist/mergeConflictMain
[2021-09-01 14:00:25.677] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-09-01 14:00:25.677] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code/extensions/testing-editor-contributions/dist/extension.js
```

### LaTeX Workshop Output [Required]

There is no 'TeX' icon. 
```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Manjaro
 - VS Code version: 1.58.0
 - Extension version: 8.20.2

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

## Probably Related:
[https://github.com/James-Yu/LaTeX-Workshop/issues/1193](https://github.com/James-Yu/LaTeX-Workshop/issues/1193)
This issue seems to have existed before when upgrading to Version 6.0.0. 
Downgrading to the previous version was a solution back then and it also works now.

**Comment by tamuratak** [comment] 2021-09-01 12:33
Duplicate of #2845.

**Closed by tamuratak** 2021-09-01 12:33 UTC
