### ISSUE TITLE
ISSUE OF PDF VIEWER BOOKMARK LIST RENDER

### ISSUE THREAD

**Issue by heartacker** [James-Yu/LaTeX-Workshop#2724] opened 2021-05-28 02:21 UTC
![PDF](https://user-images.githubusercontent.com/1876302/119920161-6ed31f80-bf9e-11eb-9b20-5026f79818a1.gif)

**Comment by tamuratak** [comment] 2021-05-28 02:31
Duplicate of #2640. This issue will be fixed after updating PDF.js to v2.8. We are not sure when we will update it.

**Closed by tamuratak** 2021-05-28 02:31 UTC

**Comment by tamuratak** [comment] 2021-05-28 02:34
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) next time.
