### ISSUE TITLE
auto Closing Pairs : dollar sign $

### ISSUE THREAD

**Issue by noctildon** [James-Yu/LaTeX-Workshop#968] opened 2018-11-08 06:16 UTC
Since I want the function that auto close the dollar sign $ in editor, I manually add ["$", "$"] to 
> ~/.vscode/extensions/james-yu.latex-workshop-X.XX.X/syntax.json

So syntax.json becomes
```json
...
"autoClosingPairs": [
	["{", "}"],
	["[", "]"],
	["(", ")"],
	["`", "'"],
        ["$", "$"]
	],
...
```
However, syntax.json returns to its original setting after the extension is updated.
Is there any way to keep this setting?

### How to reproduce
1. add  ["$", "$"] to syntax.json
2. update the extension

**Comment by tamuratak** [comment] 2018-11-08 06:46
duplicate of #544 and #235.

**Closed** 2018-11-08 07:11 UTC

**Comment by James-Yu** [comment] 2018-11-20 02:50
duplicate of #544 and #235

**Comment by praenubilus** [comment] 2018-11-20 03:41
> duplicate of #544 and #235

I see. But those two are closed too. Is there a solution or live thread for custom autoclosing pairs?

**Comment by James-Yu** [comment] 2018-11-20 04:02
Not likely. You may create custom snippets as #235 though.

**Comment by tamuratak** [comment] 2021-01-16 03:22
Please up vote microsoft/vscode/issues/38352.
