### ISSUE TITLE
command 'latex-workshop.view' not found

### ISSUE THREAD

**Issue by supertron9000** [James-Yu/LaTeX-Workshop#2857] opened 2021-09-04 08:06 UTC
Hi,

I get the error message "command 'latex-workshop.view' not found" when I want to open the in editor pdf viewer. 

I'm on manjaro linux and this is my code OSS version: 

Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-12T23:51:36.303Z
Electron: 12.0.17
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.60-1-MANJARO

The error only happens when I'm on the current LaTeX-Workshop 8.20.2 version. Downgrade to 8.19.2 solves the issue. I tried cycling between these versions, also with rebooting in between, but the error in 8.20.2 remains. 

cheers and thanks for this great plugin!

**Comment by tamuratak** [comment] 2021-09-04 08:13
Duplicate of #2845

**Closed by tamuratak** 2021-09-04 08:13 UTC
Labels: external, duplicate
