### ISSUE TITLE
Compiling projects using subfiles package

### ISSUE THREAD

**Issue by HedgehogCode** [James-Yu/LaTeX-Workshop#1272] opened 2019-04-03 09:44 UTC
If I open a subfile in a multi-file project and save it only the currently open file is compiled and not the root file of the project.

**To Reproduce**
1. Create a project with the following files:
`main.tex`:
```
\documentclass[10pt,a4paper]{report}
\usepackage{subfiles}
\usepackage{blindtext}

\begin{document}
Main file content
\subfile{./tex/subfile.tex}
\end{document}
```

`tex/subfile.tex`:
```
%! TEX root = ../main.tex
\documentclass[../main.tex]{subfiles}

\begin{document}
\blindtext
\end{document}
```

2. Open the `subfile.tex` and save it
3. Only the `subfile.tex` is compiled but not the `main.tex` like specified in the magic comment.
4. Calling the `LaTex Workshop: Build LaTeX project` command works fine and after doing so a build on save works fine too.

**Expected behavior**
I would expect the `main.tex` file to be compiled on save.

**Logs**
LaTeX Workshop logs:
```
[11:39:30] Parsing /home/bw/misc/vscode-latex-bug/tex/subfile.tex
[11:39:30] File watcher: responding to change in /home/bw/misc/vscode-latex-bug/tex/subfile.tex
[11:39:30] /home/bw/misc/vscode-latex-bug/tex/subfile.tex changed. Auto build project.
[11:39:30] Building root file: /home/bw/misc/vscode-latex-bug/tex/subfile.tex
[11:39:30] Build root file /home/bw/misc/vscode-latex-bug/tex/subfile.tex
[11:39:30] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/home/bw/misc/vscode-latex-bug/tex,/home/bw/misc/vscode-latex-bug/tex/subfile
[11:39:30] LaTeX build process spawned. PID: 14973.
[11:39:31] LaTeX log parsed with 0 messages.
[11:39:31] Recipe of length 1 finished. PID: 14973.
[11:39:31] Successfully built /home/bw/misc/vscode-latex-bug/tex/subfile.tex.
[11:39:31] No PDF viewer connected for /home/bw/misc/vscode-latex-bug/tex/subfile.pdf
[11:39:31] Parsing /home/bw/misc/vscode-latex-bug/tex/subfile.fls to compute dependencies
[11:39:31] Parsing /home/bw/misc/vscode-latex-bug/tex/subfile.tex
[11:39:31] Parsing /home/bw/misc/vscode-latex-bug/main.tex
[11:39:31] Parsing /home/bw/misc/vscode-latex-bug/tex/subfile.tex
```

**Desktop:**
 - OS: Linux (Ubuntu 18.04)
 - VS Code version: 1.32.3
 - Extension version: 6.3.0

**Additional context**
I think this is a regression because I cannot remember encountering this issue with previous versions of the extension (and my project structures haven't changed).

**Comment by jlelong** [comment] 2019-04-03 09:48
Duplicate of #1088.

**Comment by HedgehogCode** [comment] 2019-04-03 11:49
Oh, I missed that issue. Thank you for the fast reply!

I still have some small remarks:
* Could this behavior be described on the wiki page for the [Muti File Projects](https://github.com/James-Yu/LaTeX-Workshop/wiki/multi-file-projects)? After reading the section 'The root file' I thought that the magic comment has the highest priority.
* The documentation states that the `autoBuild` uses the first default recipe but using the command `LaTeX Workshop: Build with recipe` I cannot reproduce this behavior but only build the project root or the subfiles root which are both `main.tex`. Therefore I think the behavior is a bit unexpeced (Usually always the root file is build).

**Comment by jlelong** [comment] 2019-04-03 12:37
You are right some things are not clear. I will look at it.

**Closed** 2019-04-04 11:36 UTC
Labels: enhancement

**Comment by jlelong** [comment] 2019-04-04 11:42
Now, the magic comments have the highest priority. So I think _autoBuild_ is coherent with the _Build LaTeX project_ command.
Ring a bell if you still find something strange.
