### ISSUE TITLE
Feature Request: Expand/Collapse for document parts, chapters, sections, etc.

### ISSUE THREAD

**Issue by ahnafalrafi** [James-Yu/LaTeX-Workshop#676] opened 2018-06-26 15:41 UTC
Hi, I was wondering if it would be possible to work in an expand/collapse guide for document parts, chapters, sections, etc. I think ShareLaTeX has this feature. For instance, any time one of the lines starts \part{}, \chapter{}, or \section{} appeared, there would be an indent-guide type expand/collapse option until the next instance of any of those. It really helps with document management. I think that if this is possible, then there might also be scope for allowing user-defined commands of that sort (document levels) to included in adjustments in the Settings menu. For instance, I might define \subsubsubsection{} in my preamble, and then configure VS Code to recognize this as essentially the same object as those previously mentioned.

Thanks!

**Comment by jlelong** [comment] 2018-06-28 04:41
Duplicate of #263.

**Closed by jlelong** 2018-06-28 04:41 UTC
