### ISSUE TITLE
External PDF viewer support

### ISSUE THREAD

**Issue by iliyang** [James-Yu/LaTeX-Workshop#163] opened 2017-06-09 13:10 UTC
The built-in PDF viewer can be very convenient, but can be slow to process and refresh files. Even with simple files, it flickers when reloading the PDF after an update, which is visually distracting. 

Would it be difficult to add support for external viewers (with forward/inverse search functionality)? Hopefully code/ideas can be borrowed from Sublime and Atom plugins that already have this feature.

**Comment by James-Yu** [comment] 2017-06-09 13:12
Duplicate of https://github.com/James-Yu/LaTeX-Workshop/issues/23.

I am inclined to the current form and quite stubborn on this matter, unfortunately. Sorry for any inconveniences.

**Closed by James-Yu** 2017-06-09 13:12 UTC

**Comment by iliyang** [comment] 2017-06-09 13:17
Fair enough. And could anything be done to reduce the flickering of the built-in PDF viewer? Maybe some double buffering of its display?

**Comment by James-Yu** [comment] 2017-06-09 13:18
It's possible. Let me think of the implementation.

**Comment by a-reisberg** [comment] 2019-12-19 10:46
Curious if you're still interested in resolving this issue.  A while back, I made a pull request to texstudio to fix the same issue: https://github.com/texstudio-org/texstudio/pull/577.  I haven't looked into pdfjs (which I assume you use to render the pdf), so I don't know if it's applicable here.
