### ISSUE TITLE
@ prefix doesn't always work inside brackets

### ISSUE THREAD

**Issue by carlmueller** [James-Yu/LaTeX-Workshop#2197] opened 2020-07-09 21:48 UTC
## Preliminary questions [Required]

I used @i  and chose \int_{}^{} . Then I entered 0 in the first bracket and pressed "tab" to go to the second pair of brackets. Then I pressed @8 hoping to choose \infty, but no choices appeared. But if I pressed the right arrow key followed by the left arrow key, I was back where I was before. Then @8 offered \infty, as desired.

### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes/No. 

My issue does not have to do with compiling.

## Describe the bug [Required]

@ shortcuts don't work if you use a shortcut such as @i for \int_{}^{} which puts you between curly brackets.

### To Reproduce

1. Press @i
2. Choose \int_{}^{}
3. Press @8 
4. No choices appear.

### Expected behavior

At step 4, you should be presented with the choice \infty

## Logs [Required]

[17:39:21] Initializing LaTeX Workshop.
[17:39:21] Creating PDF file watcher.
[17:39:21] Creating LaTeX Workshop http and websocket server.
[17:39:21] LaTeX Workshop initialized.
[17:39:21] Found root file from active editor: /Users/carlmueller/Downloads/AC-2020-07-09.tex
[17:39:21] Root file changed: from undefined to /Users/carlmueller/Downloads/AC-2020-07-09.tex
[17:39:21] Start to find all dependencies.
[17:39:21] Instantiating a new file watcher for /Users/carlmueller/Downloads/AC-2020-07-09.tex
[17:39:21] Creating Bib file watcher.
[17:39:21] Parsing a file and its subfiles: /Users/carlmueller/Downloads/AC-2020-07-09.tex
[17:39:21] Parse fls file.
[17:39:21] Fls file found: /Users/carlmueller/Downloads/AC-2020-07-09.fls
[17:39:21] Parse aux file: /Users/carlmueller/Downloads/AC-2020-07-09.aux
[17:39:21] Server created on 127.0.0.1:51417
[17:39:21] Added to file watcher: /Users/carlmueller/Downloads/AC-2020-07-09.tex
[17:39:22] Snippet data loaded.
[17:39:22] LaTeX Workshop version: 8.11.1
[17:40:09] LOG command invoked.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```
[17:39:21] Initializing LaTeX Workshop.
[17:39:21] Creating PDF file watcher.
[17:39:21] Creating LaTeX Workshop http and websocket server.
[17:39:21] LaTeX Workshop initialized.
[17:39:21] Found root file from active editor: /Users/carlmueller/Downloads/AC-2020-07-09.tex
[17:39:21] Root file changed: from undefined to /Users/carlmueller/Downloads/AC-2020-07-09.tex
[17:39:21] Start to find all dependencies.
[17:39:21] Instantiating a new file watcher for /Users/carlmueller/Downloads/AC-2020-07-09.tex
[17:39:21] Creating Bib file watcher.
[17:39:21] Parsing a file and its subfiles: /Users/carlmueller/Downloads/AC-2020-07-09.tex
[17:39:21] Parse fls file.
[17:39:21] Fls file found: /Users/carlmueller/Downloads/AC-2020-07-09.fls
[17:39:21] Parse aux file: /Users/carlmueller/Downloads/AC-2020-07-09.aux
[17:39:21] Server created on 127.0.0.1:51417
[17:39:21] Added to file watcher: /Users/carlmueller/Downloads/AC-2020-07-09.tex
[17:39:22] Snippet data loaded.
[17:39:22] LaTeX Workshop version: 8.11.1
[17:40:09] LOG command invoked.

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

## Desktop [Required]
 - OS: MacOS 10.15.5
 - VS Code version: 1.47.0
 - Extension version: 8.11.1
 - TeX distribution version: mactex 2020.0407

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by jlelong** [comment] 2020-07-10 05:56
Duplicate of #2184.
Please see https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#i-cannot-nest-snippets
You have to set `editor.suggest.snippetsPreventQuickSuggestions: false` to enable snippet nesting.

**Closed by jlelong** 2020-07-10 05:56 UTC
