### ISSUE TITLE
You can’t type an opening brace after \end if tab size if configured to one

### ISSUE THREAD

**Issue by schuelermine** [James-Yu/LaTeX-Workshop#2651] opened 2021-04-29 19:35 UTC
Issue Type: <b>Bug</b>

- Set `editor.tabSize` setting to 1
- Make a document
- Select “LaTeX” as the language
- Type “\end”
- Try to type “{”

<details>
<summary>Extension logs</summary>
```
[22:42:08] Initializing LaTeX Workshop.
[22:42:08] Extension root: /home/anselmschueler/.vscode/extensions/james-yu.latex-workshop-8.17.0
[22:42:08] $PATH: /home/anselmschueler/.deno/bin:/home/anselmschueler/.cabal/bin:/home/anselmschueler/.ghcup/bin:/home/anselmschueler/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/anselmschueler/.dotnet/tools
[22:42:08] $SHELL: /usr/bin/fish
[22:42:08] Creating PDF file watcher.
[22:42:08] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[22:42:08] Creating LaTeX Workshop http and websocket server.
[22:42:08] LaTeX Workshop initialized.
[22:42:08] Trigger characters for intellisense of LaTeX documents: ["\\","{",",","(","["]
[22:42:08] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[]}
[22:42:08] Current workspace folders: undefined
[22:42:08] Current workspaceRootDir: 
[22:42:08] Server created on 127.0.0.1:39497
[22:42:08] Snippet data loaded.
[22:42:25] Current workspace folders: undefined
[22:42:25] Current workspaceRootDir: 
[22:42:29] Current workspace folders: undefined
[22:42:29] Current workspaceRootDir: 
[22:42:34] Current workspace folders: undefined
[22:42:34] Current workspaceRootDir: 
```
</details>

<details>
<summary>VS Code info</summary>

Extension version: 8.17.0
VS Code version: Code - Insiders 1.56.0-insider (13f1afffab09548c10ddb3bc5d5db52587876ad8, 2021-04-28T04:52:56.570Z)
OS version: Linux x64 5.11.0-7614-generic
</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (0.29GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id dbbd25fe-3f4e-426a-9c89-45e060834124|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by jlelong** [comment] 2021-04-29 20:09
I cannot reproduce with vscode `1.55.2`. I am closing the issue until more information is provided.
Try to deactivate all other extensions 
Please post the complete logs of the extension starting from `Initializing LaTeX Workshop` and the developper logs.

![74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524](https://user-images.githubusercontent.com/2910140/77959270-98c77e00-72d6-11ea-8c58-4934a9fde39a.png)

**Comment by schuelermine** [comment] 2021-04-29 20:39
OK, I’ve tested further. It *only* occurs when you have the tab size configured to one, whether per-language, per-workspace or global.

**Comment by schuelermine** [comment] 2021-04-29 20:44
I’ve added the extension’s logs.

**Comment by jlelong** [comment] 2021-04-29 20:46
I can reproduce the issue but only on the first line of an empty file. This is mostly related to VSCode itself.

**Comment by schuelermine** [comment] 2021-04-29 20:49
Why is it related to VSCode itself?

**Comment by jlelong** [comment] 2021-04-30 05:24
When typing the `{` after `\end` on an empty file with tab size set to one, the developper tools console reports an error

```
  ERR Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at Object.r [as firstNonWhitespaceIndex] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:59248)
    at Function.normalizeIndentation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:583:3122)
    at u.normalizeIndentation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:589:32577)
    at Function._runAutoIndentType (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:600:802)
    at Function.typeWithInterceptors (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:601:270)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:617:2040
    at S._executeEdit (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:617:1067)
    at S.type (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:617:1877)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618:3570
    at i._withViewEventsCollector (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618:5338)
    at i._executeCursorEdit (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618:3172)
    at i.type (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618:3535)
    at tn._type (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:653:9444)
    at tn.trigger (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:653:8450)
    at E.runCommand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:651:49234)
    at handler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:651:13949)
    at w.invokeFunction (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:624:14287)
    at w._tryExecuteCommand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1558:3496)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1558:3245
```

Exactly the same problem occurs when typing `</a>` in an empty `HTML` file. Probably worth reporting to https://github.com/microsoft/vscode/issues

**Closed** 2021-04-30 07:32 UTC
Labels: vscode-issue
