### ISSUE TITLE
No auto-rebuild after loss of focus

### ISSUE THREAD

**Issue by MaxHausmann** [James-Yu/LaTeX-Workshop#1948] opened 2020-02-14 11:25 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]
Since the last version, LW does not recompile the document after I change the focus (tab) to the vscode pdf-reader. In previous versions I changed the focus and the document was automatically recompiled. 

- VS Code Autosave: ON
- Autobuild: onFileChange

### To Reproduce

1. Do some changes on my document
2. Click on the pdf-reader tab
3. Nothing happens until I manually save the document by pressing [CTRL]+[S]

### Expected behavior

Document should be recompiled with the new output on pdf-reader tab.

## Desktop [Required]
 - OS: Ubuntu 19.04
 - VS Code version: 1.41.1
 - Extension version: 8.7.2
 - TeX distribution version: LatexMK, 25 October 2018, version: 4.61.

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment] 2020-02-14 11:38
Show us logs as requested in the issue template.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools. Paste anything suspicious.

[Paste the log here]
```

**Comment by MaxHausmann** [comment] 2020-02-14 11:49
### Logs

## LaTeX Workshop Output
```[12:41:55] LOG command invoked.
[12:41:59] Found root file from active editor: /home/mhausmann/Projects/MA/MMT/Praktikum/Versuch11/protocol/MMT11.tex
[12:41:59] Root file remains unchanged from: /home/mhausmann/Projects/MA/MMT/Praktikum/Versuch11/protocol/MMT11.tex.
[12:42:07] File watcher: responding to change in /home/mhausmann/Projects/MA/MMT/Praktikum/Versuch11/protocol/MMT11.tex
[12:42:07] Parsing /home/mhausmann/Projects/MA/MMT/Praktikum/Versuch11/protocol/MMT11.tex
[12:42:07] /home/mhausmann/Projects/MA/MMT/Praktikum/Versuch11/protocol/MMT11.tex changed. Auto build project.
[12:42:07] BUILD command invoked.
[12:42:07] Building root file: /home/mhausmann/Projects/MA/MMT/Praktikum/Versuch11/protocol/MMT11.tex
[12:42:07] Build root file /home/mhausmann/Projects/MA/MMT/Praktikum/Versuch11/protocol/MMT11.tex
[12:42:07] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/home/mhausmann/Projects/MA/MMT/Praktikum/Versuch11/protocol,/home/mhausmann/Projects/MA/MMT/Praktikum/Versuch11/protocol/MMT11
[12:42:07] LaTeX build process spawned. PID: 19407.
[12:42:08] LaTeX log parsed with 5 messages.
[12:42:08] Recipe of length 1 finished. PID: 19407.
[12:42:08] Successfully built /home/mhausmann/Projects/MA/MMT/Praktikum/Versuch11/protocol/MMT11.tex.
[12:42:08] Refresh PDF viewer for /home/mhausmann/Projects/MA/MMT/Praktikum/Versuch11/protocol/MMT11.pdf
[12:42:08] Parse fls file.
[12:42:08] Preview PDF file: /home/mhausmann/Projects/MA/MMT/Praktikum/Versuch11/protocol/MMT11.pdf
[12:42:09] Handle data type: loaded
```
## Developer Tools Console
No suspicious output, imho.

## Comment
The funny thing is, as soon as I open the log output, it works like charm.
Is the console not opened, it doesn't work. I tried it five times with the same result.

## Solution
Let the console open

**Comment by PantherJohn** [comment] 2020-02-16 04:49
@tamuratak ;( Seems like a bug introduced in the latest release. Downgraded to version 8.7.1 everything works fine now.

**Comment by xiaoweiz** [comment] 2020-02-25 05:25
I can reproduce on MacOS 10.14.6

**Comment by jlelong** [comment] 2020-03-07 11:33
The issue does not contain enough information to investigate the problem. I am closing it until more information is provided.

**Closed by jlelong** 2020-03-07 11:33 UTC
Labels: can't reproduce

**Comment by PantherJohn** [comment] 2020-03-09 00:33
@jlelong IS there any more info needed? Elaborate on how much info you need to investigate the issue. The log messages and the JSON config already explained everything. ;((
https://stackoverflow.com/questions/54824914/vscode-latex-workshop-no-autobuild-for-onfilechange

**Comment by jlelong** [comment] 2020-03-09 05:12
The stackoverflow link is totally outdated, so many things have been changed since release 6.
Unfortunately, I cannot reproduce the issue and I cannot think of any change between 8.7.1 and 8.7.2 which could be responsible for this.

Have you tried completely uninstalling the extension and then reinstalling 8.7.2? Do you still experience the problem when all other extensions are disabled?

**Comment by PantherJohn** [comment] 2020-03-17 07:54
@jlelong Tried it on a new pc, still getting the same problem.
