### ISSUE TITLE
PDF view not working on Windows 10 with remote WSL

### ISSUE THREAD

**Issue by allenjlw** [James-Yu/LaTeX-Workshop#1597] opened 2019-08-12 20:08 UTC
**Disable all the other extensions except for LaTeX Workshop and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**

1. There's no "view" small icon at the upper right corner.
2. PDF cannot be opened in tab mode.

**To Reproduce**
1. Compile a tex file
2. View the generated PDF file in tab mode

**Expected behavior**

The generated PDF file can be opened in tab mode.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.
```
[2019-08-12 14:53:30.958] [exthost] [info] extension host started
[2019-08-12 14:53:30.965] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"activationEvent":"onResolveRemoteAuthority:wsl"}
[2019-08-12 14:53:30.965] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\abc\.vscode\extensions\ms-vscode-remote.remote-wsl-0.39.2\dist\extension
[2019-08-12 14:53:31.083] [exthost] [error] ProxyResolver#getCertificates (intermediate value) is not a function
[2019-08-12 14:53:35.578] [exthost] [info] ExtensionService#_doActivateExtension vscodevim.vim {"startup":true,"activationEvent":"*"}
[2019-08-12 14:53:35.578] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\abc\.vscode\extensions\vscodevim.vim-1.9.0\out\extension
[2019-08-12 14:53:38.520] [exthost] [info] eager extensions activated
[2019-08-12 15:05:53.714] [exthost] [info] extension host started
[2019-08-12 15:05:53.717] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"activationEvent":"onResolveRemoteAuthority:wsl"}
[2019-08-12 15:05:53.717] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\abc\.vscode\extensions\ms-vscode-remote.remote-wsl-0.39.2\dist\extension
[2019-08-12 15:05:53.821] [exthost] [error] ProxyResolver#getCertificates (intermediate value) is not a function
[2019-08-12 15:05:57.430] [exthost] [info] eager extensions activated
[2019-08-12 15:14:06.830] [exthost] [info] extension host started
[2019-08-12 15:14:06.832] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"activationEvent":"onResolveRemoteAuthority:wsl"}
[2019-08-12 15:14:06.832] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\abc\.vscode\extensions\ms-vscode-remote.remote-wsl-0.39.2\dist\extension
[2019-08-12 15:14:06.877] [exthost] [error] ProxyResolver#getCertificates (intermediate value) is not a function
[2019-08-12 15:14:08.584] [exthost] [info] ExtensionService#_doActivateExtension vscodevim.vim {"startup":true,"activationEvent":"*"}
[2019-08-12 15:14:08.584] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\abc\.vscode\extensions\vscodevim.vim-1.9.0\out\extension
[2019-08-12 15:14:11.499] [exthost] [info] eager extensions activated
```
<details>
<summary>LaTeX Workshop Output [Required]</summary>

[15:14:11] Server created on 127.0.0.1:55520
[15:14:11] Snippet data loaded.
[15:14:11] LaTeX Workshop version: 7.3.0
[15:14:34] PDF command invoked.
[15:14:34] Serving PDF file at http://localhost:55520/viewer.html?file=pdf..JTJGbW50JTJGYyUyRlVzZXJzJTJGd3UlMkZEZXNrdG9wJTJGYmx1ZXNoaWVsZC11c2VuaXglMkZtYWluLnBkZg
[15:14:34] The encoded path is /mnt/c/Users/abc/Desktop/tmp/main.pdf
[15:14:34] Open PDF tab for /mnt/c/Users/abc/Desktop/tmp/main.pdf
[15:14:37] Handle data type: open
[15:14:51] ACTIONS command invoked.
[15:14:58] LOG command invoked.

</details>

<details>
<summary>Developer Tools Console [Required]</summary>

extensionHost.ts:293 [Extension Host] debugger listening on port 48975
view-pdf-light.svg:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
open-change.svg:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
activity-bar.svg:1 Failed to load resource: net::ERR_NOT_IMPLEMENTED
mainThreadExtensionService.ts:64 [[object Object]]Cannot read property 'toLocaleUpperCase' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
_doInvokeHandler @ rpcProtocol.ts:394
_invokeHandler @ rpcProtocol.ts:379
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:572
a @ ipc.net.ts:421
e @ ipc.net.ts:428
fire @ event.ts:572
_receiveMessage @ ipc.net.ts:715
S._socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:578
fire @ event.ts:572
acceptChunk @ ipc.net.ts:236
_register._socket.onData.e @ ipc.net.ts:197
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
mainThreadExtensionService.ts:65 TypeError: Cannot read property 'toLocaleUpperCase' of undefined
    at Viewer.handler (/home/abc/.vscode-server/extensions/james-yu.latex-workshop-7.3.0/out/src/components/viewer.js:158)
    at WebSocket.websocket.on (/home/abc/.vscode-server/extensions/james-yu.latex-workshop-7.3.0/out/src/components/server.js:37)
    at WebSocket.emit (events.js:182)
    at Receiver.receiverOnMessage (/home/abc/.vscode-server/extensions/james-yu.latex-workshop-7.3.0/node_modules/ws/lib/websocket.js:720)
    at Receiver.emit (events.js:182)
    at Receiver.dataMessage (/home/abc/.vscode-server/extensions/james-yu.latex-workshop-7.3.0/node_modules/ws/lib/receiver.js:414)
    at Receiver.getData (/home/abc/.vscode-server/extensions/james-yu.latex-workshop-7.3.0/node_modules/ws/lib/receiver.js:346)
    at Receiver.startLoop (/home/abc/.vscode-server/extensions/james-yu.latex-workshop-7.3.0/node_modules/ws/lib/receiver.js:133)
    at Receiver._write (/home/abc/.vscode-server/extensions/james-yu.latex-workshop-7.3.0/node_modules/ws/lib/receiver.js:69)
    at doWrite (_stream_writable.js:410)
    at writeOrBuffer (_stream_writable.js:394)
    at Receiver.Writable.write (_stream_writable.js:294)
    at Socket.socketOnData (/home/abc/.vscode-server/extensions/james-yu.latex-workshop-7.3.0/node_modules/ws/lib/websocket.js:795)
    at Socket.emit (events.js:182)
    at addChunk (_stream_readable.js:283)
    at readableAddChunk (_stream_readable.js:264)
    at Socket.Readable.push (_stream_readable.js:219)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
_doInvokeHandler @ rpcProtocol.ts:394
_invokeHandler @ rpcProtocol.ts:379
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:572
a @ ipc.net.ts:421
e @ ipc.net.ts:428
fire @ event.ts:572
_receiveMessage @ ipc.net.ts:715
S._socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:578
fire @ event.ts:572
acceptChunk @ ipc.net.ts:236
_register._socket.onData.e @ ipc.net.ts:197
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
webviewElement.ts:342 [Embedded Page] Uncaught (in promise) Error: Missing PDF file.

</details>

**Screenshots**
![image](https://user-images.githubusercontent.com/34148598/62893333-50902700-bd18-11e9-918d-ae4656af599e.png)

The generated link works. It can be opened in a browser. And the browser mode also works.
The error message is weird. I'm not sure why the PDF viewer is opening the `compressed-tracemonkey-pldi-09.pdf`.

**Desktop [Required]:**
 - OS: [Windows 10]
 - VS Code version: [1.37.0]
 - Extension version: [7.3.0]

**Are you using LaTeX Workshop with VS Code Remote?**

Yes

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote WSL
- Remote Extension Version: [0.39.2]

**Additional context**

**Comment by tamuratak** [comment] 2019-08-13 01:12
Duplicate of #1494. This is a bug of VS Code 1.36. Please downgrade to 1.35, or wait the new release of VS Code.

**Closed by tamuratak** 2019-08-13 01:12 UTC

**Comment by allenjlw** [comment] 2019-08-13 01:15
I see. Thanks!
