### ISSUE TITLE
Linter shows 0 messages

### ISSUE THREAD

**Issue by veltriuk** [James-Yu/LaTeX-Workshop#167] opened 2017-06-15 12:32 UTC
Hello. 
When I first open the file of my document, Linter shows a lot of messages (157) in the Problems tab, and then suddenly shows 0 error messages, with a message of 'No problems have been detected in the workspace so far'. Seems like there is some compiling error, and crashes, showing no errors. 

This is the Output window messages.

```
[07:30:56] Linter log parsed with 157 messages.
[07:31:00] Root file remains unchanged from: c:\Users\User\Folder\LatexFile.tex.
[07:31:01] Found root file from active editor: c:\Users\User\Folder\LatexFile.tex
[07:31:01] Root file remains unchanged from: c:\Users\User\Folder\LatexFile.tex.
[07:31:01] Linter for active file started.
[07:31:05] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-I0,-f%f:%l:%c:%d:%k:%n:%m

[07:31:09] Linter for active file failed with exit code 1 and error:
[07:31:09] Linter log parsed with 0 messages.
```

**Comment by James-Yu** [comment] 2017-06-15 12:34
Have you tried restart vscode? It seems chktex encountered some problem and failed execution. The exit code is 1.

**Comment by veltriuk** [comment] 2017-06-15 12:46
Yes I have. Actually, the same log error shows up everytime I restart vscode. It repeats when I open it, and while it's open it won't check for error anymore.

`[07:44:48] Linter for active file failed with exit code 1 and error:
  
[07:44:48] Linter log parsed with 0 messages.`

**Comment by James-Yu** [comment] 2017-06-15 12:47
I cannot reproduce this problem. If possible, can you please post the content of your latex file?

**Comment by veltriuk** [comment] 2017-06-15 12:59
Sure.
Root file is called "TesisMSc.tex". If the same error happens while testing, you should be able to see it in the Problems Tab, when the bunch of errors suddenly disappear.

Thank you for your reply.

[National University of Colombia Thesis.zip](https://github.com/James-Yu/LaTeX-Workshop/files/1077662/National.University.of.Colombia.Thesis.zip)

**Comment by James-Yu** [comment] 2017-06-15 13:31
Thanks for the issue. I have identified the problem and committed a fix. I will release the fix along with some other changes soon(TM).

**Closed** 2017-06-15 13:30 UTC
