### ISSUE TITLE
Braket Notation doesn't work on Math Preview

### ISSUE THREAD

**Issue by AnimeshSinha1309** [James-Yu/LaTeX-Workshop#991] opened 2018-11-17 08:57 UTC
**Issue Description**
Math Statement Preview does not work with symbols added from external packages, eg. Braket.
![screenshot from 2018-11-17 09-08-32](https://user-images.githubusercontent.com/9739218/48659131-7979d900-ea72-11e8-9158-fe8a6e0f1610.png)

**To Reproduce**
Just write out a LaTaX document that has `\usepackage{braket}` and in the document `$\braket{val | operator}$` and hover over the Equation to see the Predicted Math output.

**Expected behavior**
The Braket notation should be converted to the way its displayed in LaTeX, as `<val | operator>`, in the preview.

**Sample TeX file**

```
\documentclass{article}

\usepackage{amsmath}
\usepackage{braket}

\begin{document}

\section{This is the Notation}
$ \braket{ val | operation } $

\end{document}

```

**Comment by tamuratak** [comment] 2018-11-17 09:34
Duplicate of #914.

**Comment by AnimeshSinha1309** [comment] 2018-11-17 14:04
Supporting packages in general may seem to be difficult, but the Bra-Ket notation seems to be common enough in the field of Physics and Math that it seems worth implementing it in the Preview. Also, I am a new developer, so can I take an attempt at fixing this?

**Comment by James-Yu** [comment] 2018-11-17 14:40
@AnimeshSinha1309 The preview heavily relies on mathJax, so that repo seems to be a better place for feature request. Contributions to the public domain are always welcomed by everyone.

**Closed by James-Yu** 2018-11-17 14:40 UTC
