### ISSUE TITLE
Default build recipe ignoring the config value of "lastUsed" since 8.11.0

### ISSUE THREAD

**Issue by Bakerbakura** [James-Yu/LaTeX-Workshop#2187] opened 2020-06-30 14:58 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Although the setting config value `latex-workshop.latex.recipe.default` is set to `"lastUsed"`, when I issue the command to Build LaTeX Project or the project is auto-built when saving the first recipe in the list is used instead of the last used recipe.

### To Reproduce

1. Open a working LaTeX document
2. Have two recipes, `pdflatex ➞ biber ➞ pdflatex × 2` and `pdflatex × 2` in the `latex.recipes` config value, with the former recipe being the first in the list
3. Have the `latex.recipe.default` config value set to `"lastUsed"`
3. Build the LaTeX document using the `pdflatex × 2` recipe via the `Build with recipe` command
4. Build the LaTeX document using the default recipe via the `Build LaTeX Project` command

### Expected behavior

In the last step, I expect the `pdflatex × 2` recipe to be run; instead, the `pdflatex ➞ biber ➞ pdflatex × 2` recipe is run.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[16:13:42] Initializing LaTeX Workshop.
[16:13:42] Creating PDF file watcher.
[16:13:42] Creating LaTeX Workshop http and websocket server.
[16:13:42] LaTeX Workshop initialized.
[16:13:42] Server created on 127.0.0.1:41029
[16:13:42] Snippet data loaded.
[16:13:42] LaTeX Workshop version: 8.11.0
[16:13:43] Handle data type: open
[16:13:43] Preview PDF file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.pdf
[16:13:43] Found files that might be root, choose the first one: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/confidence_analysis.tex,/home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex,/home/liam/Documents/Isazi/isazi-research/Consensus/tex/CrowdConfidence.tex
[16:13:43] Root file changed: from undefined to /home/liam/Documents/Isazi/isazi-research/Consensus/tex/confidence_analysis.tex
[16:13:43] Start to find all dependencies.
[16:13:43] Instantiating a new file watcher for /home/liam/Documents/Isazi/isazi-research/Consensus/tex/confidence_analysis.tex
[16:13:43] Creating Bib file watcher.
[16:13:43] Parsing a file and its subfiles: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/confidence_analysis.tex
[16:13:43] Parse fls file.
[16:13:43] Cannot find fls file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/confidence_analysis.fls
[16:13:43] Handle data type: request_params
[16:13:43] Added to file watcher: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/confidence_analysis.tex
[16:13:43] Handle data type: loaded
[16:13:43] SyncTex after build invoked.
[16:13:43] /home/liam/.config/Code/User/settings.json is not a valid LaTeX file.
[16:13:44] Found root file from active editor: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:44] Found root file from active editor: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:44] Root file changed: from /home/liam/Documents/Isazi/isazi-research/Consensus/tex/confidence_analysis.tex to /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:44] Start to find all dependencies.
[16:13:44] Root file changed -> cleaning up old file watcher.
[16:13:44] Instantiating a new file watcher for /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:44] Parsing a file and its subfiles: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:44] Parse fls file.
[16:13:44] Cannot find fls file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.fls
[16:13:44] Keep using the same root file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex.
[16:13:44] Added to file watcher: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:48] RECIPES command invoked.
[16:13:48] BUILD command invoked.
[16:13:48] Found root file from active editor: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:48] Keep using the same root file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex.
[16:13:48] Building root file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:48] Build root file /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:48] Recipe step 1: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,/home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description
[16:13:48] cwd: /home/liam/Documents/Isazi/isazi-research/Consensus/tex
[16:13:48] LaTeX build process spawned. PID: 1824319.
[16:13:49] LaTeX log parsed with 0 messages.
[16:13:49] A step in recipe finished. PID: 1824319.
[16:13:49] Recipe step 2: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,/home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description
[16:13:49] cwd: /home/liam/Documents/Isazi/isazi-research/Consensus/tex
[16:13:49] LaTeX build process spawned. PID: 1824329.
[16:13:50] LaTeX log parsed with 0 messages.
[16:13:50] Recipe of length 2 finished. PID: 1824329.
[16:13:50] Successfully built /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex.
[16:13:50] Refresh PDF viewer for /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.pdf
[16:13:50] Parse fls file.
[16:13:50] Cannot find fls file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.fls
[16:13:50] Preview PDF file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.pdf
[16:13:50] Handle data type: loaded
[16:13:50] SyncTex after build invoked.
[16:13:50] Try to synctex /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.pdf
[16:13:53] File watcher - file changed: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:53] Parsing a file and its subfiles: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:53] Parse fls file.
[16:13:53] Cannot find fls file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.fls
[16:13:53] Auto build started detecting the change of a file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:53] BUILD command invoked.
[16:13:53] Building root file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:53] Build root file /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:13:53] Recipe step 1: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,/home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description
[16:13:53] cwd: /home/liam/Documents/Isazi/isazi-research/Consensus/tex
[16:13:53] LaTeX build process spawned. PID: 1824368.
[16:13:54] LaTeX log parsed with 0 messages.
[16:13:54] A step in recipe finished. PID: 1824368.
[16:13:54] Recipe step 2: biber, model_description
[16:13:54] cwd: /home/liam/Documents/Isazi/isazi-research/Consensus/tex
[16:13:54] LaTeX build process spawned. PID: 1824373.
[16:13:55] Recipe returns with error: 2/null. PID: 1824373. message: .
[16:13:55] Cleaning auxiliary files and retrying build after toolchain error.
[16:13:55] File cleaned: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.aux
[16:13:55] File cleaned: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.bbl
[16:13:55] File cleaned: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.out
[16:13:55] File cleaned: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.blg
[16:13:55] File cleaned: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.toc
[16:13:55] File cleaned: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.log
[16:13:55] Recipe step 1: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,/home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description
[16:13:55] cwd: /home/liam/Documents/Isazi/isazi-research/Consensus/tex
[16:13:55] LaTeX build process spawned. PID: 1824380.
[16:13:55] LaTeX log parsed with 20 messages.
[16:13:55] A step in recipe finished. PID: 1824380.
[16:13:55] Recipe step 2: biber, model_description
[16:13:55] cwd: /home/liam/Documents/Isazi/isazi-research/Consensus/tex
[16:13:55] LaTeX build process spawned. PID: 1824384.
[16:13:56] Recipe returns with error: 2/null. PID: 1824384. message: .
[16:23:23] RECIPES command invoked.
[16:23:24] BUILD command invoked.
[16:23:24] Cannot find LaTeX root file.
[16:23:26] Found root file from active editor: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:23:26] Keep using the same root file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex.
[16:23:28] RECIPES command invoked.
[16:23:29] BUILD command invoked.
[16:23:29] Found root file from active editor: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:23:29] Keep using the same root file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex.
[16:23:29] Building root file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:23:29] Build root file /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:23:29] Recipe step 1: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,/home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description
[16:23:29] cwd: /home/liam/Documents/Isazi/isazi-research/Consensus/tex
[16:23:29] LaTeX build process spawned. PID: 1827442.
[16:23:30] LaTeX log parsed with 0 messages.
[16:23:30] A step in recipe finished. PID: 1827442.
[16:23:30] Recipe step 2: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,/home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description
[16:23:30] cwd: /home/liam/Documents/Isazi/isazi-research/Consensus/tex
[16:23:30] LaTeX build process spawned. PID: 1827443.
[16:23:30] LaTeX log parsed with 0 messages.
[16:23:30] Recipe of length 2 finished. PID: 1827443.
[16:23:30] Successfully built /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex.
[16:23:30] Refresh PDF viewer for /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.pdf
[16:23:30] Parse fls file.
[16:23:30] Cannot find fls file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.fls
[16:23:30] Preview PDF file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.pdf
[16:23:30] Handle data type: loaded
[16:23:30] SyncTex after build invoked.
[16:23:30] Try to synctex /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.pdf
[16:23:32] BUILD command invoked.
[16:23:32] Found root file from active editor: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:23:32] Keep using the same root file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex.
[16:23:32] Building root file: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:23:32] Build root file /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.tex
[16:23:32] Recipe step 1: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,/home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description
[16:23:32] cwd: /home/liam/Documents/Isazi/isazi-research/Consensus/tex
[16:23:32] LaTeX build process spawned. PID: 1827484.
[16:23:33] LaTeX log parsed with 0 messages.
[16:23:33] A step in recipe finished. PID: 1827484.
[16:23:33] Recipe step 2: biber, model_description
[16:23:33] cwd: /home/liam/Documents/Isazi/isazi-research/Consensus/tex
[16:23:33] LaTeX build process spawned. PID: 1827485.
[16:23:34] Recipe returns with error: 2/null. PID: 1827485. message: .
[16:23:34] Cleaning auxiliary files and retrying build after toolchain error.
[16:23:34] File cleaned: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.bbl
[16:23:34] File cleaned: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.aux
[16:23:34] File cleaned: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.blg
[16:23:34] File cleaned: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.out
[16:23:34] File cleaned: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.toc
[16:23:34] File cleaned: /home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description.log
[16:23:34] Recipe step 1: pdflatex, -synctex=1,-interaction=nonstopmode,-file-line-error,/home/liam/Documents/Isazi/isazi-research/Consensus/tex/model_description
[16:23:34] cwd: /home/liam/Documents/Isazi/isazi-research/Consensus/tex
[16:23:34] LaTeX build process spawned. PID: 1827502.
[16:23:34] LaTeX log parsed with 20 messages.
[16:23:34] A step in recipe finished. PID: 1827502.
[16:23:34] Recipe step 2: biber, model_description
[16:23:34] cwd: /home/liam/Documents/Isazi/isazi-research/Consensus/tex
[16:23:34] LaTeX build process spawned. PID: 1827507.
[16:23:35] Recipe returns with error: 2/null. PID: 1827507. message: .
[16:44:02] LOG command invoked.
[16:44:11] LOG command invoked.
[16:44:16] LOG command invoked.
[16:44:19] LOG command invoked.
[16:44:21] LOG command invoked.

```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

Nothing suspicious.
```

## Screenshots

None applicable

## Desktop [Required]
 - OS: Ubuntu 20.04
 - VS Code version: 1.46.0
 - Extension version: 8.11.0
 - TeX distribution version: TeX Live 2019, revision 53225

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

None

**Comment by jlelong** [comment] 2020-06-30 15:04
Duplicate of #2172

**Closed by jlelong** 2020-06-30 15:04 UTC
