### ISSUE TITLE
Building failed in iCloud Drive

### ISSUE THREAD

**Issue by PhiloZhang** [James-Yu/LaTeX-Workshop#276] opened 2017-09-17 14:00 UTC
### Description

Building tex file fails in iCloud Drive, but works fine in normal path.

### How to reproduce

1.  Put a latex project which could be built successfully in normal path to iCloud Drive, then try to build it.
2. 
3. 

### Expected behavior

Building successfully

### Actual behavior

Latex toolchain terminated with error.

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>
[09:59:45] Initializing LaTeX Workshop.
[09:59:45] Creating LaTeX Workshop http and websocket server.
[09:59:45] LaTeX Workshop initialized.
[09:59:45] Found root file from active editor: /Users/philo/Library/Mobile Documents/com~apple~CloudDocs/Extra/510Extra.tex
[09:59:45] Root file changed from: undefined. Find all dependencies.
[09:59:45] Instatiating new file watcher for /Users/philo/Library/Mobile Documents/com~apple~CloudDocs/Extra/510Extra.tex
[09:59:45] Parsing /Users/philo/Library/Mobile Documents/com~apple~CloudDocs/Extra/510Extra.tex
[09:59:45] Found .bib file /Users/philo/Library/Mobile Documents/com~apple~CloudDocs/Extra/sample.bib
[09:59:45] Creating file watcher for .bib files.
[09:59:45] Parsing .bib entries from /Users/philo/Library/Mobile Documents/com~apple~CloudDocs/Extra/sample.bib
[09:59:45] Parsed 1 .bib entries from /Users/philo/Library/Mobile Documents/com~apple~CloudDocs/Extra/sample.bib.
[09:59:45] Server created on 127.0.0.1:65473
[09:59:46] Default environments loaded
[09:59:46] LaTeX Workshop version: 3.5.2
[09:59:46] Default commands loaded
[09:59:46] Default unimathsymbols loaded
[09:59:50] BUILD command invoked.
[09:59:50] Found root file from active editor: /Users/philo/Library/Mobile Documents/com~apple~CloudDocs/Extra/510Extra.tex
[09:59:50] Root file remains unchanged from: /Users/philo/Library/Mobile Documents/com~apple~CloudDocs/Extra/510Extra.tex.
[09:59:50] Building root file: /Users/philo/Library/Mobile Documents/com~apple~CloudDocs/Extra/510Extra.tex
[09:59:50] Build root file /Users/philo/Library/Mobile Documents/com~apple~CloudDocs/Extra/510Extra.tex
[09:59:50] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdfxe,-xelatex,/Users/philo/Library/Mobile Documents/com~apple~CloudDocs/Extra/510Extra
[09:59:50] Toolchain returns with error: 12/null.
[09:59:52] Root file remains unchanged from: /Users/philo/Library/Mobile Documents/com~apple~CloudDocs/Extra/510Extra.tex.

<details>
<summary>Developer Tools Console</summary>

</details>

### Additional Information

basicTex 2017
Latexmk 4.52c

"latex-workshop.latex.toolchain": [{
        "command": "latexmk",
        "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "-pdfxe",
            "-xelatex",
            "%DOC%"
        ]
    }]

**Comment by James-Yu** [comment] 2017-09-19 07:10
Duplicate of #234 #255 .

**Closed by James-Yu** 2017-09-19 07:10 UTC
