### ISSUE TITLE
Text selection Autosurround does not work

### ISSUE THREAD

**Issue by hanzckernel** [James-Yu/LaTeX-Workshop#3565] opened 2022-11-30 22:20 UTC
## Preliminary questions [Required]

The text selection are not remembering the selected text after I type environments. 

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: N/A

## Describe the bug [Required]

For example, after selecting `a sample text` in previous cases I type `fbf`which the VSintelliSense will automatically display the `\mathbf` suggestion, after completion the `a sample text` will be wrapped around to give `\mathbf{a sample text}`. __(without copying the text manually)__ 

But now it is not working. Instead the selected text are directly replaced, like other text editor.

The vscode default brackets autosurround still works.

### Expected behavior

as described above.

## Logs [Required]

N/A as it is not logged.

### LaTeX Workshop Output [Required]

```
N/A as it is not displayed in the Output.
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: [Ventura 13.0.1 / Monterey 12.6]
 - VS Code version: [1.73.1]
 - Extension version: [9.0.1]
 - TeX distribution version: [pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019)

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

 No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

### Additional context

I have looked into your intellisense manual as well as the vscode intellisense manual but did not find any solution. Apart from OS and Vscode upgrade I have not change my setting file manually before this bug shows up.

**Comment by jlelong** [comment] 2022-12-01 16:04
Duplicate of #3531

**Closed by jlelong** 2022-12-01 16:04 UTC
