### ISSUE TITLE
PDF sidebar's light gray background makes bookmarks in white font unreadable when OS is in dark mode

### ISSUE THREAD

**Issue by gdalle** [James-Yu/LaTeX-Workshop#2640] opened 2021-04-27 06:00 UTC
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

## Describe the bug [Required]

When the OS theme is dark, the PDF bookmarks in the viewer's sidebar are written in white font, which makes them unreadable due to the light gray background.

### To Reproduce

1. Compile the following file

```latex
\documentclass{article}
\usepackage{bookmark}
\begin{document}
    \section{Section 1}
    \section{Section 2}
    \section{Section 3}
\end{document}
```

2. Open the PDF using LaTeX Workshop's default viewer

### Expected behavior

In OS dark mode, I would expect the sidebar's background to be black or dark gray, and the sidebar's font to be white. Note that this is already the current behavior when the window becomes small and the sidebar is forced to overlap with the PDF display (see screenshots below).

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[07:51:50] Initializing LaTeX Workshop.
[07:51:50] Extension root: /Users/guillaume/.vscode/extensions/james-yu.latex-workshop-8.17.0
[07:51:50] $PATH: /Users/guillaume/perl5/bin:/Users/guillaume/opt/miniconda3/bin:/Users/guillaume/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
[07:51:50] $SHELL: /bin/zsh
[07:51:50] Creating PDF file watcher.
[07:51:50] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[07:51:50] Creating LaTeX Workshop http and websocket server.
[07:51:51] LaTeX Workshop initialized.
[07:51:51] Trigger characters for intellisense of LaTeX documents: ["\\","{",",","(","["]
[07:51:51] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[]}
[07:51:51] Current workspace folders: ["file:///Users/guillaume/Downloads"]
[07:51:51] Current workspaceRootDir: /Users/guillaume/Downloads
[07:51:51] Found root file from active editor: /Users/guillaume/Downloads/test.tex
[07:51:51] Root file changed: from undefined to /Users/guillaume/Downloads/test.tex
[07:51:51] Start to find all dependencies.
[07:51:51] Root file languageId: latex
[07:51:51] Creating a new file watcher for /Users/guillaume/Downloads/test.tex
[07:51:51] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[07:51:51] Creating Bib file watcher.
[07:51:51] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[07:51:51] Parsing a file and its subfiles: /Users/guillaume/Downloads/test.tex
[07:51:51] Parse fls file.
[07:51:51] Fls file found: /Users/guillaume/Downloads/test.fls
[07:51:51] Parse aux file: /Users/guillaume/Downloads/test.aux
[07:51:51] Server created on 127.0.0.1:51156
[07:51:51] Added to file watcher: /Users/guillaume/Downloads/test.tex
[07:51:51] Snippet data loaded.
[07:51:51] Checking for duplicate labels: /Users/guillaume/Downloads/test.tex.
[07:52:00] BUILD command invoked.
[07:52:00] The document of the active editor: file:///Users/guillaume/Downloads/test.tex
[07:52:00] The languageId of the document: latex
[07:52:00] Current workspace folders: ["file:///Users/guillaume/Downloads"]
[07:52:00] Current workspaceRootDir: /Users/guillaume/Downloads
[07:52:00] Found root file from active editor: /Users/guillaume/Downloads/test.tex
[07:52:00] Keep using the same root file: /Users/guillaume/Downloads/test.tex
[07:52:00] Building root file: /Users/guillaume/Downloads/test.tex
[07:52:00] Build root file /Users/guillaume/Downloads/test.tex
[07:52:00] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/Users/guillaume/Downloads,/Users/guillaume/Downloads/test
[07:52:00] Recipe step env: {}
[07:52:00] cwd: /Users/guillaume/Downloads
[07:52:00] LaTeX build process spawned. PID: 4484.
[07:52:01] Recipe of length 1 finished. PID: 4484.
[07:52:01] Successfully built /Users/guillaume/Downloads/test.tex.
[07:52:06] Restoring the PDF viewer at the column 0 from the state: {"type":"state","state":{"path":"/Users/guillaume/Downloads/test.pdf","scale":"auto","scrollMode":0,"spreadMode":0,"scrollTop":0,"scrollLeft":0,"trim":0}}
[07:52:06] The internal PDF viewer url: http://localhost:51156/viewer.html?incode=1&file=pdf..JTJGVXNlcnMlMkZndWlsbGF1bWUlMkZEb3dubG9hZHMlMkZ0ZXN0LnBkZg
[07:52:06] Handle data type: open
[07:52:06] Preview PDF file: /Users/guillaume/Downloads/test.pdf
[07:52:06] Handle data type: request_params
[07:52:06] Sending the settings of the PDF viewer for initialization: {"type":"params","scale":"auto","trim":0,"scrollMode":0,"spreadMode":0,"hand":false,"invertMode":{"enabled":false,"brightness":1,"grayscale":0.6,"hueRotate":180,"invert":0,"sepia":0},"bgColor":"#ffffff","keybindings":{"synctex":"ctrl-click"}}
[07:52:06] Handle data type: loaded
[07:52:32] LOG command invoked: default
```

### Developer Tools Console [Required]

```
workbench.desktop.main.js:60 [25h] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ workbench.desktop.main.js:60
workbench.desktop.main.js:60     at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:58:58492
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:58:60975
    at new Promise (<anonymous>)
    at Object.x [as toPromise] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:58:60956)
    at k.whenInitialized (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:4475)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:3211
    at f (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:68:11213)
    at Object.onFirstListenerAdd (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:3202)
    at _event._event (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:872)
    at l.set input [as input] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:4229)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:7162
check @ workbench.desktop.main.js:60
workbench.desktop.main.js:1543 [Embedded Page] webviewerloaded: SecurityError: Blocked a frame with origin "http://localhost:51156" from accessing a cross-origin frame.
2workbench.desktop.main.js:1543 [Embedded Page] #layers is undefined.
2workbench.desktop.main.js:1543 [Embedded Page] #layers_label is undefined.
workbench.desktop.main.js:1543 [Embedded Page] PDF 77ebc592fdb2c407deda2f3e0466cb1c [1.5 pdfTeX-1.40.21 / LaTeX with hyperref] (PDF.js: 2.6.347)
workbench.desktop.main.js:1543 [Embedded Page] #toggle_sidebar_notification2 is undefined.
```

## Screenshots

The following screenshots show the behavior when the OS is in dark mode (with large and small window), and then when it is in light mode (with large and small window).

<img width="1136" alt="dark_mode_large_window" src="https://user-images.githubusercontent.com/22795598/116192372-0ccc9380-a72e-11eb-9d88-feff34c0b3a7.png">
<img width="907" alt="dark_mode_small_window" src="https://user-images.githubusercontent.com/22795598/116192378-0dfdc080-a72e-11eb-85ee-432d2e9f580d.png">
<img width="1165" alt="light_mode_large_window" src="https://user-images.githubusercontent.com/22795598/116192380-0e965700-a72e-11eb-9e4d-2771d0a785e4.png">
<img width="888" alt="light_mode_small_window" src="https://user-images.githubusercontent.com/22795598/116192383-0f2eed80-a72e-11eb-826d-893fb3882155.png">

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: MacOS Big Sur 11.1
 - VS Code version: 1.55.2 (Universal)
 - Extension version: 8.17.0
 - TeX distribution version: TeX Live 2020

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

The problem also appeared on Ubuntu 20.04 with a dark OS theme, which is how I diagnosed it in the first place.

**Comment by tamuratak** [comment] 2021-04-27 07:03
This issue will be fixed after updating PDF.js to v2.8. We are not sure when we will update it. Already fixed in mozilla/pdf.js/pull/13039.

**Comment by tamuratak** [comment] 2021-04-27 07:28
@gdalle Would you like to check whether the issue is fixed in the latest viewer? You can view any PDF file with the viewer. 
- https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by gdalle** [comment] 2021-04-27 07:30
Yes, I forgot to mention it in the issue but the problem does not appear in Firefox, no matter the size of the window

**Comment by tamuratak** [comment] 2021-04-27 07:34
Thank you.

**Closed by tamuratak** 2021-04-27 07:34 UTC
Labels: pdf.js-issue
