### ISSUE TITLE
Inconsistent pdf->source sync with symlink folder

### ISSUE THREAD

**Issue by LucaMoschella** [James-Yu/LaTeX-Workshop#1070] opened 2018-12-16 18:24 UTC
I have as workspace a symlink folder.
When I do `ctrl + click` to go from the pdf to the source, the file that is opened is the one with the real path.

e.g.
![image](https://user-images.githubusercontent.com/11019190/50057211-8f5ce580-0167-11e9-9b3e-25981bca00e5.png)

![image](https://user-images.githubusercontent.com/11019190/50057217-9d126b00-0167-11e9-9a21-6fbfcc009dfd.png)

The problems:

* If I modify this automatically opened file, the build process does not work. I have to close both, re-open the symlinked one and then it works.
* There are some problems on how code handles this situation, when the same file is opened from multiple paths: https://github.com/Microsoft/vscode/issues/12448
 
The problem seems to appear even if I open the real folder in the workspace. Maybe the problem is that it is on a mount point?
On the notebook, where the folder is in ~/Documents I do not have this problem

**Comment by jlelong** [comment] 2018-12-19 06:15
The problem is that `synctex` fully resolves symlinks during compilation and writes the resolved path in the `.synctex.gz` file. Not clear to me how we can handle the problem from the extension side. Don't we have to wait until vscode handles symlink properly?

Yet, I am a bit confused by 

> The problem seems to appear even if I open the real folder in the workspace. Maybe the problem is that it is on a mount point?

**Comment by tamuratak** [comment] 2018-12-20 06:56
I will look into this issue. Since any fix will conflict with my PR, #1030, please wait until the PR is merged.

**Comment by jlelong** [comment] 2018-12-20 11:11
I just want to share my thoughts about this problem.
- vscode's API does not give access to the list of opened editors: see [the feature request](https://github.com/Microsoft/vscode/issues/15178).
- In the extension, we keep track the tex file tree in [`Manager.texFileTree`](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/manager.ts#L15).
- Before firing up a new editor from `synctex`, we could check whether a from `Manager.texFileTree` resolves to the result of `synctex`.
Hope this will help.

**Comment by LucaMoschella** [comment] 2018-12-20 21:18
> Yet, I am a bit confused by
> 
> > The problem seems to appear even if I open the real folder in the workspace. Maybe the problem is that it is on a mount point?

I'm confused too, since I don't seem to be able to reproduce the problem with a new, clean workspace. As I have time I'll try to do more tests

**Closed** 2018-12-23 16:54 UTC

**Comment by jlelong** [comment] 2018-12-23 16:56
@tamuratak I have just fixed this for `Kpathsea/synctex` but I am not sure what to do for `synctexjs`. Can you have a look.

**Comment by tamuratak** [comment] 2018-12-24 01:52
I can't reproduce this issue even without 8b5d00b. 

Mac OS X: 10.13.6
VS Code: 1.30.1
LaTeX Workshop Version: 5.19.0

**Comment by jlelong** [comment] 2018-12-24 07:08
I have managed to reproduce the issue with the following directory structure
```
top
  |-- dir1
  |      |-- main.tex
  |      |-- subfile.tex (called by main.tex via \include)
  |-- link-to-dir1
```

Run `code -n link-to-dir1` and open `main.tex`. Then, compile and view. Call `synctex` from the PDF file at a position resolving to `subfile.tex`, it will open `top/dir1/subfile.tex` instead fo `link-to-dir1/subfile.tex`.

Not so easy to reproduce but it can be annoying. I hope 8b5d00b fixes this properly.

**Comment by tamuratak** [comment] 2018-12-24 08:52
Thank you, I can reproduce this issue now. I also confirm that 8b5d00b solves it.

**Comment by LucaMoschella** [comment] 2018-12-24 09:44
So do I, I'm not experiencing the problem anymore!
