### ISSUE TITLE
Error displaying PDF

### ISSUE THREAD

**Issue by dsteg** [James-Yu/LaTeX-Workshop#340] opened 2017-12-07 20:52 UTC
### Description

Opening PDF viewer in tab sometimes fails with error:
"An error occurred while loading the PDF."
PDF opens fine with "view PDF file in web page"

### How to reproduce
Load multifile tex project.
Open PDF viewer (run "view PDF file in new tab")
Close it.
Open it again.
Viewer error: "An error occurred while loading the PDF."
Clicking on "more details" reveals:
PDF.js v1.5.188 (build: 0e2d50f)
Message: file origin does not match viewer's

<img width="736" alt="untitled 3" src="https://user-images.githubusercontent.com/9674007/33738211-90934868-db66-11e7-8d1c-9c62482b5d03.png">

### Log messages
[15:49:27] Found root file by magic comment: ***PATH***/MainFile.tex
[15:49:27] Root file remains unchanged from: ***PATH***/MainFile.tex.
[15:49:27] No PDF viewer connected for ***PATH***/MainFile.pdf
[15:49:27] Serving PDF file at http://127.0.0.1:56036/viewer.html?file=/pdf:%2FUsers%2Fxxxx%2FGIT%2FRedistBook%2FMainFile.pdf
[15:49:27] Open PDF tab for ***PATH***/MainFile.pdf
[15:49:27] Found root file by magic comment: ***PATH***/MainFile.tex
[15:49:27] Root file remains unchanged from: ***PATH***/MainFile.tex.

**Comment by James-Yu** [comment] 2017-12-08 01:39
Can you please provide a minimal working example? Thanks.

**Comment by Leithian** [comment] 2017-12-11 11:24
I had the same problem. For me, disabling an extra pdf-viewer for VS Code that I had installed seems to have solved the problem.

**Comment by SirNO** [comment] 2017-12-11 19:02
Yes the problem is related to vscode-pdf. One solution is to just uninstall the pdf viewer. However, since it is really nice to have arbitrary pdfs showing in vscode this might be rather inconvenient.

Anyways, I investigated a bit and found that it seems to be a conflict with viewer.js. Once you open a pdf, the viewer.js file of vscode-pdf is used. (please bare with me and my terminology, I never used javascript, so i really have no clue what i am talking about). Anyways, the error gets thrown in `validateFileURL`, because `viewerOrigin` and `fileOrigin`, i.e. `viewerOrigin = 'file://` and `fileOrigin = latex-workshop-pdf://`. 

Adding "file://" to `HOSTED_VIEWER_ORIGINS` of the vscode-pdf viewer.js unfortunately does not supply a quick fix, but just leads to some loading error. 

It would take me forever until I understand all of this and am able to fix this myself. Maybe the information above helps. It would be super nice to be able to use the two extensions along side each other (or just view any pdfs in latex workshop)

**Comment by James-Yu** [comment] 2017-12-19 03:14
Conflict with `vscode-pdf` is a known problem. I need to dig into their source code to see what was going on. It seems that the other extension is not maintained, so I'm a bit worried on that.

**Comment by James-Yu** [comment] 2017-12-26 14:10
This is due to the quite 'dirty' way that vscode-pdf did to capture all pdf viewer requests: https://github.com/tomoki1207/vscode-pdfviewer/blob/master/src/extension.ts#L30 . I still need to find a workaround to invalidate this hack.

**Comment by James-Yu** [comment] 2017-12-26 14:22
I've double checked the api and the way vscode-pdf injected into the event handler. It seems to be impossible to have a solution that only involves changes on LaTeX Workshop. I will close this issue for now and make PR on vscode-pdf soon.

**Closed by James-Yu** 2017-12-26 14:22 UTC
Labels: help wanted

**Comment by spencerkraisler** [comment] 2019-05-30 02:36
I am having this issue too. Why is no one fixing this?
