### ISSUE TITLE
Magic comment (% !TeX root) does not trigger file change (dependency not explicit by main.tex)

### ISSUE THREAD

**Issue by JimmyZJX** [James-Yu/LaTeX-Workshop#2210] opened 2020-07-16 04:56 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

### To Reproduce

1. Open an existing LaTeX project, where `main.tex` is the main file
2. Create an empty `test.tex` file, which does not depend explicitly by main.tex
3. Add the magic comment `% !TeX root = ./main.tex`
4. Save `test.tex`

### Expected behavior

A rebuild on `main.tex` should be launched

### LaTeX Workshop Output [Required]

```
The content of the log indicates that the "test.tex" is not being watched for changes
```

### Developer Tools Console [Required]

```
Nothing special
```

## Desktop [Required]
 - OS: Windows 10
 - VS Code version: 1.46.1
 - Extension version: 8.11.1
 - TeX distribution version: MiKTeX 2.9.7400 64-bit

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

The real situation is this:

I must use a 3rd-party tool to generate proper tex files through my source tex file (sub-files), which basically formats several math equations in it (used for research).

So I configured LaTeX Workshop to compile my LaTeX project directly by `make`, and mark the magic comment to each one of my source tex file. It works fine if I simply edit my `main.tex` or any other files, but not when editing my source tex files.

I think a proper solution is to also trigger a LaTeX build when the user saves the current file, in addition to the current file change hook approach. This should also solve WSL2 hook problem 90% of the time.

(I personally can live with no file watchers, such as when git pull, etc; but I definitely want `Ctrl+S` to trigger a build reliably)

**Comment by tamuratak** [comment] 2020-07-16 05:00
Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

**Comment by JimmyZJX** [comment] 2020-07-16 05:44
LaTeX Workshop log:

```
[13:42:29] Initializing LaTeX Workshop.
[13:42:29] Creating PDF file watcher.
[13:42:29] pdflatex is provided by MiKTeX
[13:42:29] Creating LaTeX Workshop http and websocket server.
[13:42:30] LaTeX Workshop initialized.
[13:42:30] Found root file from active editor: c:\Apps\main.tex
[13:42:30] Root file changed: from undefined to c:\Apps\main.tex
[13:42:30] Start to find all dependencies.
[13:42:30] Instantiating a new file watcher for c:\Apps\main.tex
[13:42:30] Creating Bib file watcher.
[13:42:30] Parsing a file and its subfiles: c:\Apps\main.tex
[13:42:30] Parse fls file.
[13:42:30] Cannot find fls file: c:\Apps\main.fls
[13:42:30] Server created on 127.0.0.1:38763
[13:42:30] Added to file watcher: c:\Apps\main.tex
[13:42:30] Snippet data loaded.
[13:42:30] LaTeX Workshop version: 8.11.1
[13:42:32] File watcher - file changed: c:\Apps\main.tex
[13:42:32] Parsing a file and its subfiles: c:\Apps\main.tex
[13:42:32] Parse fls file.
[13:42:32] Cannot find fls file: c:\Apps\main.fls
[13:42:32] Auto build started detecting the change of a file: c:\Apps\main.tex
[13:42:32] BUILD command invoked.
[13:42:32] Building root file: c:\Apps\main.tex
[13:42:32] Build root file c:\Apps\main.tex
[13:42:32] Recipe step 1: texify, --synctex,--pdf,--tex-option="-interaction=nonstopmode",--tex-option="-file-line-error",c:/Apps/main.tex
[13:42:32] cwd: c:\Apps
[13:42:32] LaTeX build process spawned. PID: 1992.
[13:42:33] Preview PDF file: c:\Apps\main.pdf
[13:42:33] Handle data type: open
[13:42:33] Handle data type: request_params
[13:42:34] Handle data type: loaded
[13:42:35] LaTeX log parsed with 0 messages.
[13:42:35] Recipe of length 1 finished. PID: 1992.
[13:42:35] Successfully built c:\Apps\main.tex.
[13:42:35] Refresh PDF viewer for c:\Apps\main.pdf
[13:42:35] Parse fls file.
[13:42:35] Cannot find fls file: c:\Apps\main.fls
[13:42:36] Preview PDF file: c:\Apps\main.pdf
[13:42:36] Handle data type: loaded
[13:42:38] Found root file by magic comment: c:\Apps\main.tex
[13:42:38] Keep using the same root file: c:\Apps\main.tex.
[13:42:44] LOG command invoked.
[13:42:44] Found root file by magic comment: c:\Apps\main.tex
[13:42:44] Keep using the same root file: c:\Apps\main.tex.
```

LaTeX compiler log
```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 2.9.7400 64-bit)
entering extended mode
(c:/Apps/main.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-04-06>
("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex/latex/base\size10.clo"))
("C:\Program Files\MiKTeX 2.9\tex/latex/geometry\geometry.sty"
("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\keyval.sty")
("C:\Program Files\MiKTeX 2.9\tex/generic/iftex\ifvtex.sty"
("C:\Program Files\MiKTeX 2.9\tex/generic/iftex\iftex.sty"))
("C:\Program Files\MiKTeX 2.9\tex/latex/geometry\geometry.cfg"))
("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amsmath.sty"
For additional information on amsmath, use the `?' option.
("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amstext.sty"
("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amsgen.sty"))
("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amsbsy.sty")
("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amsopn.sty"))
("C:\Program Files\MiKTeX 2.9\tex/latex/amsfonts\amssymb.sty"
("C:\Program Files\MiKTeX 2.9\tex/latex/amsfonts\amsfonts.sty"))
("C:\Program Files\MiKTeX 2.9\tex/latex/mathtools\mathtools.sty"
("C:\Program Files\MiKTeX 2.9\tex/latex/tools\calc.sty")
("C:\Program Files\MiKTeX 2.9\tex/latex/mathtools\mhsetup.sty"))
("C:\Program Files\MiKTeX 2.9\tex/latex/tools\enumerate.sty")
("C:\Program Files\MiKTeX 2.9\tex/latex/l3backend\l3backend-pdfmode.def")
(main.aux)
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\graphicx.sty"
("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\graphics.sty"
("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\trig.sty")
("C:\Program Files\MiKTeX 2.9\tex/latex/graphics-cfg\graphics.cfg")
("C:\Program Files\MiKTeX 2.9\tex/latex/graphics-def\pdftex.def"
("C:\Program Files\MiKTeX 2.9\tex/context/base/mkii\supp-pdf.mkii"
[Loading MPS to PDF converter (version 2006.09.02).]
))) ("C:\Program Files\MiKTeX 2.9\tex/latex/epstopdf-pkg\epstopdf-base.sty"))
("C:\Program Files\MiKTeX 2.9\tex/latex/amsfonts\umsa.fd")
("C:\Program Files\MiKTeX 2.9\tex/latex/amsfonts\umsb.fd") [1{C:/Users/Jimmy/Ap
pData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}] (main.aux) )<C:/Program Files
/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmr10.pfb><C:/Program Files/MiKTeX 2
.9/fonts/type1/public/amsfonts/cm/cmr12.pfb><C:/Program Files/MiKTeX 2.9/fonts/
type1/public/amsfonts/cm/cmr7.pfb>
Output written on main.pdf (1 page, 28585 bytes).
SyncTeX written on main.synctex.gz.
Transcript written on main.log.
```

**Comment by jlelong** [comment] 2020-07-16 09:55
See [the wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#Multi-File-Projects) for a description of how the dependency tree is computed. By design, if a file is not included, in a way or an other, in the root file, it is not listed as a dependency and I do not really feel like changing it.

As #2211 is a broader approach of the current issue, I am closing this one and I suggest to continue the discussion there.

**Closed by jlelong** 2020-07-16 09:55 UTC
