### ISSUE TITLE
\\ auto completion

### ISSUE THREAD

**Issue by MegaZeus101** [James-Yu/LaTeX-Workshop#1687] opened 2019-09-11 03:22 UTC
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.**

**Describe the bug [Required]**
 For some reason `\\` has a `\setminus` auto-complete attached to the latter `\`

**To Reproduce**
1. Create any LaTeX document
2. Attempt to enter `\\`
3. See error

**Expected behavior**
`\\` to not auto complete `\\setminus`

Logs are unrelated I believe as there is no compilation error or anything.

**Screenshots**
![image](https://user-images.githubusercontent.com/9603006/64665740-3cc00980-d419-11e9-94ae-4b764f397d47.png)

**Desktop [Required]:**
 - OS: Windows 10
 - VS Code version: 1.38.0
 - Extension version: 8.1.0

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Additional context**
I'll be honest, I'm pretty sure I boned this up by myself somehow and it's not a LaTeX Workshop issue, but I've been unable to find any fixes, so I'm unsure.

**Comment by tamuratak** [comment] 2019-09-11 03:51
duplicate of #1671

**Closed by tamuratak** 2019-09-11 03:51 UTC
