### ISSUE TITLE
How to prevent "Open compiler log" window appearing every time?

### ISSUE THREAD

**Issue by ofenerci** [James-Yu/LaTeX-Workshop#1779] opened 2019-11-01 10:07 UTC
Every time there is an error in my LaTeX document and I compile it, there is a warning window appear with "Recipe Terminated with error." I don't want to use mouse every time to open "compiler log" to see errors. I wonder there is any way to see errors without distracted with this "small frame" appearing every time and without clicking "Open Compiler log" button. 

I would like to jump to problems tab (showing LaTeX errors) with a keyboard shortcut and go to back to my writing with a keyboard shortcut again like a Vim or Emacs. 

Thanks,

**Comment by trevorgunn** [comment] 2019-11-01 14:42
Duplicate of #898 Solution is to set [`latex-workshop.message.error.show`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshopmessageerrorshow) to false.

**Closed** 2019-11-01 15:17 UTC
Labels: feature-request
