### ISSUE TITLE
Recipe terminated with errors:

### ISSUE THREAD

**Issue by david-waterworth** [James-Yu/LaTeX-Workshop#1517] opened 2019-07-19 01:49 UTC
is it possible to dismiss the "Recipe terminated with errors:" toaster pop-up once the error is fixed?

i.e. if I compile an invalid tex file I get an error pop-up "Recipe terminated with errors:" (also as an aside and identical warning pop-up). 

If I fix the error and recompile the error isn't dismissed, it sits in the bottom left of my screens until I acknowledge it.

Is there any way of dismissing this automatically. I generally dislike these sorts of notifications - I have multiple 4K monitors, and am running linux which unlike iOS and MS Windows has the notification area on the top of the screen so I tend to ignore / not see stuff on the bottom.

**Comment by tamuratak** [comment] 2019-07-19 02:31
duplicate of #898

**Closed by tamuratak** 2019-07-19 02:31 UTC
Labels: feature-request
