### ISSUE TITLE
Bracket in Math environment

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [James-Yu/LaTeX-Workshop#396] opened 2018-01-29 14:55 UTC
There's no indicator of brackets in math environment. 

i.e. in normal mode, there's something like this
![image](https://user-images.githubusercontent.com/25204046/35516623-2f9dca3c-0547-11e8-87c1-54635307b94f.png)
but in math environment it disappears like 
![image](https://user-images.githubusercontent.com/25204046/35516658-4ffdff54-0547-11e8-83ba-ccf558ecc8c4.png)
or 
![image](https://user-images.githubusercontent.com/25204046/35516748-8f8d31c6-0547-11e8-8067-fc58fd93347f.png)

What's wrong?

**Comment by James-Yu** [comment] 2018-01-30 02:54
Duplicate of #292

**Closed by James-Yu** 2018-01-30 02:54 UTC
