### ISSUE TITLE
Missing PDF after updating VSCode.

### ISSUE THREAD

**Issue by nakamin** [James-Yu/LaTeX-Workshop#1494] opened 2019-07-10 04:11 UTC
This is happening on two different machines after the most recent VSCode update. It worked perfectly before the update which was applied a few minutes ago.
**Dev Tools**
![image](https://user-images.githubusercontent.com/17557668/60939671-90419a00-a2a6-11e9-9e2c-6a2e0b90cab9.png)
**Logs**
![image](https://user-images.githubusercontent.com/17557668/60939720-b830fd80-a2a6-11e9-9b5a-9337b51989dc.png)
It might be also useful to mention that I am using Remote SSH, but this didn't cause any problems before, the PDF opened and updated perfectly. I am able to see the PDF in the browser without any issues.
**Some more interesting errors**
![image](https://user-images.githubusercontent.com/17557668/60939828-32fa1880-a2a7-11e9-973e-008463f82b7b.png)
Not sure if these are at all related.

**Comment by jlelong** [comment] 2019-07-10 05:32
This is probably related to #1472. Make sure to use LaTeX-Workshop `7.1.0`.

**Comment by nakamin** [comment] 2019-07-10 06:06
I am already using that version. I have also tried reinstalling, didn't help.

**Comment by tamuratak** [comment] 2019-07-10 07:54
I recommend you to post the whole log messages and others required in the issue template if you want to solve your problem. Understand?

Anyway, even if you have updated the extensions on your **local** machine, the updating in the **remote** machine might have failed. Remove `~/.vscode-server` in the remote machine and reinstall it. See [link](https://code.visualstudio.com/docs/remote/troubleshooting#_cleaning-up-the-vs-code-server-on-the-remote).

**Comment by tamuratak** [comment] 2019-07-10 07:57
You must shutdown the current vscode remote server if it is running.

**Comment by fabianbees** [comment] 2019-07-11 12:42
I have the same issue, but i have noticed it is related to using VS Code trough "Remote-WSL".

**Comment by tamuratak** [comment] 2019-07-11 13:17
Please show us log messages. Show us the exact versions of VSCode, LaTeX workshop, and OS. The word `latest` is NOT helpful. Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

1 Please change the theme of VSCode to the default one, and check that you still see this issue.  
2 Please change all the user settings of VSCode to the default ones, and check that you still see this issue.  
3 Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

Then please do the followings.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Thank you for your cooperation.

**Comment by yihengli** [comment] 2019-07-11 23:49
I am running to the same bug as well:

Local: MacOS 10.14.4
Remote: Ubuntu 16.04.5 LTS
VS: 1.36.1
Extension: 7.1.0

I disabled all other extensions with only local remote extensions opened, remote latex-workshop turned on.  Default settings. Only changed "latex.workshop.tool" as the absolute path to `latexpdf` tools etc.

```
[17:39:19] Initializing LaTeX Workshop.
[17:39:19] Creating LaTeX Workshop http and websocket server.
[17:39:19] LaTeX Workshop initialized.
[17:39:20] Server created on 127.0.0.1:41286
[17:39:20] Snippet data loaded.
[17:39:20] LaTeX Workshop version: 7.1.0
[17:39:20] Try root file in root directory: PATH/main.tex
[17:39:20] Found root file in root directory: PATH/main.tex
[17:39:20] Root file changed from: undefined. Find all dependencies.
[17:39:20] Instantiating a new file watcher for PATH/main.tex
[17:39:20] Parsing PATH/main.tex
[17:39:20] Cannot find file PATH/main.fls
[17:40:11] VIEW command invoked.
[17:40:11] Found root file from active editor: PATH/main.tex
[17:40:11] Root file remains unchanged from: PATH/main.tex.
[17:40:11] Serving PDF file at http://localhost:41286/viewer.html?file=/pdf:%252Fpool%252Fceph%252Flisa%252Fyli%252Fresearch%252Ftim_rt%252Ftreecko%252Fdocs%252Fmain.pdf
[17:40:11] Open PDF tab for PATH/main.pdf
[17:40:15] Handle data type: open
```

Then PDF tab open with 
![Screen Shot 2019-07-11 at 4 46 53 PM](https://user-images.githubusercontent.com/13440386/61092538-82e9f400-a3fb-11e9-98b4-93131bb47001.png)
> the port is different

Dev Tool shows
```
[Extension Host] debugger listening on port 4403
[3hg] potential listener LEAK detected, having 262 listeners already. MOST frequent listener (11):
[Embedded Page] Uncaught (in promise) Error: Missing PDF file.
```

A side note, the pdf seems generated correctly as I can use other extensions to view it remotely.

**Comment by tamuratak** [comment] 2019-07-12 12:43
Reported microsoft/vscode/issues/77281

**Comment by bro3cat** [comment] 2019-07-20 07:36
@nakamin 
I have the Same problem, but I have fond workshop works with 1.36 insider version.Try it.

**Comment by tamuratak** [comment] 2019-07-28 08:04
The issue is labeled as Milestone August 2019 now. See microsoft/vscode/issues/77281. So, it will be fixed in the release of the beginning of September.

**Comment by yihengli** [comment] 2019-08-07 17:17
> @nakamin
> I have the Same problem, but I have fond workshop works with 1.36 insider version.Try it.

In the latest vscode-insider, this bug seems back again
```
Version: 1.37.0-insider
Commit: 5e08ee01b7daee99cdda2456f19d77e715fb8762
Date: 2019-08-05T21:16:01.319Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.5.0
```

**Comment by tamuratak** [comment] 2019-08-25 01:36
I have confirmed that this problem was fixed in VS Code 1.38.0-insider 
```
Commit: 0f73473c08055054f317c1c94502f7f39fdbb164
Date: 2019-08-23T05:36:33.571Z
```

**Closed by tamuratak** 2019-08-25 01:36 UTC
Labels: vscode-issue

**Comment by huitailangyz** [comment] 2019-09-28 06:00
I still met the same problem in VS Code 1.38.1.

**Comment by tamuratak** [comment] 2019-09-28 13:53
@huitailangyz your problem does not seem the same as this issue. Please open a new issue filling out the information required in the issue template.
