### ISSUE TITLE
More problems with the "problems" tab

### ISSUE THREAD

**Issue by philipstarkey** [James-Yu/LaTeX-Workshop#796] opened 2018-09-14 02:50 UTC
This follows on from #730, I've run into similar issues when the line ends with a comma, or other special characters (like "(", etc). Again, the warnings do not show up in the problem pane, I guess we could keep playing whack-a-mole by adding in more characters to the regex for `truncatedLine` but it feels like a losing battle.

For me, changing the regex to `const truncatedLine = /(.{79})(\r\n|\n)/g;` fixes the issue, and several others that I hadn't noticed yet.

One of these that I hadn't noticed yet was that I had a warning in a category that didn't correspond to a file because the filepath had been incorrectly detected because it line wrapped exactly on the period before the file extension. The above suggested change fixes this, but while investigating I realised that the fix for #781 deliberately didn't wrap such lines.

So I'm not sure if my proposed fix for my issue will break #781 as that didn't have a minimal example for me to test with. Looking at the screenshots provided in that bug it's unclear to me if it's bad to wrap the following line or not, and the fix there did include other changes so it might still be alright?

I suppose another (rather dodgy) fix would be to parse the log twice using two different methods for unwrapping lines and then to display the union of the Set of problems generated by each (to remove duplicates that we discovered in both ways).

Anyway, I leave it for you to think about :)

**Comment by philipstarkey** [comment] 2018-09-14 05:39
Alternatively, this might be of use: https://tex.stackexchange.com/questions/52988/avoid-linebreaks-in-latex-console-log-output-or-increase-columns-in-terminal

It seems the 80 character line break is configurable, either through environment variables or command line arguments (in the case of miktex). [This](https://docs.miktex.org/manual/miktex-pdftex.html) page has some description of what the 3 options each do for miktex (presumably they are the same for other latex flavours).

**Comment by philipstarkey** [comment] 2018-09-14 07:31
Sounds good!

If it helps, I can confirm that passing `env: {max_print_line:10000}` into the options for `child_process.spawn` does indeed do what you would expect for miktex on windows (aka, it looks like it effectively stops wrapping from what I can tell). What I don't know is what the `error_line` and `half_error_line` variables actually control (the documentation I've read wasn't clear to me but that's probably just down to my unfamiliarity with the log output format from latex)

I'm also happy to help out with whatever windows testing you need.

**Comment by jlelong** [comment] 2018-09-14 12:44
The fix works fine under OSX.
I need help for testing under Linux et Windows.

**Comment by jlelong** [comment] 2018-09-15 12:32
Thanks @philipstarkey for pointing out the problem of non canonical eol. This is is fixed in 4b577c5.

I am a bit surprised of the problems you face determining the current file while parsing the log. I am afraid the format of the messages differ a little depending on the LaTeX distribution. I cannot reproduce what you are mentioning. Could you provide an example of a complex project?

**Comment by philipstarkey** [comment] 2018-09-16 04:14
I've attached a reasonably minimal example (as I don't want to upload a copy of my thesis!).
This is a screenshot of the problems tab:
![796_problems](https://user-images.githubusercontent.com/2508881/45592752-18be1980-b9b9-11e8-9412-70188f563426.png)

Compiler log and example project:
[796_compiler_output.txt](https://github.com/James-Yu/LaTeX-Workshop/files/2386278/796_compiler_output.txt)
[796.zip](https://github.com/James-Yu/LaTeX-Workshop/files/2386276/796.zip)

If you want to keep the existing version of `parseLaTeXFileStack`  then I think the problems with the current algorithm are:

- You need to look for multiple instances of brackets per line in order to count them correctly to determine whether to push/pop the detected filename.
- You need to ensure that the path you push to the stack is immediately preceded by a `(` in the log or else it might be a path of a file used to make a figure (which are preceeded by `<` instead)

However, even if those are fixed (which will likely fix all the immediate issues I'm seeing) I think the algorithm is still going to get tripped up if any log messages/warnings have uneven brackets. To work around that, I think you need to take advantage of the way opening/closing brackets for determining the file stack are typically printed (which I detailed in my previous post)

**Comment by jlelong** [comment] 2018-09-17 12:12
I have just tested your example with the current state of the `master` branch and it seems to be working quite well. Here is a screenshot of the Problems panel.
![capture d ecran 2018-09-17 a 13 56 54](https://user-images.githubusercontent.com/2910140/45621794-ecba9b00-ba81-11e8-8d08-2b981ae2da2c.png)

I am really afraid that the logs provided by miktex are a bit different. For instance, with miktex, you have 
```
(main.out) (main.out) (front_matter.tex
```
while with texlive
```
(./main.out) (./main.out) (./front_matter.tex
```
Note the missing leading `./` in the miktex logs.

**Comment by jlelong** [comment] 2018-09-18 08:52
@James-Yu, based on this issue, I think the Problems panel may be bugged in the release 5.10.1 of the extension on Windows. I will try to work on it, but I cannot test on Windows!

**Comment by James-Yu** [comment] 2018-09-18 08:53
@jlelong Sure I will take a look into it soon.

**Closed** 2018-09-18 09:32 UTC

**Comment by James-Yu** [comment] 2018-09-18 09:33
Seems this is the best result I can get to adapt to MikTeX log. I've done a little bit of tests and it seems work well with TeXLive logs too. Can you please have a brief test on the fix @jlelong @philipstarkey ? Thanks!

**Comment by James-Yu** [comment] 2018-09-18 09:35
I will test the regex by @philipstarkey soon. Seems more concise than the current implementation.

**Comment by philipstarkey** [comment] 2018-09-18 10:59
Thanks, I'll test tomorrow and let you know.

I suspect, given what @jlelong said before, that my regex might break for linux/mac (and possibly if the .tex files are spread out over multiple folders on windows). So it probably needs some work to improve the pattern matching a bit, but might ultimately end up more robust.

**Comment by jlelong** [comment] 2018-09-18 12:33
@James-Yu a brief test of your commit on Mac shows no problem. Everything works fine 😀

**Comment by philipstarkey** [comment] 2018-09-19 00:27
I tested 1b21acd and there is still a bug when processing log lines of the form 

`[1] [2] (second.tex [3] [4] [5 <./blank.png>]`

I suspect this is because the format of the image path matches the texlive/unix/mac format for tex files, so it places subsequent error/warning messages under the file `blank.png` rather than `second.tex`.

**Comment by James-Yu** [comment] 2018-09-19 02:01
We should have a finally working one for now. See below:
![image](https://user-images.githubusercontent.com/4210342/45726703-f3b4eb00-bbf2-11e8-8999-3dfb88844a88.png)

**Comment by philipstarkey** [comment] 2018-09-19 03:57
@James-Yu I just found one other new case which breaks the problems view that I hadn't tested for in my original example project.

If you put `third.tex` in a folder (let's call it `structure/third.tex`) then it doesn't detect the path to the file properly. The warning is under the a heading for `third.tex`, but when you click on the warning it tries to open `third.tex` rather than `structure/third.tex`.

Relevant log line to parse is: `[11])) (structure/third.tex [12]` 

I guess the regex just needs to updated to grab folders too.

Then I think everything will be solved!
