### ISSUE TITLE
Corrupt PDF due to auxilary files

### ISSUE THREAD

**Issue by david-waterworth** [James-Yu/LaTeX-Workshop#1493] opened 2019-07-10 00:36 UTC
I'm not sure if I'm doing something wrong but I keep getting "PDF output corrupted/missing"

I have the following folder structure. I'm not really sure if you support this but it mostly works...

```
/workspace
    /papers
        references.bib
        /paper1
            main.tex
            /tables
            /images
        /paper2
            main.tex
            /tables
            /images
```

The issue is `\tables` and `\images` contains non-standalone tex / tikz fragments which get imported into the `main.tex` using \input{tables/my-table.tex}. The issue is when I open one of these fragments, edit it and save it, the main.pdf gets corrupted. I have to open main.tex and select "Clean up auxilary files" then "Recipe: PDFLatex ..." to restore. 

Should I somehow be telling latex workshop not to attempt build these files?

>         \begin{tabular}{llll}
>             \hline
>             \(x_1<0.75\) & \(x_2<1.25\) & q & w \\
>             \hline
>             false & false & 00b & \( w_{00} \) \\
>             false & true & 01b & \( w_{01} \) \\
>             true & false & 10b & \( w_{10} \) \\
>             true & true & 11b & \( w_{11} \) \\
>             \hline
>         \end{tabular}

**Comment by tamuratak** [comment] 2019-07-10 00:51
Please show us log messages. Show us the exact versions of VSCode, LaTeX workshop, and OS. The word `latest` is NOT helpful. Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

1 Please change the theme of VSCode to the default one, and check that you still see this issue.  
2 Please change all the user settings of VSCode to the default ones, and check that you still see this issue.  
3 Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

Then please do the followings.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Thank you for your cooperation.

**Comment by david-waterworth** [comment] 2019-07-10 02:25
Looking at the logs it appears to be getting confused as to what the 'root' file is

[12:20:00] RECIPES command invoked.
[12:20:00] BUILD command invoked.
[12:20:00] Cannot find LaTeX root file.

[12:20:17] VIEW command invoked.
[12:20:17] Found root file from active editor: /home/david/dev/research/papers/paper1/main.tex
[12:20:17] Root file remains unchanged from:/home/david/dev/research/papers/paper1/main.tex

I'll try setting the vscode workspace to the folder containing main.tex instead of the parent and see if that helps

**Comment by jlelong** [comment] 2019-07-10 05:30
Your structure is for sure supported by LaTeX-Workshop. It is sufficient to open either the `workspace` or `papers` folder in vscode.
To help you, we need the full logs of the extension from the beginning and including when you edit/save and a minimal working example reproducing the issue.

**Comment by david-waterworth** [comment] 2019-07-10 23:19
No problem, give me some time and I'll try and create a clone of my project structure which replicates the problem.

I restarted vscode a couple of times and opened the paper1 subfolder, initially I observed the issue but then it went away so it may be intermittent

**Comment by david-waterworth** [comment] 2019-07-11 22:39
I've not managed to reproduce the exact issue, but I've reproduced something...

I created a sample structure that mirrors the key parts of my repo. There are two "paper" subfolders, a common bib file and a common ..\images file containing tikz files.

Note the log message below - paper1/main.tex changed but it built /paper2/main.tex instead..

[08:33:23] File watcher: responding to change in /home/david/dev/issues/1493/paper1/main.tex
[08:33:23] /home/david/dev/issues/1493/paper1/main.tex changed. Auto build project.
[08:33:23] BUILD command invoked.
[08:33:23] Building root file: /home/david/dev/issues/1493/paper2/main.tex
[08:33:23] Build root file /home/david/dev/issues/1493/paper2/main.tex

I've attached a zip file 

[1493.zip](https://github.com/James-Yu/LaTeX-Workshop/files/3384233/1493.zip)

**Comment by jlelong** [comment] 2019-07-14 04:33
I cannot reproduce the issues (neither the PDF corruption, nor the mix in building).  PR #1496 may have solved your problem. If you know how to run the `master` version of the extension, could you try and see if you still face the issue?

**Comment by david-waterworth** [comment] 2019-07-14 22:07
OK I'll try running the master release, it is quite intermittent.

**Comment by jlelong** [comment] 2019-07-21 05:49
I am closing the issue as we do not seem to reproduce it. Feel free to ask for reopening if needed.

**Closed by jlelong** 2019-07-21 05:49 UTC
Labels: can't reproduce
