### ISSUE TITLE
autoClean and clean.subforder not woking properly

### ISSUE THREAD

**Issue by Cdmium** [James-Yu/LaTeX-Workshop#1210] opened 2019-03-04 04:42 UTC
When "autoClean" set to "onBuilt" and "clean.subforder" set to "false", LaTeX auxillary files remain where they are generated. 
When "autoClean" set to "onBuilt" and "clean.subforder" set to "true", auxillary files will be clean but the process takes about 5-30 seconds. Meanwhile, other functions of LaTeX-Workshop are unusable.  
Keyboard shortcuts no response, sidebar command no response too or not showing.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - VS Code version: 1.31.1
 - Extension version: 6.0.0

**Files** :
.
├── Transcription and RNA Processing.aux
├── Transcription and RNA Processing.log
├── Transcription and RNA Processing.pdf
├── Transcription and RNA Processing.synctex.gz
└── Transcription and RNA Processing.tex

**Logs**
[11:48:32] RECIPES command invoked.
[11:48:33] BUILD command invoked.
[11:48:33] Found root file from active editor: /home/cdmium/Note/Biochemistry 2/Transcription and RNA Processing.tex
[11:48:33] Root file remains unchanged from: /home/cdmium/Note/Biochemistry 2/Transcription and RNA Processing.tex.
[11:48:33] Building root file: /home/cdmium/Note/Biochemistry 2/Transcription and RNA Processing.tex
[11:48:33] Build root file /home/cdmium/Note/Biochemistry 2/Transcription and RNA Processing.tex
[11:48:33] Recipe step 1: xelatex, -synctex=1,-interaction=nonstopmode,-file-line-error,Transcription and RNA Processing
[11:48:35] LaTeX log parsed with 1 messages.
[11:48:35] Recipe of length 1 finished.
[11:48:35] Successfully built /home/cdmium/Note/Biochemistry 2/Transcription and RNA Processing.tex
[11:48:35] No PDF viewer connected for /home/cdmium/Note/Biochemistry 2/Transcription and RNA Processing.pdf
[11:48:35] Found root file from active editor: /home/cdmium/Note/Biochemistry 2/Transcription and RNA Processing.tex
[11:48:35] Root file remains unchanged from: /home/cdmium/Note/Biochemistry 2/Transcription and RNA Processing.tex.
[11:49:07] File cleaned: /home/cdmium/Note/Biochemistry 2/Transcription and RNA Processing.aux

**Comment by jlelong** [comment] 2019-03-05 21:06
I cannot reproduce the issue. In particular, setting `"autoClean": "onBuilt"` and `"clean.subforder": false` does clean  auxiliary files but only in the top level output directory.

I have just fixed a double call of remove on auxiliary files in the top level output directory but I doubt this is related to your problem.

**Comment by Cdmium** [comment] 2019-03-06 02:55
I notice something else. 
The autoclean process seem to set /home/cdmium as the top level, which can explain why when "subfolder" false clean nothing, and when true took a lot of time and make other software crash.

I made a little test, which prove that. Result show in the file.
[1201.log](https://github.com/James-Yu/LaTeX-Workshop/files/2934099/1201.log)

**Comment by jlelong** [comment] 2019-03-06 05:41
I still cannot reproduce your problem. What is your setting for  `latex-workshop.latex.outDir`?

**Comment by jlelong** [comment] 2019-03-06 05:42
@James-Yu why don't we pass `true` as a second arg to `tex2pdf` [here](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/viewer.ts#L37)?

**Comment by James-Yu** [comment] 2019-03-06 06:00
@jlelong Because when the line in `viewer.ts` was wrote (Apr. 2017), `tex2pdf` only accepts one input argument. And it slipped through the check.

**Comment by Cdmium** [comment] 2019-03-06 12:47
![screenshot from 2019-03-06 20-45-54](https://user-images.githubusercontent.com/29893505/53882282-e7153980-4050-11e9-817e-06d4e47450dc.png)
%DIR%
I believe it's default.

**Comment by jlelong** [comment] 2019-03-14 05:20
@Cdmium Do you still have the issue with release 6.2.1?

**Comment by Cdmium** [comment] 2019-03-14 23:17
Still the same. Searching all my files.

[07:07:13] RECIPES command invoked.
[07:07:14] BUILD command invoked.
[07:07:14] Found root file from active editor: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.tex
[07:07:14] Root file remains unchanged from: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.tex.
[07:07:14] Building root file: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.tex
[07:07:14] Build root file /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.tex
[07:07:14] Recipe step 1: xelatex, -synctex=1,-interaction=nonstopmode,-file-line-error,report
[07:07:14] LaTeX build process spawned. PID: 16932.
[07:07:16] LaTeX log parsed with 1 messages.
[07:07:16] Recipe of length 1 finished. PID: 16932.
[07:07:16] Successfully built /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.tex.
[07:07:16] No PDF viewer connected for /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.pdf
[07:07:16] Cannot find file report.fls
[07:07:16] PDF is not viewed: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.pdf
[07:07:16] Found root file from active editor: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.tex
[07:07:16] Root file remains unchanged from: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.tex.
[07:08:18] File cleaned: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.out
[07:08:18] File cleaned: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.aux

**Comment by jlelong** [comment] 2019-03-15 06:35
I still cannot reproduce the issue and cannot see anything strange in the logs.
Can you describe precisely your problem and your LaTeX-Workshop settings?

**Comment by Cdmium** [comment] 2019-03-15 10:24
Problem : autoClean set /home/cdmium/ as the root directory.
If I set subfolder false, it will do nothing, since no auxillary file in /home/cdmium/.
If true, it will search all files, and takes a lot of time and delect files like *.debug.out and damage other software.  Meanwhile LaTeX-Workshop stuck.

settings.json (github does not support .json file):
[settings.txt](https://github.com/James-Yu/LaTeX-Workshop/files/2970498/settings.txt)

All extensions:
![Screenshot from 2019-03-15 18-20-06](https://user-images.githubusercontent.com/29893505/54424953-0d249300-474f-11e9-9127-cc099b56a4a0.png)

.bashrc:
`#tex live 2017.12.15
export MANPATH=${MANPATH}:/usr/local/texlive/2018/texmf-dist/doc/man
export INFOPATH=${INFOPATH}:/usr/local/texlive/2018/texmf-dist/doc/info
export PATH=${PATH}:/usr/local/texlive/2018/bin/x86_64-linux

#alias 2018.10.18
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias clc='for((i=0;i<=100;i++));do echo -e "\n";done'

#shutdown reboot confirmation 2018.11.13
shutdowntag=""
reboottag=""
alias reboot='read -p "Do you want to reboot? [Y/n]" reboottag; if [ "$reboottag"x == "Y"x ]; then reboottag=""; reboot; else reboottag=""; echo "Abort"; fi'
alias shutdown='read -p "Do you want to shutdown? [Y/n]" shutdowntag; if [ "$shutdowntag"x == "Y"x ]; then shutdowntag=""; shutdown now; else shutdowntag=""; echo "Abort"; fi'
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

#byobu 2018.12.48
#byobu

#opencv 2019.01.29
PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
export PKG_CONFIG_PATH

#ugene 2019.02.09
export PATH=$PATH:"/home/cdmium/ugene-1.31.1/"
export MANPATH=$MANPATH:"/home/cdmium/ugene-1.31.1/"

#2019.03.08
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

#2019.03.14 latexindent
alias latexformat='latexindent -w -l "/home/cdmium/LaTeX/latexindent/Settings.yaml"'`

**Comment by jlelong** [comment] 2019-03-15 10:56
I  think this is related to `"latex-workshop.docker.enabled": true`.

@James-Yu can you help on that? I do not know how the `outputDir` is exactly determined when using docker.

**Comment by Cdmium** [comment] 2019-03-15 11:08
"latex-workshop.docker.enabled": false

[19:03:06] Successfully built /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.tex.
[19:03:06] Refresh PDF viewer for /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.pdf
[19:03:06] Cannot find file /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.fls
[19:03:06] Try to synctex /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.pdf
[19:03:06] Found root file from active editor: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.tex
[19:03:06] Root file remains unchanged from: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.tex. 
[19:03:06] File cleaned: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.aux
[19:03:06] File cleaned: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.out
[19:03:06] Preview PDF file: /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.pdf
[19:03:06] Try to synctex /home/cdmium/CAU/Biochemistry_2/Experiment/1/report.pdf

Finally, It works. I cannot remember when and why set that to true.

**Comment by jlelong** [comment] 2019-03-15 11:14
Great! Finally closing this issue 😀

**Closed by jlelong** 2019-03-15 11:14 UTC
