### ISSUE TITLE
Recompiling error messages

### ISSUE THREAD

**Issue by dskinnion** [James-Yu/LaTeX-Workshop#4178] opened 2024-03-01 18:10 UTC
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The feature request has not been suggested in this repository.

## The Missed*
> _Is your feature request related to a problem? Please provide a clear and concise description of what the problem is._
- When there are compiling issues, we need to click (x) on multiple error boxes.

## The Solution*
> _Please provide a solution you would like to have._
- When you recompile, those error boxes should vanish automatically without any click.

## Anything Else?
> _Add any other context about the feature request below._
- Thanks!

**Comment by jlelong** [comment] 2024-03-01 18:39
Duplicate of #898. This is a VS Code limitation

**Closed by jlelong** 2024-03-01 18:39 UTC
