### ISSUE TITLE
Ctrl+Click on packages should open the documentation CTAN or other TeX archive network

### ISSUE THREAD

**Issue by StickySli** [James-Yu/LaTeX-Workshop#3275] opened 2022-05-02 09:21 UTC
The Ctrl+Click key combination or the F12 key allows the user to navigate to a file and seek definitions. https://code.visualstudio.com/Docs/editor/editingevolved

Currently this function is not implemented in usepackage, requirepackage, or documentclass. It would be very useful to get the package definition from TeX archive network like CTAN and to like the definition to the main site.

**Comment by tamuratak** [comment] 2022-05-02 10:46
Duplicate of #3197

**Comment by jlelong** [comment] 2022-05-02 20:16
I am not sure this is really a duplicate of #3197. if I understand well, the question here is for instance

- Is it possible to go to `https://ctan.org/pkg/amsmath` when ctrl clicking on `amsmath` in \usepackage{amsmath}`?

The short answer is no. We do not want to modify the symbol provider to include the packages.

Yet, it is almost already available using _hover on package_, see https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#documentation-of-a-package. Currently, it opens the local document but it would easy to add a link to ctan.

**Closed** 2022-05-03 18:41 UTC
Labels: enhancement
