### ISSUE TITLE
vscode keyboard shortcuts do not work when PDF preview tab is in focus

### ISSUE THREAD

**Issue by isundaylee** [James-Yu/LaTeX-Workshop#1468] opened 2019-06-28 18:08 UTC
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**

When the PDF preview tab is active, vscode keyboard shortcuts don't work anymore. Most importantly, I cannot return focus to the left-column containing the tex source code without using the mouse. Usually this can be done with Command+1 (on macOS).

**To Reproduce**
1. Open a tex file.
2. Shift+Option+V to open the PDF preview window.
3. Press Command+1 to try to go back to the tex file tab. 

**Expected behavior**
Focus should be returned to the tex file tab.

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>

```
[14:02:57] Initializing LaTeX Workshop.
[14:02:57] Creating LaTeX Workshop http and websocket server.
[14:02:57] LaTeX Workshop initialized.
[14:02:58] Server created on 127.0.0.1:65166
[14:02:58] Snippet data loaded.
[14:02:58] LaTeX Workshop version: 7.0.2
[14:02:58] Try root file in root directory: /path/to/project/main.tex
[14:02:58] Parsing /path/to/project/main.tex
[14:02:58] Parsing /path/to/project/cover.tex
[14:02:58] Parsing /path/to/project/abstract.tex
[14:02:58] Parsing /path/to/project/contents.tex
[14:02:58] Parsing /path/to/project/intro.tex
[14:02:58] Parsing /path/to/project/background.tex
[14:02:58] Parsing /path/to/project/biblio.tex
[14:02:58] Parsing /path/to/project/main.fls to compute dependencies
[14:02:58] Parsing /path/to/project/abstract.tex
[14:02:58] Found root file in root directory: /path/to/project/main.tex
[14:02:58] Root file changed from: undefined. Find all dependencies.
[14:02:58] Instantiating a new file watcher for /path/to/project/main.tex
[14:02:58] Parsing /path/to/project/main.tex
[14:02:58] Adding /path/to/project/cover.tex to file watcher.
[14:02:58] Parsing /path/to/project/cover.tex
[14:02:58] Adding /path/to/project/abstract.tex to file watcher.
[14:02:58] Parsing /path/to/project/abstract.tex
[14:02:58] Adding /path/to/project/contents.tex to file watcher.
[14:02:58] Parsing /path/to/project/contents.tex
[14:02:58] Adding /path/to/project/intro.tex to file watcher.
[14:02:58] Parsing /path/to/project/intro.tex
[14:02:58] Adding /path/to/project/background.tex to file watcher.
[14:02:58] Parsing /path/to/project/background.tex
[14:02:58] Adding /path/to/project/biblio.tex to file watcher.
[14:02:58] Parsing /path/to/project/biblio.tex
[14:02:58] Found .bib file /path/to/project/main.bib
[14:02:58] Creating file watcher for .bib files.
[14:02:58] Adding .bib file /path/to/project/main.bib to bib file watcher.
[14:02:58] Parsing .bib entries from /path/to/project/main.bib
[14:02:58] Parsed 57 .bib entries from /path/to/project/main.bib.
[14:02:58] Parsing /path/to/project/main.fls to compute dependencies
[14:02:58] Adding /path/to/project/mitthesis.cls to file watcher.
[14:02:58] Adding /path/to/project/lgrind.sty to file watcher.
[14:02:58] Parsing /path/to/project/abstract.tex
[14:02:58] Adding /path/to/project/_minted-main/default-pyg-prefix.pygstyle to file watcher.
[14:02:58] Adding /path/to/project/_minted-main/default.pygstyle to file watcher.
[14:02:58] Adding /path/to/project/_minted-main/959AD0CE3AA289A733D9B2C8087879F1042D2615758B6C3F03C186B02CFC62B2.pygtex to file watcher.
[14:02:58] Adding /path/to/project/_minted-main/7583A5CC0D3E8CDA98967300F7D86EEA042D2615758B6C3F03C186B02CFC62B2.pygtex to file watcher.
[14:02:58] Adding /path/to/project/images/policy-func.png to file watcher.
[14:02:58] Adding /path/to/project/_minted-main/0920FCC7B0DC5F4690613EDF9201C34EAA15CF4BA75075E8168D3671BF7EB064.pygtex to file watcher.
[14:02:58] Adding /path/to/project/_minted-main/AC8A20E12DF1BB345D8B37643B24B88F042D2615758B6C3F03C186B02CFC62B2.pygtex to file watcher.
[14:02:58] Adding /path/to/project/images/coloring-eg-overflow.png to file watcher.
[14:02:58] Adding /path/to/project/images/coloring-eg-uaf.png to file watcher.
[14:02:58] Adding /path/to/project/_minted-main/BA90D5A6A67646E8D424B05F8132A1B7042D2615758B6C3F03C186B02CFC62B2.pygtex to file watcher.
[14:02:58] Found .bib file /path/to/project/main.bib
[14:02:58] .bib file /path/to/project/main.bib is already being watched.
[14:03:00] VIEW command invoked.
[14:03:00] Try root file in root directory: /path/to/project/main.tex
[14:03:00] Parsing /path/to/project/main.tex
[14:03:00] Parsing /path/to/project/main.fls to compute dependencies
[14:03:00] Found root file in root directory: /path/to/project/main.tex
[14:03:00] Root file remains unchanged from: /path/to/project/main.tex.
[14:03:00] Serving PDF file at http://localhost:65166/viewer.html?file=/pdf:%252FUsers%252Fjiahaoli%252FSeafile%252FPersonal%252FClasses%252FMEng%2520Research%252Fthesis%252Fmain.pdf
[14:03:00] Open PDF tab for /path/to/project/main.pdf
[14:03:00] Handle data type: open
[14:03:00] Preview PDF file: /path/to/project/main.pdf
[14:03:00] Handle data type: loaded
```
</details>

<details>
<summary>Developer Tools Console [Required]</summary>

Nothing suspicious.
</details>

**Screenshots**
N/A

**Desktop [Required]:**
 - OS: macOS Mojave 10.14.4
 - VS Code version: 1.35.1
 - Extension version: 7.0.2

**Additional context**
N/A

**Comment by jlelong** [comment] 2019-06-28 19:01
Duplicate of #1406.

**Closed by jlelong** 2019-06-28 19:01 UTC

**Comment by isundaylee** [comment] 2019-06-28 20:51
Sorry for the dup -- I should have looked more closely. Thanks for the pointer!
