### ISSUE TITLE
Syntax Support of textcite and parencite

### ISSUE THREAD

**Issue by Pred3d** [James-Yu/LaTeX-Workshop#463] opened 2018-03-12 15:13 UTC
Hey guys,

I'd like to have the same functionality with the \textcite and with the \parencite command, as with the cite command: autocomplete of bib-sources. Would this be possible?

big thanks!

**Comment by James-Yu** [comment] 2018-03-13 01:29
They can actually pop the intellisense. See [here](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/providers/completion.ts#L105).

If that is not the case, please provide a minimal working example for debug.

![image](https://user-images.githubusercontent.com/4210342/37317648-1236d4f4-26a1-11e8-82fa-53e800eb5bf6.png)

**Comment by Pred3d** [comment] 2018-03-13 09:12
Next day autocomplete of the bib resources works, but I have different syntax highlighting, and if I confirm the auto complete suggestion I don't get brackets inserted. 
But these are really small problems :)
![unbenannt](https://user-images.githubusercontent.com/15658640/37332440-0161839e-26a7-11e8-89ef-0d65b07a02ce.JPG)

**Comment by James-Yu** [comment] 2018-03-19 08:05
It's quite hard to include all variants of cite in the family in the highlighting plan. As to the closing bracket, I also experience the same problem. My guess is that the problem is related to the editor, since the extension only provide intellisense items to the editor. Correct me if I'm wrong.

**Closed by James-Yu** 2018-03-19 08:05 UTC
