### ISSUE TITLE
Remove error notification after successfully recompiling

### ISSUE THREAD

**Issue by FMuro** [James-Yu/LaTeX-Workshop#1868] opened 2019-12-17 09:21 UTC
When typing and saving, it's not uncommon that an error is reported at the same time that I spot it in the code. Then I fix it and recompile, but the error notification of the previous compilation remains there. It would be nice if it could be removed if there are no errors in the latest compilation.

**Comment by tecosaur** [comment] 2019-12-17 09:23
I believe that this is impossible due to limitations in the vscode API. I imagine someone else will be able to provide an issue number and close this.

**Comment by jlelong** [comment] 2019-12-17 10:43
Duplicate of #898

**Closed by jlelong** 2019-12-17 10:43 UTC
Labels: feature-request
