### ISSUE TITLE
View pdf

### ISSUE THREAD

**Issue by angan06** [James-Yu/LaTeX-Workshop#115] opened 2017-04-17 07:44 UTC
Dear James, 

It looks like there is a problem to the "view pdf file in new tab" action.  
When I use it via a keyboard shortcut, I have the warning: 
"Running the contributed command:'latex-workshop.tab' failed."

If I use the contextual menu, nothing happen and I have this text in my output:
[09:42:34] ACTIONS command invoked.
[09:42:39] TAB command invoked.
[09:42:39] Found root file from active editor: ***.tex
[09:42:39] Root file remains unchanged from: ***.tex.

Best regards.

**Comment by James-Yu** [comment] 2017-04-17 07:47
Thanks for the report. I can reproduce the problem. It seems that the last update breaks something. Will fix the problem soon.

**Comment by angan06** [comment] 2017-04-17 07:48
Thank you, and as always, thank you for this extension and your work on it.

**Comment by James-Yu** [comment] 2017-04-17 07:53
The problem is fixed in the latest `2.1.3` version. Please update and see if it works.

**Closed by James-Yu** 2017-04-17 07:53 UTC

**Comment by angan06** [comment] 2017-04-17 07:57
Works perfectly now. Thanks. The forward search and backward search also works smoothly.
