### ISSUE TITLE
Since version 18.20.2, I get multiple error messages

### ISSUE THREAD

**Issue by dasnessie** [James-Yu/LaTeX-Workshop#2869] opened 2021-09-19 09:37 UTC
Since I updated to version 8.20.2, I get the error message `command 'latex-workshop.build' not found` when trying to build my project. Also, pdf files are no longer being displayed, it just keeps getting stuck on load. I reverted back to version 8.19.2, now everything works fine.

Here's the version info about my setup that Code gives me:

> Version: 1.56.2
> Commit: 054a9295330880ed74ceaedda236253b4f39a335
> Date: 2021-05-16T15:21:33.370Z
> Electron: 12.0.9
> Chrome: 89.0.4389.128
> Node.js: 14.16.0
> V8: 8.9.255.25-electron.0
> OS: Linux x64 5.12.10-arch1-1

**Comment by tamuratak** [comment] 2021-09-19 10:04
Duplicate of #2845

**Closed by tamuratak** 2021-09-19 10:04 UTC
Labels: external, duplicate

**Comment by tamuratak** [comment] 2021-09-19 10:07
See also https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#code-oss-on-arch-linux-and-manjaro-is-not-officially-supported
