### ISSUE TITLE
Forward search for external pdf viewer with mouse click

### ISSUE THREAD

**Issue by chkwon** [James-Yu/LaTeX-Workshop#2238] opened 2020-08-10 17:28 UTC
I'm currently using Skim on macOS as the external pdf viewer.

The forward search <kbd>cmd</kbd>+<kbd>option</kbd>+<kbd>j</kbd> to jump to Skim at the current line works good. 

Can we also have a mouse click option? For example, <kbd>cmd</kbd>+<kbd>option</kbd>+left click?

**Comment by tamuratak** [comment] 2020-08-10 21:59
Duplicate of  #716.

Upvote microsoft/vscode/issues/3130.

**Closed by tamuratak** 2020-08-10 21:59 UTC
Labels: feature-request
