### ISSUE TITLE
Build on save isn't working

### ISSUE THREAD

**Issue by tailerr** [James-Yu/LaTeX-Workshop#1340] opened 2019-04-27 08:03 UTC
**Description**
Saving does not trigger the file build anymore.

**To Reproduce**
1.save

**Expected behavior**
project is built

**Actual behavior**
project is not built

 - OS: Ubuntu 19.04
 - VS Code version: 1.33.1
 - Extension version: 6.5.0

**Comment by jlelong** [comment] 2019-04-27 08:17
Duplicate of #1333

**Closed by jlelong** 2019-04-27 08:17 UTC
