### ISSUE TITLE
Page display in viewer

### ISSUE THREAD

**Issue by PierreMarchand20** [James-Yu/LaTeX-Workshop#1800] opened 2019-11-12 15:11 UTC
**Is your feature request related to a problem? Please describe.**
Since the last update, the internal pdf viewer has a two-pages display by default. I did not find any 
option to set another default value (or I did not understand the effect of the existing settings).
<img width="210" alt="image" src="https://user-images.githubusercontent.com/15056323/68683243-5fc48200-055e-11ea-8526-e24f18ed5437.png">

And for some reasons, it is in French while everything else in VSCode is in English.

**Describe the solution you'd like**
I would like to be able to set a one-page display by default.

**Comment by trevorgunn** [comment] 2019-11-12 15:33
[`latex-workshop.view.pdf.spreadMode`](https://github.com/James-Yu/LaTeX-Workshop/wiki/View#latex-workshopviewpdfspreadMode) It should be 0 by default.

**Comment by PierreMarchand20** [comment] 2019-11-12 15:39
I thought it was this one, but I have 0 and I still have a two-pages display 
![image](https://user-images.githubusercontent.com/15056323/68685837-a2885900-0562-11ea-9683-bc68ae22f99c.png)

**Comment by trevorgunn** [comment] 2019-11-12 15:45
It's a single page view on all 3 of the machines I use; I'm not sure what's happening on your end. Can you post what settings you have set and your OS info and the logs?

Also, in your screenshot it's set to "Pas de double affichage" (single page view). Are you saying that you're seeing a two page view even though it's set to a single page view?

**Comment by PierreMarchand20** [comment] 2019-11-12 15:55
Sorry about the picture, it is because I changed it. Here, I just opened a new viewer and I did not change anything.
![image](https://user-images.githubusercontent.com/15056323/68686743-00697080-0564-11ea-9eeb-fdba62621774.png)

Here's my OS info
Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

I have seen nothing relevant in the logs 
![image](https://user-images.githubusercontent.com/15056323/68687060-8980a780-0564-11ea-8e4e-2f46e92c9900.png)

**Comment by PierreMarchand20** [comment] 2019-11-12 16:10
Option 1 and 2 work, but not 0

**Comment by jlelong** [comment] 2019-11-12 18:14
I do confirm that the menu is in French also in my installation despite all VSCode menus being in English.

**Comment by tamuratak** [comment] 2019-11-12 22:00
Please show us log messages. The whole log message is necessary. Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. 

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

1 Please change the theme of VSCode to the default one, and check that you still see this issue.  
2 Please change all the user settings of VSCode to the default ones, and check that you still see this issue.  
3 Please disable all the other extensions except for LaTeX Workshop, and check that you still see this issue.

**Comment by PierreMarchand20** [comment] 2019-11-13 11:12
I disabled all the extensions, I still have the problem:
![image](https://user-images.githubusercontent.com/15056323/68758775-58f14a00-0606-11ea-9dcb-cf6354018c3e.png)



Here's the log
```
[11:08:52] Initializing LaTeX Workshop.
[11:08:52] Creating LaTeX Workshop http and websocket server.
[11:08:52] LaTeX Workshop initialized.
[11:08:52] Linter for root file started.
[11:08:52] No root file found for linting.
[11:08:53] Server created on 127.0.0.1:53959
[11:08:53] LaTeX Workshop version: 8.3.1
[11:08:53] Snippet data loaded.
[11:08:53] Found root file from parent: ***********thesis.tex
[11:08:53] Root file changed from: undefined to ***********thesis.tex. Find all dependencies.
[11:08:53] Instantiating a new file watcher for ***********thesis.tex
[11:08:53] Creating file watcher for .bib files.
[11:08:53] Parsing ***********thesis.tex
[11:08:53] Parsing ***********packages.tex
[11:08:53] Parsing ***********configuration/raccourcis.tex
[11:08:53] Parsing ***********liminaires/resumes.tex
[11:08:53] Parsing ***********liminaires/remerciements.tex
[11:08:53] Parsing ***********corps/introduction_chap.tex
[11:08:53] Parsing ***********corps/introduction/french.tex
[11:08:53] Parsing ***********corps/introduction/english.tex
[11:08:53] Parsing ***********corps/bem_chap.tex
[11:08:53] Parsing ***********corps/bem/sobolev_spaces.tex
[11:08:53] Parsing ***********corps/bem/elliptic_boundary_value_prob.tex
[11:08:53] Parsing ***********corps/bem/boundary_integral_operators.tex
[11:08:53] Parsing ***********corps/bem/boundary_integral_equations.tex
[11:08:53] Parsing ***********corps/schwarz_methods_chap.tex
[11:08:53] Parsing ***********corps/schwarz_methods/continuous_schwarz_methods.tex
[11:08:53] Parsing ***********corps/schwarz_methods/discrete_setting.tex
[11:08:53] Parsing ***********corps/schwarz_methods/asm.tex
[11:08:53] Parsing ***********corps/mtf_osm_chap.tex
[11:08:53] Parsing ***********corps/mtf_osm/multi_subdomain_problems.tex
[11:08:53] Parsing ***********corps/mtf_osm/formulations_w_bio.tex
[11:08:53] Parsing ***********corps/mtf_osm/block_jacobi_method.tex
[11:08:53] Parsing ***********corps/mtf_osm/numerical_illustrations.tex
[11:08:53] Parsing ***********corps/geneo_chap.tex
[11:08:53] Parsing ***********corps/geneo/finite_element_setting.tex
[11:08:53] Parsing ***********corps/geneo/split.tex
[11:08:53] Parsing ***********corps/geneo/two_level.tex
[11:08:53] Parsing ***********corps/geneo/numerical_experiments_geneo_hyper.tex
[11:08:53] Parsing ***********corps/geneo/conlusion_remarks_perspectives.tex
[11:08:53] Parsing ***********corps/htool_chap.tex
[11:08:53] Parsing ***********corps/htool/low_rank_approx.tex
[11:08:53] Parsing ***********corps/htool/hmatrix.tex
[11:08:53] Parsing ***********corps/htool/implementation.tex
[11:08:53] Parsing ***********corps/htool/perspectives.tex
[11:08:53] Parsing ***********annexes/slobodeckij_mass_matrix.tex
[11:08:53] Parsing ***********annexes/discussion_single_layer_coarse_space.tex
[11:08:53] Parsing ***********annexes/code_example.tex
[11:08:53] Found .bib file ***********auxiliaires/bibliographie.bib
[11:08:53] Adding .bib file ***********auxiliaires/bibliographie.bib to bib file watcher.
[11:08:53] Parsing .bib entries from ***********auxiliaires/bibliographie.bib
[11:08:53] Parsed 442 bib entries from ***********auxiliaires/bibliographie.bib.
[11:08:53] Adding ***********thesis.tex to file watcher.
[11:08:53] Adding ***********packages.tex to file watcher.
[11:08:53] Adding ***********configuration/raccourcis.tex to file watcher.
[11:08:53] Adding ***********liminaires/resumes.tex to file watcher.
[11:08:53] Adding ***********liminaires/remerciements.tex to file watcher.
[11:08:53] Adding ***********corps/introduction_chap.tex to file watcher.
[11:08:53] Adding ***********corps/introduction/french.tex to file watcher.
[11:08:53] Adding ***********corps/introduction/english.tex to file watcher.
[11:08:53] Adding ***********corps/bem_chap.tex to file watcher.
[11:08:53] Adding ***********corps/bem/sobolev_spaces.tex to file watcher.
[11:08:53] Adding ***********corps/bem/elliptic_boundary_value_prob.tex to file watcher.
[11:08:53] Adding ***********corps/bem/boundary_integral_operators.tex to file watcher.
[11:08:53] Adding ***********corps/bem/boundary_integral_equations.tex to file watcher.
[11:08:53] Adding ***********corps/schwarz_methods_chap.tex to file watcher.
[11:08:53] Adding ***********corps/schwarz_methods/continuous_schwarz_methods.tex to file watcher.
[11:08:53] Adding ***********corps/schwarz_methods/discrete_setting.tex to file watcher.
[11:08:53] Adding ***********corps/schwarz_methods/asm.tex to file watcher.
[11:08:53] Adding ***********corps/mtf_osm_chap.tex to file watcher.
[11:08:53] Adding ***********corps/mtf_osm/multi_subdomain_problems.tex to file watcher.
[11:08:53] Adding ***********corps/mtf_osm/formulations_w_bio.tex to file watcher.
[11:08:53] Adding ***********corps/mtf_osm/block_jacobi_method.tex to file watcher.
[11:08:53] Adding ***********corps/mtf_osm/numerical_illustrations.tex to file watcher.
[11:08:53] Adding ***********corps/geneo_chap.tex to file watcher.
[11:08:53] Adding ***********corps/geneo/finite_element_setting.tex to file watcher.
[11:08:53] Adding ***********corps/geneo/split.tex to file watcher.
[11:08:53] Adding ***********corps/geneo/two_level.tex to file watcher.
[11:08:53] Adding ***********corps/geneo/numerical_experiments_geneo_hyper.tex to file watcher.
[11:08:53] Adding ***********corps/geneo/conlusion_remarks_perspectives.tex to file watcher.
[11:08:53] Adding ***********corps/htool_chap.tex to file watcher.
[11:08:53] Adding ***********corps/htool/low_rank_approx.tex to file watcher.
[11:08:53] Adding ***********corps/htool/hmatrix.tex to file watcher.
[11:08:53] Adding ***********corps/htool/implementation.tex to file watcher.
[11:08:53] Adding ***********corps/htool/perspectives.tex to file watcher.
[11:08:53] Adding ***********annexes/slobodeckij_mass_matrix.tex to file watcher.
[11:08:53] Adding ***********annexes/discussion_single_layer_coarse_space.tex to file watcher.
[11:08:53] Adding ***********annexes/code_example.tex to file watcher.
[11:08:55] Cannot parse ***********corps/mtf_osm/block_jacobi_method.tex: Fall back to regex-based completion.
[11:09:00] LOG command invoked.
[11:09:05] Found root file from parent: ***********thesis.tex
[11:09:05] Root file remains unchanged from: ***********thesis.tex.
[11:09:05] VIEW command invoked.
[11:09:05] Found root file from parent: ***********thesis.tex
[11:09:05] Root file remains unchanged from: ***********thesis.tex.
[11:09:05] Serving PDF file at http://localhost:53959/viewer.html?file=pdf..JTJGVXNlcnMlMkZwZmNtMjAlMkZQYXJ0YWdlJTJGTGFUZVglMkZQaERfTGFUZVglMkZUaGVzaXMlMkZ0aGVzaXMucGRm
[11:09:05] The encoded path is ***********thesis.pdf
[11:09:05] Open PDF tab for ***********thesis.pdf
[11:09:05] Handle data type: open
[11:09:05] Preview PDF file: ***********thesis.pdf
[11:09:05] Handle data type: loaded
[11:09:05] Found root file from parent: ***********thesis.tex
[11:09:05] Root file remains unchanged from: ***********thesis.tex.
```

**Comment by tamuratak** [comment] 2019-11-13 11:25
Create a new empty directory outside this directory, and create a new simple TeX file, and do you still see this problem?

**Comment by PierreMarchand20** [comment] 2019-11-13 14:12
I don't have this problem on a new repository. I checked with other latex projects I have and indeed, it seems to be the only one with this issue. And it was not like that before the last update.

**Comment by jlelong** [comment] 2019-11-13 14:14
There is probably something wrong in your `.vscode/settings.json` file inside that directory.

**Comment by PierreMarchand20** [comment] 2019-11-13 14:29
I don't have any `.vscode` directory in this directory. How could I debug ?

**Comment by jlelong** [comment] 2019-11-13 14:33
In an upper directory maybe. It seems that something is wrong in your current vscode workspace. What does happen when you try to edit your workspace preferences? Can you check the content of the workspace `settings.json` file.

**Comment by PierreMarchand20** [comment] 2019-11-13 14:44
I do not have any `setting.json` in the workspace, I never use local settings. And when I call `Preferences: Open Workspace settings`, I have the 0 for the spread mode option. It is really weird...

**Comment by PierreMarchand20** [comment] 2019-11-13 14:47
Actually, if I create a simple tex file in the same workspace, I do not have this issue. But I really do not see how the tex file I want to view may change something when calling the viewer.

**Comment by jlelong** [comment] 2019-11-13 15:16
I would rather bet that there is something wrong in vscode's cache, see in `~/Library/Application Support/Code`. Try to make a copy of it and start with a fresh one.  Then, restore

    User/settings.json
    User/keybindings.json
    User/snippets

Note that this will remove your vscode's history.

**Comment by jlelong** [comment] 2019-11-14 17:13
@PierreMarchand20 the issue seems to be related to some jerks in your local vscode files. So I close this issue. Feel free to ask for reopening if you find more information to reproduce the bug.

**Closed by jlelong** 2019-11-14 17:13 UTC
Labels: can't reproduce
