### ISSUE TITLE
Switching to PDF view tab ignores keyboard shortcuts

### ISSUE THREAD

**Issue by justinarose** [James-Yu/LaTeX-Workshop#1537] opened 2019-07-26 04:45 UTC
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**
When I create a pdf and view it in VSCode, if I switch to the pdf tab I can no longer use any keyboard shortcuts including the command palette. This is frustrating because I have to click back to my source tab to get any keyboard shortcuts working again. 

**To Reproduce**

- Have a built latex project with source open and run the command (through the command pallette) 
- Switch to the pdf tab with command+2 (running on mac)
- No more keyboard shortcuts work (sometimes this occurs after switch back and forth twice ie command+2 then command+1 then command+2)

**Expected behavior**
The keyboard shortcuts shouldn't hang after switching to the 

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>

[21:17:27] Initializing LaTeX Workshop.
[21:17:27] Creating LaTeX Workshop http and websocket server.
[21:17:27] LaTeX Workshop initialized.
[21:17:27] Server created on 127.0.0.1:59121
[21:17:27] Snippet data loaded.
[21:17:27] LaTeX Workshop version: 7.2.0
[21:17:27] Try root file in root directory: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:17:47] VIEW command invoked.
[21:17:47] Found root file from active editor: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:17:47] Root file changed from: undefined. Find all dependencies.
[21:17:47] Instantiating a new file watcher for /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:17:47] Parsing /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:17:47] Parsing /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.fls to compute dependencies
[21:17:47] Serving PDF file at http://localhost:59121/viewer.html?file=pdf..JTJGVXNlcnMlMkZqdXN0aW5yb3NlJTJGRG9jdW1lbnRzJTJGc3RhbmZvcmQlMkZzb3Bob21vcmUlMkZzcHJpbmclMkZtYXRoMTIwJTJGcHNldDclMkZwc2V0Ny5wZGY
[21:17:47] The encoded path is /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:17:47] Open PDF tab for /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:17:47] Handle data type: open
[21:17:47] Preview PDF file: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:17:47] Handle data type: loaded
[21:18:05] Handle data type: click
[21:18:05] SyncTeX to file /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:18:28] Handle data type: click
[21:18:28] SyncTeX to file /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:18:41] CLEAN command invoked.
[21:18:41] Found root file from active editor: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:18:41] Root file remains unchanged from: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex.
[21:18:41] File cleaned: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.log
[21:18:41] File cleaned: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.aux
[21:18:41] File cleaned: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.fdb_latexmk
[21:18:41] File cleaned: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.fls
[21:18:44] BUILD command invoked.
[21:18:44] Found root file from active editor: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:18:44] Root file remains unchanged from: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex.
[21:18:44] Building root file: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:18:44] Build root file /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:18:44] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7,/Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7
[21:18:44] LaTeX build process spawned. PID: 5513.
[21:18:45] LaTeX log parsed with 2 messages.
[21:18:45] Recipe of length 1 finished. PID: 5513.
[21:18:45] Successfully built /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex.
[21:18:45] Refresh PDF viewer for /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:18:45] Parsing /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.fls to compute dependencies
[21:18:45] Handle data type: position
[21:18:46] Preview PDF file: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:18:46] Handle data type: loaded
[21:20:33] Handle data type: close
[21:20:54] VIEW command invoked with mode: tab.
[21:20:54] Found root file from active editor: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:20:54] Root file remains unchanged from: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex.
[21:20:54] Serving PDF file at http://localhost:59121/viewer.html?file=pdf..JTJGVXNlcnMlMkZqdXN0aW5yb3NlJTJGRG9jdW1lbnRzJTJGc3RhbmZvcmQlMkZzb3Bob21vcmUlMkZzcHJpbmclMkZtYXRoMTIwJTJGcHNldDclMkZwc2V0Ny5wZGY
[21:20:54] The encoded path is /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:20:54] Open PDF tab for /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:20:55] Handle data type: open
[21:20:55] Preview PDF file: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:20:55] Handle data type: loaded
[21:21:31] Handle data type: close
[21:27:20] VIEW command invoked with mode: tab.
[21:27:20] Found root file from active editor: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:27:20] Root file remains unchanged from: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex.
[21:27:20] Serving PDF file at http://localhost:59121/viewer.html?file=pdf..JTJGVXNlcnMlMkZqdXN0aW5yb3NlJTJGRG9jdW1lbnRzJTJGc3RhbmZvcmQlMkZzb3Bob21vcmUlMkZzcHJpbmclMkZtYXRoMTIwJTJGcHNldDclMkZwc2V0Ny5wZGY
[21:27:20] The encoded path is /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:27:20] Open PDF tab for /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:27:21] Handle data type: open
[21:27:21] Preview PDF file: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:27:21] Handle data type: loaded
[21:27:33] Handle data type: close
[21:27:35] VIEW command invoked with mode: tab.
[21:27:35] Found root file from active editor: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:27:35] Root file remains unchanged from: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex.
[21:27:35] Serving PDF file at http://localhost:59121/viewer.html?file=pdf..JTJGVXNlcnMlMkZqdXN0aW5yb3NlJTJGRG9jdW1lbnRzJTJGc3RhbmZvcmQlMkZzb3Bob21vcmUlMkZzcHJpbmclMkZtYXRoMTIwJTJGcHNldDclMkZwc2V0Ny5wZGY
[21:27:35] The encoded path is /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:27:35] Open PDF tab for /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:27:35] Handle data type: open
[21:27:35] Preview PDF file: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:27:35] Handle data type: loaded
[21:27:44] Handle data type: close
[21:27:49] VIEW command invoked.
[21:27:49] Found root file from active editor: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:27:49] Root file remains unchanged from: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex.
[21:27:49] Serving PDF file at http://localhost:59121/viewer.html?file=pdf..JTJGVXNlcnMlMkZqdXN0aW5yb3NlJTJGRG9jdW1lbnRzJTJGc3RhbmZvcmQlMkZzb3Bob21vcmUlMkZzcHJpbmclMkZtYXRoMTIwJTJGcHNldDclMkZwc2V0Ny5wZGY
[21:27:49] The encoded path is /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:27:49] Open PDF tab for /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:27:50] Handle data type: open
[21:27:50] Preview PDF file: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:27:50] Handle data type: loaded
[21:28:07] Handle data type: close
[21:28:09] VIEW command invoked.
[21:28:09] Found root file from active editor: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:28:09] Root file remains unchanged from: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex.
[21:28:09] Serving PDF file at http://localhost:59121/viewer.html?file=pdf..JTJGVXNlcnMlMkZqdXN0aW5yb3NlJTJGRG9jdW1lbnRzJTJGc3RhbmZvcmQlMkZzb3Bob21vcmUlMkZzcHJpbmclMkZtYXRoMTIwJTJGcHNldDclMkZwc2V0Ny5wZGY
[21:28:09] The encoded path is /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:28:09] Open PDF tab for /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:28:10] Handle data type: open
[21:28:10] Preview PDF file: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:28:10] Handle data type: loaded
[21:29:01] Handle data type: close
[21:29:05] VIEW command invoked.
[21:29:05] Found root file from active editor: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex
[21:29:05] Root file remains unchanged from: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.tex.
[21:29:05] Serving PDF file at http://localhost:59121/viewer.html?file=pdf..JTJGVXNlcnMlMkZqdXN0aW5yb3NlJTJGRG9jdW1lbnRzJTJGc3RhbmZvcmQlMkZzb3Bob21vcmUlMkZzcHJpbmclMkZtYXRoMTIwJTJGcHNldDclMkZwc2V0Ny5wZGY
[21:29:05] The encoded path is /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:29:05] Open PDF tab for /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:29:05] Handle data type: open
[21:29:05] Preview PDF file: /Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/pset7.pdf
[21:29:05] Handle data type: loaded
</details>

<details>
<summary>Developer Tools Console [Required]</summary>

ERR Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/.vscode'
log.ts:173   ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Users/justinrose/Documents/stanford/sophomore/spring/math120/pset7/.vscode'
webviewElement.ts:363 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
webviewElement.ts:363 [Embedded Page] PDF df4d8ce485f566f160817e107f91747f [1.5 pdfTeX-1.40.20 / TeX] (PDF.js: 2.0.943)
webviewElement.ts:363 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
webviewElement.ts:363 [Embedded Page] PDF 915f1eb8bb9e2bcf249937c629814038 [1.5 pdfTeX-1.40.20 / TeX] (PDF.js: 2.0.943)
webviewElement.ts:363 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
webviewElement.ts:363 [Embedded Page] PDF 915f1eb8bb9e2bcf249937c629814038 [1.5 pdfTeX-1.40.20 / TeX] (PDF.js: 2.0.943)
webviewElement.ts:363 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
webviewElement.ts:363 [Embedded Page] PDF 915f1eb8bb9e2bcf249937c629814038 [1.5 pdfTeX-1.40.20 / TeX] (PDF.js: 2.0.943)
webviewElement.ts:363 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
webviewElement.ts:363 [Embedded Page] PDF 915f1eb8bb9e2bcf249937c629814038 [1.5 pdfTeX-1.40.20 / TeX] (PDF.js: 2.0.943)
webviewElement.ts:363 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
webviewElement.ts:363 [Embedded Page] PDF 915f1eb8bb9e2bcf249937c629814038 [1.5 pdfTeX-1.40.20 / TeX] (PDF.js: 2.0.943)
webviewElement.ts:363 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
webviewElement.ts:363 [Embedded Page] PDF 915f1eb8bb9e2bcf249937c629814038 [1.5 pdfTeX-1.40.20 / TeX] (PDF.js: 2.0.943)
webviewElement.ts:363 [Embedded Page] Uncaught (in promise) SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
webviewElement.ts:363 [Embedded Page] PDF 915f1eb8bb9e2bcf249937c629814038 [1.5 pdfTeX-1.40.20 / TeX] (PDF.js: 2.0.943)
</details>

**Screenshots**

**Desktop [Required]:**
 - OS: macOS Mojave 10.14.5
 - VS Code version: 1.36.1
 - Extension version: 7.2.0

**Are you using LaTeX Workshop with VS Code Remote?**

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 5.0.0]

**Additional context**

**Comment by jlelong** [comment] 2019-07-26 04:48
Duplicate of #1406.

**Closed by jlelong** 2019-07-26 04:48 UTC
