### ISSUE TITLE
Autosuggestions on every word 

### ISSUE THREAD

**Issue by btracey** [James-Yu/LaTeX-Workshop#645] opened 2018-05-23 17:35 UTC
I apologize, I've been working for a while to get a consistent and minimal reproducer, but I cannot really. With the new VS Code 5.5, there are suggestions on macro autocompletes way too frequently in normal text mode. Here is the minimal reproducer I have:

![image](https://user-images.githubusercontent.com/3680859/40440335-0604ee7a-5e7b-11e8-9331-1f1a94ad5f54.png)

With that minimal reproducer, it seems to only pop-up on the letters "b" and "f", and no other. 

However, if the line goes beyond column 100, and the text is being edited in the middle, then extra autocompletes start up:

![image](https://user-images.githubusercontent.com/3680859/40440804-485d041e-5e7c-11e8-9a06-59335c10af26.png)

It seems that when I get to column 105, an macro suggestion gets made on every letter (not just b and f)

![image](https://user-images.githubusercontent.com/3680859/40440832-5b49a6ea-5e7c-11e8-8209-8c4a93cd10bf.png)

However, this does not happen if I'm typing and the end of the line (with no characters after the cursor)

![image](https://user-images.githubusercontent.com/3680859/40440878-7ca5b342-5e7c-11e8-995f-ca9405adc21c.png)

### Log messages

I don't see anything interesting in the Latex Workshop Output.

This is what I see in the developer tools that looks fishy. Not sure if it's relevant.

```
[James-Yu.latex-workshop]ENOENT: no such file or directory, open 'Untitled-1'
```

```
mainThreadExtensionService.ts:44 Error: ENOENT: no such file or directory, open 'Untitled-1'
	at Object.fs.openSync (fs.js:584:18)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
	at Object.fs.readFileSync (fs.js:491:33)
	at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
	at Manager.findDependentFiles (/Users/brendan/.vscode/extensions/James-Yu.latex-workshop-5.5.0/out/src/components/manager.js:187:28)
	at Manager.findAllDependentFiles (/Users/brendan/.vscode/extensions/James-Yu.latex-workshop-5.5.0/out/src/components/manager.js:168:18)
	at Manager.findRoot (/Users/brendan/.vscode/extensions/James-Yu.latex-workshop-5.5.0/out/src/components/manager.js:62:26)
	at context.subscriptions.push.vscode.window.onDidChangeActiveTextEditor (/Users/brendan/.vscode/extensions/James-Yu.latex-workshop-5.5.0/out/src/main.js:197:35)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:89:496)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:688:563
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:89:496)
	at e.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:686:754)
	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:599:737)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:599:455)
	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:598:529)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:598:298)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:597:226
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:600:324
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:88:119
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:89:496)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
mainThreadExtensionService.ts:43 [James-Yu.latex-workshop]ENOENT: no such file or directory, open 'Untitled-1'
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
```

### Additional Information

Here are my (possibly) relevant user settings

```
    "editor.wordWrap": "on",
    "editor.wordBasedSuggestions": false,
    "editor.rulers": [
        80
    ],
    "[latex]":{
        "editor.wordWrap": "on",
        "editor.wordBasedSuggestions": false
    },
    "latex-workshop.view.pdf.viewer": "tab",
```

**Comment by James-Yu** [comment] 2018-05-24 01:41
Thank you for the report. This is a problem introduced in the last updates in which many new snippets are introduced. Will look into it.

**Comment by jlelong** [comment] 2018-05-24 05:02
The following new snippets (not starting with `\`) have been added:
1. `BXY` inserts an environment with `XY` being the first two letters of the environment name.
1. `BSXY` does the same as above but using the star version of the environment.
1. `@ + letter` inserts the associated greek letter. `@a` expands into `\alpha`.
1. `FXY` inserts the font modifier `\textxy` where `xy` can be `it`, `bf`, `tt` or `em`.
1. `__` inserts `_{}` and `**` inserts `^{}`.

This is basically based on `vim-latex`.

Googling around, I have found out that vscode intellisense is case insensitive, which is the reason why `b` and `f` also trigger completion.

After some tests, it seems that the setting `"editor.wordBasedSuggestions": false` does nothing in `latex` mode, word based suggestions are always triggered.

I am a bit puzzled by your second and third screenshots, it looks as if you had manually triggered auto-completion on a blank character. Do you have any other settings referring to `suggestions`?

**Comment by btracey** [comment] 2018-05-24 22:56
I do not have any other settings related to `suggestions`. I don't know how to manually trigger autocomplete, so I am not doing that as far as I understand. Just to point out, the cursor in the section screenshot is after the "e" in "complete", and after typing that e the suggestions popped up (mid typing). In the third screenshot, the cursor is at the solo "t" where the autocomplete appears.

I was similarly surprised about the column length thing, when I was trying to reproduce the bug I was looking at dealing with quotations, brackets, inline math mode, none of that seemed to matter. The column length was what I found. Typing in my real tex document, this is very reproducible. If I start typing toward the beginning of the paragraph, nothing. If I start typing around column index 120 or 160, the autocomplete kicks in. If I add a newline and start typing from the same place (such that I'm typing at column ~130 from the end of the line and not the middle) the issue does not happen.

**Comment by jlelong** [comment] 2018-05-25 06:09
I finally managed to reproduce this strange behaviour while typing in the middle of a line. The intellisense popup shows all the snippets of the current mode when `"editor.wordBasedSuggestions": false` and `"editor.quickSuggestions": true` and and the cursor is at least at column 100. Setting `"editor.quickSuggestions": true` 

 If `"editor.wordBasedSuggestions": true` or `"editor.quickSuggestions": false`, no such strange completion occurs.

I believe this bug is not related to this extension but rather a problem in vscode. Maybe, it is worth posting an issue directly on vscode repo.

I will keep investigating this, but so far I cannot really localize the issue.

**Comment by jlelong** [comment] 2018-07-10 09:46
It seems to be fixed in the new release of vscode.

**Closed by jlelong** 2018-07-10 09:46 UTC
Labels: thank you so much contributor!
