### ISSUE TITLE
Incorrect display of text in the TikZ code snippets when using scaled size.

### ISSUE THREAD

**Issue by vvitez** [James-Yu/LaTeX-Workshop#3779] opened 2023-03-19 21:15 UTC
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ x] The issue has not been reported in this repository.
- [ x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [ x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Linux (Arch, linux-lts 6.1.20-1, xorg,) but same thing happens on Ubuntu 22.04, too
- Visual Studio Code Version: [e.g. 1.41.0] 1.76.1
- LaTeX Workshop Version: [e.g. 8.5.0] 9.7.0
- TeX Distribution Version: [e.g. TeX Live 2019 / MiKTeX 2.9.7250] doesn't matter

## The Issue*
> _Please briefly describe the issue you come across._
- When using a scaled view of VSCode, (Ctrl - [+]) the TikZ snippets located on the bottom left aren't displayed properly.
![image](https://user-images.githubusercontent.com/66899393/226209753-c09b95ee-93e2-45db-878d-1c504a403584.png)

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Go to the extension tab
2. scale up the size of text and UI with CTRL- [+]
3. See garbled text ^^

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- readable text, potentially with a side-scroll bar

I know this is a minor issue, but thought I'd report it anyways, as it confused me a bit, until I scaled down to see what happened.
Love this extension btw, great work :).

**Comment by James-Yu** [comment] 2023-03-24 05:31
I cannot reproduce this issue on my macos 13.2 or windows 11. As I do not have access to a linux desktop with GUI, I may not be able to fix the bug.

I'm closing this issue for now, and hopefully the community may provide technical analysis or even fix to the problem.

**Closed by James-Yu** 2023-03-24 05:31 UTC
