### ISSUE TITLE
Cannot extend existing recipes

### ISSUE THREAD

**Issue by SpechtMagnus** [James-Yu/LaTeX-Workshop#2992] opened 2021-11-29 14:57 UTC
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

When writing new recipes in the settings.json file all the default recipes are replaced. I just want to add a new recipe without losing all the default ones. It seems that the default recipes should already be in the settings. json, but this file does not contain any Latex Workshop settings.

### To Reproduce

1. Go to 'settings.json'
2. Add a custom recipe
3. Restart VScode
4. All default recipes get replaced with the custom recipe

### Expected behavior

The default recipes should still be there and the custom recipe should appear either above or below them.

## Logs [Required]

*There is no relevant logging*

### LaTeX Workshop Output [Required]

```
Ready
```

### Developer Tools Console [Required]

*There is no relevant logging*

## Screenshots

![image](https://user-images.githubusercontent.com/17083450/143890585-d0046556-aa64-424e-8a67-cbfd5899f4c0.png)

## Desktop [Required]

 - OS: Windows 10
 - VS Code version: 1.62.3
 - Extension version: 8.22.0
 - TeX distribution version: MikTex Console 4.4

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment] 2021-11-29 17:30
Duplicate of #2964

**Closed by jlelong** 2021-11-29 17:30 UTC
