### ISSUE TITLE
Editor no longer closes "\[" and "\(" brackets automatically

### ISSUE THREAD

**Issue by martinprad0** [James-Yu/LaTeX-Workshop#3985] opened 2023-08-17 11:00 UTC
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ x] The issue has not been reported in this repository.
- [ x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [ x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Fedora 38
- Visual Studio Code Version: 1.80.1
- LaTeX Workshop Version: v9.13.4
- TeX Distribution Version: TeX Live 2022

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using Snap whose version is 1.80.1

## The Issue*
> _Please briefly describe the issue you come across._
-  The snippets for closing "\\[" and "\\(" brackets no longer work
-  However, "(", "[" and "{" do close automatically

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1.  Open .tex file in vscode
2.  Write "\\[" or "\\("

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
-  Whenever I write "\\[", I expect the editor to autocomplete it with "\\]"
-  Also, I expected the same behavior when typing "$" to autocomplete with another "$", except when I write "\\$"

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
5:55:27.971][Logger] New log placeholder %WS1% registered for /home/martin/Documents/VSCode/Latex .
[05:55:27.971][Config] latex-workshop.intellisense.unimathsymbols.enabled: true .
[05:55:27.991][Config] latex-workshop.message.badbox.show: false .
[05:55:27.993][Config] latex-workshop.message.error.show: false .
[05:55:28.016][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[05:55:28.033][Server] Creating LaTeX Workshop http and websocket server.
[05:55:28.104][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":33409} .
[05:55:28.126][Extension] Initializing LaTeX Workshop.
[05:55:28.127][Extension] Extension root: /home/martin/.vscode/extensions/james-yu.latex-workshop-9.13.4
[05:55:28.127][Extension] $PATH: /home/martin/gems/bin:/home/martin/gems/bin:/home/martin/.local/bin:/home/martin/bin:/usr/lib64/ccache:/home/martin/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin
[05:55:28.128][Extension] $SHELL: /bin/bash
[05:55:28.128][Extension] $LANG: en_US.UTF-8
[05:55:28.128][Extension] $LC_ALL: undefined
[05:55:28.129][Extension] process.platform: linux
[05:55:28.129][Extension] process.arch: x64
[05:55:28.129][Extension] vscode.env.appName: Visual Studio Code
[05:55:28.130][Extension] vscode.env.remoteName: undefined
[05:55:28.130][Extension] vscode.env.uiKind: 1
[05:55:28.130][Extension] LaTeX Workshop initialized.
[05:55:28.138][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[05:55:28.140][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[05:55:28.143][Manager] Current workspace folders: ["file://%WS1%"]
[05:55:28.144][Manager] Found root file from active editor: %WS1%/Geometry Homework/GD-HW1.tex
[05:55:28.144][Manager] Root file changed: from undefined to %WS1%/Geometry Homework/GD-HW1.tex
[05:55:28.145][Manager] Start to find all dependencies.
[05:55:28.145][Manager] Root file languageId: latex
[05:55:28.146][Event] ROOT_FILE_CHANGED: "%WS1%/Geometry Homework/GD-HW1.tex"
[05:55:28.146][Cacher][Watcher] Reset.
[05:55:28.151][Cacher] Adding %WS1%/Geometry Homework/GD-HW1.tex .
[05:55:28.153][Cacher][Watcher] Watched %WS1%/Geometry Homework/GD-HW1.tex with a new watcher on %WS1%/Geometry Homework .
[05:55:28.153][Event] FILE_WATCHED: "%WS1%/Geometry Homework/GD-HW1.tex"
[05:55:28.158][Cacher] Caching %WS1%/Geometry Homework/GD-HW1.tex .
[05:55:28.160][Cacher] Updated inputs of %WS1%/Geometry Homework/GD-HW1.tex .
[05:55:28.160][Cacher] Parse LaTeX AST: %WS1%/Geometry Homework/GD-HW1.tex .
[05:55:28.161][Event] ROOT_FILE_SEARCHED
[05:55:28.313][Cacher] Parsed LaTeX AST: %WS1%/Geometry Homework/GD-HW1.tex .
[05:55:28.314][Cacher][Path] Calling kpsewhich to resolve exam.cls .
[05:55:28.460][Cacher] Updated elements in 146.62 ms: %WS1%/Geometry Homework/GD-HW1.tex .
[05:55:28.460][Event] FILE_PARSED: "%WS1%/Geometry Homework/GD-HW1.tex"
[05:55:28.462][Cacher] Parsing .fls %WS1%/Geometry Homework/GD-HW1.fls .
[05:55:28.494][Cacher] Found .aux %WS1%/Geometry Homework/GD-HW1.tex from .fls %WS1%/Geometry Homework/GD-HW1.fls , parsing.
[05:55:28.495][Cacher] Parsed .aux %WS1%/Geometry Homework/GD-HW1.tex .
[05:55:28.496][Cacher] Parsed .fls %WS1%/Geometry Homework/GD-HW1.fls .
[05:55:28.497][Structure] Structure force updated with 0 root sections for %WS1%/Geometry Homework/GD-HW1.tex .
[05:55:28.498][Event] STRUCTURE_UPDATED
[05:55:28.503][Server] valdOrigin is http://127.0.0.1:33409
[05:55:44.486][Event] STRUCTURE_UPDATED
```

**Comment by James-Yu** [comment] 2023-08-17 11:03
Can you help identify from which version the feature no longer works?

**Comment by martinprad0** [comment] 2023-08-17 11:05
**Update:** Whenever I disable the extension, the issue dissapears

**Comment by martinprad0** [comment] 2023-08-17 11:07
> Can you help identify from which version the feature no longer works?

I'm sorry, which version of what specifically? I believe I'm using v9.13.4 of the extension.

**Comment by James-Yu** [comment] 2023-08-17 11:18
I mean the version of the extension. You can install older version via the extension tab.

**Comment by martinprad0** [comment] 2023-08-17 11:28
> I mean the version of the extension. You can install older version via the extension tab.

From version 8.15 onward, I start getting a suggestion but it doesn't autocomplete as I mentioned earlier
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/66460425/90c49f80-4aec-430e-af48-27a9522129b8)

In all of the versions below 8.14, "\\[" autocompletes with just "]"
![image](https://github.com/James-Yu/LaTeX-Workshop/assets/66460425/85d566ef-7f13-4d94-80e6-9f345ffea6a2)

**Comment by martinprad0** [comment] 2023-08-17 11:55
Thanks for the attention. But I need to keep working on my homework, so for those who may encounter the same problem as me I made a "workaround" using another extension called HyperSnips. I made a file called latex.hsnips in the path the extension specified (In my case is `.config/Code/User/hsnips/latex.hsnips`). The contents of the file are the following:

```
snippet \[ "Math" wA
\[$1 \] $0
endsnippet

snippet \( "Math" wA
\($1 \) $0
endsnippet
```

I really hope this issue gets solved soon, so I don't have to depend on third-party scripts to have a comfortable editing experience.

**Comment by James-Yu** [comment] 2023-08-17 13:23
Thanks for the info. I will fix the issue, but it may be a bit delayed as I was too busy recently.

**Comment by jlelong** [comment] 2023-08-17 19:07
I cannot reproduce the issue with VS Code `1.81.1` and LW `9.13.4`. Do you have any other extension installed dealing with bracket pairs?

In your original post, you also mentioned the autocompletion of the dollar sign. This has been already discussed a lot and we have decided not to autocomplete `$` on purpose.

**Comment by jlelong** [comment] 2023-08-17 19:08
I cannot reproduce the issue with VS Code `1.81.1` and LW `9.13.4`. Do you have any other extension installed dealing with bracket pairs?

In your original post, you also mentioned the autocompletion of the dollar sign. This has been already discussed a lot and we have decided not to autocomplete `$` on purpose.

**Comment by AVAtarMod** [comment] 2023-08-18 06:38
On Visual Studio Code `1.77.3` and LaTeX Workshop `9.13.4` I also cannot reproduce this bug.

**Comment by jlelong** [comment] 2023-08-24 16:08
I am closing this issue as we do not seem to be able to reproduce it.
Feel free to ask for reopening if you can provide more information to reproduce it.

**Closed by jlelong** 2023-08-24 16:08 UTC
Labels: can't reproduce
