### ISSUE TITLE
"align" component not listed in IntelliSense

### ISSUE THREAD

**Issue by charleslambert98** [James-Yu/LaTeX-Workshop#2086] opened 2020-05-15 03:01 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: N/A

## Describe the bug [Required]

When attempting to input the \align component (previously the shorthand for \begin{align}, there is no IntelliSense detection.  This was not the case prior to the most recent version.

### To Reproduce

1. Type "\align"
2. No text recommendation

### Expected behavior

1. Type "\align"
2. Text recommendation for "\begin{align} ... \end{align}"

## Desktop [Required]
 - OS: Ubuntu 18.04, macOS 10.15.2
 - VS Code version: 1.45.0
 - Extension version: 8.9.0
 - TeX distribution version: N/A

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment] 2020-05-15 03:08
Duplicate of  #2052

**Closed by tamuratak** 2020-05-15 03:08 UTC
