### ISSUE TITLE
Synctex forward search does not trigger on click (short cut works)

### ISSUE THREAD

**Issue by breecummins** [James-Yu/LaTeX-Workshop#981] opened 2018-11-13 19:36 UTC
### Description

Cmd-option-J triggers forward search, but plain click or double click or highlight and click does not trigger forward search. Cmd-click triggers reverse search as described.

### Log messages

I don't think the logs are correlated. I have warnings only, no errors, and the pdf built correctly.

<details>
<summary>LaTeX Workshop Output</summary>

</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. Build project.
2. Click or double click on .tex source.
3. Observe that the .pdf position does not change.

### Expected behavior

I expect a click or double-click to take me from the position in the .tex source to the corresponding position in the .pdf. This works only if I use cmd-option-J, or go through the Command Palette. 

### Actual behavior

Click/double-click has no effect.

### Additional Information

I'm on Mac OS X High Sierra, with 2018 MacTeX installation.

**Comment by breecummins** [comment] 2018-11-13 19:39
I should also mention that I tried on two different documents and saw the same behavior.

**Comment by tamuratak** [comment] 2018-11-14 06:29
Duplicate of #716

**Closed** 2018-11-14 07:07 UTC
