### ISSUE TITLE
"latex-workshop.latexindent.path" option is not working on Windows

### ISSUE THREAD

**Issue by qiansen1386** [James-Yu/LaTeX-Workshop#2248] opened 2020-08-20 19:19 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

"latex-workshop.latexindent.path": "D:\\path\\to\\texlive\\bin\\latexindent.exe" setting option is not working on Windows 10.

VS Code complains about: `Can not find latexindent in PATH!`

However if I manually run the command in Powershell, it works
```
'D:\path\to\texlive\bin\latexindent.exe' --version
3.8.2, 2020-06-10
```

### To Reproduce

1. Paste the path to Latexindent.exe to "latex-workshop.latexindent.path" Setting textbox
3. Try format a tex document

### Expected behavior

Format tex file using latexindent.exe

### LaTeX Workshop Output [Required]
```
[05:12:54] Initializing LaTeX Workshop.
[05:12:54] Creating PDF file watcher.
[05:12:54] Creating LaTeX Workshop http and websocket server.
[05:12:54] LaTeX Workshop initialized.
[05:12:54] Linter for root file started.
[05:12:54] No root file found for linting.
[05:12:54] Found root file from active editor: c:\path\to\filename.tex
[05:12:54] Root file changed: from undefined to c:\path\to\filename.tex
[05:12:54] Start to find all dependencies.
[05:12:54] Instantiating a new file watcher for c:\path\to\filename.tex
[05:12:54] Creating Bib file watcher.
[05:12:54] Parsing a file and its subfiles: c:\path\to\filename.tex
[05:12:54] Found .bib file: c:\path\to\filename.bib
[05:12:54] Added to bib file watcher: c:\path\to\filename.bib
[05:12:54] Parsing .bib entries from c:\path\to\filename.bib
[05:12:54] Parse fls file.
[05:12:54] Fls file found: c:\path\to\filename.fls
[05:12:54] Parse aux file: c:\path\to\filename.aux
[05:12:54] Server created on 127.0.0.1:12992
[05:12:55] Added to file watcher: c:\path\to\filename.tex
[05:12:55] Added to file watcher: c:\path\to\filename.png
[05:12:55] Snippet data loaded.
[05:12:55] LaTeX Workshop version: 8.11.1
[05:12:55] Parsed 1 bib entries from c:\path\to\filename.bib.
[05:12:56] Preview PDF file: c:\path\to\filename.pdf
[05:12:56] Handle data type: open
[05:12:56] Handle data type: request_params
[05:12:56] Handle data type: loaded
[05:12:59] Start formatting with latexindent.
[05:13:00] Can not find latexindent in PATH!
```

### Developer Tools Console [Required]

```
[Embedded Page] PDF dc93700ee9ed08148250fd0dfff8cd8c [1.5 pdfTeX-1.40.20 / LaTeX with hyperref] (PDF.js: 2.3.200)
workbench.desktop.main.js:sourcemap:2988 Can not find latexindent in PATH!
onDidChangeNotification @ workbench.desktop.main.js:sourcemap:2988
4workbench.desktop.main.js:sourcemap:1679  INFO Setting search error: XHR timeout: 5000ms
```

## Desktop [Required]
 - OS: [e.g. Windows 10]
 - VS Code version: [e.g. 1.48.7]
 - Extension version: [e.g. 8.11.1]
 - TeX distribution version: [e.g. TeX Live 2020]

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by qiansen1386** [comment] 2020-08-20 19:25
Update: If we do not put a full path, but just a "latexindent.exe", then it works fine.

**Comment by tamuratak** [comment] 2020-08-20 21:53
Duplicate of  #2202

**Closed by tamuratak** 2020-08-20 21:53 UTC
