### ISSUE TITLE
WSL remote: View latex Pdf file - shows garbage. It's bug.

### ISSUE THREAD

**Issue by sfolje0** [James-Yu/LaTeX-Workshop#2258] opened 2020-08-28 13:55 UTC
Simmilar as issue: PDFviewer broken in VS Code 1.47.0 over remote ssh #2206

Steps:
Open code in remote WSL: Legacy, open .`tex `file and click on View latex PDF file, or run
"Latex Workshop:  View latex PDF file". It will first display `pdf `file properly. Now change and build your .`tex `file and View it again. It will not work any more. It will not show `pdf `file but instead some kind of `Html `form like, when your webpage is halfway loaded (without images). So you can see buttons like "Print", "Thumbnails", "Close", "Next", "Previous", "Find" and so on. It is clearly a bug:
![Untitled](https://user-images.githubusercontent.com/17193453/91571690-b44ab980-e946-11ea-81bb-4f6fa59438ab.png)

On the other side, in standard Windows code it works flawlessly.

**Comment by tamuratak** [comment] 2020-08-28 14:11
Duplicate of #2206

**Closed by tamuratak** 2020-08-28 14:11 UTC
