### ISSUE TITLE
Autocompletion leaves trailing brace after environments included with `\begin{<environment>}`

### ISSUE THREAD

**Issue by BambOoxX** [James-Yu/LaTeX-Workshop#2087] opened 2020-05-15 09:16 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Not applicable

## Describe the bug [Required]

Autocompletion for environments leaves a trailing `}` after `\end{<environment>}`.
Autocompletion with `\<environment>` works fine

### To Reproduce

Not working
![2020-05-15-11-11-25](https://user-images.githubusercontent.com/42067365/82033372-ec323780-969c-11ea-9dd2-0c9148b4af26.gif)

Working
![2020-05-15-11-13-50](https://user-images.githubusercontent.com/42067365/82033579-361b1d80-969d-11ea-8fd1-75c9aa860873.gif)

### Expected behavior

The behavior should be the same for `\begin{<environment>}` and `\<environment>` autocompletions.

## Logs [Required]

[11:06:18] Initializing LaTeX Workshop.
[11:06:18] Creating file watcher for .pdf files.
[11:06:19] pdflatex is provided by MiKTeX
[11:06:19] Creating LaTeX Workshop http and websocket server.
[11:06:19] LaTeX Workshop initialized.
[11:06:19] Found root file from active editor: c:\Users\bamboo\Desktop\test\test.tex
[11:06:19] Root file changed from: undefined to c:\Users\bamboo\Desktop\test\test.tex. Find all dependencies.
[11:06:19] Instantiating a new file watcher for c:\Users\bamboo\Desktop\test\test.tex
[11:06:19] Creating file watcher for .bib files.
[11:06:19] Parsing c:\Users\bamboo\Desktop\test\test.tex
[11:06:19] Parse fls file.
[11:06:19] Cannot find fls file.
[11:06:19] Server created on 127.0.0.1:60704
[11:06:19] Adding c:\Users\bamboo\Desktop\test\test.tex to file watcher.
[11:06:19] LaTeX Workshop version: 8.9.0
[11:06:19] Snippet data loaded.

## Desktop [Required]
 - OS: Windows 10
 - VS Code version: 1.45.1
 - Extension version: 8.9.0

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment] 2020-05-15 10:01
Duplicate of #2075

**Closed by tamuratak** 2020-05-15 10:01 UTC

**Comment by BambOoxX** [comment] 2020-05-15 10:06
@tamuratak Sorry for that, totally missed this previous issue. Thanks for pointing the duplicate.
