### ISSUE TITLE
Can't compile latex files with '~' in path (such as iClouds 'real' path)

### ISSUE THREAD

**Issue by jawalking** [James-Yu/LaTeX-Workshop#1292] opened 2019-04-11 06:26 UTC
**Describe the bug**
On OS X, building a PDF from source LaTex fails if there is at least one tilde (\~) in anywhere in the path. Such as the path to iCloud (/Users/UserName/Library/Mobile Documents/com\~apple\~CloudDocs/Projects/resume).

**To Reproduce**
1. Open a .tex file with at least one '~' in the path, such as /User/UserName/~resume_test/resume.tex
2. Attempt to build a PDF.
3. See error

**Expected behavior**
If you remove all tildes from the path and build, it will complete as expected.

**Logs**

<details>
<summary>LaTeX Workshop Output</summary>
[23:04:36] Initializing LaTeX Workshop.
[23:04:36] Creating LaTeX Workshop http and websocket server.
[23:04:36] LaTeX Workshop initialized.
[23:04:36] Found root file from active editor: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:04:38] Root file changed from: undefined. Find all dependencies.
[23:04:38] Instantiating a new file watcher for /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:04:38] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:04:38] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.fls
[23:04:38] Server created on 127.0.0.1:64633
[23:04:38] Snippet data loaded.
[23:04:38] LaTeX Workshop version: 6.3.0
[23:04:40] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:04:40] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.fls
[23:04:40] File watcher: responding to change in /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:04:40] /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex changed. Auto build project.
[23:04:40] Building root file: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:04:40] Build root file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:04:40] Recipe step 1: xelatex, --synctex=1,--interaction=nonstopmode,/Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:04:40] LaTeX build process spawned. PID: 71894.
[23:04:41] Recipe returns with error: 1/null. PID: 71894.
[23:04:41] Cleaning auxillary files and retrying build after toolchain error.
[23:04:41] CLEAN command invoked.
[23:04:41] Found root file from active editor: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:04:41] Root file remains unchanged from: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex.
[23:04:41] Found root file from active editor: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:04:41] Root file remains unchanged from: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex.
[23:04:41] File cleaned: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/texput.log
[23:04:41] Recipe step 1: xelatex, --synctex=1,--interaction=nonstopmode,/Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:04:41] LaTeX build process spawned. PID: 71895.
[23:04:41] Recipe returns with error: 1/null. PID: 71895.
[23:07:26] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:07:26] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:07:26] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.fls
[23:07:26] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:07:26] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:07:26] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.fls
[23:07:26] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:07:26] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:07:26] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.fls
[23:07:26] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:07:26] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:07:26] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.fls
[23:07:26] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:07:26] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:07:26] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.fls
[23:07:26] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:07:26] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:07:26] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.fls
[23:07:26] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:07:26] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:07:26] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.fls
[23:07:26] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:07:26] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:07:26] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.fls
[23:07:26] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:07:26] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:07:26] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.fls
[23:07:26] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:07:26] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:07:26] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.fls
[23:07:26] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:07:26] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:07:26] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.fls
[23:07:26] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:07:26] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:07:26] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.fls
[23:07:52] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:07:52] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:07:52] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.fls
[23:07:52] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:07:52] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:07:52] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.fls
[23:07:52] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:07:52] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:07:52] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.fls
[23:07:52] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:07:52] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:07:52] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.fls
[23:07:52] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:07:52] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:07:52] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.fls
[23:07:52] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:07:52] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:07:52] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.fls
[23:07:52] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:07:52] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:07:52] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.fls
[23:07:52] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:07:52] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:07:52] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.fls
[23:07:52] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:07:52] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:07:52] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.fls
[23:07:52] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:07:52] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:07:52] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.fls
[23:07:52] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:07:52] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:07:52] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.fls
[23:07:52] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:07:52] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:07:52] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.fls
[23:08:02] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:08:02] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:08:02] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.fls
[23:08:02] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:08:02] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:08:02] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.fls
[23:08:02] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:08:02] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:08:02] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.fls
[23:08:02] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:08:02] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:08:02] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.fls
[23:08:02] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:08:02] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:08:02] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.fls
[23:08:02] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:08:02] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:08:02] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.fls
[23:08:02] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:08:02] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:08:02] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.fls
[23:08:02] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:08:02] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:08:02] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.fls
[23:08:02] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:08:02] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:08:02] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.fls
[23:08:02] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:08:02] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:08:02] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.fls
[23:08:02] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:08:02] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:08:02] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.fls
[23:08:02] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:08:02] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:08:02] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.fls
[23:08:33] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:08:33] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:08:33] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.fls
[23:08:33] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:08:33] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:08:33] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.fls
[23:08:33] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:08:33] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:08:33] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.fls
[23:08:33] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:08:33] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:08:33] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.fls
[23:08:33] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:08:33] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:08:33] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.fls
[23:08:33] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:08:33] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:08:33] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.fls
[23:08:33] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:08:33] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:08:33] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.fls
[23:08:33] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:08:33] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.tex
[23:08:33] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_test.fls
[23:08:33] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:08:33] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.tex
[23:08:33] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_8.fls
[23:08:33] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:08:33] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.tex
[23:08:33] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_7.fls
[23:08:33] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:08:33] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.tex
[23:08:33] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_6.fls
[23:08:33] Try root file in root directory: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:08:33] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.tex
[23:08:33] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/archive/resume_5.fls
[23:13:25] Parsing /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:13:25] Cannot find file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.fls
[23:13:25] File watcher: responding to change in /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:13:25] /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex changed. Auto build project.
[23:13:25] Building root file: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:13:25] Build root file /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:13:25] Recipe step 1: xelatex, --synctex=1,--interaction=nonstopmode,/Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:13:25] LaTeX build process spawned. PID: 72429.
[23:13:25] Recipe returns with error: 1/null. PID: 72429.
[23:13:25] Cleaning auxillary files and retrying build after toolchain error.
[23:13:25] CLEAN command invoked.
[23:13:25] Found root file from active editor: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:13:25] Root file remains unchanged from: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex.
[23:13:25] Found root file from active editor: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:13:25] Root file remains unchanged from: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex.
[23:13:25] File cleaned: /Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/texput.log
[23:13:25] Recipe step 1: xelatex, --synctex=1,--interaction=nonstopmode,/Users/jawalking/Library/Mobile Documents/com~apple~CloudDocs/Projects/resume/resume.tex
[23:13:25] LaTeX build process spawned. PID: 72430.
[23:13:26] Recipe returns with error: 1/null. PID: 72430.

</details>

**Desktop (please complete the following information):**
 - OS: OS X 10.14
 - VS Code version: 1.33.0 
 - Extension version: 6.3.0

**Comment by jlelong** [comment] 2019-04-11 06:54
Duplicate of #1239.

**Closed by jlelong** 2019-04-11 06:54 UTC
