### ISSUE TITLE
Hover preview for pdf-images does not work on macOS Big Sur

### ISSUE THREAD

**Issue by camots** [James-Yu/LaTeX-Workshop#2592] opened 2021-03-21 08:56 UTC
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes/No

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

When hovering the mouse over \includegraphics, the Hover Preview works for jpg and png files, however it does not work for pictures in pdf format. 
![pdf-hoover](https://user-images.githubusercontent.com/27863692/111899258-a320e180-8a2b-11eb-9994-4840eb9ed45d.png)

### To Reproduce
Just hover the mouse above the \includegraphics argument

### Expected behavior
You should get the preview of the image

## Logs [Required]
Nothing is reported in the console (log)

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]
Nothing is written to console

To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[Paste the log here]
Nothing reported

### Developer Tools Console [Required]
Nothing reported

To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
Nothing reported

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: [macOS Big Sur 11.2.3]
 - VS Code version: [e.g. 1.54.3]
 - Extension version: [e.g. 8.16.1]
 - TeX distribution version: [e.g. MiKTeX 21.1.0]

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by tamuratak** [comment] 2021-03-21 09:24
Duplicate of  #2574. Fixed in 47b54cf520da2419c09c208130fbe287a1907704

**Closed by tamuratak** 2021-03-21 09:24 UTC
Labels: duplicate
