### ISSUE TITLE
Command autocomplete not working

### ISSUE THREAD

**Issue by harrysw1729** [James-Yu/LaTeX-Workshop#3640] opened 2023-01-10 20:55 UTC
Autocomplete does not seem to be working in Version 9.4.1–9.4.4.

For example, when I typed `\frac`, there was no autocomplete suggestion showing up for extension version 9.4.1–9.4.4.

In version 9.4.0, autocomplete started to work as expected, as shown in the screenshot below.

![latex_autocomplete](https://user-images.githubusercontent.com/10522520/211659838-f0c6d7f5-aeef-454d-801a-36097cf54088.jpg)

I found only one intellisense-related setting that differs from the default:
```json
"latex-workshop.intellisense.citation.backend": "biblatex"
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: macOS 13.1 (22C65)
 - VS Code version: 1.74.3 (Universal)
 - Extension version: 9.4.4
 - TeX distribution version: MacTex-2022

Thanks for your help in advance.

**Comment by James-Yu** [comment] 2023-01-11 02:24
I confirm this issue is a local one. You may try uninstall and reinstall the extension and see.

**Comment by harrysw1729** [comment] 2023-01-11 15:17
Thank you for the reply.

On two of my Mac devices, reinstalling the extension did not work. 
However, if I remove all the extensions on my VS Code and then install LaTeX-Workshop, 
then autocomplete works again.

Suspecting that one of my extensions might have interfered with LaTeX-Workshop, 
I went on to install other extensions one by one. 
Then I found that the extension isort, a python extension developed by Microsoft that was last updated a month ago, 
appeared to be interfering with LaTeX-Workshop.

When I had the following extensions installed and enabled, there was no autocomplete suggestion when I typed `\frac`.
<img width="237" alt="extensions_isort" src="https://user-images.githubusercontent.com/10522520/211842059-ace15ef3-f72c-440a-9039-970463036723.png">

However, after I disabled the extension isort, autocomplete started to work as expected.
<img width="254" alt="installed_no_isort" src="https://user-images.githubusercontent.com/10522520/211842167-8ad4c2f7-98e4-439a-8e87-9eaa86e18223.png">
<img width="478" alt="autocomplete" src="https://user-images.githubusercontent.com/10522520/211842191-f6451ec5-e4b8-4463-9ed4-66f9a447a707.png">

I also noticed that I could only replicate the issue on my Mac devices. On a Windows device with both LaTeX-Workshop and isort extensions installed, I could not replicate the issue.

Could you please advise whether this issue should be dealt with by developers of the Python extension instead?

**Comment by James-Yu** [comment] 2023-01-11 15:35
That’s weird. I’m afraid the issue is not on our side as I have totally no idea why this may happen. You may approach the other extension for possible help.

**Comment by aperezlebel** [comment] 2023-01-12 09:30
Same issue here using Linux. Disabling the isort extension solved the problem for me as well.

**Comment by James-Yu** [comment] 2023-01-12 09:43
May you confirm this bug only appears on 9.4.1+ but not 9.4.0?

**Comment by aperezlebel** [comment] 2023-01-12 10:29
Yes, on 9.4.1-9.4.4 the issue occurs when isort is enabled and disappears when isort is disabled. On 9.4.0 the issue does not occur whether isort is enabled or not.

**Comment by James-Yu** [comment] 2023-01-12 13:22
I can't understand why `isort` interferes the command intellisense. Here goes the diff between 9.4.0 and .1: https://github.com/James-Yu/LaTeX-Workshop/compare/v9.4.0...v9.4.1

You may see nothing related to command intellisense was touched, let alone functions that may overlap with isort.

I have no idea. Maybe other helps are needed.

**Comment by harrysw1729** [comment] 2023-01-12 15:50
I don't know why, but I‘ve noticed that after I commented out the following part of code in `~/.vscode/extensions/james-yu.latex-workshop-9.4.1/out/src/providers/completion.js` on my Mac device and restarted VS Code, autocompletion started to work.

```javascript
if (type === 'argument') {
            line = line.replaceAll(/{[^[\]{}]*}/g, '').replaceAll(/\[[^[\]{}]*\]/g, '')
        }
```

The same trick worked for 9.4.4.

**Comment by James-Yu** [comment] 2023-01-12 16:43
Can you help me test out the extension of 53f859108b07cec922b6352c631cb088dcdd323d? You may download the packed `vsix` file from https://github.com/James-Yu/LaTeX-Workshop/actions/runs/3904213258, at the bottom of this page?

This commit just add additional log messages around the said line. Please create an empty .tex file, and press a `\` key, then post the log messages here. Many thanks!

**Comment by harrysw1729** [comment] 2023-01-12 17:21
Thanks for your help! I've downloaded the package for the test.

Meanwhile, I found another way to make the issue disappear with isort enabled.

When I created an empty directory and a new `.tex` file, autocomplete actually worked! The log message from LaTeX workshop is below:
```
[17:13:33][Logger] New log placeholder %WS1% registered for /Users/harryw/Documents/testing .
[17:13:33][Config] Configuration for workspace: file://%WS1% .
[17:13:33][Config] editor.acceptSuggestionOnEnter: "on" .
[17:13:33][Config] latex-workshop.bind.enter.key: false .
[17:13:33][Config] latex-workshop.docker.enabled: false .
[17:13:33][Config] latex-workshop.docker.image.latex: "" .
[17:13:33][Config] latex-workshop.hover.preview.mathjax.extensions: [] .
[17:13:33][Config] latex-workshop.intellisense.package.enabled: true .
[17:13:33][Config] latex-workshop.intellisense.update.aggressive.enabled: false .
[17:13:33][Config] latex-workshop.intellisense.update.delay: 1000 .
[17:13:33][Config] latex-workshop.latex.autoBuild.run: "never" .
[17:13:33][Config] latex-workshop.latex.build.forceRecipeUsage: true .
[17:13:33][Config] latex-workshop.latex.outDir: "%DIR%" .
[17:13:33][Config] latex-workshop.latex.recipes: [
 {
  "name": "latexmk (lualatex)",
  "tools": [
   "lualatexmk"
  ]
 },
 {
  "name": "latexmk (xelatex)",
  "tools": [
   "xelatexmk"
  ]
 },
 {
  "name": "latexmk 🔃",
  "tools": [
   "latexmk"
  ]
 },
 {
  "name": "latexmk (latexmkrc)",
  "tools": [
   "latexmk_rconly"
  ]
 },
 {
  "name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
  "tools": [
   "pdflatex",
   "bibtex",
   "pdflatex",
   "pdflatex"
  ]
 },
 {
  "name": "Compile Rnw files",
  "tools": [
   "rnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Jnw files",
  "tools": [
   "jnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "tectonic",
  "tools": [
   "tectonic"
  ]
 }
] .
[17:13:33][Config] latex-workshop.latex.tools: [
 {
  "name": "latexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-pdf",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "lualatexmk",
  "command": "latexmk",
  "args": [
   "-time",
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-lualatex",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "xelatexmk",
  "command": "latexmk",
  "args": [
   "-time",
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-xelatex",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "latexmk_rconly",
  "command": "latexmk",
  "args": [
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "pdflatex",
  "command": "pdflatex",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "bibtex",
  "command": "bibtex",
  "args": [
   "%DOCFILE%"
  ],
  "env": {}
 },
 {
  "name": "rnw2tex",
  "command": "Rscript",
  "args": [
   "-e",
   "knitr::opts_knit$set(concordance = TRUE); knitr::knit('%DOCFILE_EXT%')"
  ],
  "env": {}
 },
 {
  "name": "jnw2tex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"tex\")"
  ],
  "env": {}
 },
 {
  "name": "jnw2texmintex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"texminted\")"
  ],
  "env": {}
 },
 {
  "name": "tectonic",
  "command": "tectonic",
  "args": [
   "--synctex",
   "--keep-logs",
   "%DOC%.tex"
  ],
  "env": {}
 }
] .
[17:13:33][Config] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto" .
[17:13:33][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[17:13:33][Server] Creating LaTeX Workshop http and websocket server.
[17:13:33][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":50806}
[17:13:33][Extension] Initializing LaTeX Workshop.
[17:13:33][Extension] Extension root: /Users/harryw/.vscode/extensions/james-yu.latex-workshop-9.4.4
[17:13:33][Extension] $PATH: /Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
[17:13:33][Extension] $SHELL: /bin/zsh
[17:13:33][Extension] $LANG: undefined
[17:13:33][Extension] $LC_ALL: undefined
[17:13:33][Extension] process.platform: darwin
[17:13:33][Extension] process.arch: arm64
[17:13:33][Extension] vscode.env.appName: Visual Studio Code
[17:13:33][Extension] vscode.env.remoteName: undefined
[17:13:33][Extension] vscode.env.uiKind: 1
[17:13:33][Extension] LaTeX Workshop initialized.
[17:13:33][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[17:13:33][] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[17:13:33][Manager] Current workspace folders: ["file://%WS1%"]
[17:13:33][Manager] Current workspaceRootDir: file://%WS1%
[17:13:33][Server] valdOrigin is http://127.0.0.1:50806
[17:13:33][Cacher][Path] Non-existent .fls for %WS1%/foo.tex .
[17:13:33][Linter] No root file found for ChkTeX.
[17:13:35][Structure] Error loading LaTeX during structuring: %WS1%/foo.tex .
[17:13:49][Intelli] citation
[17:13:49][Intelli] reference
[17:13:49][Intelli] environment
[17:13:49][Intelli] package
[17:13:49][Intelli] documentclass
[17:13:49][Intelli] input
[17:13:49][Intelli] subimport
[17:13:49][Intelli] import
[17:13:49][Intelli] includeonly
[17:13:49][Intelli] glossary
[17:13:49][Intelli] argument
[17:13:49][Intelli] \
[17:13:49][Intelli] \\(\+?[a-zA-Z]*)((?:\[.*?\]|{.*?})*)[[{][^[\]{}]*$
[17:13:49][Intelli] command
[17:13:49][Structure] Error loading LaTeX during structuring: %WS1%/foo.tex .

```

---

However, after I created an empty `.py` file in the same directory, autocomplete stopped working. Below is the log message:
```
[17:16:35][Logger] New log placeholder %WS1% registered for /Users/harryw/Documents/testing .
[17:16:35][Config] Configuration for workspace: file://%WS1% .
[17:16:35][Config] editor.acceptSuggestionOnEnter: "on" .
[17:16:35][Config] latex-workshop.bind.enter.key: false .
[17:16:35][Config] latex-workshop.docker.enabled: false .
[17:16:35][Config] latex-workshop.docker.image.latex: "" .
[17:16:35][Config] latex-workshop.hover.preview.mathjax.extensions: [] .
[17:16:35][Config] latex-workshop.intellisense.package.enabled: true .
[17:16:35][Config] latex-workshop.intellisense.update.aggressive.enabled: false .
[17:16:35][Config] latex-workshop.intellisense.update.delay: 1000 .
[17:16:35][Config] latex-workshop.latex.autoBuild.run: "never" .
[17:16:35][Config] latex-workshop.latex.build.forceRecipeUsage: true .
[17:16:35][Config] latex-workshop.latex.outDir: "%DIR%" .
[17:16:35][Config] latex-workshop.latex.recipes: [
 {
  "name": "latexmk (lualatex)",
  "tools": [
   "lualatexmk"
  ]
 },
 {
  "name": "latexmk (xelatex)",
  "tools": [
   "xelatexmk"
  ]
 },
 {
  "name": "latexmk 🔃",
  "tools": [
   "latexmk"
  ]
 },
 {
  "name": "latexmk (latexmkrc)",
  "tools": [
   "latexmk_rconly"
  ]
 },
 {
  "name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
  "tools": [
   "pdflatex",
   "bibtex",
   "pdflatex",
   "pdflatex"
  ]
 },
 {
  "name": "Compile Rnw files",
  "tools": [
   "rnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Jnw files",
  "tools": [
   "jnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "tectonic",
  "tools": [
   "tectonic"
  ]
 }
] .
[17:16:35][Config] latex-workshop.latex.tools: [
 {
  "name": "latexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-pdf",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "lualatexmk",
  "command": "latexmk",
  "args": [
   "-time",
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-lualatex",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "xelatexmk",
  "command": "latexmk",
  "args": [
   "-time",
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-xelatex",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "latexmk_rconly",
  "command": "latexmk",
  "args": [
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "pdflatex",
  "command": "pdflatex",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "bibtex",
  "command": "bibtex",
  "args": [
   "%DOCFILE%"
  ],
  "env": {}
 },
 {
  "name": "rnw2tex",
  "command": "Rscript",
  "args": [
   "-e",
   "knitr::opts_knit$set(concordance = TRUE); knitr::knit('%DOCFILE_EXT%')"
  ],
  "env": {}
 },
 {
  "name": "jnw2tex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"tex\")"
  ],
  "env": {}
 },
 {
  "name": "jnw2texmintex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"texminted\")"
  ],
  "env": {}
 },
 {
  "name": "tectonic",
  "command": "tectonic",
  "args": [
   "--synctex",
   "--keep-logs",
   "%DOC%.tex"
  ],
  "env": {}
 }
] .
[17:16:35][Config] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto" .
[17:16:35][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[17:16:35][Server] Creating LaTeX Workshop http and websocket server.
[17:16:35][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":50927}
[17:16:35][Extension] Initializing LaTeX Workshop.
[17:16:35][Extension] Extension root: /Users/harryw/.vscode/extensions/james-yu.latex-workshop-9.4.4
[17:16:35][Extension] $PATH: /Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
[17:16:35][Extension] $SHELL: /bin/zsh
[17:16:35][Extension] $LANG: undefined
[17:16:35][Extension] $LC_ALL: undefined
[17:16:35][Extension] process.platform: darwin
[17:16:35][Extension] process.arch: arm64
[17:16:35][Extension] vscode.env.appName: Visual Studio Code
[17:16:35][Extension] vscode.env.remoteName: undefined
[17:16:35][Extension] vscode.env.uiKind: 1
[17:16:35][Extension] LaTeX Workshop initialized.
[17:16:35][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[17:16:35][] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[17:16:35][Manager] Current workspace folders: ["file://%WS1%"]
[17:16:35][Manager] Current workspaceRootDir: file://%WS1%
[17:16:35][Server] valdOrigin is http://127.0.0.1:50927
[17:16:35][Cacher][Path] Non-existent .fls for %WS1%/foo.tex .
[17:16:35][Linter] No root file found for ChkTeX.
[17:16:36][Structure] Error loading LaTeX during structuring: %WS1%/foo.tex .
[17:16:46][Manager] Current workspace folders: ["file://%WS1%"]
[17:16:46][Manager] Current workspaceRootDir: file://%WS1%
[17:16:46][Cacher][Path] Non-existent .fls for %WS1%/foo.tex .
[17:16:46][Linter] No root file found for ChkTeX.
[17:16:50][Intelli] citation
[17:16:50][Intelli] reference
[17:16:50][Intelli] environment
[17:16:50][Intelli] package
[17:16:50][Intelli] documentclass
[17:16:50][Intelli] input
[17:16:50][Intelli] subimport
[17:16:50][Intelli] import
[17:16:50][Intelli] includeonly
[17:16:50][Intelli] glossary
[17:16:50][Intelli] argument
[17:16:50][Structure] Error loading LaTeX during structuring: %WS1%/foo.tex .
```

The issue would persit even if I deleted the empty Python script file, but autocomplete would start to work after restarting VS Code.

**Comment by James-Yu** [comment] 2023-01-12 17:44
```
line.replace.toString()
'function replace() { [native code] }'
line.replaceAll.toString()
'function(e,t){return this?this.replace(new RegExp(e.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"g"),t):this}'
```

It seems that `ms-python` bound `String.replaceAll()` to something strange. I have no idea on their purpose, yet the issue will be fixed shortly.

**Closed** 2023-01-12 17:46 UTC

**Comment by jlelong** [comment] 2023-01-12 17:51
See microsoft/vscode-python#19761

**Comment by James-Yu** [comment] 2023-01-12 18:00
What a terrible design! Lucky we figured it out with help from @harrysw1729 @aperezlebel !
