### ISSUE TITLE
Unable to run any commands associated with this plugin

### ISSUE THREAD

**Issue by lgsmith** [James-Yu/LaTeX-Workshop#2183] opened 2020-06-28 21:28 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Even though my plugins dropdown claims that LaTeX-Workshop is installed, and even though the commands (like build latex project) appear in the crtl + P menu, when I run them I get an error popup saying the command cannot be found. There's also not a 'tex' tab on the left-hand extensions list. I'm a longtime user just trying to get this plugin set up on a new computer and I've not run into this before. Happy to provide any other information, but unsure of what else may be helpful. Based on the developer console it is pretty clear that the plugin's not getting loaded. The files it says it 'depends on' in that screenshot are present on my system.

I'm on Ubuntu 20.04 and am using KDE, if any of that matters.
### To Reproduce

1. Search for and install plugin in plugin store.
2. Note that plugin tab doesn't appear in usual place next to debugger.
3. Try to run build latex project in command palette. 
4. Get a command not found error (see attached screenshot).
![image](https://user-images.githubusercontent.com/4299489/85958342-dcc43080-b962-11ea-87b6-a33bb4c1e336.png)

### Expected behavior

I expected my project to build. It builds with the install I have on my desktop, just not the one I have on my laptop.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

I cannot perform this action. There is no tex icon, even though in the plugin menu the plugin is listed as installed.
![image](https://user-images.githubusercontent.com/4299489/85958373-1c8b1800-b963-11ea-97c2-c770036ecf64.png)

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

[Paste the log here]
```
![image](https://user-images.githubusercontent.com/4299489/85958466-ba7ee280-b963-11ea-85b7-cf4baf4b561a.png)

## Desktop [Required]
 - OS: Ubuntu 20.04
 - VS Code version: 1.46.1
 - Extension version: 8.10.0
 - TeX distribution version:
```
$ latex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
kpathsea version 6.3.1
Copyright 2019 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.01
```

Text from vscode 'help->about'
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-19T10:53:55.306Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-39-generic
```

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment] 2020-06-28 21:41
Duplicate of #2160. This is related to VSCodium. Please contact the development team of VSCodium.

**Closed by tamuratak** 2020-06-28 21:41 UTC

**Comment by tamuratak** [comment] 2020-06-29 03:20
Please post to #2160 if any progress.
