### ISSUE TITLE
inline math `\( \)` is not rendered correctly

### ISSUE THREAD

**Issue by redmouth** [James-Yu/LaTeX-Workshop#4314] opened 2024-07-09 05:04 UTC
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ *] The issue has not been reported in this repository.
- [* ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [* ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [ *] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: ubuntu22.04.4
- Visual Studio Code Version:  1.91.0
- LaTeX Workshop Version:  v10.1.0
- TeX Distribution Version:  TeX Live 2022/dev/Debian

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using Visual Studio Code whose version is 1.91.0

## The Issue*
> _Please briefly describe the issue you come across._
- Inline math using `\( \)` is not rendered as expected
- For example, \( E = mc^2 \) is not rendered in the preview window.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. open/create a .md file
2. input \( E = mc^2 \) 
3. open markdown preview

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- 
- 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by jlelong** [comment] 2024-07-09 08:05
I cannot reproduce the issue. Can you post a screenshot showing the problem?

**Comment by redmouth** [comment] 2024-07-09 08:32
![Screenshot from 2024-07-09 16-31-26](https://github.com/James-Yu/LaTeX-Workshop/assets/11191632/74f20a62-8414-4082-ad66-52006d3d18fd)

**Comment by jlelong** [comment] 2024-07-09 10:12
Still I confirm that I cannot reproduce the problem. Can you try with a file just containing the above Latex code?
Can you post the content of the **Developer Tools Console**? What about the extension logs?

**Comment by redmouth** [comment] 2024-07-09 11:54
The file containing only the Latex code still is not rendered as expected. There is no related logs in Developer Tools Console?

**Comment by jlelong** [comment] 2024-07-09 12:21
I am afraid I cannot help without any logs (Developer Tools Console and extension logs). So I am closing the issue.

**Closed by jlelong** 2024-07-09 12:21 UTC
Labels: need more info
