### ISSUE TITLE
How to disable some intellisense

### ISSUE THREAD

**Issue by innerlee** [James-Yu/LaTeX-Workshop#1979] opened 2020-03-06 06:50 UTC
I want to disable all the snippets starting with `@`. Kindly ask which option to set?

![image](https://user-images.githubusercontent.com/9464825/76059358-9c0e6900-5fb9-11ea-985e-b441096009e9.png)

**Comment by jlelong** [comment] 2020-03-06 15:11
Duplicate of #1974. It is impossible. 
The snippets are defined in https://github.com/James-Yu/LaTeX-Workshop/blob/master/snippets/latex.json

**Closed by jlelong** 2020-03-06 15:11 UTC
