### ISSUE TITLE
brace matching is not working in equation environment

### ISSUE THREAD

**Issue by starship863** [James-Yu/LaTeX-Workshop#405] opened 2018-02-06 03:59 UTC
### Description
The brace matching is working for the braces "{" and "}" in text, but it is not working for braces "{" and "}" in equation environment.

### How to reproduce

1. put cursor at a right brace "}" in the equation environment
2. the corresponding left brace "{" is not highlighted

### Expected behavior
Brace matching should also work in the equation environment.

### Additional Information

Vscode - Insiders V. 1.20.0-insider

**Comment by James-Yu** [comment] 2018-02-08 02:17
Duplicate of #292

**Closed by James-Yu** 2018-02-08 02:17 UTC
