### ISSUE TITLE
Delay when pressing enter

### ISSUE THREAD

**Issue by flxflx** [James-Yu/LaTeX-Workshop#903] opened 2018-10-18 14:34 UTC
I just installed version 5.13.0 and I am now getting a long delay (2s?) when pressing enter. Disabling latex-workshop.bind.enter.key does not help. Thanks!

**Comment by tecosaur** [comment] 2018-10-18 15:33
For solidarity, I've recently been getting this issue too. At least from 5.12. 

Another interesting quirk with this – I've found that despite the issues getting `enter` to create a new line — if you expand snippets that include a new line it's instant and works fine. However, pasting new lines also has a long delay so I'm not sure quite what to make of this.

**Comment by arjunguha** [comment] 2018-10-18 15:59
I am having the same issue. It seems to coincide with the release of VSCode 1.28.2, but that may be a coincidence.

**Comment by tecosaur** [comment] 2018-10-19 04:13
Another thing I've found: `Shift`+`Enter` seems to work for some reason...

**Comment by jlelong** [comment] 2018-10-19 07:29
Unfortunately, I cannot reproduce the problem on OS X.

**Comment by tecosaur** [comment] 2018-10-19 07:33
Am I correct in guessing you've tried a large file?

**Comment by jlelong** [comment] 2018-10-19 07:37
I have tried on a 56k tex file. Can you provide an example?

**Comment by tecosaur** [comment] 2018-10-19 07:41
That's much larger than the files I am having an issue with, since this seems to be a PC/mac difference could it be something to do with vs code itself?
If you can tell us how to try an earlier version of LaTeX-Workshop we could try that and see if there's still an issue.

**Comment by James-Yu** [comment] 2018-10-19 07:43
I just tried on two PC, one is a rotten potato, and no significant delay is observed. I am neither aware of what might be causing this.

**Comment by tecosaur** [comment] 2018-10-19 07:53
I'm there some way to do something like performance analysis since Vs code
uses electron?

**Comment by arjunguha** [comment] 2018-10-19 10:44
I tried this more systematically. I'm on macOS latest:

- There is no issue when LaTeX Workshop is the only extension loaded
- This problem only occurs when using LaTeX Workshop and [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright)
- However, the problem does not occur when spell checking a plain text file. (i.e., if I change the extension from .tex to .txt, the delay on enter disappears).

So, it appears to be some sort of bad interaction between extensions. Other folks who have this issue: are you also using Spell Right (or some other spell-checker)?

**Comment by tecosaur** [comment] 2018-10-19 11:44
Another tidbit, I used the performance profiley thingy and got this graph:
![image](https://user-images.githubusercontent.com/20903656/47215920-b8663180-d3d5-11e8-9ddf-8ca41f791f1a.png)
Every odd small hump (1st, 3rd, 5th, and 7th hump) correspands to me pressing a letter and enter and basically the same time, and the big bump is when all the enters are actually added.
![imageedit_3_7923626959](https://user-images.githubusercontent.com/20903656/47216378-59092100-d3d7-11e8-89a4-90b33127101e.gif)

**Comment by tecosaur** [comment] 2018-10-19 12:02
# Perormance Analysis Part 2
## When new lines are inserted
The following refers to this section:
![image](https://user-images.githubusercontent.com/20903656/47216835-dd0fd880-d3d8-11e8-8e92-beaf25cdf762.png)
I noticed that the actual adding of the new lines seems to happen at the end of the purple blip. This corresponded to this function call:
![image](https://user-images.githubusercontent.com/20903656/47216616-214ea900-d3d8-11e8-8008-b81f8ae87db0.png)
And the call tree is … deep. Quite deep
![image](https://user-images.githubusercontent.com/20903656/47216643-375c6980-d3d8-11e8-8710-9c09540ef854.png)
![image](https://user-images.githubusercontent.com/20903656/47216806-c49fbe00-d3d8-11e8-8ac5-b144ed785638.png)
## When enter pressed (and before new line inserted)
The following refers to this section:
![image](https://user-images.githubusercontent.com/20903656/47216890-1ea08380-d3d9-11e8-8f1b-98939ea8c7f8.png)
This is what the call tree looks like
![image](https://user-images.githubusercontent.com/20903656/47217005-7939df80-d3d9-11e8-82c6-42bafdc2b01e.png)
![image](https://user-images.githubusercontent.com/20903656/47217025-8c4caf80-d3d9-11e8-81fc-5e2a62b9acc4.png)

#### Sorry about the scroling, hopefuly something here might be helpful, let me know if you want more detail on any of the events

**Comment by James-Yu** [comment] 2018-10-19 12:30
Actually when Spell Right came out I tried it several times. In each time I was just bothered by the random delay you described. I have no idea what was causing that, and I highly suspect it was on the other side.

**Comment by tecosaur** [comment] 2018-10-19 12:47
@James-Yu have you got any comment about what I found (Performance Analysis Pt1&2) because that was with _Spell Right_ **Disabled**.

**Comment by James-Yu** [comment] 2018-10-19 13:57
Have you tried disabling all extensions except for this one?

**Comment by tecosaur** [comment] 2018-10-19 14:54
Have tried. Result:

I retract my earlier statement, this isn't purely because of this extension. My best guess is that there are multiple extension-interaction type things contributing to this. I still find it odd that since it doesn't seem to be purely LaTeX workshop, that other file types didn't suffer from the same issue.

**Comment by James-Yu** [comment] 2018-10-19 14:57
Unfortunately, until you or someone identified which extensions are fighting, I cannot proceed to debugging. A worse guess is that this might be an upstream vscode problem.

**Comment by tecosaur** [comment] 2018-10-19 15:10
### Some extensions which cause this issue
 - Spell Right
 - Brackets Pair Colouriser 2
 - Prettify Symbols Mode

That's the list from me so far

**Comment by bartosz-antosik** [comment] 2018-10-22 12:31
Hello everyone.

I would eagerly try to have a look but would like to have some reference file that someone can declare as the one which suffers the delay when pressing Enter here or there.

I have edited multitude of LaTeX documents (using LaTeX Workhop) and have not noticed the issue. Maybe they were not big enough.

**Comment by tecosaur** [comment] 2018-10-22 13:40
@bartosz-antosik try this:
[test.tex.zip](https://github.com/James-Yu/LaTeX-Workshop/files/2501532/test.zip)

**Comment by bartosz-antosik** [comment] 2018-10-23 16:40
@James-Yu Please help! I have been staring at this issue for quite few hours and all the observations seem to be true: Once Latex Workshop is used alone no blocking at all, same with Spell Right used alone!

Once however I remove in `onDidChangeTextDocument` event (which seems to be the only thing I do around enter click) nothing changes - the delay is still there. Strange observation that when I log start and stop of processing in `onDidChangeTextDocument` event, they both start after substantial delay after the enter is pressed.

It could suggest that "there is something wrong in they part" but I have seen strange things.

Could you please have some thought on this from your POV please?

**Comment by James-Yu** [comment] 2018-10-24 01:39
I'll look into it

**Comment by tamuratak** [comment] 2018-10-24 07:15
Profiler says that `RegExp.prototype.exec()` called from [_filter](https://github.com/bartosz-antosik/vscode-spellright/blob/master/lib/parsers/latex.js#L61) and [_parse](https://github.com/bartosz-antosik/vscode-spellright/blob/master/lib/parsers/latex.js#L130) in `vscode-spellright/blob/master/lib/parsers/latex.js` consumes the most of CPU time.

![2018-10-24 16 07 29](https://user-images.githubusercontent.com/10665499/47412629-31370600-d7a7-11e8-95fc-e6736a8c926e.png)

**Comment by bartosz-antosik** [comment] 2018-10-24 07:44
@tamuratak Yes, I am aware about this, but: 1/ this time is linearly proportional to the size of the document, 2/ it does happen in every type of document spelled (so not LaTeX documents only) 3/ In This cooperation (Latex Workshop + Spel Right) this delay after `ENTER` key does not happen at every press of `ENTER` 4/ When I disable whole processing in `onDidChangeTextDocument` the delay persists 5/ It amounts to 1.4 second not over 5. Technically it is parsing for InDocument commands & some general cleanup before spelling (e-mails, www addresses etc.)

**Comment by tamuratak** [comment] 2018-10-24 09:55
I think the following is the cause.

When pressing Enter key,  a command `latex-workshop.onEnterKey` is queued. Until Spell Right finishes its job, and it takes very long time, VSCode waits to invoke the command. Then, we see a delay. When pressing Shift+Enter, a command `latex-workshop.onEnterKey` is not queued. Then we don't see the delay. For example, if we delete `latex-workshop.onEnterKey` in `package.json`, we don't see the delay.

**Comment by tamuratak** [comment] 2018-10-24 11:50
No, it should not. Please try yourself.

**Comment by bartosz-antosik** [comment] 2018-10-24 12:07
@tamuratak I did and I still have the delay.

**Comment by tamuratak** [comment] 2018-10-24 12:17
1. Please uninstall all the other plugins except LaTeX-Workshop and Spell Right.
2. Paste the following to `keybindings.json`
```
    {
        "key": "enter",
        "command": "-latex-workshop.onEnterKey",
        "when": "editorTextFocus && !editorReadonly && !suggestWidgetVisible && !vim.active && editorLangId == 'latex'"
    },
    {
        "key": "enter",
        "command": "-latex-workshop.onEnterKey",
        "when": "editorTextFocus && vim.active && !editorReadonly && !suggestWidgetVisible && editorLangId == 'latex' && vim.mode == 'Insert'"
    }
```
3. See any delay?

**Comment by tamuratak** [comment] 2018-10-24 12:33
I cannot get your point. I want to know whether you still see any delay with only the two extensions.

**Comment by bartosz-antosik** [comment] 2018-10-25 07:53
@James-Yu I think you may close this thread.

**Closed** 2018-10-25 07:56 UTC

**Comment by tecosaur** [comment] 2018-10-25 12:14
@bartosz-antosik can I take that to mean you've found a fix (and implemented it)?

**Comment by bartosz-antosik** [comment] 2018-10-25 12:29
@tecosaur No. Fix is very complicated and will take time.

**Comment by tecosaur** [comment] 2018-10-30 08:30
@bartosz-antosik I'm sorry to hear that. Can you confirm that a fix is on the horizon for the extension (I really don't want to stop using your extension)?

**Comment by bartosz-antosik** [comment] 2018-10-30 09:16
@tecosaur Yes I am working on resolution.

**Comment by krupenja** [comment] 2019-03-26 16:49
@bartosz-antosik Is there an issue in SpellRight repo tracking this? Could not find one.

**Comment by felipecrp** [comment] 2019-04-01 11:50
> I think the following is the cause.
> 
> When pressing Enter key, a command `latex-workshop.onEnterKey` is queued. Until Spell Right finishes its job, and it takes very long time, VSCode waits to invoke the command. Then, we see a delay. When pressing Shift+Enter, a command `latex-workshop.onEnterKey` is not queued. Then we don't see the delay. For example, if we delete `latex-workshop.onEnterKey` in `package.json`, we don't see the delay.

Manually disabling these binds solved the problem.
