### ISSUE TITLE
 command 'latex-workshop.view' not found

### ISSUE THREAD

**Issue by xxxxpenny** [James-Yu/LaTeX-Workshop#1213] opened 2019-03-06 12:14 UTC
**Desktop (please complete the following information):**
 - OS: Mac OS
 - VS Code version: 1.31.1
 - Extension version: 6.1.0

When I view leatex pdf file, there is a problem that command 'latex-workshop.view' not found, why?

I have a setting.json.
```json
{
    "latex-workshop.latex.tools": [
        {
            "name": "latexmk",
            "command": "latexmk",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "-outdir=%OUTDIR%",
                "%DOC%"
            ],
            "env": {}
        },
        {
            "name": "pdflatex",
            "command": "pdflatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "%DOC%"
            ],
            "env": {}
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ],
            "env": {}
        }
    ]
}
```

**Comment by jlelong** [comment] 2019-03-06 13:56
I believe this is a duplicate of #1193.
Try to completely remove this extension `~/.vscode/extensions/james-yu.latex-workshop-6.1.0` and then reinstall it.

**Closed by jlelong** 2019-03-06 13:56 UTC

**Comment by t4kesh** [comment] 2019-03-11 11:54
same problem here, i don't think this issue was solved. I tried to reinstall, but only solved the problem by getting an older version.

**Comment by xxxxpenny** [comment] 2019-03-11 11:58
> same problem here, i don't think this issue was solved. I tried to reinstall, but only solved the problem by getting an older version.

emm, I solve the problem by the answer, but I restart vscode after reinstall it.

**Comment by tamuratak** [comment] 2019-03-14 08:30
@t4kesh, if you wanto to solve your problem, please open a new issue.

**Comment by xq114** [comment] 2020-01-15 14:27
> same problem here, i don't think this issue was solved. I tried to reinstall, but only solved the problem by getting an older version.

On my upgrading LaTeX-Workshop to version 8.6.0, I had run into the same problem as yours. I solved the issue by downgrading the extension to version 8.5.0 and upgrade again to version 8.6.0. Now I think that the issue has something to do with the upgrade system of vs code.
