### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by aloispichler** [James-Yu/LaTeX-Workshop#2685] opened 2021-05-15 10:19 UTC
VS Code has some useful keyboard shortcuts which behave the same way in many extension. It seems that the integrated pdf-previewer disables or breaks some of these shortcuts. These include

- `ctrl+1`, `ctrl+2`, etc. to select the tab group,
- `ctrl+tab` to navigate between tabs, or
- `alt-LeftArrow` (go back) and `alt-RigtArrow` (go forward); these are typically overly useful in code navigation and editing LaTeX documents, but focusing the pdf-viewer in between breaks its functionalities.

Perhaps you would like to have a look at that issue.

Thank you for maintaining LaTeX-Workshop, I use your extension daily.

 - OS: [e.g. Windows 10]
 - VS Code version: [1.56]
 - Extension version: [e.g. 8.18]
 - TeX distribution version: [TeX Live 2021]

**Comment by tamuratak** [comment] 2021-05-15 10:47
Duplicate of #2334

**Closed by tamuratak** 2021-05-15 10:47 UTC

**Comment by tamuratak** [comment] 2021-05-16 22:44
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) next time.
