### ISSUE TITLE
synctex inverse search shouldn't open new view

### ISSUE THREAD

**Issue by jonas-frey** [James-Yu/LaTeX-Workshop#2784] opened 2021-06-29 21:34 UTC
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you can not see the requested feature. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before requesting a feature.

You visited the wiki?: Yes

## Is your requested feature  related to a problem? Please describe. [Required]

I like to have the compiled pdf on the right of my screen (either in internal vscode viewer or in okular), and the editor view on the left, split horizontally where I have say the tex file on the top, and a file with notes on the bottom. Now when I'm editing the notes, and then try to inverse search from the pdf
(either with shift+mouse from okular or with ctrl+mouse from the internal viewer), vscode will often reopen the tex file in the bottom half of my split view
instead of jumping to the correct position in the top half.

## To Reproduce  [Required]

See problem description.

## Describe the solution you'd like  [Required]

I think it would be preferable to always activate a file that's already open instead of opening a new view when inverse searching.

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Kubuntu 20.04
 - VS Code version: 1.57.1
 - Extension version: 8.19.2
 - TeX distribution version: TeX Live 2019/Debian

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment] 2021-06-29 22:40
Duplicate of  #2537. See https://github.com/James-Yu/LaTeX-Workshop/issues/2537#issuecomment-784134122

> I have found that we cannot implement the requested feature due to the restriction of VS Code API.

**Closed by tamuratak** 2021-06-29 22:40 UTC
Labels: feature-request
