### ISSUE TITLE
new feature: automatic completion of the includegraphics command

### ISSUE THREAD

**Issue by jerabaul29** [James-Yu/LaTeX-Workshop#774] opened 2018-09-03 20:49 UTC
I am using a path matcher in Atom that allows me to easily fill in the filenames for figures, as it automatically kicks in as soon as I start typing ```./``` (which I therefore use to prefix the name of my figures).

Maybe a similar feature would be helpful here? Would it possible to make it even better - start autocompletion of only relevant figure paths (i.e. ```.pdf```, ```.eps```, ```.png```, ```.jpg```, and maybe some others) as soon as an ```\includegraphics{}``` is encountered? It is important to allow directories even if they do not have the right extension, as usually people will put their figures in for example a ```Figures/``` folder.

**Comment by jlelong** [comment] 2018-09-04 04:05
Duplicate of #563.

**Closed by jlelong** 2018-09-04 04:05 UTC
