### ISSUE TITLE
BibTeX doesn't work with custom `outDir` (like `%TMPDIR%`)

### ISSUE THREAD

**Issue by maltejur** [James-Yu/LaTeX-Workshop#3023] opened 2021-12-26 13:43 UTC
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

### To Reproduce
With the two files

`main.tex`
```tex
\documentclass{report}

\begin{document}
\cite{a-reference}

\bibliographystyle{plain}
\bibliography{bibliography}
\end{document}
```
`bibliography.bib`
```bib
@misc{a-reference,
  title  = {A Reference},
  author = {Leandro Facchinetti},
  year   = {2019}
}
```

Make sure first the setting `latex-workshop.latex.outDir` is set to `%DIR%`.

Clicking on `Build LaTex project` in the LaTeX tab should work without any errors.

Then change `latex-workshop.latex.outDir` to `%TMPDIR%`.

Click on `Build LaTex project` again and get an error.

### Expected behavior

I would expect everything would compile the same with `%TMPDIR%` as with `%DIR%`.

### LaTeX Workshop Output [Required]

```
[14:31:45] Initializing LaTeX Workshop.
[14:31:45] Extension root: /home/maltejur/.vscode/extensions/james-yu.latex-workshop-8.22.0
[14:31:45] $PATH: /home/maltejur/repos/kinopub_downloader/bin:/home/maltejur/repos/winapps/bin:/home/maltejur/repos/scripts:/home/maltejur/repos/pandoc-watch:/home/maltejur/repos/kinocli/dist:/home/maltejur/scripts:/home/maltejur/Programme/kinocli/dist:/home/maltejur/Programme/audio-share-discord-linux/bin:/home/maltejur/Android/Sdk/platform-tools:/home/maltejur/Android/Sdk/cmdline-tools/latest/bin:/home/maltejur/.yarn/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[14:31:45] $SHELL: /bin/fish
[14:31:45] vscode.env.appName: Visual Studio Code
[14:31:45] vscode.env.remoteName: undefined
[14:31:45] vscode.env.uiKind: 1
[14:31:45] latex-workshop.bind.enter.key: true
[14:31:45] latex-workshop.docker.enabled: false
[14:31:45] latex-workshop.docker.image.latex: ""
[14:31:45] latex-workshop.intellisense.package.enabled: true
[14:31:45] latex-workshop.intellisense.update.aggressive.enabled: false
[14:31:45] latex-workshop.intellisense.update.delay: 1000
[14:31:45] latex-workshop.latex.autoBuild.run: "onSave"
[14:31:45] latex-workshop.latex.outDir: "%TMPDIR%"
[14:31:45] latex-workshop.latex.recipes: [
 {
  "name": "latexmk 🔃",
  "tools": [
   "latexmk"
  ]
 },
 {
  "name": "latexmk (latexmkrc)",
  "tools": [
   "latexmk_rconly"
  ]
 },
 {
  "name": "latexmk (lualatex)",
  "tools": [
   "lualatexmk"
  ]
 },
 {
  "name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
  "tools": [
   "pdflatex",
   "bibtex",
   "pdflatex",
   "pdflatex"
  ]
 },
 {
  "name": "Compile Rnw files",
  "tools": [
   "rnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Jnw files",
  "tools": [
   "jnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "tectonic",
  "tools": [
   "tectonic"
  ]
 }
]
[14:31:45] latex-workshop.latex.tools: [
 {
  "name": "latexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-pdf",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "lualatexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-lualatex",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "latexmk_rconly",
  "command": "latexmk",
  "args": [
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "pdflatex",
  "command": "pdflatex",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "bibtex",
  "command": "bibtex",
  "args": [
   "%DOCFILE%"
  ],
  "env": {}
 },
 {
  "name": "rnw2tex",
  "command": "Rscript",
  "args": [
   "-e",
   "knitr::opts_knit$set(concordance = TRUE); knitr::knit('%DOCFILE_EXT%')"
  ],
  "env": {}
 },
 {
  "name": "jnw2tex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"tex\")"
  ],
  "env": {}
 },
 {
  "name": "jnw2texmintex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"texminted\")"
  ],
  "env": {}
 },
 {
  "name": "tectonic",
  "command": "tectonic",
  "args": [
   "--synctex",
   "--keep-logs",
   "%DOC%.tex"
  ],
  "env": {}
 }
]
[14:31:45] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto"
[14:31:45] Creating a new file watcher.
[14:31:45] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[14:31:45] Creating PDF file watcher.
[14:31:45] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[14:31:45] Creating Bib file watcher.
[14:31:45] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[14:31:45] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[14:31:45] [Server] Creating LaTeX Workshop http and websocket server.
[14:31:45] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[14:31:45] LaTeX Workshop initialized.
[14:31:45] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[14:31:45] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[14:31:45] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[14:31:45] Current workspace folders: ["file:///home/maltejur/repos/test"]
[14:31:45] Current workspaceRootDir: file:///home/maltejur/repos/test
[14:31:45] Found root file from active editor: /home/maltejur/repos/test/main.tex
[14:31:45] Root file changed: from undefined to /home/maltejur/repos/test/main.tex
[14:31:45] Start to find all dependencies.
[14:31:45] Root file languageId: latex
[14:31:45] [Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":45655}
[14:31:45] Reset file watcher.
[14:31:45] Parsing a file and its subfiles: /home/maltejur/repos/test/main.tex
[14:31:45] Found .bib file: /home/maltejur/repos/test/bibliography.bib
[14:31:45] Added to bib file watcher: /home/maltejur/repos/test/bibliography.bib
[14:31:45] Parsing .bib entries from /home/maltejur/repos/test/bibliography.bib
[14:31:45] Added to file watcher: /home/maltejur/repos/test/main.tex
[14:31:45] Snippet data loaded.
[14:31:46] Parsed 1 bib entries from /home/maltejur/repos/test/bibliography.bib.
[14:31:46] Parse fls file.
[14:31:46] Cannot find fls file: /tmp/tmp-19687-1qsRKrClES68/main.fls
[14:31:46] Checking for duplicate labels: /home/maltejur/repos/test/main.tex.
[14:31:48] Manager.fileWatcher.getWatched: {"/home/maltejur/repos/test":["main.tex"]}
[14:31:48] Manager.filesWatched: ["/home/maltejur/repos/test/main.tex"]
[14:31:48] BibWatcher.bibWatcher.getWatched: {"/home/maltejur/repos/test":["bibliography.bib"]}
[14:31:48] BibWatcher.bibsWatched: ["/home/maltejur/repos/test/bibliography.bib"]
[14:31:48] PdfWatcher.pdfWatcher.getWatched: {}
[14:31:48] PdfWatcher.pdfsWatched: []
[14:31:51] Start formatting with latexindent.
[14:31:51] Checking latexindent: which latexindent
[14:31:51] Checking latexindent is ok: /usr/bin/latexindent

[14:31:51] Formatting with command latexindent -c,/home/maltejur/repos/test/,/home/maltejur/repos/test/__latexindent_temp.tex,-y=defaultIndent: '  '
[14:31:51] Formatted /home/maltejur/repos/test/main.tex
[14:31:51] onDidSaveTextDocument triggered: file:///home/maltejur/repos/test/main.tex
[14:31:51] Auto build started on saving file: /home/maltejur/repos/test/main.tex
[14:31:51] Auto build started detecting the change of a file: /home/maltejur/repos/test/main.tex
[14:31:51] BUILD command invoked.
[14:31:51] The document of the active editor: file:///home/maltejur/repos/test/main.tex
[14:31:51] The languageId of the document: latex
[14:31:51] Building root file: /home/maltejur/repos/test/main.tex
[14:31:51] Build root file /home/maltejur/repos/test/main.tex
[14:31:51] outDir: /tmp/tmp-19687-1qsRKrClES68
[14:31:51] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/tmp/tmp-19687-1qsRKrClES68,/home/maltejur/repos/test/main
[14:31:51] Recipe step env: {}
[14:31:51] cwd: /home/maltejur/repos/test
[14:31:51] LaTeX build process spawned. PID: 19845.
[14:31:51] LaTeX log parsed with 2 messages.
[14:31:51] Recipe returns with error: 12/null. PID: 19845. message: Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 29 September 2020, version: 4.70b.
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="/tmp/tmp-19687-1qsRKrClES68"  "/home/maltejur/repos/test/main.tex"'
------------
Latexmk: Non-existent bbl file '/tmp/tmp-19687-1qsRKrClES68/main.bbl in line'
 No file main.bbl.
Latexmk: Log file says output to '/tmp/tmp-19687-1qsRKrClES68/main.pdf'
Latexmk: List of undefined refs and citations:
  Citation `a-reference' on page 1 undefined on input line 4
Latexmk: Found bibliography file(s) [bibliography.bib]
Rule 'bibtex /tmp/tmp-19687-1qsRKrClES68/main': File changes, etc:
   Changed files, or newly in use since previous run(s):
      '/tmp/tmp-19687-1qsRKrClES68/main.aux'
------------
Run number 1 of rule 'bibtex /tmp/tmp-19687-1qsRKrClES68/main'
------------
------------
Running 'bibtex  "/tmp/tmp-19687-1qsRKrClES68/main.aux"'
------------

bibtex: Not writing to /tmp/tmp-19687-1qsRKrClES68/main.blg (openout_any = p).
Latexmk: Summary of warnings from last run of *latex:
  Latex failed to resolve 1 citation(s)
Collected error summary (may duplicate other messages):
  bibtex /tmp/tmp-19687-1qsRKrClES68/main: Could not open bibtex log file for '/tmp/tmp-19687-1qsRKrClES68/main'
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
.
[14:31:51] The environment variable $PATH: /home/maltejur/repos/kinopub_downloader/bin:/home/maltejur/repos/winapps/bin:/home/maltejur/repos/scripts:/home/maltejur/repos/pandoc-watch:/home/maltejur/repos/kinocli/dist:/home/maltejur/scripts:/home/maltejur/Programme/kinocli/dist:/home/maltejur/Programme/audio-share-discord-linux/bin:/home/maltejur/Android/Sdk/platform-tools:/home/maltejur/Android/Sdk/cmdline-tools/latest/bin:/home/maltejur/.yarn/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[14:31:51] The environment variable $Path: undefined
[14:31:51] The environment variable $SHELL: /bin/fish
[14:31:51] Cleaning auxiliary files and retrying build after toolchain error.
[14:31:51] Clean glob matched files: {"globs":["*.aux","*.bbl","*.blg","*.idx","*.ind","*.lof","*.lot","*.out","*.toc","*.acn","*.acr","*.alg","*.glg","*.glo","*.gls","*.fls","*.log","*.fdb_latexmk","*.snm","*.synctex(busy)","*.synctex.gz(busy)","*.nav","*.vrb"],"outdir":"/tmp/tmp-19687-1qsRKrClES68"}
[14:31:51] Cleaning file: /tmp/tmp-19687-1qsRKrClES68/main.aux
[14:31:51] Cleaning file: /tmp/tmp-19687-1qsRKrClES68/main.fls
[14:31:51] Cleaning file: /tmp/tmp-19687-1qsRKrClES68/main.log
[14:31:51] Cleaning file: /tmp/tmp-19687-1qsRKrClES68/main.fdb_latexmk
[14:31:51] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/tmp/tmp-19687-1qsRKrClES68,/home/maltejur/repos/test/main
[14:31:51] Recipe step env: {}
[14:31:51] cwd: /home/maltejur/repos/test
[14:31:51] LaTeX build process spawned. PID: 19850.
[14:31:51] File watcher - file changed: /home/maltejur/repos/test/main.tex
[14:31:51] Parsing a file and its subfiles: /home/maltejur/repos/test/main.tex
[14:31:51] Found .bib file: /home/maltejur/repos/test/bibliography.bib
[14:31:51] Checking for duplicate labels: /home/maltejur/repos/test/main.tex.
[14:31:51] LaTeX log parsed with 2 messages.
[14:31:51] Recipe returns with error: 12/null. PID: 19850. message: Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 29 September 2020, version: 4.70b.
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="/tmp/tmp-19687-1qsRKrClES68"  "/home/maltejur/repos/test/main.tex"'
------------
Latexmk: Non-existent bbl file '/tmp/tmp-19687-1qsRKrClES68/main.bbl in line'
 No file main.bbl.
Latexmk: Log file says output to '/tmp/tmp-19687-1qsRKrClES68/main.pdf'
Latexmk: List of undefined refs and citations:
  Citation `a-reference' on page 1 undefined on input line 4
Latexmk: Found bibliography file(s) [bibliography.bib]
Rule 'bibtex /tmp/tmp-19687-1qsRKrClES68/main': File changes, etc:
   Changed files, or newly in use since previous run(s):
      '/tmp/tmp-19687-1qsRKrClES68/main.aux'
------------
Run number 1 of rule 'bibtex /tmp/tmp-19687-1qsRKrClES68/main'
------------
------------
Running 'bibtex  "/tmp/tmp-19687-1qsRKrClES68/main.aux"'
------------

bibtex: Not writing to /tmp/tmp-19687-1qsRKrClES68/main.blg (openout_any = p).
Latexmk: Summary of warnings from last run of *latex:
  Latex failed to resolve 1 citation(s)
Collected error summary (may duplicate other messages):
  bibtex /tmp/tmp-19687-1qsRKrClES68/main: Could not open bibtex log file for '/tmp/tmp-19687-1qsRKrClES68/main'
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
.
[14:31:51] The environment variable $PATH: /home/maltejur/repos/kinopub_downloader/bin:/home/maltejur/repos/winapps/bin:/home/maltejur/repos/scripts:/home/maltejur/repos/pandoc-watch:/home/maltejur/repos/kinocli/dist:/home/maltejur/scripts:/home/maltejur/Programme/kinocli/dist:/home/maltejur/Programme/audio-share-discord-linux/bin:/home/maltejur/Android/Sdk/platform-tools:/home/maltejur/Android/Sdk/cmdline-tools/latest/bin:/home/maltejur/.yarn/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[14:31:51] The environment variable $Path: undefined
[14:31:51] The environment variable $SHELL: /bin/fish
[14:31:55] LOG command invoked: default
[14:32:00] Current workspace folders: ["file:///home/maltejur/repos/test"]
[14:32:00] Current workspaceRootDir: file:///home/maltejur/repos/test
[14:32:00] Found root file from active editor: /home/maltejur/repos/test/main.tex
[14:32:00] Keep using the same root file: /home/maltejur/repos/test/main.tex
[14:32:02] Manager.fileWatcher.getWatched: {"/home/maltejur/repos/test":["main.tex"]}
[14:32:02] Manager.filesWatched: ["/home/maltejur/repos/test/main.tex"]
[14:32:02] BibWatcher.bibWatcher.getWatched: {"/home/maltejur/repos/test":["bibliography.bib"]}
[14:32:02] BibWatcher.bibsWatched: ["/home/maltejur/repos/test/bibliography.bib"]
[14:32:02] PdfWatcher.pdfWatcher.getWatched: {}
[14:32:02] PdfWatcher.pdfsWatched: []
[14:32:02] Current workspace folders: ["file:///home/maltejur/repos/test"]
[14:32:02] Current workspaceRootDir: file:///home/maltejur/repos/test
[14:32:02] Found root file from active editor: /home/maltejur/repos/test/main.tex
[14:32:02] Keep using the same root file: /home/maltejur/repos/test/main.tex
[14:32:04] Manager.fileWatcher.getWatched: {"/home/maltejur/repos/test":["main.tex"]}
[14:32:04] Manager.filesWatched: ["/home/maltejur/repos/test/main.tex"]
[14:32:04] BibWatcher.bibWatcher.getWatched: {"/home/maltejur/repos/test":["bibliography.bib"]}
[14:32:04] BibWatcher.bibsWatched: ["/home/maltejur/repos/test/bibliography.bib"]
[14:32:04] PdfWatcher.pdfWatcher.getWatched: {}
[14:32:04] PdfWatcher.pdfsWatched: []
```

### Developer Tools Console [Required]

Nothing related to LaTeX Workshop

## Desktop [Required]

 - OS: Arch Linux
 - VS Code version: 1.63.2
 - Extension version: 8.22.0
 - TeX distribution version: TeX Live 2021.58710

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

Possibly the same as #1137

**Comment by jlelong** [comment] 2021-12-27 10:23
> `bibtex: Not writing to /tmp/tmp-19687-1qsRKrClES68/main.blg (openout_any = p).`

Duplicate of #2303.

**Closed by jlelong** 2021-12-27 10:23 UTC
Labels: external

**Comment by jlelong** [comment] 2021-12-29 07:04
I did a bit more testing and it turned out that I cannot reproduce the issue with `latexmk-4.76` and `texlive-2021`. The author of `latexmk` has worked a lot to improve the handling of `-outdir` since #2303.  Could you try updating `latexmk`?

**Comment by okarin001** [comment] 2022-01-09 16:36
I have this exact same issue. and the same version installed as yours
>  `latexmk-4.76` and `texlive-2021`
Still when I set an output directory, in my case it was %DIR%/build (I edited my BibTeX,latexmk recipes with -outdir="%OUTDIR%/%DOCFILE%" accordingly but It still couldn't compile. and gave this exact error.

**Comment by jlelong** [comment] 2022-01-09 19:20
@okarin001 This issue is not related to the extension but to the use of `-outdir` with `bibtex` in `latexmk`. There is nothing we can do on our side. 

Read carefully the comments in #2303 and https://tex.stackexchange.com/a/564691

Please post the logs of the extension next time. Otherwise we cannot help.

**Comment by maltejur** [comment] 2022-01-09 19:30
> I did a bit more testing and it turned out that I cannot reproduce the issue with latexmk-4.76 and texlive-2021. The author of latexmk has worked a lot to improve the handling of -outdir since #2303. Could you try updating latexmk?

I somehow didn't see your message originaly, but after updating to `latexmk-4.76` I can confirm that the issue is fixed.
