### ISSUE TITLE
Keyboard shortcuts ignored in PDF tab

### ISSUE THREAD

**Issue by office-chair** [James-Yu/LaTeX-Workshop#2435] opened 2020-12-14 01:45 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

When I'm on the PDF tab, I cannot use keyboard shortcuts like ctrl+w or ctrl+shift+t or ctrl+shift+p or ctrl+tab.

### To Reproduce

1. Open a PDF file
2. Try using a keyboard shortcut

### Expected behavior

Same thing happens as in any other regular tab.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[20:22:58] Initializing LaTeX Workshop.
[20:22:58] Extension root: o:\bin\vscode_win32_x64_1_52_0\data\extensions\james-yu.latex-workshop-8.15.0
[20:22:58] Creating PDF file watcher.
[20:22:58] Creating LaTeX Workshop http and websocket server.
[20:22:58] LaTeX Workshop initialized.
[20:22:58] Current workspace folders: ["file:///o:/documents/<path>"]
[20:22:58] Current workspaceRootDir: o:\documents\<path>
[20:22:58] Server created on 127.0.0.1:6167
[20:22:58] Snippet data loaded.
[20:22:58] LaTeX Workshop version: 8.15.0
[20:22:58] Restoring the PDF viewer at the column 1 from the state: {"type":"state","state":{"path":"o:\\documents\\<path>\\spec.pdf","scale":"auto","scrollMode":0,"spreadMode":0,"scrollTop":5066,"scrollLeft":0,"trim":0}}
[20:22:59] Preview PDF file: o:\documents\<path>\spec.pdf
[20:23:00] Handle data type: open
[20:23:00] Handle data type: request_params
[20:23:00] Sending the settings of the PDF viewer for initialization: {"type":"params","scale":"auto","trim":0,"scrollMode":0,"spreadMode":0,"hand":false,"invertMode":{"enabled":true,"brightness":1,"grayscale":0.6,"hueRotate":180,"invert":0.88,"sepia":0},"bgColor":"#ffffff","keybindings":{"synctex":"ctrl-click"}}
[20:23:00] Handle data type: loaded
[20:35:53] Added to PDF file watcher: o:\documents\<path>\spec.pdf
[20:35:53] PDF command invoked.
[20:35:53] Serving PDF file at http://localhost:6167/viewer.html?file=pdf..byUzQSU1Q2RvY3VtZW50cyU1Q2ZvcmRoYW0lNUMyMDIwMDkwMV9jaXNjXzU4MDBfbWwlNUMyMDIwMTIxNF9wcm9qJTVDc3BlYy5wZGY
[20:35:53] The encoded path is o:\documents\<path>\spec.pdf
[20:35:53] Open PDF tab for o:\documents\<path>\spec.pdf
[20:35:54] Preview PDF file: o:\documents\<path>\spec.pdf
[20:35:54] Handle data type: open
[20:35:54] Handle data type: request_params
[20:35:54] Sending the settings of the PDF viewer for initialization: {"type":"params","scale":"auto","trim":0,"scrollMode":0,"spreadMode":0,"hand":false,"invertMode":{"enabled":true,"brightness":1,"grayscale":0.6,"hueRotate":180,"invert":0.88,"sepia":0},"bgColor":"#ffffff","keybindings":{"synctex":"ctrl-click"}}
[20:35:54] Handle data type: loaded
[20:39:51] VIEW command invoked.
[20:39:51] Active document is not a TeX file.
[20:40:01] LOG command invoked: compiler
[20:40:02] LOG command invoked: default
```

### Developer Tools Console [Required]

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.
webviewElement.ts:90 [Embedded Page] webviewerloaded: SecurityError: Blocked a frame with origin "http://localhost:6167" from accessing a cross-origin frame.
webviewElement.ts:90 [Embedded Page] PDF 9e08f4a946974f4c8ddfccf300fe66f3 [1.5 Microsoft® Word 2013 / Microsoft® Word 2013] (PDF.js: 2.5.207)
webviewElement.ts:90 [Embedded Page] Uncaught TypeError: Cannot set property 'type' of undefined
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/940b5f4bb5fa47866a54529ed759d95d09ee80be/node_modules/windows-process-tree/lib/index.js.map: Unknown error
```

## Desktop [Required]
 - OS: Windows 10 1809
 - VS Code version: 1.52.0
 - Extension version: 8.15.0
 - TeX distribution version: TeX Live 2020

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment] 2020-12-14 03:04
Duplicate of #2334.

**Closed by tamuratak** 2020-12-14 03:04 UTC
Labels: duplicate

**Comment by office-chair** [comment] 2020-12-14 04:59
Whoops, my bad, somehow I only came across #1406
