### ISSUE TITLE
Single page PDF view

### ISSUE THREAD

**Issue by dpo** [James-Yu/LaTeX-Workshop#2482] opened 2021-01-16 01:21 UTC
**Is your feature request related to a problem? Please describe.**

Not really a problem, but when writing Beamer presentations, the "continuous page view" in the PDF view isn't really appropriate.

**Describe the solution you'd like**

A single-page view that would allow the user to display a single page at a time in the viewer tab and move forward or backward one entire page at a time would be great when authoring presentations.

**Describe alternatives you've considered**

Choosing "fit to page width" and resizing the VSCode window so a single slide appears in the tab, and moving foward and backward with the "previous/next page" buttons works, but resizing the VSCode window in this way is a bit awkward.

**Additional context**

I suggested this feature back when you were maintaining the Atom package: https://github.com/ashthespy/Atom-LaTeX/issues/165

**Comment by tamuratak** [comment] 2021-01-16 01:27
Duplicate of  #1789

**Closed by tamuratak** 2021-01-16 01:27 UTC
Labels: feature-request
