### ISSUE TITLE
The "Documentation of a command" feature is not working. The tooltip just displays the name of the command and nothing else.

### ISSUE THREAD

**Issue by devonupton** [James-Yu/LaTeX-Workshop#2630] opened 2021-04-20 15:02 UTC
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: **Yes**

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: **Yes**, 

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: **Yes**, but compilation is fine anyway.

## Describe the bug [Required]

When hovering over a command, the documentation does not display in the tooltip. Instead, just the name of the command appears. However, if I hover over a package, the tooltip is correctly populated and the "View documentation" link works perfectly, so this only affects commands.

See below for a gif demonstrating the issue.

### To Reproduce

1. Firstly, I tried to find a convenient way to run VS Code in safe mode, but alas, I gave up and just disabled all my extensions except this one and temporarily deleted my vscode settings.json file in %appdata%. (Also, I tested this with the default light theme as well and the bug persists).
2. Create a new minimal tex file in an otherwise empty workspace as shown in the gif below. Any compilable code with a command invocation should sufficiently demonstrate the issue.
3. Hover over a command.

### Expected behavior

I expect a tooltip, similar to the one shown [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#documentation-of-a-command), to appear that displays the command's signatures, along with a link to the PDF documentation.

### LaTeX Workshop Output [Required]

```
[08:39:06] Initializing LaTeX Workshop.
[08:39:06] Extension root: c:\Users\[redacted]\.vscode\extensions\james-yu.latex-workshop-8.16.1
[08:39:06] $PATH: [redacted];C:\Program Files (x86)\texlive\2021\bin\win32;[redacted];C:\Users\[redacted]\AppData\Local\Programs\Microsoft VS Code\bin;[redacted];
[08:39:06] $SHELL: undefined
[08:39:06] Creating PDF file watcher.
[08:39:06] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[08:39:06] Creating LaTeX Workshop http and websocket server.
[08:39:06] LaTeX Workshop initialized.
[08:39:06] Trigger characters for intellisense of LaTeX documents: ["\\","{",",","(","["]
[08:39:06] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[]}
[08:39:06] Current workspace folders: ["file:///c:/Users/[redacted]/Desktop/VS Code Bug"]
[08:39:06] Current workspaceRootDir: c:\Users\[redacted]\Desktop\VS Code Bug
[08:39:06] Found root file from active editor: c:\Users\[redacted]\Desktop\VS Code Bug\minimal.tex
[08:39:06] Root file changed: from undefined to c:\Users\[redacted]\Desktop\VS Code Bug\minimal.tex
[08:39:06] Start to find all dependencies.
[08:39:06] Root file languageId: latex
[08:39:06] Creating a new file watcher for c:\Users\[redacted]\Desktop\VS Code Bug\minimal.tex
[08:39:06] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[08:39:06] Creating Bib file watcher.
[08:39:06] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[08:39:06] Parsing a file and its subfiles: c:\Users\[redacted]\Desktop\VS Code Bug\minimal.tex
[08:39:06] Parse fls file.
[08:39:06] Cannot find fls file: c:\Users\[redacted]\Desktop\VS Code Bug\minimal.fls
[08:39:06] Server created on 127.0.0.1:53430
[08:39:06] Added to file watcher: c:\Users\[redacted]\Desktop\VS Code Bug\minimal.tex
[08:39:06] Snippet data loaded.
[08:39:06] LaTeX Workshop version: 8.16.1
[08:39:06] Checking for duplicate labels: c:\Users\[redacted]\Desktop\VS Code Bug\minimal.tex.
[08:39:17] LOG command invoked: default
```

### Developer Tools Console [Required]

**No output**

## Screenshots

![tooltip_issue](https://user-images.githubusercontent.com/17400426/115417448-db941680-a1b5-11eb-887a-59129d5164f5.gif)

## Desktop [Required]

 - OS: Windows **10**
 - VS Code version: **1.55.2**
 - Extension version: **8.16.1**
 - TeX distribution version: **TeX Live 2021**

### Are you using VSCodium?

**No**

### Are you using LaTeX Workshop with VS Code Remote?

**No**

### Additional context

**N/A**

**Comment by jlelong** [comment] 2021-04-20 15:12
Duplicate of #2617

**Closed by jlelong** 2021-04-20 15:12 UTC
