### ISSUE TITLE
couldn't read files in iCloud folder 

### ISSUE THREAD

**Issue by TiansuYu** [James-Yu/LaTeX-Workshop#1946] opened 2020-02-13 13:03 UTC
I have encountered a bug while using latex workshop on vs code. That is it cannot compile tex files under the iCloud folder, given its path having symbols such as: 

> com~apple~CloudDocs

But this has no issue if I direct compile it using terminal command xelatex. Thus I have to conclude this must be some built-in ignorance of this potential issue. 

This is my machine version: macOS Mojave Version 10.14.6, MacBook Pro (13-in, 2017). 

Here is the log I got from the error report on latex workshop: 

> This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `"/Users/tiansuyu/Library/Mobile Documents/com"'.
<to be read again> 
                   \protect 
<*> "/Users/tiansuyu/Library/Mobile Documents/com~
                                                  apple~CloudDocs/Work/Proje...
(Press Enter to retry, or Control-D to exit)
Please type another input file name
! Emergency stop.
<to be read again> 
                   \protect 
<*> "/Users/tiansuyu/Library/Mobile Documents/com~
                                                  apple~CloudDocs/Work/Proje...
No pages of output.
Transcript written on texput.log.

And I have to added in the tex file the first line with 

> % !TEX program = xelatex

in order to force xelatex to compile.

**Comment by jlelong** [comment] 2020-02-13 13:05
Duplicate of #1773

**Closed by jlelong** 2020-02-13 13:05 UTC

**Comment by TiansuYu** [comment] 2020-02-13 13:07
I have searched for iCloud related issue and found none, thus opened this. But thanks for pointing out the duplication.
