### ISSUE TITLE
Unable to return control back to VSCode from the PDF viewer with the keyboard

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [James-Yu/LaTeX-Workshop#1832] opened 2019-11-25 20:02 UTC
### Description
When I switch focus to the PDF viewer (from the preview), I'm unable to invoke any VSCode commands (e.g. open the command palette).

![Screen Shot 2019-11-25 at 2 28 28 PM](https://user-images.githubusercontent.com/1993919/69571344-dfefdc00-0f8f-11ea-83b2-917f05d07a16.png)

Issue Type: <b>Bug</b>

Extension version: 8.4.1
VS Code version: Code - Insiders 1.41.0-insider (abbf52b1378e2976803f81b1317fe3a5e6e39c23, 2019-11-25T10:09:34.712Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|-psn_0_4076515|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jlelong** [comment] 2019-11-25 20:40
Duplicate of #1406

**Closed by jlelong** 2019-11-25 20:40 UTC
