### ISSUE TITLE
Keyboard navigation in focused internal pdf viewer not working

### ISSUE THREAD

**Issue by coxackie** [James-Yu/LaTeX-Workshop#1814] opened 2019-11-16 08:18 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

When editing a tex file and using the internal pdf viewer, clicking with the mouse on the pdf and pressing Page Up / Page Down will scroll the text in the actual tex file, and not the pdf file.

### To Reproduce

1. Start editing a file with the internal pdf viewer on.
2. Click on the internal pdf viewer
3. Press Page Up / Page Down

### Expected behavior

When focus is on pdf viewer, pressing Page Up / Page Down should scroll the pdf file.

## Desktop [Required]
 - OS: Linux (Arch)
 - VS Code version: 1.40.1
 - Extension version: 8.4.1

(Was also happening with VS Code version 1.40.0, extension version 8.3.x)

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment] 2019-11-16 08:30
duplicate of #1481

**Closed by tamuratak** 2019-11-16 08:30 UTC
