### ISSUE TITLE
LaTeX document gets built twice when embedded Asymptote code is modified

### ISSUE THREAD

**Issue by BessieTheCow** [James-Yu/LaTeX-Workshop#2237] opened 2020-08-09 23:41 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

When I edit some Asymptote code inside a LaTeX document and build it, Latexmk is run twice even when `latex-workshop.latex.autoBuild.cleanAndRetry.enabled` is set to `false`.

### To Reproduce

1. Create a `foo.tex` file with the following contents:
```latex
\documentclass{article}
\usepackage{asymptote}
\begin{document}
    \begin{asy}
        draw((0,0)--(100,100));
    \end{asy}
\end{document}
```
2. Create a `latexmkrc` file in the same directory with the following contents:
```
sub asy {return system("asy \"$_[0]\"");}
add_cus_dep("asy","eps",0,"asy");
add_cus_dep("asy","pdf",0,"asy");
add_cus_dep("asy","tex",0,"asy");
```
3. Build the document.
4. Edit the Asymptote code and build it again, either by saving with automatic build enabled or using <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>B</kbd>.
5. Notice that Latexmk is run twice. In the output panel, you can see the first build complete and then the output is cleared and Latexmk is run a second time, which results in a message saying that the targets are up-to-date.

### Expected behavior

The document should only be build once, since Latexmk already handles reruns.

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[16:28:31] Initializing LaTeX Workshop.
[16:28:31] Creating PDF file watcher.
[16:28:31] Creating LaTeX Workshop http and websocket server.
[16:28:31] LaTeX Workshop initialized.
[16:28:32] Found root file from active editor: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:32] Root file changed: from undefined to c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:32] Start to find all dependencies.
[16:28:32] Instantiating a new file watcher for c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:32] Creating Bib file watcher.
[16:28:32] Parsing a file and its subfiles: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:32] Parse fls file.
[16:28:32] Fls file found: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.fls
[16:28:32] Parse aux file: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.aux
[16:28:32] Server created on 127.0.0.1:55785
[16:28:32] Added to file watcher: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:32] Added to file watcher: c:\Users\zhang\Desktop\Discrete Math HW\test\foo-1.pdf
[16:28:32] LaTeX Workshop version: 8.11.1
[16:28:32] Snippet data loaded.
[16:28:34] Preview PDF file: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.pdf
[16:28:34] Handle data type: open
[16:28:34] Handle data type: request_params
[16:28:34] Handle data type: loaded
[16:28:40] BUILD command invoked.
[16:28:40] Found root file from active editor: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:40] Keep using the same root file: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex.
[16:28:40] Building root file: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:40] Build root file c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:40] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=c:/Users/zhang/Desktop/Discrete Math HW/test,c:/Users/zhang/Desktop/Discrete Math HW/test/foo
[16:28:40] cwd: c:\Users\zhang\Desktop\Discrete Math HW\test
[16:28:40] LaTeX build process spawned. PID: 24672.
[16:28:41] File watcher - file changed: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:41] Parsing a file and its subfiles: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:41] Parse fls file.
[16:28:41] Fls file found: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.fls
[16:28:41] Parse aux file: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.aux
[16:28:41] Auto Build Run is temporarily disabled during a second.
[16:28:44] Found root file from active editor: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:44] Keep using the same root file: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex.
[16:28:46] File watcher - file changed: c:\Users\zhang\Desktop\Discrete Math HW\test\foo-1.pdf
[16:28:46] Auto build started detecting the change of a file: c:\Users\zhang\Desktop\Discrete Math HW\test\foo-1.pdf
[16:28:46] BUILD command invoked.
[16:28:46] Building root file: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:48] LaTeX log parsed with 0 messages.
[16:28:48] Recipe of length 1 finished. PID: 24672.
[16:28:48] Successfully built c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex.
[16:28:48] Refresh PDF viewer for c:\Users\zhang\Desktop\Discrete Math HW\test\foo.pdf
[16:28:48] Parse fls file.
[16:28:48] Fls file found: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.fls
[16:28:48] Parse aux file: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.aux
[16:28:48] Build root file c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:48] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=c:/Users/zhang/Desktop/Discrete Math HW/test,c:/Users/zhang/Desktop/Discrete Math HW/test/foo
[16:28:48] cwd: c:\Users\zhang\Desktop\Discrete Math HW\test
[16:28:48] LaTeX build process spawned. PID: 19680.
[16:28:48] Preview PDF file: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.pdf
[16:28:48] Handle data type: loaded
[16:28:48] Recipe of length 1 finished. PID: 19680.
[16:28:48] Successfully built c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex.
[16:28:50] Found root file from active editor: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex
[16:28:50] Keep using the same root file: c:\Users\zhang\Desktop\Discrete Math HW\test\foo.tex.
```

### Developer Tools Console [Required]

This is the only thing I see in the console:
```
webviewElement.ts:160 [Embedded Page] PDF 91c45522f82abcd17b959e9d21985848 [1.5 pdfTeX-1.40.21 / TeX] (PDF.js: 2.3.200)
webviewElement.ts:160 [Embedded Page] PDF b31dfe5da87f6c7c21e88cb6c4e56242 [1.5 pdfTeX-1.40.21 / TeX] (PDF.js: 2.3.200)
```

## Screenshots

This is after I modified the Asymptote code and built the document. Notice that it says its up-to-date in the output pane because it's been run a second time.
![image](https://user-images.githubusercontent.com/35056002/89744015-9da6f600-da5d-11ea-9e77-0d53318c0985.png)

## Desktop [Required]
 - OS: Windows 10
 - VS Code version: 1.47.3
 - Extension version: 8.11.1
 - TeX distribution version: TeX Live 2020

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

I'm using the default recipe and tools, with automatic retry on build failure disabled. The build only gets run twice when the Asymptote code is modified. If I modify some other part of the document the build only gets run once and I can see the full output.

Here's the contents of `foo.aux`:
```
\relax 
```

And here's `foo.fls`:
```
PWD c:/Users/zhang/Desktop/test
INPUT c:/texlive/2020/texmf.cnf
INPUT c:/texlive/2020/texmf-dist/web2c/texmf.cnf
INPUT c:/texlive/2020/texmf-var/web2c/pdftex/pdflatex.fmt
INPUT c:/Users/zhang/Desktop/test/foo.tex
OUTPUT c:/Users/zhang/Desktop/test/foo.log
INPUT c:/texlive/2020/texmf-dist/tex/latex/base/article.cls
INPUT c:/texlive/2020/texmf-dist/tex/latex/base/article.cls
INPUT c:/texlive/2020/texmf-dist/tex/latex/base/size10.clo
INPUT c:/texlive/2020/texmf-dist/tex/latex/base/size10.clo
INPUT c:/texlive/2020/texmf-dist/tex/latex/asymptote/asymptote.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/asymptote/asymptote.sty
INPUT c:/Users/zhang/Desktop/test/foo.pre
INPUT c:/Users/zhang/Desktop/test/foo.pre
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics/keyval.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics/keyval.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/base/ifthen.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/base/ifthen.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics/color.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics/color.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics-cfg/color.cfg
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics-cfg/color.cfg
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics-def/pdftex.def
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics-def/pdftex.def
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics/graphicx.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics/graphicx.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics/graphics.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics/graphics.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics/trig.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics/trig.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics-cfg/graphics.cfg
INPUT c:/texlive/2020/texmf-dist/tex/latex/graphics-cfg/graphics.cfg
INPUT c:/texlive/2020/texmf-dist/tex/generic/iftex/ifpdf.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/iftex/ifpdf.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/iftex/ifpdf.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/iftex/iftex.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/iftex/iftex.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/iftex/ifxetex.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/iftex/ifxetex.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/iftex/ifxetex.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/catchfile/catchfile.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/catchfile/catchfile.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/catchfile/catchfile.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/infwarerr/infwarerr.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/infwarerr/infwarerr.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/etexcmds/etexcmds.sty
INPUT c:/texlive/2020/texmf-dist/tex/generic/etexcmds/etexcmds.sty
OUTPUT c:/Users/zhang/Desktop/test/foo.pre
INPUT c:/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def
INPUT c:/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def
INPUT c:/Users/zhang/Desktop/test/foo.aux
INPUT c:/Users/zhang/Desktop/test/foo.aux
OUTPUT c:/Users/zhang/Desktop/test/foo.aux
INPUT c:/texlive/2020/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
INPUT c:/texlive/2020/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
INPUT c:/texlive/2020/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/epstopdf-pkg/epstopdf-base.sty
INPUT c:/texlive/2020/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg
INPUT c:/texlive/2020/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg
OUTPUT c:/Users/zhang/Desktop/test/foo-1.asy
INPUT c:/Users/zhang/Desktop/test/foo-1.pdf
INPUT c:/Users/zhang/Desktop/test/foo-1.pdf
INPUT c:/Users/zhang/Desktop/test/foo-1.pdf
OUTPUT c:/Users/zhang/Desktop/test/foo.pdf
INPUT c:/Users/zhang/Desktop/test/foo-1.pdf
INPUT c:/texlive/2020/texmf-var/fonts/map/pdftex/updmap/pdftex.map
INPUT c:/Users/zhang/Desktop/test/foo.aux
INPUT c:/texlive/2020/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb
```

**Comment by tamuratak** [comment] 2020-08-09 23:56
This is the cause:
```
[16:28:46] Auto build started detecting the change of a file: c:\Users\zhang\Desktop\Discrete Math HW\test\foo-1.pdf
```
I am not sure where `foo-1.pdf` comes from.

Please paste `foo.fls` and `foo.aux`. Thank you for your cooperation.

**Comment by BessieTheCow** [comment] 2020-08-10 03:37
@tamuratak Sorry, I forgot to mention that the document is saved in a file named `foo.tex`. `foo-1.pdf` is the image produced by Asymptote.

**Comment by tamuratak** [comment] 2020-08-10 04:24
A workaround is to adding `foo-1.pdf` to `latex-workshop.latex.watch.files.ignore`.

See https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile#latex-workshoplatexwatchfilesignore

**Comment by jlelong** [comment] 2020-08-11 06:27
This is because `foo-1.pdf` is listed as an input file in `foo.fls`

```
INPUT c:/Users/zhang/Desktop/test/foo-1.pdf
```

I would have expected it to be listed as output too because it is generated during compilation but unfortunately such is not the case. I cannot see how we can handle automatically.

**Comment by tamuratak** [comment] 2020-08-11 07:04
We can exclude `INPUT c:/Users/zhang/Desktop/test/foo-1.pdf` if there exists a line
```
OUTPUT c:/Users/zhang/Desktop/test/foo-1.asy
```
The suffix, `.asy`, is the one for [Aymptone](https://github.com/vectorgraphics/asymptote/tree/master/examples).

**Comment by jlelong** [comment] 2020-08-13 06:39
@tamuratak yes we can but it looks like a hack to me. 
I think Asymptote should declare the generated `.asy` files both as input and output files as the `minted` package does.
I have filled an issue on https://github.com/vectorgraphics/asymptote/issues/173

**Comment by jlelong** [comment] 2020-08-24 12:14
This is still under discussion in vectorgraphics/asymptote#173.

From a more general point of view, I suggest to drop all the `onChange` events occurring during a build and to only keep the `onSave` events. I think this would also solve #2153. @tamuratak what do you think of this?

**Comment by tamuratak** [comment] 2020-08-24 12:48
The change on `foo-1.pdf` is detected by `Manager.fileWatcher`:

https://github.com/James-Yu/LaTeX-Workshop/blob/ca3614501b2c68ed235cb5fa2c454d8cf9455fd4/src/components/manager.ts#L766-L770

I cannot see the difference between `onChange` and `onSave`.

**Comment by jlelong** [comment] 2020-08-24 13:54
I was referring to `latex-workshop.latex.autoBuild.run`.

- The `onFileChange` value is handled by https://github.com/James-Yu/LaTeX-Workshop/blob/ca3614501b2c68ed235cb5fa2c454d8cf9455fd4/src/components/manager.ts#L766-L770
- Then `onSave` value is handled by https://github.com/James-Yu/LaTeX-Workshop/blob/19ab221ceea1bc40bcdf4bbba248532104247ee4/src/main.ts#L132-L148

**Comment by tamuratak** [comment] 2020-08-24 23:19
Thank you. I see.

I don't like making building processes more complicated. It is enough complicated.

**Comment by jlelong** [comment] 2020-08-25 09:38
> I don't like making building processes more complicated.

I tend to agree with this. 

Yet, there does not seem to be any easy solution to fix this issue. Since `latexmk` detects that the second build is useless and does nothing, I think we can close this issue.

There are two workarounds to this issue

1. Adding `foo-1.pdf`, or `"**/*.pdf"`, to `latex-workshop.latex.watch.files.ignore`.
1. Setting `latex-workshop.latex.autoBuild.run` to `onSave` instead of `onFileChange`.

**Closed by jlelong** 2020-08-25 09:38 UTC
Labels: enhancement, external
