### ISSUE TITLE
Non-english characters in the path of a source file

### ISSUE THREAD

**Issue by SlavekRydval** [James-Yu/LaTeX-Workshop#846] opened 2018-10-04 09:21 UTC
### Description

When non-english characters are in the path of a source file, then compiler failed.

### Log messages

This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `"c:/Sl൥k/Elebedial/UML pro analytiky/Sazba/UML pro analytiky.tex"'.
<*> ... pro analytiky/Sazba/UML pro analytiky.tex"

<details>
<summary>LaTeX Workshop Output</summary>

N/A
</details>

<details>
<summary>Developer Tools Console</summary>

</details>

### How to reproduce

1. I have a directory such as c:\Slávek\TeX
2. I have my own recipe 
        {
            "name": "My recipe",
            "tools": [
              "xelatex"
            ]
          }
3. I have defined tool:
{
          "name": "xelatex",
          "command": "c:\\texlive\\2018\\bin\\win32\\xelatex.exe",
          "args": [
            "-synctex=1",
            "-interaction=nonstopmode",
            "-file-line-error",
            "%DOC%.tex"
          ]
        }

### Expected behavior

The filename will be passed correctly.

### Actual behavior

It works only if English characters are in the path and filename.

### Additional Information

I use Czech locale on Windows.

**Comment by jlelong** [comment] 2018-10-04 09:57
Duplicate of #269 and #157.

**Closed by jlelong** 2018-10-04 09:57 UTC
