### ISSUE TITLE
Messages in Problems pane are wrong with MikTeX and lualatex (logs are truncated to 80 chars)

### ISSUE THREAD

**Issue by jebej** [James-Yu/LaTeX-Workshop#1916] opened 2020-01-24 20:42 UTC
Hello, I am able to compile and view files properly, but am having an issue with the "problems" pane. While errors are listed properly, if I click on one of them to jump to the location, I get the error:

```
Unable to open `main`: Unable to read file (Error: File not found (....).
```

My file is named `main.tex`, so I assume the missing extension is what is causing the error. How can I fix this?

**Comment by jlelong** [comment] 2020-01-24 20:46
Please fill in the bug report template and provide a MWE.

**Comment by jebej** [comment] 2020-01-24 21:06
Sorry, there isn't anything useful in the logs.

I was able to determine that the issue is caused by the filepath being truncated to some length which was just long enough to chop the extension. I noticed this when I tried changing the filename.

The general issue is that the path length is limited. Hopefully this can be fixed.

**Comment by jlelong** [comment] 2020-01-26 14:54
> Sorry, there isn't anything useful in the logs.

Really? Are we supposed to guess the maximum path length? This is why MWE and logs are so important to avoid wasting our time and help us identify the real issue.

**Comment by jebej** [comment] 2020-01-26 17:35
I understand your frustration, here are the logs:

File:
```
\documentclass{article}
\begin{document}

A problem \hspace{15cm} space.

\end{document}
```
Click on overfull box message to get the error message:
```
Unable to open 'longgggggggggggi': Unable to read file (Error: File not found (d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggi)).
```

You can see the actual path below.


Latex-Workshop Output:
```
[12:32:07] Initializing LaTeX Workshop.
[12:32:07] pdflatex is provided by MiKTeX
[12:32:07] Creating LaTeX Workshop http and websocket server.
[12:32:07] LaTeX Workshop initialized.
[12:32:07] Found root file from active editor: d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggilename.tex
[12:32:07] Root file changed from: undefined to d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggilename.tex. Find all dependencies.
[12:32:07] Instantiating a new file watcher for d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggilename.tex
[12:32:07] Creating file watcher for .bib files.
[12:32:07] Parsing d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggilename.tex
[12:32:07] Server created on 127.0.0.1:52537
[12:32:07] Adding d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggilename.tex to file watcher.
[12:32:07] Snippet data loaded.
[12:32:07] LaTeX Workshop version: 8.6.0
[12:32:09] File watcher: responding to change in d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggilename.tex
[12:32:09] Parsing d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggilename.tex
[12:32:09] d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggilename.tex changed. Auto build project.
[12:32:09] BUILD command invoked.
[12:32:09] Building root file: d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggilename.tex
[12:32:09] Build root file d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggilename.tex
[12:32:09] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-lualatex,-shell-escape,-outdir=d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder,d:/temp/averylooooooooooooooooooooooooooooooooooooooongfolder/longgggggggggggilename.tex
[12:32:09] LaTeX build process spawned. PID: 15780.
[12:32:13] LaTeX log parsed with 1 messages.
[12:32:13] Recipe of length 1 finished. PID: 15780.
[12:32:13] Successfully built d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggilename.tex.
[12:32:13] No PDF viewer connected for d:\temp\averylooooooooooooooooooooooooooooooooooooooongfolder\longgggggggggggilename.pdf
[12:32:13] Parse fls file.
```

**Comment by jebej** [comment] 2020-01-26 17:41
This is on Windows 10, fully updated, only extension running in VSCode.

**Comment by jlelong** [comment] 2020-01-28 20:53
I cannot reproduce the issue on OSX. This is surely not related to the extension.
Try to see if you experience the same kind of troubles with other filetypes as `.md` files for instance. If so, file an issue in vscode repo.

**Comment by jebej** [comment] 2020-01-28 21:01
Yes, the issue is not due to the missing extension, but more generally missing characters since the path is being truncated.

I am not sure how I would reproduce this with a markdown file, since this has to do with Latex errors.

I do have a spellcheck extension (Spell Right, installed after) that works fine for in-file links for that same latex doc, so AFAICT it doesn't seem to be a problem with VSCode.

I tried looking at the parser code to see where that path was being determined but couldn't really follow the logic. Opening the PDF works fine, and so does feeding the file to latexmk, so I assume it must be directly related to the either the parsing of the error, or the generation of the path from the parsing. Is there some kind of normalization being applied?

**Comment by jlelong** [comment] 2020-01-28 21:09
I am wondering whether it could be related to the way VSCode stores _Problems_.
Could you try to create a `averyveryverylongfile.md` (make sure the filename itself is sufficiently long without considering its directory part) with some linter warnings? 
What is the path length limit for which the issue appears?
We do not do anything fancy when parsing the logs

https://github.com/James-Yu/LaTeX-Workshop/blob/c6756708ac8fd87809149184f0327d81a0ecefa6/src/components/parser/log.ts#L193-L202

https://github.com/James-Yu/LaTeX-Workshop/blob/c6756708ac8fd87809149184f0327d81a0ecefa6/src/components/parser/log.ts#L322

**Comment by jebej** [comment] 2020-01-28 23:44
Does my example with the spell check not answer this question? Those spell check errors are displayed in the "Problems" pane.

Thanks for the link, I'll check this out.

**Comment by jebej** [comment] 2020-01-29 00:11
The issue has to do with the log file breaking lines at 80chars. Very similar to issue #796.

**Comment by jebej** [comment] 2020-01-29 00:32
Although interestingly, the parser for Atom-Latex, also originally written by James-Yu, handles those line breaks properly.

**Comment by jlelong** [comment] 2020-01-29 06:11
We have spent a lot of time trying to improve the log parser and one of the very first thing we did was to instruct the LaTeX compiler not to truncate lines to 80 characters. Rejoining lines after the truncation is really a headache for all LaTeX log parsers. Unfortunately, we have not found a way to achieve this with MikTeX and `lualatex`. See #885, MiKTeX/miktex/issues/192

**Comment by tamuratak** [comment] 2020-03-10 08:03
@jlelong  I remembered that I had made `latex-utensils`  be able to parse LaTeX [logs](https://github.com/tamuratak/latex-utensils/tree/master/test/latex_log). I am not sure it is reliable on real usage. If you have time and are interested, please try 

```
   ./bin/luparse test/latex_log/e01.log
```

**Comment by James-Yu** [comment] 2022-09-10 04:30
I'm closing this issue for now. It seems that the issue will resolve itself when MikTeX may eventually unify the lualatex behavior.

**Closed by James-Yu** 2022-09-10 04:30 UTC
Labels: external issue

**Comment by sharadhr** [comment] 2022-09-16 18:04
I've solved this problem after having trawled through MiKTeX's source code and debugging runs of `miktex-luahbtex` (note that `miktex-luatex` symlinks to it on both Windows and Linux; it should be the same on OS X although I haven't tested it). 

It turns out that although the `miktex-luahbtex` executable doesn't have the command-line options that the `pdftex`/`xetex` executables do, the `max_print_line` and `error_line` variables can still be configured on the fly because a certain configuration file is read and said configuration applied at runtime. 

Look for `texmfapp.ini`; on a per-user MiKTeX install on Windows, this file is in `%LOCALAPPDATA%\Programs\MiKTeX\miktex\config`. On Linux, this is in `~/.miktex/miktex/config`. 

See the lines:
```.ini
;; Width of context lines on terminal error messages.
error_line = <some number>

...

;; Width of longest text lines output; should be at least 60.
max_print_line = <some number>
```

Change both numbers to 2147483647 (which is $2^{31} - 1$, aka `MAX_INT` in C/C++). Save, then run LuaTeX. You should get perfectly un-truncated lines now.
