### ISSUE TITLE
Opening non-tex PDF?

### ISSUE THREAD

**Issue by Astrantia** [James-Yu/LaTeX-Workshop#816] opened 2018-09-22 03:18 UTC
Hi. With the editor group support in newer vscode versions I want to work in the following setup:

```
------------------------
|        |  PDF Output |
|        |             |
|        |             |
| TEX    |-------------|
|        |             |
|        | UNRELATED   |
|        |       PDF   |
-----------------------
```
However, I can't seem to open unrelated PDF with latex-workshop (and I wouldn't expect latex workshop to support opening arbitrary pdf), but the strange thing is when I downloaded vscode pdf view extension Latex workshop complained it had everything that vscode pdf view extension view contributed and that it was unnecessary.
So I would suggest to either support viewing any PDF, or just make it compatible with other pdf viewer extension.

To reproduce just go in any latex directory, open up tex, open up generated pdf in vscode tab and then try to open unrelated pdf in the workspace as a third editor group.

**Comment by aobo-y** [comment] 2018-09-22 18:57
Same here. 

In README, it says `To view an arbitrary PDF file, right click on the file in the explorer and select View PDF.`, but there is no such option

**Comment by jlelong** [comment] 2018-09-24 16:59
Duplicate of #775.
Just click on the pdf file to open it.

**Comment by Astrantia** [comment] 2018-09-24 17:13
@jlelong None of the pdfs i tried to open by left clicks opened up

**Comment by jlelong** [comment] 2018-09-24 17:14
What does happen exactly?

**Comment by Astrantia** [comment] 2018-09-24 17:19
Maybe its an issue with vscode insiders. Ill try to reproduce it when i get home

**Comment by Astrantia** [comment] 2018-09-24 18:19
@jlelong The pdf opens in its binary representation in the text editor for a microsecond and then autocloses. Here's the log:
```
[Extension Host]% {$mid: 1, fsPath: "c:\Users\User\Desktop\TestDir\Test\Test.pdf", external: "file:///c%3A/Users/User/Desktop/TestDir/Test/Test.pdf", path: "/c:/Users/User/Desktop/TestDir/Test/Test.pdf", scheme: "file"}$mid: 1external: "file:///c%3A/Users/User/Desktop/TestDir/Test/Homework%203.pdf"fsPath: "c:\Users\User\Desktop\TestDir\Test\Test.pdf"path: "/c:/Users/User/Desktop/TestDir/Test/Test.pdf"scheme: "file"__proto__: Object (at Commander.pdf (C:\Users\User\.vscode-insiders\extensions\james-yu.latex-workshop-5.10.1\out\src\commander.js:168:17))
```

**Comment by Astrantia** [comment] 2018-09-24 20:02
@jlelong can we reopen this?

**Comment by Astrantia** [comment] 2018-09-25 02:34
@James-Yu I don't understand how to run the PDF though. I can't even open a PDF with Latex-Workshop file scheme without explicitly using `View Latex PDF File in VSCode Tab` command.

**Comment by James-Yu** [comment] 2018-09-25 02:39
It seems to be an unstable function. I'll explore.

**Comment by Astrantia** [comment] 2018-09-25 03:08
@James-Yu Here's more log that I didn't notice earlier:
```
[22:57:55] PDF command invoked.
[22:57:55] No PDF viewer connected for c:\dist\TEST.pdf
[22:57:55] Cannot find PDF file c:\test\TEST.pdf
```

**Comment by Astrantia** [comment] 2018-09-25 03:27
Well it's something like this:
```
ParentFolder
    ChildOne
    ChildTwo
          Tex.tex
          dist
               Tex.pdf
    ChildThree
    NonTex.pdf
```

**Comment by James-Yu** [comment] 2018-09-25 06:34
I cannot reproduce the problem. I've tested the following structure, and it works however I click the files. Without further information, I cannot identify the problem.

![image](https://user-images.githubusercontent.com/4210342/45996805-19992e80-c0d0-11e8-9bce-5ce20a3e749e.png)

**Comment by Astrantia** [comment] 2018-09-25 06:38
@jlelong Did you try with vscode insiders?

**Comment by James-Yu** [comment] 2018-09-25 06:39
Just a sidenote, Insider is typically not tested, and is not planned to be covered due to the fast changes.

**Comment by jlelong** [comment] 2018-09-25 06:40
@Astrantia , no I use the latest stable release. Anyway, I have just tested on the insiders version and the pdf shows up properly after first blinking in its binary form.

**Comment by Astrantia** [comment] 2018-09-27 07:17
@James-Yu @jlelong I set up a completely new machine and there's still the same issue. Are you guys using Windows? Here's a gif:
https://i.imgur.com/dI4AIS8.gifv

**Comment by Astrantia** [comment] 2018-09-29 15:46
@James-Yu @jlelong Were you able to reproduce this?

**Comment by jlelong** [comment] 2018-10-03 19:28
It seems to only work for `.pdf` files associated to a `.tex` file. Otherwise, I only get the binary form of it.

**Comment by Astrantia** [comment] 2018-10-03 20:21
@jlelong I was always testing this with `.pdf` that weren't associated to a `.tex` so maybe that's why it's never been working for me. @James-Yu ideas why this is so?

**Comment by James-Yu** [comment] 2018-10-04 03:02
You may refer to my previous screenshot, the `Non.pdf` is not related to a tex file but works just right.

**Comment by Astrantia** [comment] 2018-10-04 03:54
@jlelong Since you were able to reproduce this, was there anything more conrrete than the `.pdf` not being associated to a `.tex`?

**Comment by jlelong** [comment] 2018-10-04 06:33
Well, the problem is even worse than I thought. If i first open a `.tex` and then a non `.tex` related `.pdf` file, vscode sort of freezes : I cannot modify the open `.tex` file, nor build it, .... I cannot find any log relevant to that freeze. @James-Yu any idea ?

**Comment by James-Yu** [comment] 2018-10-04 08:05
Will definitely look into that, now(TM).

**Comment by Astrantia** [comment] 2018-10-04 15:53
@James-Yu I have finally realized how to reproduce this. Set your settings to `"latex-workshop.latex.outputDir": "./dist"`. Place the non-tex PDF in a parent folder of dist and try to open it.

**Comment by Astrantia** [comment] 2018-10-04 19:08
@James-Yu Actually what I just found out is that this doesn't have to be a non-tex pdf. I can't open a pdf that was built from latex workshop by just left clicking it either. I have to invoke `View Latex PDF File in VSCode Tab` to view the generated pdf. So the issue is narrowed down now:
**Using custom build folder and changing the two settings i noted above, left-clicking pdf doesn't work because wrong path is passed to the function that opens pdf.**

**Comment by James-Yu** [comment] 2018-10-05 05:55
This is a bug introduced in 1ed99b46d62bfe339c93d98ea9af4227ac047998 which aims to address #520. Really sorry for overlooking it for such a long time.

**Closed** 2018-10-05 05:55 UTC

**Comment by Astrantia** [comment] 2018-10-05 06:00
Thanks!

**Comment by tecosaur** [comment] 2018-10-18 13:11
@James-Yu is there any way to stop this message from coming up?
![image](https://user-images.githubusercontent.com/20903656/47156773-66140a80-d31a-11e8-879c-976e8bd5d607.png)

**Comment by James-Yu** [comment] 2018-10-18 13:12
@tecosaur I'm not aware of ways bypassing this.
