### ISSUE TITLE
Add highlight to forward search

### ISSUE THREAD

**Issue by quoc-ho** [James-Yu/LaTeX-Workshop#344] opened 2017-12-10 10:01 UTC
For backward search, it's easy to see what the result is since the cursor goes directly to the right place. It's not as easy for forward search. Is it possible to add some highlighting to the word/line/paragraph so that it's easy to see what the search result is? TexStudio, for example, does this.

Thanks!

**Comment by James-Yu** [comment] 2017-12-11 02:18
Duplicate of #315

**Closed by James-Yu** 2017-12-11 02:18 UTC
