### ISSUE TITLE
[dev feature] Use actions to check build system on UNIX and Windows

### ISSUE THREAD

**Issue by funnym0nk3y** [James-Yu/LaTeX-Workshop#1909] opened 2020-01-16 12:48 UTC
As I filed the issue #1897 it became clear that there are difficulties to make the build system work on different platforms with different configurations. As I updated my version of this extension to 8.6.0 I am having some strange issues with the build system (no filed bug yet, I have to first figure out what is happening). To improve reliability and add some testing I am suggesting to use github actions to run some tests.

Looking forward to your comments!

funnym0nk3y

**Comment by jlelong** [comment] 2020-01-16 13:55
Unfortunately, easier said than done. The real difficulty is to design the tests considering the wide variety of configurations. It goes far beyond the Windows or Unix dichotomy. I would love to see automated non-regression tests.

**Comment by tamuratak** [comment] 2020-01-16 23:21
Because we can override user settings with `.vscode/settigns.json` in workspaces, we can test  "the wide variety of configurations"  by creating directories having `.vscode/settigns.json` corresponding to each test case.

**Comment by jlelong** [comment] 2020-01-17 05:53
Of course we can use local configurations. I was more referring to the combinatorial aspects (OS, Docker, remote, LaTeX distribution, special characters, ...)

**Comment by tamuratak** [comment] 2020-01-17 06:13
On GitHub Actions, we can choose Ubuntu, Windows, and macOS as OS with free. On each OS, lots of software are already installed. 
 
- https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

I have tried installing TeX Live on Windows on GitHub Actions. It seems to work. 

- https://github.com/tamuratak/github-actions-examples

On Windows, we can use [Chocolatey](https://chocolatey.org/), a package manager for Windows, already [installed](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#chocolatey-1). The [MikTeX package](https://chocolatey.org/packages/miktex) is available.

**Comment by funnym0nk3y** [comment] 2020-01-18 22:25
@tamuratak You are way more proficient with github actions than I am. I will try to follow your steps, but I can't guarantee I can contribute...

@jlelong So what should be tested? 

- OS: Windows, Linux, macOS
- Multiple build systems: pdflatex, lualatex through latexmk
- Multiple distributions (if available): TeXLive, MikTeX

What do you mean by docker and special characters?

**Comment by jlelong** [comment] 2020-01-19 05:50
- build systems: 
  - `latexmk` with one of the following options at a time: `-pdf`, `-lualatex`, `-xelatex`. This can be set in a  `.latexmkrc` file
  - it is also important to consider different `-output-directory` (variable `$out_dir` in `.latexmkrc`)
- Among all, we should also consider documents using the `subfiles` package. See #1895 for examples of such documents.
> What do you mean by docker and special characters?

Most of the problems we add recently were related to using a dockerized LaTeX distribution.

**Comment by tamuratak** [comment] 2020-01-19 07:20
I have added an example of running `latexmk` on GitHub Actions.

- https://github.com/tamuratak/github-actions-examples/tree/texlive

You can see the [familiar log](https://github.com/tamuratak/github-actions-examples/runs/397398171).

**Comment by tamuratak** [comment] 2020-03-01 08:29
@jlelong Have you changed your mind on adding tests from [the time](https://github.com/James-Yu/LaTeX-Workshop/pull/1284#issuecomment-480711400)?  As I said before, if adding tests harms your motivation, I do not push that strongly.  I will close this issue.

**Comment by jlelong** [comment] 2020-03-01 08:35
I am afraid I was not clear at the time. I would be delighted to have automated tests, they would be so helpful to check all the different situations with subfiles for instance. My point is that unfortunately I do not have the time to design all this. @tamuratak if you can find the time to implement the whole framework, I would be happy to contribute.

**Comment by tamuratak** [comment] 2020-03-01 09:04
Great. I think aiming at adding comprehensive unit tests is not feasible. I will start by adding integration tests. On GitHub Actions,

1.  VS Code automatically opens test directories as workspace and calls a build command. 
2. We check whether pdf files are generated.

**Closed** 2020-03-04 22:19 UTC
Labels: dev
