### ISSUE TITLE
Autocomplete too vigorous

### ISSUE THREAD

**Issue by HyacinthPlus** [James-Yu/LaTeX-Workshop#3013] opened 2021-12-14 21:13 UTC
## Preliminary questions [Required]
when I try to type "suppose", it pairs me with an unrelated snippet that starts with the letter "e", as well as many other that contains the char "e".

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

### To Reproduce

1. Open a .tex file
2. Add a snippet that starts with char "e" or just any snippet that contains "e"
3. Type "suppose" in the .tex file, and unrelated suggestions show up
This happens to other words as well. 
For example:
1. when I type "lim", it suggests "item". 
2. when I type $\frac{}{}$, it starts to suggest a bunch of unrelated snippets.
3. when I type "definition", it suggests "oline".

### Expected behavior

I think:
1. when typing "suppose", I should not get suggestions like "ezsplit".
2. when typing "lim", "item" should not be suggested.
3. after finishing typing \frac{}{}, \bslash is definitely not the word I wanted.

## Logs [Required]

Since I'm not having a problem with compiling, I guess there is no point for logs, but I will throw my settings for suggestions here...

```
"editor.tabCompletion": "on",

"editor.suggest.shareSuggestSelections": true,

"editor.suggest.localityBonus": true,

"editor.suggestSelection": "recentlyUsedByPrefix",

"editor.quickSuggestionsDelay": 1,

"editor.suggest.snippetsPreventQuickSuggestions": false,

"latex-workshop.intellisense.update.delay": 1,

"latex-workshop.chktex.delay": 10,

"editor.suggest.showStatusBar": true,

"editor.wordBasedSuggestionsMode":"matchingDocuments",

"editor.suggest.showClasses": false,
```

## Screenshots

The following are screenshots of this issue.
![image](https://user-images.githubusercontent.com/18757347/146077592-0e32f399-aa14-42c2-aca2-0acca58f7559.png)
![image](https://user-images.githubusercontent.com/18757347/146077661-0b4c03d9-2fdc-4aa8-b45e-f6b3b39b8fbc.png)
![image](https://user-images.githubusercontent.com/18757347/146077764-0f63c55a-8cea-4653-9a0e-81732b7d9cef.png)
![image](https://user-images.githubusercontent.com/18757347/146082727-4df745d5-08fd-43b8-8c8b-5d465b8ee0ed.png)

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Windows 10
 - VS Code version: 1.63.1
 - Extension version: 8.22.0
 - TeX distribution version: Tex Live 2019

##Additional Context
Seems unrelated, but when I turn the suggestions for snippets on, I lost my suggestions for words on .tex file (it still works on other file types), and when I turn the suggestions for snippets off, the suggestions for words are back on.

**Comment by tamuratak** [comment] 2021-12-14 22:34
Duplicate of microsoft/vscode/issues/138707

These are user snippets. They are defined by users, not us. We can do nothing on user snippets. There is no API to control user snippets on our side. If you see other issues on user snippets, please report to https://github.com/microsoft/vscode

**Closed by tamuratak** 2021-12-14 22:34 UTC
