### ISSUE TITLE
Auto-completion for bibliography keys is not working

### ISSUE THREAD

**Issue by seybi87** [James-Yu/LaTeX-Workshop#1803] opened 2019-11-13 17:28 UTC
Hi guys, 

I am using VS Code 1.40 with Latex-Workshop in the latest version 8.3.1 with default settings. 

I have a large tex document with two bibliographies. 

I recently changed the bibliography backend from bibtex (with multibib) to biblatex using 

`\usepackage[backend=biber,defernumbers,maxnames=10, sorting=ynt]{biblatex}
\addbibresource{own.bib}
\addbibresource{related.bib}`

The latex project is compiled with xelatex: 
` "xelatex",
    "biber",
    "xelatex",
    "xelatex"`

The project comprises multiple .tex files that are included in the main .tex file. 

Since I changed the bibliography backend to biblatex the auto-completion of the `\cite{}` is not working anymore. In particular, no references are shown while typing `\cite{` and the bibliography key needs to be inserted manually. 

This was not the case while working with bibtex and all references popped up as suggestion for the auto-completion via the `\cite{}`command. 

Yet, there are no compile errors and the references are resolved and the two bibliographies show up as expected in the PDF. 

There are no additional custom settings applied. 

Thanks in advance for your help!

**Comment by jlelong** [comment] 2019-11-13 18:03
It should be working so please provide the logs of the extension to investigate why the `.bib` files are not parsed.

**Comment by jlelong** [comment] 2019-11-20 06:01
The issue does not contain enough information to investigate the problem. I am closing it until more information is provided.

**Comment by jgoulet1994** [comment] 2019-11-21 20:34
I had this issue, but found the solution.  For me, the extension "Path Autocomplete" was interfering with auto-completion of citations.

**Comment by jlelong** [comment] 2019-11-22 12:39
I have added a wiki entry on this, see [here](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#known-incompatible-extensions).

**Comment by seybi87** [comment] 2019-11-22 12:57
@jgoulet1994  and @jlelong  thanks a lot guys for pointing that out! 

Unfortunately I do not have this extension activated (not even installed).

I will come up with a MWE within the next days.

**Comment by cbuhl** [comment] 2019-12-06 15:43
I unfortunately have no further information to add, other than this happened for me as well - same MO, changing from bibtex to biblatex.

`\usepackage[style=ieee]{biblatex}`
`\addbibresource{bib/mybib.bib}`
 
I do not have any of the incompatible extensions installed either. 

It's on a mac, if that matters.

**Comment by jlelong** [comment] 2019-12-14 21:13
Unfortunately I cannot reproduce the issue. Can you post the full logs of the extension?

**Comment by nawordar** [comment] 2019-12-15 12:52
Maybe OS has something to do with that? I have the same exact problem and I am using Manjaro Linux. I use `latexmk` for compiling with the following command: `$pdflatex = 'lualatex -file-line-error %O %S';`. I will post the logs in a moment.

**Comment by tecosaur** [comment] 2019-12-15 13:18
I may be experiencing the same issue. I am also using `biblatex`. Here's what's happening for me is that at some point, coinciding with the bibliography file being updated, `\cite{}` autocompletion stops working.

When the issue appears my LaTeX Workshop "output" looks like this, with nothing notable appearing in the console.
```
[21:12:21] Bib file watcher - responding to change in /my/file/here/refs.bib
[21:12:21] Parsing .bib entries from /my/file/here/refs.bib
[21:12:21] /my/file/here/refs.bib changed. Auto build project.
[21:12:21] BUILD command invoked.
[21:12:21] Building root file: /my/file/here/texfile.tex
[21:12:21] Parsed 0 bib entries from /my/file/here/refs.bib.
[21:12:21] File watcher: responding to change in /my/file/here/texfile.tex
[21:12:21] Parsing /my/file/here/texfile.tex
[21:12:21] Found .bib file /my/file/here/refs.bib
[21:12:21] Auto Build Run is temporarily disabled during a second.
[21:12:21] Linter for root file started.
[21:12:21] Linter for root file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n1,-n24,-n11,-f%f:%l:%c:%d:%k:%n:%m
,/my/file/here/texfile.tex
[21:12:21] Build root file /my/file/here/texfile.tex
[21:12:21] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-shell-escape,-file-line-error,-pdf,/my/file/here/texfile
[21:12:21] LaTeX build process spawned. PID: 12465.
[21:12:21] Linter for root file successfully finished in 0s 107ms
[21:12:21] Linter log parsed with 2 messages.
[21:12:22] Linter for active file started.
[21:12:22] Linter for active file running command chktex with arguments -wall,-n22,-n30,-e16,-q,-n1,-n24,-n11,-I0,-f%f:%l:%c:%d:%k:%n:%m

[21:12:22] Linter for active file successfully finished in 0s 98ms
[21:12:22] Linter log parsed with 26 messages.
```

**Comment by nawordar** [comment] 2019-12-15 13:23
Alright, so I found the problem with my bibliography file.
```bibtex
@reference{dictionary_of_contemporary_english,
    editor = "",
    edition = {Fourth edition},
    title = "Dictionary of Contemporary English",
    publisher = "Longman",
    year = 2003,
    ISBN = 1-405-80673-7
}
```
As you can see, ISBN is not in the brackets. It compiles just fine, but it breaks the auto-completion. I have the following messages in the Chromium log:
```
▶ [Extension Host]
rejected promise not handled within 1 second: SyntaxError: Expected "#", ",", "\r\n", "}", or [ \t\n] but "@" found.
  t.log @ console.ts:137
▶ [Extension Host] 
stack trace: SyntaxError: Expected "#", ",", "\r\n", "}", or [ \t\n] but "@" found.
    at peg$buildStructuredError (/home/nawordar/.vscode/extensions/james-yu.latex-workshop-8.4.2/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:366:12)
    at Object.peg$parse [as parse] (/home/nawordar/.vscode/extensions/james-yu.latex-workshop-8.4.2/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:2011:11)
    at Object.parse (/home/nawordar/.vscode/extensions/james-yu.latex-workshop-8.4.2/node_modules/latex-utensils/out/src/bibtex/bibtex_parser.js:21:30)
    at Function.parseBibtex (/home/nawordar/.vscode/extensions/james-yu.latex-workshop-8.4.2/out/src/components/parser/syntax_worker.js:12:42)
    at process.<anonymous> (/home/nawordar/.vscode/extensions/james-yu.latex-workshop-8.4.2/node_modules/workerpool/dist/workerpool.min.js:25:16221)
    at process.emit (events.js:200:13)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
  t.log @ console.ts:137
```
My .bib file has LF line ending, so that might be the cause in my case.

**Comment by nawordar** [comment] 2019-12-15 13:26
@tecosaur Can you run `Toggle Developer Tools` command? Maybe there is something interesting there.

**Comment by tecosaur** [comment] 2019-12-15 13:27
@nawordar erm... that's what I meant by "nothing notable appearing in the console." :stuck_out_tongue:

**Comment by tecosaur** [comment] 2019-12-15 15:19
Hmm. I've been working in the vscode debug version of this extension to try to better track down this issue. I haven't been able to reproduce it so far (which I guess could be considered a good sign); but on a side note, I have noticed the pdf.js render no longer works (blank white content) which is strange.

**Comment by jlelong** [comment] 2019-12-16 06:18
@tecosaur there is indeed something interested in your logs

```
[21:12:21] Parsed 0 bib entries from /my/file/here/refs.bib.
```

This is coherent with @nawordar's comment: the issue comes from the `.bib` file content. I will dig into it.

> but on a side note, I have noticed the pdf.js render no longer works (blank white content) which is strange.

Do you mean that the viewer remains blank?

**Comment by tecosaur** [comment] 2019-12-16 06:21
@jlelong 

#### re: 0 bib entries

That's curious. What I have is a live-upadating `.bib` file generated by Zotero. Interestingly after it fails and reports `0 bib entries`, I find that after restarting everythng works just fine (with the bib file staying the same between breaking - restarting - working).

#### re: pdf viewer

It's like so
<img width="515" alt="image" src="https://user-images.githubusercontent.com/20903656/70883878-53c15980-200f-11ea-8037-fd8c7354333d.png">

**Comment by jlelong** [comment] 2019-12-16 07:14
> That's curious. What I have is a live-updating .bib file generated by Zotero. Interestingly after it fails and reports 0 bib entries, I find that after restarting everything works just fine (with the bib file staying the same between breaking - restarting - working).

This is strange as the `.bib` is first parsed at discovery time and then every time it gets updated (this is triggered by a file watcher). What do the logs say when Zotero updates the `.bib` file?

**Comment by tecosaur** [comment] 2019-12-16 10:27
The logs I have in my [earlier comment](https://github.com/James-Yu/LaTeX-Workshop/issues/1803#issuecomment-565808970) are all from immediately after the Zotero bib update. Unfortunately I don't have anything more for you at the moment, but I'll let you know when I do.

**Closed** 2019-12-16 14:40 UTC

**Comment by tecosaur** [comment] 2019-12-17 15:43
I see that 88b4a91 was pushed. Unfortunately I'm still experencing this isue in the manner I previously described, i.e. upon bib update I get:
```
[23:25:55] Bib file watcher - responding to change in /some/file/path/refs.bib
[23:25:55] Parsing .bib entries from /some/file/path/refs.bib
[23:25:55] /some/file/path/refs.bib changed. Auto build project.
[23:25:55] BUILD command invoked.
[23:25:55] Building root file: /some/file/path/Report.tex
[23:25:55] Parsed 0 bib entries from /some/file/path/refs.bib.
```
Then after reloading (and nothing else) I see
```
[23:30:58] Creating file watcher for .bib files.
[23:30:58] Parsing /some/file/path/Report.tex
[23:30:58] Found .bib file /some/file/path/refs.bib
[23:30:58] Adding .bib file /some/file/path/refs.bib to bib file watcher.
[23:30:58] Parsing .bib entries from /some/file/path/refs.bib
[23:30:58] Server created on 127.0.0.1:44019
[23:30:58] Adding /some/file/path/Report.tex to file watcher.
[23:30:58] Parsed 11 bib entries from /some/file/path/refs.bib.
```

I am now reproducing this in the debugger though, which is good.

**Comment by tecosaur** [comment] 2019-12-17 15:54
Hmm. I think I've found something. It seems that at the instant which the file is read, it is empty.

Just speculating here, but it may be the case that the `.bib` file it updated by Zotero by (a) clearing the file (b) writing the content.

I suspect that a significant portion of the time the extension is reading the file when it's empty, and then parsing nothing. In the meantime, the contents of the file is written very quickly (it's just a few hundred bytes after all), and this finishes before the `parseBibFile` function. To an extent, this also explains why sometimes after zotero re-updates the file, I see `Parsed 11 bib entries`.
From a few quick tests of mine, it seems that if the file is updated while `parseBibFile` is running, the update is missed. Hence, the `0 bib entries` is not corrected.

To me, the obvious fix is adding some minimal timeout (100ms?) to make sure that the sort of update-blocking can't occur so easily.

@jlelong what are you thoughts?

**Comment by jlelong** [comment] 2019-12-17 16:45
I think you are right. We need to add an extra delay after the watcher trigger before actually parsing the file. We can make the delay configurable.

**Comment by tamuratak** [comment] 2019-12-17 22:55
See `awaitWriteFinish` at https://github.com/paulmillr/chokidar#performance

**Comment by tecosaur** [comment] 2019-12-18 04:28
Perhaps the best option is a combination of `awaitWriteFinish` with a low hardcoded time (e.g. 100ms), but then a `setTimeout` to compare the file size in say, 1000ms, and re-run `parseBibFile` if it has changed.

**Comment by drandran12** [comment] 2021-07-25 21:10
Is this issue solved? Because I think I face the same problem.

**Comment by drandran12** [comment] 2021-07-25 21:54
> Is this issue solved? Because I think I face the same problem.

In my case there was a year in a Biblatex entry that was not enclosed with brackets. So there was
`...
year = 2016
...
`
What fixed the issue was enclosing the Biblatex entry with brackets:
`...
year ={2016}
...
`

**Comment by tamuratak** [comment] 2021-07-25 22:15
Please open a new issue filling out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md).
