### ISSUE TITLE
Hide LaTeX Outline

### ISSUE THREAD

**Issue by christianmalek** [James-Yu/LaTeX-Workshop#185] opened 2017-07-06 08:04 UTC
It really annoys me that that every VS Code Project shows this:

![image](https://user-images.githubusercontent.com/2873986/27901440-6b86deac-6232-11e7-848b-acb58ceeb55f.png)

Could you please add a option to hide/show it?

**Comment by James-Yu** [comment] 2017-07-06 08:05
Duplicate of #178 . Wait for Microsoft to release the API.

**Closed by James-Yu** 2017-07-06 08:05 UTC

**Comment by christianmalek** [comment] 2017-07-06 08:07
@James-Yu Thanks for your fast response.
