### ISSUE TITLE
Possible to view the pdf from browser on a host machine?

### ISSUE THREAD

**Issue by arisliang** [James-Yu/LaTeX-Workshop#2155] opened 2020-06-12 15:02 UTC
I'm editing in vscode in a ubuntu vm (virtualbox), it's fine to view the PDF in the browser on the same vm. Is it possible to view it on a host machine though (windows 10)?

By default, it listens to http://localhost:37339. It refuses connection from host machine, I imagine change the listening address to something like http://*:37339 might help?

Please advise.

**Comment by tamuratak** [comment] 2020-06-12 15:32
Duplicate of #1265. Use  [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) for the purpose.

**Closed by tamuratak** 2020-06-12 15:32 UTC
Labels: feature-request
