### ISSUE TITLE
Preview is just a part of the split window

### ISSUE THREAD

**Issue by XiangruiCAI** [James-Yu/LaTeX-Workshop#5] opened 2017-01-16 02:22 UTC
Currently, the preview do not work well for me. It only covers the left top part in the split window.
Is it due to the high resolution ratio of my laptop?

**Comment by James-Yu** [comment] 2017-01-16 02:24
Can you please provide a screenshot?

**Comment by James-Yu** [comment] 2017-01-16 05:54
I cannot reproduce this problem. Does it work fine with in-browser preview?

**Comment by XiangruiCAI** [comment] 2017-01-16 08:17
What do you mean? The pdf is correct. But it does not present well in VSCode.

Could this problem be due to the resolution ratio of my laptop(1920*1080)?

**Comment by James-Yu** [comment] 2017-01-16 08:18
From v0.2.0 there is a new feature that allows users to preview pdf in a browser tab. Can you try that and see if the pdf viewer works well in a browser tab?

**Comment by XiangruiCAI** [comment] 2017-01-16 08:20
It works well.

**Comment by James-Yu** [comment] 2017-01-16 08:25
It seems to be some problem with vscode. I would recommend reinstall the extension/vscode and see if the problem persists.

The code that controls the vscode preview panel is [https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/preview.ts#L274](url). The iframe is set to 100% width and height. As I cannot re-produce the problem, I've no idea what is going wrong.

It should not have any relation with the screen resolution tho. Do you have similar problems with previous versions?

**Comment by XiangruiCAI** [comment] 2017-01-16 08:32
I remember it works well in previous version(I mean latex workshop). This problem came maybe from version 0.2.x. I'm not quite sure. Thanks!

**Comment by James-Yu** [comment] 2017-01-16 08:40
Can you please try the following commands in `Help -> Toggle Developer Tools` as attached?

`document.getElementsByTagName('webview')[0].style.width`
`document.getElementsByTagName('webview')[0].style.height`

If both are `100%`, then that should be a problem with vscode.

![screenshot from 2017-01-16 16 39 28](https://cloud.githubusercontent.com/assets/4210342/21975958/6b25bc3e-dc0a-11e6-8b0b-131b3c65e8f5.png)

**Comment by XiangruiCAI** [comment] 2017-01-16 08:48
I get a type error:

document.getElementsByTagName('webview')[0].style.width
VM754:1 Uncaught TypeError: Cannot read property 'style' of undefined
    at <anonymous>:1:44(anonymous function) @ VM754:1

**Comment by James-Yu** [comment] 2017-01-16 08:49
Should open preview panel first then try that. If problem still exists, it's a vscode problem for sure.

**Comment by XiangruiCAI** [comment] 2017-01-16 08:51
Yes! Both are 100%. Thanks for your help. Now waiting for vscode update.

**Comment by James-Yu** [comment] 2017-01-16 08:54
My guess is that your installation/chromium setting is tampered. I and some others never encountered this problem.

I will temporarily close this issue. If the problem still exists in following versions of vscode or anyone else can reproduce it, I will reopen this issue.

**Closed by James-Yu** 2017-01-16 08:54 UTC
Labels: bug, cannot reproduce
