### ISSUE TITLE
Hover equation preview fails with confusing error

### ISSUE THREAD

**Issue by danmackinlay** [James-Yu/LaTeX-Workshop#1801] opened 2019-11-12 17:52 UTC
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**
I understand there is a hover equation preview feature. I have never witnessed this working on my computer, but I do see errors in the logs when I hover over an equation. Unfortunately the error is not helpful in diagnosing the problem.
I am sure the error is due to some problem in my system or configuration, of course! However, I cannot work out what it would be.

**To Reproduce**
1. create a minimal document, such as the following

```latex
\documentclass{article}

\title{Topics in stochastic processes}
\author{Daniel MacKinlay}
\date{2019}


\begin{document}

\maketitle

\[x\]

\end{document}
```
2. Mouse over the `\[x\]`

**Expected behavior**
A hover should appear showing the letter `x` typeset as a display math equation

**Actual behavior**
No hover appears. errors appear in the extension host logs

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>
n/a
</details>

<details>
<summary>Developer Tools Console [Required]</summary>
[Extension Host] Error when JSON.parse theme files.
console.ts:137 [Extension Host] Unexpected token ] in JSON at position 3948
console.ts:137 [Extension Host] TeX parse error: Extra close brace or missing open brace
t.log @ console.ts:137
log.ts:196   ERR TeX parse error: Extra close brace or missing open brace
</details>

<details>
<summary>Extention host log</summary>
[2019-11-12 18:43:59.757] [exthost] [error] [James-Yu.latex-workshop] provider FAILED
[2019-11-12 18:43:59.757] [exthost] [error] ["TeX parse error: Extra close brace or missing open brace"]
</details>

**Desktop [Required]:**
 - OS: Ubuntu 18.04
 - VS Code version:1.40.0
 - Extension version: 8.3.1

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Additional context**

**Comment by jlelong** [comment] 2019-11-12 18:20
I cannot reproduce the error with your small example. You need to hover on the opening `\[`.

**Comment by danmackinlay** [comment] 2019-11-12 18:26
Yes, I doubt you can reproduce this; it must surely be something about my machine, or someone else woudl alread have noticed shipping a broken feature.

However my point is that the error gives me no clue where to look in my machine fo this broken configuration. I cannot see a LaTeX hover and I have never seen a latex hover on any document on this computer. I have, to be clear, moused over everything I can imagine, and done my best to imitate the instructional ![](https://raw.githubusercontent.com/James-Yu/LaTeX-Workshop/master/demo_media/hover.gif) on the [help wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#previewing-equations), and played with settings such as  `latex-workshop.hover.preview.enabled` that the `TeX parse error` log entries do not appear, or is that a spurious correlation?

Am I correct that on a machine which is in fact able to preview latex math in a hover that the

**Comment by jlelong** [comment] 2019-11-12 19:16
The message `TeX parse error` is issued by mathjax not being able to render your equation. This can come from a syntax error in your equation or most probably from the definitions of your preamble (`\newcommands` and companions).

**Comment by danmackinlay** [comment] 2019-11-12 19:24
Interesting. I assumed that must be the case from my original document, which does have a preamble. This MWE however, obviously does not have a preamble.

Note that both this example and my original longer example compile fine from the command line so this is presumably something special about the settings of latex-workshop, right? Perhaps it would be useful for latex-workshop to dump the string that could not be parsed in this context So that the source of this error could be identified.

**Comment by jlelong** [comment] 2019-11-12 21:09
> Note that both this example and my original longer example compile fine from the command line so this is presumably something special about the settings of latex-workshop, right? Perhaps it would be useful for latex-workshop to dump the string that could not be parsed in this context So that the source of this error could be identified.

No, this is not LW being stuck while parsing but instead that `mathjax` does not understand your new definitions, see [`latex-workshop.hover.preview.newcommand.parseTeXFile.enabled`](https://github.com/James-Yu/LaTeX-Workshop/wiki/Hover#latex-workshophoverpreviewnewcommandparseTeXFileenabled).

Can you post an example of a file triggering this TeX parse error?

**Comment by tamuratak** [comment] 2019-11-12 21:56
Please show us log messages. 

![2018-11-07 20 34 24](https://user-images.githubusercontent.com/10665499/48129417-c4565c80-e2cc-11e8-89de-05b36ef1fa76.png)

**Comment by danmackinlay** [comment] 2019-11-13 06:07
Hi @tamuratak 

The LaTeX-Workshop extension log from fresh restart:


<details><summary>LaTeX Workshop Extension log complete</summary>[07:01:36] Initializing LaTeX Workshop.
[07:01:36] Creating LaTeX Workshop http and websocket server.
[07:01:36] LaTeX Workshop initialized.
[07:01:38] Found root file from active editor: /media/dan/SchnittPunkt/Source/thesis/test.tex
[07:01:38] Root file changed from: undefined to /media/dan/SchnittPunkt/Source/thesis/test.tex. Find all dependencies.
[07:01:38] Instantiating a new file watcher for /media/dan/SchnittPunkt/Source/thesis/test.tex
[07:01:38] Creating file watcher for .bib files.
[07:01:38] Parsing /media/dan/SchnittPunkt/Source/thesis/test.tex
[07:01:38] Server created on 127.0.0.1:36173
[07:01:38] Adding /media/dan/SchnittPunkt/Source/thesis/test.tex to file watcher.
[07:01:38] LaTeX Workshop version: 8.3.1
[07:01:38] Snippet data loaded.
[07:01:47] LOG command invoked.
[07:03:08] Found root file from active editor: /media/dan/SchnittPunkt/Source/thesis/test.tex
[07:03:08] Root file remains unchanged from: /media/dan/SchnittPunkt/Source/thesis/test.tex.
[07:03:36] Found root file from parent: /media/dan/SchnittPunkt/Source/thesis/thesis.tex
[07:03:36] Found root file from parent: /media/dan/SchnittPunkt/Source/thesis/thesis.tex
[07:03:36] Root file changed from: /media/dan/SchnittPunkt/Source/thesis/test.tex to /media/dan/SchnittPunkt/Source/thesis/thesis.tex. Find all dependencies.
[07:03:36] Root file changed -> cleaning up old file watcher.
[07:03:36] Instantiating a new file watcher for /media/dan/SchnittPunkt/Source/thesis/thesis.tex
[07:03:36] Parsing /media/dan/SchnittPunkt/Source/thesis/thesis.tex
[07:03:36] Parsing /media/dan/SchnittPunkt/Source/thesis/_macros_latex.tex
[07:03:36] Parsing /media/dan/SchnittPunkt/Source/thesis/011-split-chap-background.tex
[07:03:36] Parsing /media/dan/SchnittPunkt/Source/thesis/012-split-chap-qm.tex
[07:03:36] Parsing /media/dan/SchnittPunkt/Source/thesis/013-split-chap-problems.tex
[07:03:36] Parsing /media/dan/SchnittPunkt/Source/thesis/014-split-chap-prune.tex
[07:03:36] Parsing /media/dan/SchnittPunkt/Source/thesis/015-split-chap-conclusion.tex
[07:03:36] Found .bib file /media/dan/SchnittPunkt/Source/thesis/bib/thesis.bib
[07:03:36] Adding .bib file /media/dan/SchnittPunkt/Source/thesis/bib/thesis.bib to bib file watcher.
[07:03:36] Parsing .bib entries from /media/dan/SchnittPunkt/Source/thesis/bib/thesis.bib
[07:03:37] Parsed 317 bib entries from /media/dan/SchnittPunkt/Source/thesis/bib/thesis.bib.
[07:03:37] Root file remains unchanged from: /media/dan/SchnittPunkt/Source/thesis/thesis.tex.
[07:03:37] Adding /media/dan/SchnittPunkt/Source/thesis/thesis.tex to file watcher.
[07:03:37] Adding /media/dan/SchnittPunkt/Source/thesis/_macros_latex.tex to file watcher.
[07:03:37] Adding /media/dan/SchnittPunkt/Source/thesis/011-split-chap-background.tex to file watcher.
[07:03:37] Adding /media/dan/SchnittPunkt/Source/thesis/012-split-chap-qm.tex to file watcher.
[07:03:37] Adding /media/dan/SchnittPunkt/Source/thesis/013-split-chap-problems.tex to file watcher.
[07:03:37] Adding /media/dan/SchnittPunkt/Source/thesis/014-split-chap-prune.tex to file watcher.
[07:03:37] Adding /media/dan/SchnittPunkt/Source/thesis/015-split-chap-conclusion.tex to file watcher.
[07:03:39] Found root file from active editor: /media/dan/SchnittPunkt/Source/thesis/test.tex
[07:03:39] Root file changed from: /media/dan/SchnittPunkt/Source/thesis/thesis.tex to /media/dan/SchnittPunkt/Source/thesis/test.tex. Find all dependencies.
[07:03:39] Root file changed -> cleaning up old file watcher.
[07:03:39] Instantiating a new file watcher for /media/dan/SchnittPunkt/Source/thesis/test.tex
[07:03:39] Parsing /media/dan/SchnittPunkt/Source/thesis/test.tex
[07:03:39] Adding /media/dan/SchnittPunkt/Source/thesis/test.tex to file watcher.
[07:03:43] Found root file from active editor: /media/dan/SchnittPunkt/Source/thesis/test.tex
[07:03:43] Root file remains unchanged from: /media/dan/SchnittPunkt/Source/thesis/test.tex.
[07:03:48] LOG command invoked.
[07:03:50] LOG command invoked.
[07:03:50] Found root file from active editor: /media/dan/SchnittPunkt/Source/thesis/test.tex
[07:03:50] Root file remains unchanged from: /media/dan/SchnittPunkt/Source/thesis/test.tex.
[07:04:05] Found root file from active editor: /media/dan/SchnittPunkt/Source/thesis/test.tex
[07:04:05] Root file remains unchanged from: /media/dan/SchnittPunkt/Source/thesis/test.tex.
</details>

**Comment by jlelong** [comment] 2019-11-13 06:13
Everything looks fine in your logs. What is the value of your configuration variable `latex-workshop.hover.preview.enabled`?

**Comment by tamuratak** [comment] 2019-11-13 06:26
It does not look fine to me. Lots of unrelated TeX files are being parsed when we are discussing about a simple example.

@danmackinlay, please create an empty directory outside `/media/dan/SchnittPunkt/Source/thesis/`, then test this extension with your `test.tex`.

**Comment by danmackinlay** [comment] 2019-11-14 16:59
OK, Thanks @tamuratak and @jlelong this is very helpful.

Indeed if I create a completely new project and create math markup in that, I can indeed get equation preview, and I do get less files in my log.

<details>
<summary>latex-workshop-log</summary>
[17:46:13] Initializing LaTeX Workshop.
[17:46:13] Creating LaTeX Workshop http and websocket server.
[17:46:13] LaTeX Workshop initialized.
[17:46:14] Found root file from active editor: /media/dan/SchnittPunkt/Source/lwtest/test.tex
[17:46:14] Root file changed from: undefined to /media/dan/SchnittPunkt/Source/lwtest/test.tex. Find all dependencies.
[17:46:14] Instantiating a new file watcher for /media/dan/SchnittPunkt/Source/lwtest/test.tex
[17:46:14] Creating file watcher for .bib files.
[17:46:14] Parsing /media/dan/SchnittPunkt/Source/lwtest/test.tex
[17:46:14] Server created on 127.0.0.1:46439
[17:46:14] Adding /media/dan/SchnittPunkt/Source/lwtest/test.tex to file watcher.
[17:46:14] Snippet data loaded.
[17:46:14] LaTeX Workshop version: 8.3.1
[17:47:52] Found root file from active editor: /media/dan/SchnittPunkt/Source/lwtest/test.tex
[17:47:52] Root file remains unchanged from: /media/dan/SchnittPunkt/Source/lwtest/test.tex.
[17:47:56] LOG command invoked.
</details>

Interestingly I *do* still get JSON parse errors in the developer console when I mouseover an equation

```
[Extension Host] Error when JSON.parse theme files.
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:250
[Extension Host] Unexpected token ] in JSON at position 3948
```

So I guess that error must be... expected behaviour? I will ignore the developer log I suppose.

It seems then that I have not in fact produced an MWE. I suppose I must begin the long slow journe of working out what is a true MWE...

**Comment by jlelong** [comment] 2019-11-14 19:27
The `JSON.parse` error is related to your theme, which is not considered as a valid JSON file by the `JSON.parse` function. The syntax error in the `.json` file is

    Unexpected token ] in JSON at position 3948

**Comment by jlelong** [comment] 2019-11-14 19:31
As the issue seems solved, I close this issue. Feel free to open a new one in case you can make a MWE. Note that with the recent changes on preview, it should be more robust in the next release.

**Closed by jlelong** 2019-11-14 19:31 UTC
Labels: can't reproduce, need more info

**Comment by trevorgunn** [comment] 2019-11-14 19:41
@jlelong So you know, the phrase to use in English is "I am closing this issue." I know in French both translate to "je ferme" so it can be hard for native French speakers to know which tense to use in English.

**Comment by danmackinlay** [comment] 2019-11-15 17:29
Yes, although I have no longer an MWE I still feel there is an outstanding problem, that the errors are not informative. It will take a long time to create an MWE with no clues about the actual source of the bug!

**Comment by danmackinlay** [comment] 2019-11-22 12:23
I have an MWE.

I note here for future reference, the lack of error was due to the extension host eventually hanging for some presumably unrelated reason to do with the build process. I managed to fix that by fixing some font errors in the latex file.

Here is an MWE

```latex
\documentclass{article}

\title{Topics in stochastic processes}
\author{Daniel MacKinlay}
\date{2019}

\usepackage[hidelinks]{hyperref}
\renewcommand{\hyperref}[2][???]{\autoref{#1}}

\begin{document}

\maketitle


\[x=3\]

\end{document}
```

The resulting error is 

```text
[13:18:07] Error when MathJax is rendering 
\renewcommand{\hyperref}[2][???]{\autoref{#1}}x=3{\color{#ffffff}\!|\!}
```

This `\renewcommand{\hyperref}[2][???]{\autoref{#1}}` thing is the standard output from RMarkdown.

**Comment by danmackinlay** [comment] 2019-11-22 14:33
AIEEE, wait sorry cancel that. :disappointed:  this "MWE" does not reproduce the problem if I quit VS code and restart it. I guess the problematic macro definition is bleeding through from some other document. :man_shrugging:  We can leave this issue closed.

**Comment by drthegirlfriend** [comment] 2021-12-15 11:34
This is somewhat old, but using Latex-workshop now still has broken previews, and took me some time to find the culprit, but defining this in my preample caused previews to be broken:

\def\dunderline#1{\underline{\underline{#1}}}

So if you have something similar in yours, this may be the problem.
