### ISSUE TITLE
Can not view PDF on the fly after upgrade

### ISSUE THREAD

**Issue by my1347** [James-Yu/LaTeX-Workshop#491] opened 2018-03-25 08:57 UTC
### Description

Click the PDF button on the top right, a New safari window is automaticly open to present the PDF fiel, rather than view the PDF inside VS editor as it used to be.

**Comment by James-Yu** [comment] 2018-03-25 08:58
Duplicate of #482

**Closed by James-Yu** 2018-03-25 08:58 UTC
