### ISSUE TITLE
Getting focus to the PDF viewer requires to double click on the tab name

### ISSUE THREAD

**Issue by PierreMarchand20** [James-Yu/LaTeX-Workshop#1481] opened 2019-07-05 21:45 UTC
**Describe the bug [Required]**
I used to do `cmd+F` to search for words in the PDF viewer. Also trying to change the page number does not work. Writing in the PDF viewer just does not work. And I need to click on the name of the pane to focus on the PDF viewer and not just the PDF. It seems that it worked before so I feel it is a bug, may be it was introduced by the last update of VSCode ?

**To Reproduce**
1. Click on the PDF viewer and try to change the page number or search for a word

**Expected behavior**
When I write something (a page number or a word to search), it should be written in the pane of the pdf viewer. And I should be able to focus easily on the pdf viewer.

**Logs [Required]**
Nothing appears in the output pane or the developer tools.

**Desktop [Required]:**
 - OS: macOS 10.14.5
 - VS Code version: 1.36.0 
 - Extension version: 7.0.2

**Additional context**

**Comment by jlelong** [comment] 2019-07-06 04:43
I guess the real issue is that clicking in the PDF viewer does not give it the focus. Instead you have to click on the tab name (sometimes twice) to give it the focus. Once it has the focus, everything works as before.
This is probably related to VSCode 1.36 update.

**Comment by PierreMarchand20** [comment] 2019-07-06 08:47
Even with the right focus, I cannot write anything (change of number, writing word in search bar) and `cmd+f` does not work. I wanted to show you, but it actually works with the screencast mode -_-

**Comment by jlelong** [comment] 2019-07-06 11:48
This is exactly that!

**Comment by PierreMarchand20** [comment] 2019-07-06 15:34
It is just the PDF viewer, it is not part of this extension ?

**Comment by jlelong** [comment] 2019-07-06 17:28
The PDF viewer is a `WebViewPanel` showing the content returned by `pdf.js`. I bet that vscode 1.36 update has changed the way `WebViewPanels` get the focus. If anyone knows an other extension using `WebViewPanel`, it would be worth trying if they suffer from the same issue.

**Comment by jlelong** [comment] 2019-07-06 20:55
Humm, `markdown` uses `WebViewPanel` for preview and they do not seem to have the issue.
@James-Yu @tamuratak  I have never dug into the PDF viewer, do you have any idea of what is happening?

**Comment by tamuratak** [comment] 2019-07-07 01:03
I think the difference comes from that we use iframe in `WebViewPanel`. We should call [focus](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) during the initialization of pdf viewer. 

VS Code 1.36 has [upgraded](https://github.com/microsoft/vscode/blob/1.36.0/.yarnrc) the version of its using electron from 3 to 4. That is the cause.

**Comment by jlelong** [comment] 2019-07-07 06:31
@tamuratak could you make a PR to try and solve this issue?

**Comment by tamuratak** [comment] 2019-07-07 07:27
We already call `focus`. See [link](https://github.com/James-Yu/LaTeX-Workshop/blob/master/src/components/viewer.ts#L142). So, I was wrong.

**Comment by jlelong** [comment] 2019-07-07 13:58
The issue seems to be that clicking in the PDF viewer does not give it the focus (ie make it the `activeTextEditor`). Could it be related to #1406?

**Comment by tamuratak** [comment] 2019-07-08 01:34
I will look into it. It will take a while.

**Comment by tamuratak** [comment] 2019-07-08 10:21
Reported microsoft/vscode/issues/76863.

**Comment by Hirse** [comment] 2019-07-09 22:46
My extension is opening an `iframe` in the Webview too and I am having the same problem:
https://github.com/Hirse/vscode-ungit/issues/79

**Comment by david-waterworth** [comment] 2019-07-14 04:39
Not sure if this is related but I'm seeing other annoyances with the PDF panel since updating to 1.36.1

If I try and resize, releasing the mouse button doesn't stop the resize - the splitter gets stuck to the mouse pointer and I have to click again to release it.

**Comment by tamuratak** [comment] 2019-07-14 05:40
Already reported microsoft/vscode/issues/76866. It will be fixed in the next release of VS Code.

**Comment by ivankravets** [comment] 2019-07-23 20:53
Ping @mjbvz

**Comment by tamuratak** [comment] 2019-07-23 22:29
The focus problem still persists. Tracked in microsoft/vscode/issues/76863.

**Comment by romulogcerqueira** [comment] 2019-09-21 13:57
Up

**Comment by jlelong** [comment] 2019-11-20 09:44
The issue has been fixed in Chromium. We are waiting for the patch to be included in Electron, see electron/electron#21219

**Comment by jlelong** [comment] 2019-11-21 10:12
The fix has been merged into Electron and is on its way to vscode. I guess we can close this issue.

**Closed by jlelong** 2019-11-21 10:12 UTC
Labels: vscode-issue
