### ISSUE TITLE
wrong parenthesis at autocomplete

### ISSUE THREAD

**Issue by 7be** [James-Yu/LaTeX-Workshop#1852] opened 2019-12-03 11:37 UTC
### Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Hi all,

while using the latex extension, which in my opinion includes Intellisense I have an autocomplete probleme:
typing \todo it autocompletes \todo{}{} which makes no sense.
correct would be \todo[]{}. I found no way to customize it.
My favority would be to have it autocomplete to \todo[inline]{}.
Is there a file, where I can change the suggestions?
Thanks

### To Reproduce

1. Go to random .tex file
2. Click on : type \tod
3. See error

### Expected behavior
to produce \todo[]{}

## Logs [Required]
no log for this issue

### LaTeX Workshop Output [Required]
not necessary here

### Developer Tools Console [Required]

not necessary here

## Desktop [Required]
OS version: Windows_NT x64 10.0.18362
 - VS Code version:  Code 1.40.2 (f359dd6, 2019-11-25T14:54:45.096Z)
 - Extension version:Version: 8.4.2

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 5.0.0]

**Comment by jlelong** [comment] 2019-12-03 12:55
I cannot reproduce the issue. Please post a minimal working example.

**Comment by jlelong** [comment] 2019-12-06 08:08
The issue does not contain enough information to investigate the problem. I am closing it until more information is provided.

**Closed by jlelong** 2019-12-06 08:08 UTC
Labels: can't reproduce, need more info
