### ISSUE TITLE
Add single-page view option to the PDF preview

### ISSUE THREAD

**Issue by nicola-gigante** [James-Yu/LaTeX-Workshop#2060] opened 2020-04-30 06:28 UTC
When making Beamer presentations, the most useful way to show the PDF preview is the single-page mode, because that is how the PDF will be shown during the presentation, and, among other things, it allows to test Beamer overlay transitions. 

However, the built-in previewer does not offer such an option, among the available ones (vertical scroll, horizontal scroll, etc..).

It would be very useful if the PDF viewer would support a single-page viewing mode which is essential when making Beamer presentations.

**Comment by tamuratak** [comment] 2020-04-30 06:32
Duplicate of #1789

**Closed by tamuratak** 2020-04-30 06:32 UTC
Labels: feature-request
