### ISSUE TITLE
chktex: some warnings do not appear anymore

### ISSUE THREAD

**Issue by PierreMarchand20** [James-Yu/LaTeX-Workshop#1444] opened 2019-06-17 13:11 UTC
**Describe the bug [Required]**
Some warnings from chtex do not appear anymore. For example 
 ```
figure \ref{some_fig}
```
should produce a warning (it should suggest to add a non-breaking space, see p13 of [documentation](https://www.nongnu.org/chktex/ChkTeX.pdf) of chktex), and it used to but I do not see it anymore. It is not a problem from chktex because it works as expected with the command line. What is strange is that some warnings do appear (I have warning 41 and 26 for example)

**To Reproduce**
1. Try the previous example or something like `foo \cite{bar}`

**Expected behavior**
There should be more warnings appearing 

**Screenshots**
![image](https://user-images.githubusercontent.com/15056323/59606659-00c72200-9112-11e9-813f-48835d0dd7a6.png)

**Desktop [Required]:**
 - OS: macOS 10.14.5
 - VS Code version: 1.35.1
 - Extension version: 1.35.1

**Comment by PierreMarchand20** [comment] 2019-06-17 13:52
Another warning that disappeared is the one suggesting using `\( \)` instead of `$ $`

**Comment by jlelong** [comment] 2019-06-17 15:43
I cannot reproduce the issue with non-breaking space using either `figure \ref{some_fig}` or `foo \cite{bar}`.

I do confirm that `chktex` launched from the command line does not raise any warning with `$...$` in the following example

````
\documentclass{article}
\begin{document}
  figure \ref{some_fig} 

  $ 1 +2 = \alpha $

  Some text
\end{document}
````

**Comment by PierreMarchand20** [comment] 2019-06-18 09:01
You are right... the above example works also for me. And even stranger, chktex in command line does not raise any issue with `$$`. But I have this warning in VS Code
![image](https://user-images.githubusercontent.com/15056323/59667294-c1064600-91b6-11e9-86e6-2bf14e508548.png)

But if I copy paste it in my document (my thesis) where I noticed this issue, I get nothing
![image](https://user-images.githubusercontent.com/15056323/59667333-d7ac9d00-91b6-11e9-832b-9f3c4992bd49.png)

More precisely, if I copy paste it in my `main.tex`, it works
![image](https://user-images.githubusercontent.com/15056323/59667517-2d814500-91b7-11e9-8569-379c36403f24.png)

But if I copy paste it in `bem.tex` (included in my main document as you can see in the above figure)
![image](https://user-images.githubusercontent.com/15056323/59667623-56093f00-91b7-11e9-8492-9dd2c78c6262.png)
it does not work... But wait, I also tried in another document (an article), and then it worked everywhere...

**Comment by PierreMarchand20** [comment] 2019-06-18 09:02
Ok I found it! it was tricky, it happens there is a file and a repo with the same name.

**Comment by PierreMarchand20** [comment] 2019-06-18 09:05
MWE:
`main.tex`:
```
%!TEX encoding =UTF-8 Unicode

\documentclass{article}
% \documentclass[mainlanguage=english,localtocs,output=screen,version=inprogress,fncychap=Sonny]{yathesis}

\begin{document}

% Premier chapitre
\include{chapter1}

\end{document}
```

`chapter1.tex`
```
% !TEX root = main.tex

figure \ref{some_fig} 

$ 1 +2 = \alpha $

Some texts
```
and create a folder named `chapter1`

**Comment by jlelong** [comment] 2019-06-18 12:25
All this is quite odd but I do not think this related to the extension. So I close this issue. Feel free to reopen if you have some extra information.

**Closed by jlelong** 2019-06-18 12:25 UTC
Labels: can't reproduce

**Comment by PierreMarchand20** [comment] 2019-06-18 12:33
Don't you think it is just the way the extension use chktex ? The way you get the filename and call chktex ?

**Comment by jlelong** [comment] 2019-06-18 12:40
It could but I doubt about it. We have not changed anything on this and from my tests, the results obtained inside the extension are coherent with the command line.

**Comment by PierreMarchand20** [comment] 2019-06-18 12:41
Did you try the MWE ?

**Comment by jlelong** [comment] 2019-06-18 12:48
Yes. Here are my results with the MWE. I always have the same from LW and from the command line.

1. When I do not create the `chapter1` folder.
````
ChkTeX v1.7.6 - Copyright 1995-96 Jens T. Berger Thielemann.
Compiled with POSIX extended regex support.
Warning 2 in chapter1.tex line 3: Non-breaking space (`~') should have been used.
figure \ref{some_fig}
      ^
No errors printed; One warning printed; No user suppressed warnings; No line suppressed warnings.
See the manual for how to suppress some or all of these warnings/errors.
````
1. With a `chapter1` folder, no warning.

**Comment by PierreMarchand20** [comment] 2019-06-18 13:03
Ah well ok, I had seen that. Then it is an issue from chktex, I will report the issue to them. Thank you !

**Comment by PierreMarchand20** [comment] 2019-06-18 13:51
Well, I retried with the MWE and it is not coherent:
![image](https://user-images.githubusercontent.com/15056323/59689702-697cd000-91e0-11e9-9bf7-a750b05fd6ce.png)
I have the warning in command line but not in VS Code. I also noticed that using `\include{chapter1.tex}` instead of `\include{chapter1}` solves the issue. But it seems that in practice, the latter should be used, see [here](https://tex.stackexchange.com/questions/319506/why-do-include-and-input-handle-extension-name-differently)

**Comment by PierreMarchand20** [comment] 2019-06-18 13:57
Concerning why the warning 46 shows up in VS Code (when it works), and not in command line, it is because it is not checked by default and LW calls chktex with the option `-wall` by default.

**Comment by PierreMarchand20** [comment] 2019-06-18 14:00
> > I have the warning in command line but not in VS Code. I also noticed that using
> 
> Can you tell me exactly what you get in the two cases (LW and command line)?

With command line, I got the warning (just one, as I explained in my previous message):
```
ChkTeX v1.7.6 - Copyright 1995-96 Jens T. Berger Thielemann.
Compiled with POSIX extended regex support.
Warning 2 in chapter1.tex line 3: Non-breaking space (`~') should have been used.
figure \ref{some_fig}   
      ^
No errors printed; One warning printed; No user suppressed warnings; No line suppressed warnings.
See the manual for how to suppress some or all of these warnings/errors.
```

with LW, nothing:
![image](https://user-images.githubusercontent.com/15056323/59690612-f3796880-91e1-11e9-8eac-55ed2fff8c04.png)

with LW, but changing \include{chapter1} to \include{chapter1.tex}, I get the warnings:
![image](https://user-images.githubusercontent.com/15056323/59690661-0b50ec80-91e2-11e9-8826-242c3848c167.png)
![image](https://user-images.githubusercontent.com/15056323/59690677-13a92780-91e2-11e9-9a7c-348688007e00.png)

**Comment by jlelong** [comment] 2019-06-18 15:21
So at the end of the day, everything is fine.

**Comment by PierreMarchand20** [comment] 2019-06-18 15:40
Well no, `\include` command should be called with filenames without the extension and it does not work.

**Comment by PierreMarchand20** [comment] 2019-06-18 21:42
Ok, I think I understood why we did not understand each other. When I called chktex, I called it directly on `chapter1.tex`, but it seems that in LW, you always call chktex on the root file (in my test, `lintRootFile` is always called). And in this case, LW is coherent with chktex, there seems to be an issue in chktex when a folder has the same name as a file.

Sorry for taking your time...
