### ISSUE TITLE
\input files associated wrong

### ISSUE THREAD

**Issue by felixlinker** [James-Yu/LaTeX-Workshop#1612] opened 2019-08-19 09:47 UTC
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Describe the bug [Required]**
I have a repository for my masters thesis which is structured likes this:
```
thesis/
|-- sections/
    |-- background.tex
    |-- introduction.tex
    |-- ...
|-- outline.tex
|-- thesis.tex
```

The outline is a standalone tex-document with no `\input` commands. The thesis tex-document only has some definitions and holds the document block that does nothing but list `\input` commands for all section files in the right order.

When build and/or preview the outline and/or thesis documents, everything works as expected.

However, when I build and/or preview one of the sections, the outline gets built and previewed. Furthermore, synctex from cursor does not work.

I started to experience this behavior just today after VS Code was updated to `1.37`. I last worked on this project last Friday where everything worked fine.

With build and preview I mean the commands called `latex-workshop.build` and `latex-workshop.view`.

**To Reproduce**
Should be obvious from issue description.

**Expected behavior**
`thesis.tex` should be built and previewed as opposed to `outline.tex`.

**Logs [Required]**

<details>
<summary>LaTeX Workshop Output [Required]</summary>

```
[11:33:24] Initializing LaTeX Workshop.
[11:33:24] Creating LaTeX Workshop http and websocket server.
[11:33:24] LaTeX Workshop initialized.
[11:33:25] Server created on 127.0.0.1:51932
[11:33:25] Snippet data loaded.
[11:33:25] BUILD command invoked.
[11:33:25] LaTeX Workshop version: 8.0.3
[11:33:26] Found root file from workspace: c:\Users\felix\git\secure-m\thesis\outline.tex
[11:33:26] Root file changed from: undefined. Find all dependencies.
[11:33:26] Instantiating a new file watcher for c:\Users\felix\git\secure-m\thesis\outline.tex
[11:33:26] Creating file watcher for .bib files.
[11:33:26] Parsing c:\Users\felix\git\secure-m\thesis\outline.tex
[11:33:26] Found .bib file c:\Users\felix\git\secure-m\thesis\references.bib
[11:33:26] Adding .bib file c:\Users\felix\git\secure-m\thesis\references.bib to bib file watcher.
[11:33:26] Parsing .bib entries from c:\Users\felix\git\secure-m\thesis\references.bib
[11:33:26] Parsed 10 bib entries from c:\Users\felix\git\secure-m\thesis\references.bib.
[11:33:26] Building root file: c:\Users\felix\git\secure-m\thesis\outline.tex
[11:33:26] Adding c:\Users\felix\git\secure-m\thesis\outline.tex to file watcher.
[11:33:26] Found root file from workspace: c:\Users\felix\git\secure-m\thesis\outline.tex
[11:33:26] Root file remains unchanged from: c:\Users\felix\git\secure-m\thesis\outline.tex.
[11:33:26] Build root file c:\Users\felix\git\secure-m\thesis\outline.tex
[11:33:26] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=c:/Users/felix/git/secure-m/thesis,c:/Users/felix/git/secure-m/thesis/outline
[11:33:26] LaTeX build process spawned. PID: 392.
[11:33:27] Recipe of length 1 finished. PID: 392.
[11:33:27] Successfully built c:\Users\felix\git\secure-m\thesis\outline.tex.
[11:33:28] VIEW command invoked.
[11:33:28] Found root file from workspace: c:\Users\felix\git\secure-m\thesis\outline.tex
[11:33:28] Root file remains unchanged from: c:\Users\felix\git\secure-m\thesis\outline.tex.
[11:33:28] Serving PDF file at http://localhost:51932/viewer.html?file=pdf..YyUzQSU1Q1VzZXJzJTVDZmVsaXglNUNnaXQlNUNzZWN1cmUtbSU1Q3RoZXNpcyU1Q291dGxpbmUucGRm
[11:33:28] The encoded path is c:\Users\felix\git\secure-m\thesis\outline.pdf
[11:33:28] Open PDF tab for c:\Users\felix\git\secure-m\thesis\outline.pdf
[11:33:29] Preview PDF file: c:\Users\felix\git\secure-m\thesis\outline.pdf
[11:33:29] Handle data type: open
[11:33:29] Handle data type: loaded
[11:42:32] BUILD command invoked.
[11:42:32] Found root file from workspace: c:\Users\felix\git\secure-m\thesis\outline.tex
[11:42:32] Root file remains unchanged from: c:\Users\felix\git\secure-m\thesis\outline.tex.
[11:42:32] Building root file: c:\Users\felix\git\secure-m\thesis\outline.tex
[11:42:32] Build root file c:\Users\felix\git\secure-m\thesis\outline.tex
[11:42:32] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=c:/Users/felix/git/secure-m/thesis,c:/Users/felix/git/secure-m/thesis/outline
[11:42:32] LaTeX build process spawned. PID: 7040.
[11:42:33] Recipe of length 1 finished. PID: 7040.
[11:42:33] Successfully built c:\Users\felix\git\secure-m\thesis\outline.tex.
[11:42:37] Handle data type: close
[11:42:39] VIEW command invoked.
[11:42:39] Found root file from workspace: c:\Users\felix\git\secure-m\thesis\outline.tex
[11:42:39] Root file remains unchanged from: c:\Users\felix\git\secure-m\thesis\outline.tex.
[11:42:39] Serving PDF file at http://localhost:51932/viewer.html?file=pdf..YyUzQSU1Q1VzZXJzJTVDZmVsaXglNUNnaXQlNUNzZWN1cmUtbSU1Q3RoZXNpcyU1Q291dGxpbmUucGRm
[11:42:39] The encoded path is c:\Users\felix\git\secure-m\thesis\outline.pdf
[11:42:39] Open PDF tab for c:\Users\felix\git\secure-m\thesis\outline.pdf
[11:42:41] Handle data type: open
[11:42:41] Preview PDF file: c:\Users\felix\git\secure-m\thesis\outline.pdf
[11:42:41] Handle data type: loaded
```

</details>

<details>
<summary>Developer Tools Console [Required]</summary>

![image](https://user-images.githubusercontent.com/9728715/63255899-da8b4300-c276-11e9-8716-0a9cc73d759e.png)

</details>

**Screenshots**
N/A

**Desktop [Required]:**
 - OS: Windows 10
 - VS Code version: 1.37
 - Extension version: 8.0.3

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Additional context**
If you want to use the exact same files, find them in this repository: https://github.com/felixlinker/ifc-rv-thesis

**Comment by James-Yu** [comment] 2019-08-19 09:49
Use `%!TEX root` to define the root file. Otherwise the extension does not know which one is correct and just pick a random one.

**Comment by jlelong** [comment] 2019-08-19 12:10
Hum, this sounds like a regression. From the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects)

> Root directory check LaTeX Workshop iterates through all .tex files in the root folder of the workspace. The first one containing \begin{document} and which includes the file in the active editor is set as the root file.

As  only `thesis.tex` includes the section files, it should be set as the root file.

I took @felixlinker's repo and I played a bit. The root file seems to be properly detected at least when building/previewing. However, the logs are weird as they do not show any change in the root file when switching from  `outline.tex` to `introduction.tex` (or any other included file), but triggering build confirms that the root file is correct. I think the logs should reflect any change in the root file.
1. Open folder `thesis`
1. Open `

**Comment by James-Yu** [comment] 2019-08-20 02:19
That is interesting. How root file is identified is not changed in all these commits, and I suspect this might be a mistake either in the wiki or in the previous implementation. Anyways as it is claimed, I will try implement this feature.

**Comment by James-Yu** [comment] 2019-08-20 03:13
There is a small issue with this commit. You need to at least open the correct root file once for the extension to register the project structure. Otherwise the root will fallback to workspace file. I cannot have this problem fixed due to the limit of root-finding and sub-file-parsing logic, yet I consider it not a very big issue.

**Comment by James-Yu** [comment] 2019-08-20 03:20
Edit: actually can be solved, but at the cost of longer startup time. Committed.

**Comment by jlelong** [comment] 2019-08-20 18:54
Maybe, I did not make my point precise. I do confirm that prior to release 8, the root file was detected as explained in the wiki. Let us take the following steps in release 7.3.0

1. Open the `thesis` directory in vscode
1. Open `outline.tex`, the logs say : ` Found root file from active editor: XXXXXXX/tests/thesis/outline.tex`
1. Open `introduction.tex`, the logs say `Try root file in root directory: XXXXXXX/tests/thesis/thesis.tex` and then `Found root file in root directory: XXXXXX/tests/thesis-1612/thesis.tex`.

`Git diff v7.3.0..master` yields the following change 

````
@@ -312,16 +328,6 @@ export async function activate(context: vscode.ExtensionContext) {
         }

         if (e && extension.manager.hasTexId(e.document.languageId)) {
-            if (extension.manager.fileWatcher && extension.manager.filesWatched.indexOf(e.document.fileName) < 0) {
-                const previousRoot = extension.manager.rootFile
-                extension.manager.findRoot().then(rootFile => {
-                    if (rootFile === undefined || rootFile === previousRoot) {
-                        return
-                    }
-                    extension.structureProvider.refresh()
-                    extension.structureProvider.update()
-                })
-            }
             extension.linter.lintActiveFileIfEnabled()
         } else {
             isLaTeXActive = false
````
which is responsible for the current issue and maybe others (in particular the issues related to completion). So, there is no need of commit  b9fd03b.

**Comment by jlelong** [comment] 2019-08-20 20:45
There is also an other issue. Revert b9fd03b and open `introduction.tex`, the logs say
````
[22:40:11] Initializing LaTeX Workshop.
[22:40:11] Creating LaTeX Workshop http and websocket server.
[22:40:11] LaTeX Workshop initialized.
[22:40:11] Guess project structure without root file.
[22:40:11] Linter for root file started.
[22:40:11] No root file found for linting.
[22:40:13] Server created on 127.0.0.1:49416
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/thesis.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/introduction.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/background.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/risc-v.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/model.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/checking.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/results.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/conclusion.tex
[22:40:13] Found .bib file /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/references.bib
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/outline.tex
[22:40:13] Found .bib file /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/references.bib
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/model.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/background.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/conclusion.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/results.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/introduction.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/risc-v.tex
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/checking.tex
[22:40:13] Snippet data loaded.
[22:40:13] LaTeX Workshop version: 8.0.4
[22:40:13] Found root file from workspace: /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/thesis.tex
[22:40:13] Root file changed from: undefined. Find all dependencies.
[22:40:13] Instantiating a new file watcher for /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/thesis.tex
[22:40:13] Creating file watcher for .bib files.
[22:40:13] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/thesis.tex
[22:40:13] Found .bib file /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/references.bib
[22:40:13] Adding .bib file /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/references.bib to bib file watcher.
[22:40:13] Parsing .bib entries from /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/references.bib
[22:40:13] Parsed 10 bib entries from /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/references.bib.
[22:40:13] Re-parse project structure with root file set.
[22:40:13] Adding /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/thesis.tex to file watcher.
[22:40:14] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/outline.tex
[22:40:14] Found .bib file /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/references.bib
[22:40:14] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/model.tex
[22:40:14] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/background.tex
[22:40:14] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/conclusion.tex
[22:40:14] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/results.tex
[22:40:14] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/introduction.tex
[22:40:14] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/risc-v.tex
[22:40:14] Parsing /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/checking.tex
[22:40:14] Adding /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/outline.tex to file watcher.
[22:40:14] Adding /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/model.tex to file watcher.
[22:40:14] Adding /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/background.tex to file watcher.
[22:40:14] Adding /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/conclusion.tex to file watcher.
[22:40:14] Adding /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/results.tex to file watcher.
[22:40:14] Adding /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/introduction.tex to file watcher.
[22:40:14] Adding /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/risc-v.tex to file watcher.
[22:40:14] Adding /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/sections/checking.tex to file watcher.
[22:40:14] Found root file from workspace: /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/thesis.tex
[22:40:14] Root file remains unchanged from: /Users/jl/devel/LaTeX-Workshop/tests/thesis-1612/thesis.tex.
````
In particular, you can see that `outline.tex`  is added to the file watcher whereas it is not included in the LaTeX project with root file `thesis.tex`. I think that these issues with setting the correct root file and watched files may be responsible for other issues too.

**Comment by James-Yu** [comment] 2019-08-21 09:29
I get your idea and come up with a neat solution. Will implement shortly (maybe by tmr?).

**Closed** 2019-08-21 12:28 UTC
Labels: bug
