### ISSUE TITLE
In case of nested .tex files all log entries refer to main .tex file under MS Win/MikTeX

### ISSUE THREAD

**Issue by black-snake** [James-Yu/LaTeX-Workshop#274] opened 2017-09-14 10:18 UTC
### Description

First of all, great job on this VS Code extension - pretty cool!

I have a nested structure for my .tex files, meaning that I have a main.tex that includes other .tex files via `\input{...}`-command, where the folder structure is as follows (no subfolders or anything like that):
```
- main.tex
- chapter1.tex
- ...
```

When I build my latex document under MS Win 10 with MikTeX installed, I just see all warnings, errors, and infos under the main.tex section in the although many of the messages come from another .tex file (e. g. chapter1.tex). When I click on any message, the cursor is always set to a position in main.tex but not in the correct .tex file, like chapter1.tex for example.

When I build my latex document under MacOS with TeX live, warnings, errors and infos are clearly indicated for the actual .tex file in which they occur. When I click on a message, the cursor is always set to the correct position in the correct .tex file.

The latex toolchain is exactly the same under both OS and both have the latest VS Code and the latest version of your extension installed.

### How to reproduce

Just build the latex document under the respective OS.

### Expected behavior

When I build my latex document under MS Win 10 with MikTeX installed, warnings, errors and infos should be indicated for the actual .tex file in which they occur. When I click on a message, the cursor should be set to the correct position in the correct .tex file.

### Actual behavior

see above

### Log messages

If log messages are of any help I can amend them to this post.

### Additional Information

none

**Comment by James-Yu** [comment] 2017-09-15 01:05
This should already been fixed in #223 . Can you please provide a minimal working example?

**Comment by black-snake** [comment] 2017-09-18 15:29
Hey, no problem and thanks.

Unfortunately, .tex is not a supported file type for attachments, so I post I hereafter:

**main.tex**:
```
\documentclass{article}

\usepackage[utf8]{inputenc}

\title{\textbf{Title}}
\author{N. N.}

\begin{document}

\maketitle

\input{input1.tex}

\end{document}
```

**input1.tex**:
```
\chapter{Chapter 1}

This is a text and I will provoke an error right after this.

\begin{equation}
    E = mc^2\chapter{title}
\end{equation}
```

**Comment by James-Yu** [comment] 2017-09-19 06:51
This actually looks very well for me. Can you please describe what is the expected log?

![image](https://user-images.githubusercontent.com/4210342/30579137-f0d9130c-9d49-11e7-82ec-ee40ecf6ea27.png)

**Comment by black-snake** [comment] 2017-09-19 16:10
Strange. I see the error under `main.tex` and not under `input1.tex` (see screenshot) and when I click on the error message the cursor is pointed the first line of `main.tex`.
![screen](https://user-images.githubusercontent.com/23463170/30602735-c5839c9c-9d65-11e7-8cb2-98c9ba903349.png)

**Comment by James-Yu** [comment] 2017-09-20 02:37
Can you please provide your LaTeX compiler log? The behavior is quite weird.

**Comment by black-snake** [comment] 2017-09-20 14:36
The LaTeX compiler log is as follows:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6400 64-bit)
entering extended mode
(main.tex
LaTeX2e <2017-04-15>
Babel <3.12> and hyphenation patterns for 75 language(s) loaded.
("C:\Program Files\MiKTeX 2.9\tex\latex\base\article.cls"
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex\latex\base\size10.clo"))
("C:\Program Files\MiKTeX 2.9\tex\latex\base\inputenc.sty"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\utf8.def"
("C:\Program Files\MiKTeX 2.9\tex\latex\base\t1enc.dfu")
("C:\Program Files\MiKTeX 2.9\tex\latex\base\ot1enc.dfu")
("C:\Program Files\MiKTeX 2.9\tex\latex\base\omsenc.dfu"))) (main.aux)
(input1.tex
! Undefined control sequence.
l.1 \chapter
            {Chapter 1}
! Undefined control sequence.
l.6     E = mc^2\chapter
                        {title}
) [1{C:/Users/snake/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]
(main.aux) )
(see the transcript file for additional information)<C:/Program Files/MiKTeX 2.
9/fonts/type1/public/amsfonts/cm/cmbx12.pfb><C:/Program Files/MiKTeX 2.9/fonts/
type1/public/amsfonts/cm/cmmi10.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/pu
blic/amsfonts/cm/cmr10.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsf
onts/cm/cmr12.pfb><C:/Program Files/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/c
mr7.pfb>
Output written on main.pdf (1 page, 51120 bytes).
SyncTeX written on main.synctex.gz.
Transcript written on main.log.
```

However, today I figured out that it works fine with `latexmk` under Windows but not with `pdflatex`.

My exact LaTeX toolchain looks like this:
```
"latex-workshop.latex.toolchain": [{
		"command": "pdflatex",
		"args": [
			"-synctex=1",
			"-interaction=nonstopmode",
			"%DOCFILE%.tex"
		]
	}, {
		"command": "makeindex",
		"args": [
			"%DOCFILE%.nlo",
			"-s",
			"nomencl.ist",
			"-o",
			"%DOCFILE%.nls"]
	}, {
		"command": "bibtex",
		"args": [
			"%DOCFILE%.aux"
		]
	}, {
		"command": "pdflatex",
		"args": [
			"-synctex=1",
			"-interaction=nonstopmode",
			"%DOCFILE%.tex"
		]
	}, {
		"command": "pdflatex",
		"args": [
			"-synctex=1",
			"-interaction=nonstopmode",
			"%DOCFILE%.tex"
		]
	}
]
```

**Comment by James-Yu** [comment] 2017-10-06 10:01
Sorry for being AFK for long. Will look into the issue soon.

**Comment by James-Yu** [comment] 2017-10-21 11:38
Sorry again for another AFK cuz I was (and is) on a conference trip. In the meantime I can actually reproduce this bug with `pdflatex` toolchain. Making some progress and I'll be back soon (TM).

**Comment by black-snake** [comment] 2017-10-21 11:46
Hey, thanks. No problem and thanks for looking into this.

**Closed** 2017-10-21 12:07 UTC

**Comment by James-Yu** [comment] 2017-10-21 12:08
This commit should fix the problem. However, since the regex constraint is quite loose, I need to double check if it still works fine for other log messages. I will push the fix after some tests.
