### ISSUE TITLE
Citation intellisense not working

### ISSUE THREAD

**Issue by ShuCaiMonkaS** [James-Yu/LaTeX-Workshop#2122] opened 2020-05-28 01:17 UTC
### Describe the bug [Required]

The preview of the citation does not work. It works the first time after I open the VSCode, but the IntelliSense disappear whether I autocomplete the citation or not.

When the bug happens:

<img width="716" alt="Screen Shot 2020-05-27 at 8 04 49 PM" src="https://user-images.githubusercontent.com/43042885/83086957-bfdfc900-a055-11ea-99fd-01342dfae5c4.png">

Also, the hover to preview citation feature does not work for me. (Sorry if this is a dumb mistake on my side).

### To Reproduce
Have a `test.tex` main file
```
\documentclass{article}

\begin{document}

\bibliography{testbib}
\end{document}
```
and `testbib.bib` file
```
@article {citekey,
    AUTHOR = {author}
}
```
### Expected behavior
Show intellisense for available citation (this is when I use `\cite{}` the first time after opening VSCode.
<img width="713" alt="Screen Shot 2020-05-27 at 8 04 38 PM" src="https://user-images.githubusercontent.com/43042885/83086895-93c44800-a055-11ea-926d-0c3ddbc2dda8.png">

## Logs [Required]
no log since there's no compiling

### LaTeX Workshop Output [Required]
```
[20:08:33] Initializing LaTeX Workshop.
[20:08:34] Creating file watcher for .pdf files.
[20:08:34] Creating LaTeX Workshop http and websocket server.
[20:08:34] LaTeX Workshop initialized.
[20:08:34] Server created on 127.0.0.1:51206
[20:08:34] Snippet data loaded.
[20:08:34] LaTeX Workshop version: 8.9.0
[20:08:34] Found root file from active editor: /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/test.tex
[20:08:34] Found root file from active editor: /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/test.tex
[20:08:34] Root file changed from: undefined to /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/test.tex. Find all dependencies.
[20:08:34] Instantiating a new file watcher for /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/test.tex
[20:08:34] Creating file watcher for .bib files.
[20:08:34] Parsing /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/test.tex
[20:08:34] Found .bib file /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/testbib.bib
[20:08:34] Adding .bib file /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/testbib.bib to bib file watcher.
[20:08:34] Parsing .bib entries from /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/testbib.bib
[20:08:34] Parse fls file.
[20:08:34] Cannot find fls file.
[20:08:34] Root file remains unchanged from: /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/test.tex.
[20:08:34] Adding /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/test.tex to file watcher.
[20:08:34] Parsed 1 bib entries from /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/testbib.bib.
[20:08:35] Found files that might be root, choose the first one: /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/test.tex
[20:08:35] Root file remains unchanged from: /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/test.tex.
[20:10:11] Found root file from active editor: /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/test.tex
[20:10:11] Root file remains unchanged from: /Users/shengchao/Documents/RiceUniversity/nonresearch/Presentation/test/test.tex.
[20:10:36] LOG command invoked.
```

### Developer Tools Console [Required]
No information happened when I open the developer tools console. 

## Screenshots
See above

## Desktop [Required]
 - OS: macOS Catalina 10.15.4 (19E287)
 - VS Code version: 1.45.1
 - Extension version: 8.9.0
 - TeX distribution version: TeX Live 2019

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by tamuratak** [comment] 2020-05-28 01:24
Duplicate of #2081

**Closed by tamuratak** 2020-05-28 01:24 UTC

**Comment by flimofly** [comment] 2020-06-05 16:29
Gentle request for a release that includes a fix.
