### ISSUE TITLE
Enter does not work

### ISSUE THREAD

**Issue by Marco87Developer** [James-Yu/LaTeX-Workshop#961] opened 2018-11-06 22:50 UTC
### Description

I can’t use `Enter` because it does not work. Works if I use `Shift+Enter`, but it is annoying. The problem began with **5.15.0 version** of the extension.

**Comment by tamuratak** [comment] 2018-11-06 22:55
Duplicate of #903. Disabling other extensions except for LaTeX Workshop solves this problem. Please disable Spell Right, Brackets Pair Colouriser 2, and Prettify Symbols Mode especially.

**Closed** 2018-11-07 03:28 UTC
