### ISSUE TITLE
Close compile error windows after successful recompilation

### ISSUE THREAD

**Issue by orzechow** [James-Yu/LaTeX-Workshop#2517] opened 2021-02-08 12:00 UTC
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

When compiling a broken latex document, an error window ("Recipe terminated with error") is properly shown.
After fixing the reason in the latex document and recompiling, the error window is still present / does not hide.

### To Reproduce

1. Create a dummy test file with a small latex syntax error:  
```tex
\documentclass{article}
\begin{document}
  test: $
\end{document}
```
2. Compile (e.g. with latexmk) and you should see something like this (do not close it manually):  
![VSCode Latex Workshop 1](https://user-images.githubusercontent.com/5220714/107215805-b9d32200-6a03-11eb-815d-073e801f609e.png)
3. Fix the latex syntax issue:  
```tex
\documentclass{article}
\begin{document}
  test: $E=mc^2$
\end{document}
```
4. Recompile and the error window is still there (see in the lower left that the build has actually no issues any more):  
![VSCode Latex Workshop 2](https://user-images.githubusercontent.com/5220714/107215897-e25b1c00-6a03-11eb-9e79-c6ff1613ab32.png)

### Expected behavior

I'd love to see an error window being closed, if a recipe succeeds again (I'm rarely closing these windows manually).

## Logs [Required]

Please paste the whole log messages here, not parts of ones. The log should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

### LaTeX Workshop Output [Required]

```
[12:52:57] Initializing LaTeX Workshop.
[12:52:57] Extension root: /home/userfoo/.vscode/extensions/james-yu.latex-workshop-8.15.0
[12:52:57] Creating PDF file watcher.
[12:52:57] Creating LaTeX Workshop http and websocket server.
[12:52:57] LaTeX Workshop initialized.
[12:52:57] Current workspace folders: ["file:///tmp"]
[12:52:57] Current workspaceRootDir: /tmp
[12:52:57] Found root file from active editor: /tmp/text.tex
[12:52:57] Root file changed: from undefined to /tmp/text.tex
[12:52:57] Start to find all dependencies.
[12:52:57] Root file languageId: latex
[12:52:57] Instantiating a new file watcher for /tmp/text.tex
[12:52:57] Creating Bib file watcher.
[12:52:57] Parsing a file and its subfiles: /tmp/text.tex
[12:52:57] Parse fls file.
[12:52:57] Fls file found: /tmp/out/text.fls
[12:52:57] Parse aux file: /tmp/out/text.aux
[12:52:57] Server created on 127.0.0.1:35051
[12:52:57] Added to file watcher: /tmp/text.tex
[12:52:57] Added to file watcher: /home/userfoo/.texlive2017/texmf-var/fonts/map/pdftex/updmap/pdftex.map
[12:52:57] Snippet data loaded.
[12:52:57] LaTeX Workshop version: 8.15.0
[12:53:00] Auto build started on saving file: /tmp/text.tex
[12:53:00] BUILD command invoked.
[12:53:00] The document of the active editor: file:///tmp/text.tex
[12:53:00] The languageId of the document: latex
[12:53:00] Current workspace folders: ["file:///tmp"]
[12:53:00] Current workspaceRootDir: /tmp
[12:53:00] Found root file from active editor: /tmp/text.tex
[12:53:00] Keep using the same root file: /tmp/text.tex
[12:53:00] Building root file: /tmp/text.tex
[12:53:00] Build root file /tmp/text.tex
[12:53:00] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-shell-escape,-outdir=out,/tmp/text
[12:53:00] Recipe step env: {}
[12:53:00] cwd: /tmp
[12:53:00] LaTeX build process spawned. PID: 32027.
[12:53:00] File watcher - file changed: /tmp/text.tex
[12:53:00] Parsing a file and its subfiles: /tmp/text.tex
[12:53:00] Parse fls file.
[12:53:00] Fls file found: /tmp/out/text.fls
[12:53:00] Parse aux file: /tmp/out/text.aux
[12:53:00] Cannot parse a TeX file: /tmp/text.tex
[12:53:00] Fall back to regex-based completion.
[12:53:00] LaTeX log parsed with 1 messages.
[12:53:00] Recipe returns with error: 12/null. PID: 32027. message: Unquoted string "out" may clash with future reserved word at (eval 10) line 2, <GEN1> chunk 1.
Latexmk: This is Latexmk, John Collins, 26 Dec. 2019, version: 4.67.
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      '/tmp/text.tex'
      'text.tex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -shell-escape -recorder -output-directory="out"  "/tmp/text.tex"'
------------
Latexmk: Log file says output to 'out/text.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'out/text.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
.
[12:53:00] The environment variable $PATH: /home/userfoo/.anaconda3/condabin:/usr/lib/ccache:/home/userfoo/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/userfoo/.fzf/bin
[12:53:00] The environment variable $SHELL: /bin/bash
[12:53:00] Cleaning auxiliary files and retrying build after toolchain error.
[12:53:00] File cleaned: /tmp/out/text.aux
[12:53:00] File cleaned: /tmp/out/text.log
[12:53:00] File cleaned: /tmp/out/text.fls
[12:53:00] File cleaned: /tmp/out/text.fdb_latexmk
[12:53:00] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-shell-escape,-outdir=out,/tmp/text
[12:53:00] Recipe step env: {}
[12:53:00] cwd: /tmp
[12:53:00] LaTeX build process spawned. PID: 32032.
[12:53:01] LaTeX log parsed with 1 messages.
[12:53:01] Recipe returns with error: 12/null. PID: 32032. message: Unquoted string "out" may clash with future reserved word at (eval 10) line 2, <GEN1> chunk 1.
Latexmk: This is Latexmk, John Collins, 26 Dec. 2019, version: 4.67.
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -shell-escape -recorder -output-directory="out"  "/tmp/text.tex"'
------------
Latexmk: Log file says output to 'out/text.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'out/text.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
.
[12:53:01] The environment variable $PATH: /home/userfoo/.anaconda3/condabin:/usr/lib/ccache:/home/userfoo/.local/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/userfoo/.fzf/bin
[12:53:01] The environment variable $SHELL: /bin/bash
[12:53:04] Auto build started on saving file: /tmp/text.tex
[12:53:04] BUILD command invoked.
[12:53:04] The document of the active editor: file:///tmp/text.tex
[12:53:04] The languageId of the document: latex
[12:53:04] Current workspace folders: ["file:///tmp"]
[12:53:04] Current workspaceRootDir: /tmp
[12:53:04] Found root file from active editor: /tmp/text.tex
[12:53:04] Keep using the same root file: /tmp/text.tex
[12:53:04] Building root file: /tmp/text.tex
[12:53:04] Build root file /tmp/text.tex
[12:53:04] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-shell-escape,-outdir=out,/tmp/text
[12:53:04] Recipe step env: {}
[12:53:04] cwd: /tmp
[12:53:04] LaTeX build process spawned. PID: 32037.
[12:53:04] File watcher - file changed: /tmp/text.tex
[12:53:04] Parsing a file and its subfiles: /tmp/text.tex
[12:53:04] Parse fls file.
[12:53:04] Fls file found: /tmp/out/text.fls
[12:53:04] Parse aux file: /tmp/out/text.aux
[12:53:04] LaTeX log parsed with 0 messages.
[12:53:04] Recipe of length 1 finished. PID: 32037.
[12:53:04] Successfully built /tmp/text.tex.
[12:53:04] No PDF viewer connected for /tmp/out/text.pdf
[12:53:04] Parse fls file.
[12:53:04] Fls file found: /tmp/out/text.fls
[12:53:04] Parse aux file: /tmp/out/text.aux
[12:53:10] Current workspace folders: ["file:///tmp"]
[12:53:10] Current workspaceRootDir: /tmp
[12:53:10] Found root file from active editor: /tmp/text.tex
[12:53:10] Keep using the same root file: /tmp/text.tex
```

### Developer Tools Console [Required]

```
log.ts:197   ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/tmp/.vscode'
notificationsAlerts.ts:40 Recipe terminated with error.
onDidChangeNotification @ notificationsAlerts.ts:40
```

## Screenshots

See above

## Desktop [Required]
 - OS: Linux Mint 19.3 (based on Ubuntu 18.04)
 - VS Code version: 1.53.0
 - Extension version: 8.15.0
 - TeX distribution version: Tex Live 2017 (via apt sources of Ubuntu 18.04)

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

If anything is still unclear, please head back to me!

**Comment by tamuratak** [comment] 2021-02-08 12:35
Not possible from the restriction of VS Code API. Duplicate of #898.

**Closed by tamuratak** 2021-02-08 12:35 UTC

**Comment by orzechow** [comment] 2021-02-08 13:03
Thanks for the quick response and this great plugin!
Sorry, for the duplicate – I didn't find the other issue even though I was looking through the closed issues…

Seem like I'll have to disable the notifications then and watch the build icons.
