### ISSUE TITLE
External build command not honored in autobuild

### ISSUE THREAD

**Issue by djrenren** [James-Yu/LaTeX-Workshop#1286] opened 2019-04-09 23:22 UTC
**Describe the bug**
If you set the "latex-workshop.latex.external.build.command", explicit build commands will use this setting but autoBuild still uses the default recipe.

**To Reproduce**
1. Set "latex-workshop.latex.external.build.command"
2. Edit file and save
3. See build log for verification that the old build recipe was performed

**Expected behavior**
autoBuild should execute the external command or at the very least offer a configuration option to do so.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.2
 - VS Code version: 1.33.0
 - Extension version: 6.3.0

**Comment by jlelong** [comment] 2019-04-10 05:40
Duplicate of #1276.

**Closed by jlelong** 2019-04-10 05:40 UTC
