### ISSUE TITLE
Unable to rename the folder containing tex files when the extension is activated

### ISSUE THREAD

**Issue by haimingz** [James-Yu/LaTeX-Workshop#3998] opened 2023-09-01 13:26 UTC
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Win11 22H2
- Visual Studio Code Version: 1.81.1
- LaTeX Workshop Version: 9.13
- TeX Distribution Version: TeX Live 2020

## The Issue*
> _Please briefly describe the issue you come across._
- This extension prevents renaming folders containing .tex files

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. Open any folder with a latex subfolder in vscode
2. If you rename the subfolder without latex-workshop activated, the rename will be successful.
3. However, if you have opened a tex file and thus activated latex-workshop, you will not be able to rename the folder. After a while, a notification will pop up saying "Error: EPERM: operation not permitted, rename..."
4. Bizarrely, if I manually reload the vscode, I will find that the folder has been successfully renamed.

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[21:04:10.108][Logger] New log placeholder %WS1% registered for d:\OneDrive\当前\2022 Data-driven VIV\studies\01 sparse modal decomposition 1 .
[21:04:10.108][Config] latex-workshop.latex.recipes: [{"name":"latexmk","tools":["latexmk"]},{"name":"xelatex","tools":["xelatex"]},{"name":"pdflatex","tools":["pdflatex"]},{"name":"bibtex","tools":["bibtex"]},{"name":"xelatex -> bibtex -> xelatex*2","tools":["xelatex","bibtex","xelatex","xelatex"]},{"name":"pdflatex -> bibtex -> pdflatex*2","tools":["pdflatex","bibtex","pdflatex","pdflatex"]}] .
[21:04:10.109][Config] latex-workshop.latex.tools: [{"args":["%DOCFILE%.nlo","-s","nomencl.ist","-o","%DOCFILE%.nls"],"command":"makeindex","name":"makeindex"},{"args":["-synctex=1","-interaction=nonstopmode","-file-line-error","-pdflatex","%DOC%"],"command":"latexmk","name":"latexmk"},{"args":["-synctex=1","-interaction=nonstopmode","-file-line-error","%DOC%"],"command":"xelatex","name":"xelatex"},{"args":["-synctex=1","-interaction=nonstopmode","-file-line-error","%DOC%"],"command":"pdflatex","name":"pdflatex"},{"args":["%DOCFILE%"],"command":"bibtex","name":"bibtex"}] .
[21:04:10.113][Config] latex-workshop.latex.autoBuild.run: "never" .
[21:04:10.114][Config] latex-workshop.latex.clean.fileTypes: ["*.aux","*.bbl","*.blg","*.idx","*.ind","*.lof","*.lot","*.out","*.toc","*.acn","*.acr","*.alg","*.glg","*.glo","*.gls","*.ist","*.fls","*.log","*.fdb_latexmk"] .
[21:04:10.116][Config] latex-workshop.view.outline.commands: [] .
[21:04:10.117][Config] latex-workshop.view.outline.floats.enabled: false .
[21:04:10.117][Config] latex-workshop.view.outline.floats.number.enabled: false .
[21:04:10.118][Config] latex-workshop.view.outline.floats.caption.enabled: false .
[21:04:10.155][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[21:04:11.084][Server] Creating LaTeX Workshop http and websocket server.
[21:04:11.127][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":11879} .
[21:04:11.158][Extension] Initializing LaTeX Workshop.
[21:04:11.158][Extension] Extension root: c:\Users\zhuha\.vscode\extensions\james-yu.latex-workshop-9.13.4
[21:04:11.159][Extension] $PATH: C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Programs\ffmpeg\bin;C:\Users\zhuha\AppData\Local\Programs\Python\Python311;C:\Users\zhuha\AppData\Local\Programs\Python\Python311\Scripts;C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.1.0\;C:\Users\zhuha\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;C:\Users\zhuha\AppData\Local\BypassRuntm;C:\Users\zhuha\AppData\Local\GitHubDesktop\bin;C:\Programs\texlive\2020\bin\win32;C:\Users\zhuha\OneDrive\Interests;C:\Users\zhuha\AppData\Local\Microsoft\WindowsApps;C:\Users\zhuha\AppData\Local\Programs\Python\Python311;C:\Users\zhuha\AppData\Local\Programs\Python\Python311\scripts;;C:\Users\zhuha\AppData\Local\Programs\Julia-1.9.2\bin
[21:04:11.159][Extension] $SHELL: undefined
[21:04:11.159][Extension] $LANG: undefined
[21:04:11.159][Extension] $LC_ALL: undefined
[21:04:11.159][Extension] process.platform: win32
[21:04:11.159][Extension] process.arch: x64
[21:04:11.160][Extension] vscode.env.appName: Visual Studio Code
[21:04:11.160][Extension] vscode.env.remoteName: undefined
[21:04:11.160][Extension] vscode.env.uiKind: 1
[21:04:11.161][Extension] LaTeX Workshop initialized.
[21:04:11.167][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[21:04:11.176][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[21:04:11.177][Manager] Current workspace folders: ["file:///d:/OneDrive/当前/2022 Data-driven VIV/studies/01 sparse modal decomposition 1"]
[21:04:11.179][Manager] Found root file from active editor: %WS1%\manuscript\manuscript.tex
[21:04:11.179][Manager] Root file changed: from undefined to %WS1%\manuscript\manuscript.tex
[21:04:11.179][Manager] Start to find all dependencies.
[21:04:11.179][Manager] Root file languageId: latex
[21:04:11.179][Event] ROOT_FILE_CHANGED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\manuscript.tex"
[21:04:11.180][Cacher][Watcher] Reset.
[21:04:11.183][Cacher] Adding %WS1%\manuscript\manuscript.tex .
[21:04:11.184][Cacher][Watcher] Watched %WS1%\manuscript\manuscript.tex with a new watcher on %WS1%\manuscript .
[21:04:11.184][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\manuscript.tex"
[21:04:11.186][Cacher] Caching %WS1%\manuscript\manuscript.tex .
[21:04:11.188][Cacher] Updated inputs of %WS1%\manuscript\manuscript.tex .
[21:04:11.188][Cacher] Parse LaTeX AST: %WS1%\manuscript\manuscript.tex .
[21:04:11.188][Event] ROOT_FILE_SEARCHED
[21:04:11.194][Server] valdOrigin is http://127.0.0.1:11879
[21:04:11.691][Cacher] Parsed LaTeX AST: %WS1%\manuscript\manuscript.tex .
[21:04:11.692][Cacher][Path] Calling kpsewhich to resolve sn-jnl.cls .
[21:04:12.646][Cacher] Bib %WS1%\manuscript\references.bib from %WS1%\manuscript\manuscript.tex .
[21:04:12.646][Intelli][Citation] Parsing .bib entries from %WS1%\manuscript\references.bib
[21:04:12.647][Intelli][Citation] Parse BibTeX AST from %WS1%\manuscript\references.bib .
[21:04:12.647][Cacher][Watcher] Watched %WS1%\manuscript\references.bib with a new watcher on %WS1%\manuscript .
[21:04:12.647][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\references.bib"
[21:04:12.647][Cacher] Updated elements in 955.99 ms: %WS1%\manuscript\manuscript.tex .
[21:04:12.648][Event] FILE_PARSED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\manuscript.tex"
[21:04:12.650][Cacher] Parsing .fls %WS1%\manuscript\manuscript.fls .
[21:04:12.658][Cacher] Adding %WS1%\manuscript\sn-jnl.cls .
[21:04:12.658][Cacher][Watcher] Watched %WS1%\manuscript\sn-jnl.cls .
[21:04:12.658][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\sn-jnl.cls"
[21:04:12.682][Cacher] Adding %WS1%\manuscript\figures\coord.pdf .
[21:04:12.683][Cacher][Watcher] Watched %WS1%\manuscript\figures\coord.pdf with a new watcher on %WS1%\manuscript\figures .
[21:04:12.683][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\coord.pdf"
[21:04:12.684][Cacher] Adding %WS1%\manuscript\figures\algorithm.pdf .
[21:04:12.684][Cacher][Watcher] Watched %WS1%\manuscript\figures\algorithm.pdf .
[21:04:12.685][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\algorithm.pdf"
[21:04:12.686][Cacher] Adding %WS1%\manuscript\figures\experiment.pdf .
[21:04:12.686][Cacher][Watcher] Watched %WS1%\manuscript\figures\experiment.pdf .
[21:04:12.686][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\experiment.pdf"
[21:04:12.688][Cacher] Adding %WS1%\manuscript\figures\spectra.pdf .
[21:04:12.688][Cacher][Watcher] Watched %WS1%\manuscript\figures\spectra.pdf .
[21:04:12.688][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\spectra.pdf"
[21:04:12.690][Cacher] Adding %WS1%\manuscript\figures\rms_2350_basic.pdf .
[21:04:12.690][Cacher][Watcher] Watched %WS1%\manuscript\figures\rms_2350_basic.pdf .
[21:04:12.690][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\rms_2350_basic.pdf"
[21:04:12.692][Cacher] Adding %WS1%\manuscript\figures\weight_il_2350_basic.pdf .
[21:04:12.692][Cacher][Watcher] Watched %WS1%\manuscript\figures\weight_il_2350_basic.pdf .
[21:04:12.692][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\weight_il_2350_basic.pdf"
[21:04:12.693][Cacher] Adding %WS1%\manuscript\figures\weight_cf_2350_basic.pdf .
[21:04:12.694][Cacher][Watcher] Watched %WS1%\manuscript\figures\weight_cf_2350_basic.pdf .
[21:04:12.694][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\weight_cf_2350_basic.pdf"
[21:04:12.695][Cacher] Adding %WS1%\manuscript\figures\weight_il_2350_pseudo.pdf .
[21:04:12.695][Cacher][Watcher] Watched %WS1%\manuscript\figures\weight_il_2350_pseudo.pdf .
[21:04:12.695][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\weight_il_2350_pseudo.pdf"
[21:04:12.697][Cacher] Adding %WS1%\manuscript\figures\rms_2350_pseudo.pdf .
[21:04:12.697][Cacher][Watcher] Watched %WS1%\manuscript\figures\rms_2350_pseudo.pdf .
[21:04:12.697][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\rms_2350_pseudo.pdf"
[21:04:12.698][Cacher] Adding %WS1%\manuscript\figures\weight_il_2350_sparse.pdf .
[21:04:12.698][Cacher][Watcher] Watched %WS1%\manuscript\figures\weight_il_2350_sparse.pdf .
[21:04:12.699][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\weight_il_2350_sparse.pdf"
[21:04:12.700][Cacher] Adding %WS1%\manuscript\figures\rms_2350_sparse.pdf .
[21:04:12.700][Cacher][Watcher] Watched %WS1%\manuscript\figures\rms_2350_sparse.pdf .
[21:04:12.700][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\rms_2350_sparse.pdf"
[21:04:12.701][Cacher] Adding %WS1%\manuscript\figures\rms_2420_basic.pdf .
[21:04:12.702][Cacher][Watcher] Watched %WS1%\manuscript\figures\rms_2420_basic.pdf .
[21:04:12.702][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\rms_2420_basic.pdf"
[21:04:12.703][Cacher] Adding %WS1%\manuscript\figures\rms_2420_pseudo.pdf .
[21:04:12.703][Cacher][Watcher] Watched %WS1%\manuscript\figures\rms_2420_pseudo.pdf .
[21:04:12.703][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\rms_2420_pseudo.pdf"
[21:04:12.704][Cacher] Adding %WS1%\manuscript\figures\rms_2420_sparse.pdf .
[21:04:12.705][Cacher][Watcher] Watched %WS1%\manuscript\figures\rms_2420_sparse.pdf .
[21:04:12.705][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\rms_2420_sparse.pdf"
[21:04:12.706][Cacher] Adding %WS1%\manuscript\figures\weight_il_2420_sparse.pdf .
[21:04:12.706][Cacher][Watcher] Watched %WS1%\manuscript\figures\weight_il_2420_sparse.pdf .
[21:04:12.706][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\weight_il_2420_sparse.pdf"
[21:04:12.708][Cacher] Adding %WS1%\manuscript\figures\weight_cf_2420_sparse.pdf .
[21:04:12.709][Cacher][Watcher] Watched %WS1%\manuscript\figures\weight_cf_2420_sparse.pdf .
[21:04:12.709][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\weight_cf_2420_sparse.pdf"
[21:04:12.710][Cacher] Adding %WS1%\manuscript\figures\different_input.pdf .
[21:04:12.711][Cacher][Watcher] Watched %WS1%\manuscript\figures\different_input.pdf .
[21:04:12.711][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\different_input.pdf"
[21:04:12.713][Cacher] Adding %WS1%\manuscript\figures\different_s.pdf .
[21:04:12.713][Cacher][Watcher] Watched %WS1%\manuscript\figures\different_s.pdf .
[21:04:12.713][Event] FILE_WATCHED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\figures\\different_s.pdf"
[21:04:12.718][Cacher] Found .aux %WS1%\manuscript\manuscript.tex from .fls %WS1%\manuscript\manuscript.fls , parsing.
[21:04:12.719][Cacher] Parsed .aux %WS1%\manuscript\manuscript.tex .
[21:04:12.719][Cacher] Parsed .fls %WS1%\manuscript\manuscript.fls .
[21:04:12.726][Structure] Structure force updated with 0 root sections for %WS1%\manuscript\manuscript.tex .
[21:04:12.727][Event] STRUCTURE_UPDATED
[21:04:12.730][Intelli][Citation] Parsed 36 bib entries from %WS1%\manuscript\references.bib .
[21:04:12.730][Event] FILE_PARSED: "d:\\OneDrive\\当前\\2022 Data-driven VIV\\studies\\01 sparse modal decomposition 1\\manuscript\\references.bib"
[21:04:12.732][Structure] Structure force updated with 6 root sections for %WS1%\manuscript\manuscript.tex .
[21:04:12.732][Event] STRUCTURE_UPDATED
[21:10:49.340][Event] STRUCTURE_UPDATED
[21:20:07.655][Event] STRUCTURE_UPDATED

```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
ERR Error: EPERM: operation not permitted, rename 'd:\OneDrive\当前\2022 Data-driven VIV\studies\01 sparse modal decomposition 1\manuscript' -> 'd:\OneDrive\当前\2022 Data-driven VIV\studies\01 sparse modal decomposition 1\manuscripta': NoPermissions (FileSystemError): Error: EPERM: operation not permitted, rename 'd:\OneDrive\当前\2022 Data-driven VIV\studies\01 sparse modal decomposition 1\manuscript' -> 'd:\OneDrive\当前\2022 Data-driven VIV\studies\01 sparse modal decomposition 1\manuscripta'
    at n.create (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:37:3400)
    at i (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:37:3512)
    at t.ab (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:42:38244)
    at t.rename (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:42:36197)
```

**Comment by James-Yu** [comment] 2023-09-01 20:02
I cannot reproduce on my Mac. Are you renaming from explorer.exe or within vscode?

**Comment by James-Yu** [comment] 2023-09-01 20:03
Please also consider share a minimal working example.

**Comment by haimingz** [comment] 2023-09-02 13:38
@James-Yu Thanks for the reply. This issue occurs when I try to rename within the vscode. 
I have been experiencing this issue occasionally for some time, but I am not sure what triggers it. 
After a reboot, the issue no longer exists. So I am sorry that I can not provide any further information at the moment.

**Comment by James-Yu** [comment] 2023-09-02 16:29
Thanks for the information. Unfortunately we need to find a consistent reproduction method before debugging into the issue. I am closing this issue for now, but any further information/discoveries are welcomed.

**Closed by James-Yu** 2023-09-02 16:29 UTC
