### ISSUE TITLE
Cannot find the correct root file

### ISSUE THREAD

**Issue by wyunnn** [James-Yu/LaTeX-Workshop#776] opened 2018-09-05 12:56 UTC
It seems latex workshop cannot find the correct root file.
My files can be correctly built when I am under the main.tex window.

However, when I am editing other files and save it, it shows
"Found root file by the magic comment: [....\article.tex]", but actually the file article.tex does not exist. It continuously runs "parsing" and does not complete running for a long time.

**Comment by jlelong** [comment] 2018-09-05 13:45
It looks like you have a wrong magic comment `% TeX root`.
Can you give us a minimal example reproducing the problem?

**Comment by wyunnn** [comment] 2018-09-05 15:02
I did not use any magic comment in all my tex files.

Why does it continuously run and show the output like this?
[22:56:55] Root file remains unchanged from: c:\Users\Paper\main.tex.
[22:57:22] Try root file in root directory: c:\Users\Paper\main.tex
[22:57:22] Parsing c:\Users\Paper\main.tex
[22:57:22] Parsing c:\Users\texfiles\abstract.tex
[22:57:22] Parsing c:\Users\texfiles\intro.tex
[22:57:22] Parsing c:\Users\texfiles\relatedwork.tex
[22:57:22] Parsing c:\Users\texfiles\methodology.tex
[22:57:22] Parsing c:\Users\texfiles\conclusion.tex

**Comment by jlelong** [comment] 2018-09-06 06:48
I cannot reproduce the problem, can you provide a minimal example?

**Comment by oerpli** [comment] 2018-09-14 10:19
@wyunnn , if you're still having problems, try the following:

1. Open the project folder with VS Code (make sure, that your root file is in some subdirectory of this folder)
2. Open the .tex file from which you want to compile the document
3. Press F1 (or whatever hotkey you have assigned to the "Show All Commands"-command
4. Enter "root magic" - this should find the command "latex-workshop.addtexroot"  (full name: Insert %!TeX root magic command) and pick the command.
5. A list of .tex files in the projects should open - start typing the name of your desired root file (main.tex) and press enter. This inserts a correctly formatted root-comment and removes incorrectly formatted/old root-comments (if if recognizes them)
6. Save the file and compile.

**Comment by wyunnn** [comment] 2018-09-14 12:03
Thank you! 
It works when I insert the correct root magic command.
But when I remove the magic commands, it cannot find the root file (with \begin{document}) by itself...

**Comment by oerpli** [comment] 2018-09-14 12:36
Just don't remove it.

**Comment by jlelong** [comment] 2018-09-18 14:45
Is it solved?

**Comment by wyunnn** [comment] 2018-09-19 03:15
When I use the magic command, it works.

I tried to open it in the upper layer folder
When I remove the magic command, It shows
[11:06:06] Could not resolve included file c:\Users\Paper\main.tex

**Comment by jlelong** [comment] 2018-09-19 08:27
This is very strange. Can you post a zip of minimal example, so that I can track what is going on?

**Closed** 2018-09-27 18:15 UTC
Labels: needs more info

**Comment by SimonZsx** [comment] 2019-05-31 15:17
Hi all, I encountered the same Issue when I used LaTex Workshop in Win10 while including sub files with the LaTex package **import**. 
I tried the root magic but it still failed.
I resolve this issue by changing the `import{sections/}{xxx.tex}` to `include {sections/xxx.tex}`.
BTW, the **import** package works fine under my MacOS environment, I think there might be some OS related issue with the **import** package.

**Comment by paddymccrudden** [comment] 2019-06-05 04:12
I have a very similar problem. It would be great if the installation instructions were more comprehensive.

**Comment by jlelong** [comment] 2019-06-05 06:17
@SimonZsx From the `import` package documentation
````
\import{〈full_path〉}{〈file〉}
\subimport{〈path_extension〉}{〈file〉}
````
It looks like that you should be using `subimport` instead of `import`.

**Comment by jlelong** [comment] 2019-06-05 06:19
@paddymccrudden Have a look at the [wiki](https://github.com/James-Yu/LaTeX-Workshop/wiki/Multi-File-Projects#the-root-file) and feel free to make a PR if you think some extra information should be added.

**Comment by SimonZsx** [comment] 2019-06-05 14:23
Yes, that's a great solution. Thanks a lot!

**Comment by paddymccrudden** [comment] 2019-06-12 01:08
Thanks guys - I got it working. Very nice package.
