### ISSUE TITLE
menu structure in PDF bad to read

### ISSUE THREAD

**Issue by update-freak** [James-Yu/LaTeX-Workshop#2981] opened 2021-11-24 20:38 UTC
You still see this issue?: Yes
You visited the wiki?: Yes
You can compile a TeX document manually?: Yes

## Describe the bug

In the structure menu of the intern PDF viewer it's not easy to read the titles of the chapter (see picture)

![bad to read](https://user-images.githubusercontent.com/40196995/143309278-2e2419c1-13f0-48d6-9a93-5cc6a1660af8.png)

### To Reproduce

Compile the document.
View the document in the intern viewer.

### Expected behavior

Darker color of the font of the menu structure would be great to improve the readibility.

## Desktop

 - OS: Windows 11 (21H2)
 - VS Code version: 1.62.3
 - Extension version: 8.22.0
 - TeX distribution version: TeX Live 2021

**Comment by jlelong** [comment] 2021-11-24 21:30
Duplicate of #2640

**Comment by tamuratak** [comment] 2021-11-24 23:17
#2640 is already fixed. So, this might not be duplicate.

**Comment by tamuratak** [comment] 2021-11-24 23:18
- Fill out all the information required in [the issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). 
- Please paste the whole log messages here, not parts of ones. It should start with `Initializing LaTeX Workshop`. It is very important to identify problems.

![スクリーンショット 2020-02-14 20 41 25](https://user-images.githubusercontent.com/10665499/74528024-87b2ef80-4f6a-11ea-9c5d-4f9feff25524.png)

When all of the above is done, we will reopen this issue if needed.

**Comment by tamuratak** [comment] 2021-11-24 23:21
You might have to restart VS Code.

**Closed** 2021-11-25 00:21 UTC
Labels: enhancement
