### ISSUE TITLE
possible to add non-math mode accents to the latex snippet panel

### ISSUE THREAD

**Issue by rms3145** [James-Yu/LaTeX-Workshop#1674] opened 2019-09-07 04:23 UTC
**Is your feature request related to a problem? Please describe.**
Hello!  I would like to be able to use the latex snippet panel in latex workshop to get the code for letter accents such as \`{o} or \'{o} or \^{o} and these do not require math mode to compile correctly.  (the backslashes disappear when I submit this comment to GitHub ... it would be for example backslash ^{o}.)

The snippet panel currently gives me   \grave{o} or \acute{o} or \hat{o}  etc, however these require math mode such as  $\hat{o}$ to compile correctly.

**Describe the solution you'd like**
I am not so great at coding, but is there any way to make this kind of change using the json preferences?  I would probably never use the $\hat{o}$ solution personally in my work but I use the \^{o} types of symbols a lot. (again with the backslashes.)

**Describe alternatives you've considered**
I currently just open up this page (https://en.wikibooks.org/wiki/LaTeX/Special_Characters) and copy and paste which is sub-optimal.   I googled around a lot for a while and I was unable to find any existing description of a solution to my problem online. Thanks in advance for your help!  And thanks for LaTeX workshop!

**Comment by tecosaur** [comment] 2019-10-01 03:59
Hi,

Sorry for the long delay. This is actually something I did originally try to add — the issue is that since the symbols are produced with mathJax I need to find a way to produce the correct icon with mathJax-supported syntax. Unfortunately, I wasn't able to do this for the full set of text symbols.

If you're able to pick up where I left off, or have any bright ideas that would be great!

**Comment by rms3145** [comment] 2019-10-02 14:19
Hi,

Thanks for your response.  I'd be happy to take a look and try to think of a solution.  I am not a hardcore coder, but I know a very small amount of coding and a more about LaTeX.  I'd be happy to look at the code and think about a possible solution.  

Could I ask, do you know exactly where I would look in this repository for the specific code that handles the international symbols in the latex snippet panel?    I would be very grateful if you could tell me the exact file to download and the line numbers where the code is located.  

I guess you have probably thought of this but the first thing that comes to my mind is to try to find a way to tell mathJax to display one symbol for the button to "click" and to tell the button that you are clicking to print the other code into the LaTeX document.  

Thanks a lot for your help!

**Comment by trevorgunn** [comment] 2019-10-03 15:02
@rms3145 I think the file you're looking for is `resources/snippetpanel/snippetpanel.json`. The file is organized into a list of arrays. You want the "`accents`" array: https://github.com/James-Yu/LaTeX-Workshop/blob/d67ca28c7c05a510db38c5f6c7513d48befa25fb/resources/snippetpanel/snippetpanel.json#L2947-L2954

Maybe what needs to happen is to create an array in the json file for math-mode accents and one for text-mode accents.

**Comment by tamuratak** [comment] 2020-05-20 01:22
It will not be implemented in the near future, so close it.

**Closed by tamuratak** 2020-05-20 01:22 UTC
Labels: feature-request
