### ISSUE TITLE
Forward SyncTex not available

### ISSUE THREAD

**Issue by mcoweber** [James-Yu/LaTeX-Workshop#805] opened 2018-09-17 12:25 UTC
Hi,

with the newest version of LaTeX-Workshop, "SyncTex from cursor" disappeared from the context menu. I could not find any comments on SyncTex in the change log.

PS: I'm using Windows 10 with MikTeX

Best regards
Marc

**Comment by jlelong** [comment] 2018-09-17 12:29
Duplicate of #802, #804.

**Closed by jlelong** 2018-09-17 12:29 UTC
