### ISSUE TITLE
Editor warning on Chinese "："

### ISSUE THREAD

**Issue by Firestar-Reimu** [James-Yu/LaTeX-Workshop#3010] opened 2021-12-13 01:50 UTC
![Screenshot_20211213_094758](https://user-images.githubusercontent.com/65082432/145740115-f3b0ac0e-35c7-4026-a02c-f73e7018c551.png)

Like this, it only gives warning on "：" but not other symbols, it does not gives warning when compiling latex.

**Comment by tamuratak** [comment] 2021-12-13 02:02
Duplicate of microsoft/vscode/issues/138767

See https://code.visualstudio.com/updates/v1_63#_unicode-highlighting

**Comment by tamuratak** [comment] 2021-12-13 02:03
Please fill out the [issue template](https://github.com/James-Yu/LaTeX-Workshop/blob/master/.github/ISSUE_TEMPLATE/bug-report.md) next time.

**Closed by tamuratak** 2021-12-13 02:02 UTC
Labels: vscode-issue
