### ISSUE TITLE
Resolve latexmkrc vs. Latex-Workshop output directory conflicts

### ISSUE THREAD

**Issue by samquinan** [James-Yu/LaTeX-Workshop#1075] opened 2018-12-18 20:09 UTC
I ran into an issue where I having trouble launching the pdf viewer for the latexmk build of my thesis. I eventually traced the issue to there being a mismatch in the output directories settings between my latexmkrc and Latex-Workshop.

latexmkrc allows for the output directory to be set using the `$out_dir` flag, which the latexmk build in  the Latex-Workshop recipe completely respects. The pdf viewer, on the other hand, searches the path associated with the `latex-workshop.latex.outputDir` setting, which is independent.

There is a relatively simple workaround where one can create local workspace settings for `latex-workshop.latex.outputDir` that match what's in the latexmkrc files. If one does that, everything seems to work fine.

But since this is just a path issue, I was wondering if it would be possible to have the pdf viewer check for a specified output directory in the latexmkrc? Either that or provide some way of making users aware when there are conflicting output directory settings between latexmkrc and LaTex-Workshop so they can update them accordingly? 

While automagically handling this for the user would be optimal, I totally understand that the question of which settings take precedence gets complicated. I'm thinking you could probably get away with something as simple as adding a linting check to the latexmkrc file that exposes a warning or "problem" in the vscode output when the output directory settings conflict, though...

**Comment by jlelong** [comment] 2018-12-18 20:38
Duplicate of #758.

**Closed by jlelong** 2018-12-18 20:38 UTC

**Comment by samquinan** [comment] 2018-12-18 20:55
While related, this is neither a duplicate nor resolved. I fully understand, as outlined in #758, that the `latex-workshop.latex.outputDir` variable does not influence the build process and that this is the expected behavior of the variable.

I am expressly requesting the additional feature that the `latex-workshop.latex.outputDir` variable in the settings is automatically updated to reflect the settings in latexmkrc. Either that or that the user be prompted in some way to make that update when an `$out_dir` by the latexmkrc.

**Comment by jlelong** [comment] 2018-12-19 06:04
By design, it is up to the user to properly set `latex-workshop.latex.outputDir`. Making this variable automatically discovered in a robust way is quite delicate and would undoubtedly raise more issues than it actually solves. If you can think of a smart way of handling this, feel free to make a PR and I will look at it carefully.
