### ISSUE TITLE
LaTexFormatter ENOTDIR

### ISSUE THREAD

**Issue by cbarkachi** [James-Yu/LaTeX-Workshop#2576] opened 2021-03-11 22:27 UTC
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug

Whenever I try to compile a tex document (e.g. save the document to generate a pdf version of it), I get the little red X in Latex Workshop indicating that the build failed.

### To Reproduce

3. See error

### LaTeX Workshop Output

```
To access the log, click the 'TeX' icon on the Activity Bar on the left side, select 'View Log Messages', then select 'View LaTeX Workshop extension log'.

[17:15:00] Initializing LaTeX Workshop.
[17:15:00] Extension root: /Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1
[17:15:00] $PATH: /Users/chris/.opam/4.10.2/bin:/Users/chris/perl5/perlbrew/bin:/Users/chris/perl5/perlbrew/perls/perl-5.28.0/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/openssl@1.1/bin/openssl:/opt/homebrew/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/Library/Apple/usr/bin
[17:15:00] $SHELL: /bin/zsh
[17:15:00] Creating PDF file watcher.
[17:15:00] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[17:15:00] Creating LaTeX Workshop http and websocket server.
[17:15:00] LaTeX Workshop initialized.
[17:15:00] Trigger characters for intellisense of LaTeX documents: ["\\","{",",","(","["]
[17:15:00] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[]}
[17:15:00] Current workspace folders: ["file:///Users/chris/2021spring/484/a2/theory"]
[17:15:00] Current workspaceRootDir: /Users/chris/2021spring/484/a2/theory
[17:15:00] Found root file from active editor: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:00] Root file changed: from undefined to /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:00] Start to find all dependencies.
[17:15:00] Root file languageId: latex
[17:15:00] Creating a new file watcher for /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:00] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[17:15:00] Creating Bib file watcher.
[17:15:00] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[17:15:00] Parsing a file and its subfiles: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:00] Parse fls file.
[17:15:00] Cannot find fls file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.fls
[17:15:00] Server created on 127.0.0.1:59141
[17:15:00] Added to file watcher: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:00] Restoring the PDF viewer at the column 1 from the state: {"type":"state","state":{"path":"/Users/chris/2021spring/484/a2/theory/Assignment 2 - PDF Image submission.pdf","scale":"auto","scrollMode":0,"spreadMode":0,"scrollTop":0,"scrollLeft":0,"trim":0}}
[17:15:00] Snippet data loaded.
[17:15:00] LaTeX Workshop version: 8.16.1
[17:15:00] The internal PDF viewer url: http://localhost:59141/viewer.html?incode=1&file=pdf..JTJGVXNlcnMlMkZjaHJpcyUyRjIwMjFzcHJpbmclMkY0ODQlMkZhMiUyRnRoZW9yeSUyRkFzc2lnbm1lbnQlMjAyJTIwLSUyMFBERiUyMEltYWdlJTIwc3VibWlzc2lvbi5wZGY
[17:15:00] Checking for duplicate labels: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex.
[17:15:00] Handle data type: open
[17:15:00] Preview PDF file: /Users/chris/2021spring/484/a2/theory/Assignment 2 - PDF Image submission.pdf
[17:15:01] Handle data type: request_params
[17:15:01] Sending the settings of the PDF viewer for initialization: {"type":"params","scale":"auto","trim":0,"scrollMode":0,"spreadMode":0,"hand":false,"invertMode":{"enabled":false,"brightness":1,"grayscale":0.6,"hueRotate":180,"invert":0,"sepia":0},"bgColor":"#ffffff","keybindings":{"synctex":"ctrl-click"}}
[17:15:01] Handle data type: loaded
[17:15:05] Current workspace folders: ["file:///Users/chris/2021spring/484/a2/theory"]
[17:15:05] Current workspaceRootDir: /Users/chris/2021spring/484/a2/theory
[17:15:05] Found root file from active editor: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:05] Keep using the same root file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:31] Start formatting with latexindent.
[17:15:31] Checking latexindent: which latexindent
[17:15:31] Checking latexindent is ok: /Library/TeX/texbin/latexindent

[17:15:31] Formatting with command latexindent -c,/Users/chris/2021spring/484/a2/theory/,/Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex,-y=defaultIndent: '    '
[17:15:32] File watcher - file changed: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:32] Parsing a file and its subfiles: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:32] Parse fls file.
[17:15:32] Cannot find fls file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.fls
[17:15:32] Auto build started detecting the change of a file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:32] BUILD command invoked.
[17:15:32] The document of the active editor: file:///Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:32] The languageId of the document: latex
[17:15:32] Building root file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:32] Build root file /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:32] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/Users/chris/2021spring/484/a2/theory,/Users/chris/2021spring/484/a2/theory/__latexindent_temp
[17:15:32] Recipe step env: {}
[17:15:32] cwd: /Users/chris/2021spring/484/a2/theory
[17:15:32] Unexpected Error: please see the console log of the Developer Tools of VS Code.
[17:15:32] Checking for duplicate labels: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex.
[17:15:33] File watcher - file changed: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:33] Parsing a file and its subfiles: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:33] Parse fls file.
[17:15:33] Cannot find fls file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.fls
[17:15:33] Auto build started detecting the change of a file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:33] BUILD command invoked.
[17:15:33] The document of the active editor: file:///Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:33] The languageId of the document: latex
[17:15:33] Building root file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:33] Build root file /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:15:33] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/Users/chris/2021spring/484/a2/theory,/Users/chris/2021spring/484/a2/theory/__latexindent_temp
[17:15:33] Recipe step env: {}
[17:15:33] cwd: /Users/chris/2021spring/484/a2/theory
[17:15:33] Unexpected Error: please see the console log of the Developer Tools of VS Code.
[17:15:33] Checking for duplicate labels: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex.
[17:21:54] Start formatting with latexindent.
[17:21:54] Formatting with command latexindent -c,/Users/chris/2021spring/484/a2/theory/,/Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex,-y=defaultIndent: '    '
[17:21:54] File watcher - file changed: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:21:54] Parsing a file and its subfiles: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:21:54] Parse fls file.
[17:21:54] Cannot find fls file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.fls
[17:21:54] Auto build started detecting the change of a file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:21:54] BUILD command invoked.
[17:21:54] The document of the active editor: file:///Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:21:54] The languageId of the document: latex
[17:21:54] Building root file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:21:54] Build root file /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:21:54] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/Users/chris/2021spring/484/a2/theory,/Users/chris/2021spring/484/a2/theory/__latexindent_temp
[17:21:54] Recipe step env: {}
[17:21:54] cwd: /Users/chris/2021spring/484/a2/theory
[17:21:54] Unexpected Error: please see the console log of the Developer Tools of VS Code.
[17:21:55] Checking for duplicate labels: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex.
[17:21:56] File watcher - file changed: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:21:56] Parsing a file and its subfiles: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:21:56] Parse fls file.
[17:21:56] Cannot find fls file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.fls
[17:21:56] Auto build started detecting the change of a file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:21:56] BUILD command invoked.
[17:21:56] The document of the active editor: file:///Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:21:56] The languageId of the document: latex
[17:21:56] Building root file: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:21:56] Build root file /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex
[17:21:56] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/Users/chris/2021spring/484/a2/theory,/Users/chris/2021spring/484/a2/theory/__latexindent_temp
[17:21:56] Recipe step env: {}
[17:21:56] cwd: /Users/chris/2021spring/484/a2/theory
[17:21:56] Unexpected Error: please see the console log of the Developer Tools of VS Code.
[17:21:56] Checking for duplicate labels: /Users/chris/2021spring/484/a2/theory/__latexindent_temp.tex.
[17:23:11] LOG command invoked: default
```

### Developer Tools Console [Required]

I'm not sure how to copy Chrome's log without it looking hideous so here's a picture (followed by the text that I captured from the log)

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/24356178/110864085-9fed5f00-828f-11eb-9105-0923e6ce306f.png">

```
To access the log, click 'help' -> 'Toggle Developer Tools' -> 'Console'. Paste anything suspicious.

 WARN Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407)
	at Object.spawn (child_process.js:557)
	at Object.spawn [as default] (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/node_modules/cross-spawn/index.js:12)
	at /Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/providers/latexformatter.js:171
	at new Promise (<anonymous>)
	at LaTexFormatter.format (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/providers/latexformatter.js:144)
	at LaTexFormatter.formatDocument (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/providers/latexformatter.js:80)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: spawn ENOTDIR
v @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
console.ts:137 [Extension Host] stack trace: Error: spawn ENOTDIR	at ChildProcess.spawn (internal/child_process.js:407:11)	at Object.spawn (child_process.js:557:9)	at Object.spawn [as default] (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/node_modules/cross-spawn/index.js:12:24)	at Builder.buildStep (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:317:38)	at Builder.buildInitiator (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:197:14)	at Builder.build (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:259:18)	at processTicksAndRejections (internal/process/task_queues.js:97:5)	at async Commander.build (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/commander.js:115:9)
v @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
mainThreadExtensionService.ts:59 [[object Object]]spawn ENOTDIR
$onExtensionRuntimeError @ mainThreadExtensionService.ts:59
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
mainThreadExtensionService.ts:60 Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407)
	at Object.spawn (child_process.js:557)
	at Object.spawn [as default] (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/node_modules/cross-spawn/index.js:12)
	at Builder.buildStep (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:317)
	at Builder.buildInitiator (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:197)
	at Builder.build (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:259)
	at processTicksAndRejections (internal/process/task_queues.js:97)
	at async Commander.build (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/commander.js:115)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: spawn ENOTDIR
v @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
console.ts:137 [Extension Host] stack trace: Error: spawn ENOTDIR	at ChildProcess.spawn (internal/child_process.js:407:11)	at Object.spawn (child_process.js:557:9)	at Object.spawn [as default] (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/node_modules/cross-spawn/index.js:12:24)	at Builder.buildStep (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:317:38)	at Builder.buildInitiator (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:197:14)	at Builder.build (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:259:18)	at processTicksAndRejections (internal/process/task_queues.js:97:5)	at async Commander.build (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/commander.js:115:9)
v @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
mainThreadExtensionService.ts:59 [[object Object]]spawn ENOTDIR
$onExtensionRuntimeError @ mainThreadExtensionService.ts:59
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
mainThreadExtensionService.ts:60 Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407)
	at Object.spawn (child_process.js:557)
	at Object.spawn [as default] (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/node_modules/cross-spawn/index.js:12)
	at Builder.buildStep (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:317)
	at Builder.buildInitiator (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:197)
	at Builder.build (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/components/builder.js:259)
	at processTicksAndRejections (internal/process/task_queues.js:97)
	at async Commander.build (/Users/chris/.vscode/extensions/james-yu.latex-workshop-8.16.1/out/src/commander.js:115)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
```

## Screenshots

N/A

## Desktop

 - OS: Windows 10
 - VS Code version: 1.54.1
 - Extension version: 8.16.1
 - TeX distribution version: MacTeX-2020

### Are you using VSCodium?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

### Additional context

Everything was working fine and I can't pinpoint what changed to cause this bug. I don't believe I upgraded VSCode and I've tried everything, from reinstalling Latex Workshop and installing older versions to reinstalling VSCode itself and deleting and reinstalling MacTex and latexformatter.

**Comment by tamuratak** [comment] 2021-03-11 22:36
Duplicate of #2567. A workaround is downgrading to v1.53.2: https://code.visualstudio.com/updates/v1_53.

**Closed by tamuratak** 2021-03-11 22:36 UTC
Labels: vscode-issue

**Comment by cbarkachi** [comment] 2021-03-11 22:39
> Duplicate of #2567. A workaround is downgrading to v1.53.2: https://code.visualstudio.com/updates/v1_53.

I'm actually on a Mac M1, and there are no downloads on that page for the new ARM chip. I'm a little confused because this extension was working fine about a week ago?

**Comment by tamuratak** [comment] 2021-03-11 22:47
We can do nothing on our side.

**Comment by tamuratak** [comment] 2021-03-12 03:57
Updating to v1.54.2 might solve the issue. https://github.com/microsoft/vscode-remote-release/issues/4630#issuecomment-797143707

If not, please open a new issue filling out all the information required in the issue template.
