### ISSUE TITLE
PDF viewer disables other keybinds

### ISSUE THREAD

**Issue by johncoltrane** [James-Yu/LaTeX-Workshop#1616] opened 2019-08-19 15:46 UTC
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**
When opening a multi-page pdf in vscode using the LaTeX-Workshop pdf viewer, other keybinds stop working. For example, I can no longer change tabs, exit the tab, or open a terminal.

**To Reproduce**
1. Click "View LaTeX PDF" and ensure that it opens in a vscode tab
2. Begin navigating the pdf with arrow keys, or some similar interaction.
3. Attempt to navigate away from the tab using keyboard shortcuts. For example, try navigating the file explorer, closing the tab, or opening a keyboard, using shortcuts.

**Expected behavior**
This should all work as expected.

**Logs [Required]**
<details>
<summary>LaTeX Workshop Output [Required]</summary>

[11:34:57] Initializing LaTeX Workshop.
[11:34:57] Creating LaTeX Workshop http and websocket server.
[11:34:57] LaTeX Workshop initialized.
[11:34:57] Linter for root file started.
[11:34:57] No root file found for linting.
[11:34:57] "latex-workshop.latex.autoBuild.onSave.enabled" and "latex-workshop.latex.autoBuild.onTexChange.enabled" have been replaced by "latex-workshop.latex.autoBuild.run", which is set to "never". Please manually remove the deprecated configs from your settings.
[11:34:57] Found root file from active editor: /Users/dannydarvish/Documents/tex/menu_proceedings/main.tex
[11:34:58] Root file changed from: undefined. Find all dependencies.
[11:34:58] Instantiating a new file watcher for /Users/dannydarvish/Documents/tex/menu_proceedings/main.tex
[11:34:58] Creating file watcher for .bib files.
[11:34:58] Parsing /Users/dannydarvish/Documents/tex/menu_proceedings/main.tex
[11:34:58] Found .bib file /Users/dannydarvish/Documents/tex/menu_proceedings/thebib.bib
[11:34:58] Adding .bib file /Users/dannydarvish/Documents/tex/menu_proceedings/thebib.bib to bib file watcher.
[11:34:58] Parsing .bib entries from /Users/dannydarvish/Documents/tex/menu_proceedings/thebib.bib
[11:34:58] Parsed 12 bib entries from /Users/dannydarvish/Documents/tex/menu_proceedings/thebib.bib.
[11:34:58] Server created on 127.0.0.1:53175
[11:34:58] Adding /Users/dannydarvish/Documents/tex/menu_proceedings/main.tex to file watcher.
[11:34:58] Snippet data loaded.
[11:34:58] LaTeX Workshop version: 8.0.3
[11:35:23] PDF command invoked.
[11:35:23] Serving PDF file at http://localhost:53175/viewer.html?file=pdf..JTJGVXNlcnMlMkZkYW5ueWRhcnZpc2glMkZEb2N1bWVudHMlMkZ0ZXglMkZtZW51X3Byb2NlZWRpbmdzJTJGbWFpbi5wZGY
[11:35:23] The encoded path is /Users/dannydarvish/Documents/tex/menu_proceedings/main.pdf
[11:35:23] Open PDF tab for /Users/dannydarvish/Documents/tex/menu_proceedings/main.pdf
[11:35:24] Handle data type: open
[11:35:24] Preview PDF file: /Users/dannydarvish/Documents/tex/menu_proceedings/main.pdf
[11:35:24] Handle data type: loaded
[11:35:34] Handle data type: close
[11:37:55] VIEW command invoked.
[11:37:55] Found root file from active editor: /Users/dannydarvish/Documents/tex/menu_proceedings/main.tex
[11:37:55] Root file remains unchanged from: /Users/dannydarvish/Documents/tex/menu_proceedings/main.tex.
[11:37:55] Serving PDF file at http://localhost:53175/viewer.html?file=pdf..JTJGVXNlcnMlMkZkYW5ueWRhcnZpc2glMkZEb2N1bWVudHMlMkZ0ZXglMkZtZW51X3Byb2NlZWRpbmdzJTJGbWFpbi5wZGY
[11:37:55] The encoded path is /Users/dannydarvish/Documents/tex/menu_proceedings/main.pdf
[11:37:55] Open PDF tab for /Users/dannydarvish/Documents/tex/menu_proceedings/main.pdf
[11:37:55] Handle data type: open
[11:37:55] Preview PDF file: /Users/dannydarvish/Documents/tex/menu_proceedings/main.pdf
[11:37:55] Handle data type: loaded
[11:40:17] LOG command invoked.
</details>

<details>
<summary>Developer Tools Console [Required]</summary>

Nothing suspicious.
</details>

**Screenshots**

**Desktop [Required]:**
 - OS: macOS 10.13.6
 - VS Code version: 1.37.1
 - Extension version: 8.0.3

**Are you using LaTeX Workshop with VS Code Remote?**

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 5.0.0]

**Additional context**

**Comment by jlelong** [comment] 2019-08-19 18:34
Duplicate of #1406.

**Closed by jlelong** 2019-08-19 18:34 UTC
