### ISSUE TITLE
"Cannot read property 'uri' of undefined: TypeError: Cannot read property 'uri' of undefined" when no workspace folder added

### ISSUE THREAD

**Issue by kamransoomro84** [James-Yu/LaTeX-Workshop#2968] opened 2021-11-10 15:26 UTC
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes

## Describe the bug [Required]

I get the following error when running any command when there is no workspace folder added:
```bash
ERR Cannot read property 'uri' of undefined: TypeError: Cannot read property 'uri' of undefined
    at /Users/username/.vscode/extensions/james-yu.latex-workshop-8.21.1/out/src/utils/utils.js:188:103
    at Manager.getOutDir (/Users/username/.vscode/extensions/james-yu.latex-workshop-8.21.1/out/src/components/manager.js:111:94)
    at Manager.tex2pdf (/Users/username/.vscode/extensions/james-yu.latex-workshop-8.21.1/out/src/components/manager.js:214:27)
    at Viewer.checkViewer (/Users/username/.vscode/extensions/james-yu.latex-workshop-8.21.1/out/src/components/viewer.js:165:48)
    at Viewer.openTab (/Users/username/.vscode/extensions/james-yu.latex-workshop-8.21.1/out/src/components/viewer.js:210:26)
    at /Users/username/.vscode/extensions/james-yu.latex-workshop-8.21.1/out/src/commander.js:203:50
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

As described [here](https://github.com/microsoft/vscode/issues/96111), this appears to be due to the incorrect use of the VSCode API.

### To Reproduce

1. Make sure no folder is added to the workspace.
2. Build a LaTeX file or run any command.
3. See error.

### Expected behavior

The command should execute successfully.

### LaTeX Workshop Output [Required]

```
[15:10:29] Initializing LaTeX Workshop.
[15:10:29] Extension root: /Users/k-soomro/.vscode/extensions/james-yu.latex-workshop-8.21.1
[15:10:29] $PATH: /Users/k-soomro/.jenv/shims:/Users/k-soomro/.jenv/bin:/usr/local/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin
[15:10:29] $SHELL: /usr/local/bin/fish
[15:10:29] vscode.env.appName: Visual Studio Code
[15:10:29] vscode.env.remoteName: undefined
[15:10:29] vscode.env.uiKind: 1
[15:10:29] latex-workshop.bind.enter.key: true
[15:10:29] latex-workshop.docker.enabled: false
[15:10:29] latex-workshop.docker.image.latex: ""
[15:10:29] latex-workshop.intellisense.package.enabled: true
[15:10:29] latex-workshop.intellisense.update.aggressive.enabled: false
[15:10:29] latex-workshop.intellisense.update.delay: 1000
[15:10:29] latex-workshop.latex.autoBuild.run: "onFileChange"
[15:10:29] latex-workshop.latex.outDir: "%DIR%"
[15:10:29] latex-workshop.latex.recipes: [
 {
  "name": "latexmk 🔃",
  "tools": [
   "latexmk"
  ]
 },
 {
  "name": "latexmk (latexmkrc)",
  "tools": [
   "latexmk_rconly"
  ]
 },
 {
  "name": "latexmk (lualatex)",
  "tools": [
   "lualatexmk"
  ]
 },
 {
  "name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
  "tools": [
   "pdflatex",
   "bibtex",
   "pdflatex",
   "pdflatex"
  ]
 },
 {
  "name": "Compile Rnw files",
  "tools": [
   "rnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Jnw files",
  "tools": [
   "jnw2tex",
   "latexmk"
  ]
 }
]
[15:10:29] latex-workshop.latex.tools: [
 {
  "name": "lualatexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-lualatex",
   "-outdir=%OUTDIR%",
   "'%DOC%'"
  ],
  "env": {}
 },
 {
  "name": "latexmk_rconly",
  "command": "latexmk",
  "args": [
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "pdflatex",
  "command": "pdflatex",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "bibtex",
  "command": "bibtex",
  "args": [
   "%DOCFILE%"
  ],
  "env": {}
 },
 {
  "name": "rnw2tex",
  "command": "Rscript",
  "args": [
   "-e",
   "knitr::opts_knit$set(concordance = TRUE); knitr::knit('%DOCFILE_EXT%')"
  ],
  "env": {}
 },
 {
  "name": "jnw2tex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"tex\")"
  ],
  "env": {}
 },
 {
  "name": "jnw2texmintex",
  "command": "julia",
  "args": [
   "-e",
   "using Weave; weave(\"%DOC_EXT%\", doctype=\"texminted\")"
  ],
  "env": {}
 },
 {
  "name": "latexmk",
  "command": "latexmk",
  "args": [
   "--pdf",
   "-xelatex",
   "--shell-escape",
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "%DOC%"
  ]
 }
]
[15:10:29] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto"
[15:10:29] Creating a new file watcher.
[15:10:29] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[15:10:29] Creating PDF file watcher.
[15:10:29] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[15:10:29] Creating Bib file watcher.
[15:10:29] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[15:10:29] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[15:10:29] [Server] Creating LaTeX Workshop http and websocket server.
[15:10:29] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[15:10:29] LaTeX Workshop initialized.
[15:10:29] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[15:10:29] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[15:10:29] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[15:10:29] Current workspace folders: []
[15:10:29] Current workspaceRootDir: 
[15:10:30] [Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":53524}
[15:10:30] Snippet data loaded.
[15:11:05] Current workspace folders: []
[15:11:05] Current workspaceRootDir: 
[15:11:05] Found root file from active editor: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:05] Root file changed: from undefined to /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:05] Start to find all dependencies.
[15:11:05] Root file languageId: latex
[15:11:05] Reset file watcher.
[15:11:05] Parsing a file and its subfiles: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:05] Parse fls file.
[15:11:06] Added to file watcher: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:06] Checking for duplicate labels: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex.
[15:11:09] VIEW command invoked.
[15:11:09] Current workspace folders: []
[15:11:09] Current workspaceRootDir: 
[15:11:09] Found root file from active editor: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:09] Keep using the same root file: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:11] Manager.fileWatcher.getWatched: {"/Users/k-soomro/Documents/Docs/Papers/MDPIPaper":["equation.tex"]}
[15:11:11] Manager.filesWatched: ["/Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex"]
[15:11:11] BibWatcher.bibWatcher.getWatched: {}
[15:11:11] BibWatcher.bibsWatched: []
[15:11:11] PdfWatcher.pdfWatcher.getWatched: {}
[15:11:11] PdfWatcher.pdfsWatched: []
[15:11:11] BUILD command invoked.
[15:11:11] The document of the active editor: file:///Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:11] The languageId of the document: latex
[15:11:11] Current workspace folders: []
[15:11:11] Current workspaceRootDir: 
[15:11:11] Found root file from active editor: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:11] Keep using the same root file: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:11] Building root file: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:11] Build root file /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:11] Unexpected Error: please see the console log of the Developer Tools of VS Code.
[15:11:13] BUILD command invoked.
[15:11:13] The document of the active editor: file:///Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:13] The languageId of the document: latex
[15:11:13] Current workspace folders: []
[15:11:13] Current workspaceRootDir: 
[15:11:13] Found root file from active editor: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:13] Keep using the same root file: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:13] Building root file: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:13] Build root file /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:11:13] Unexpected Error: please see the console log of the Developer Tools of VS Code.
[15:11:13] Manager.fileWatcher.getWatched: {"/Users/k-soomro/Documents/Docs/Papers/MDPIPaper":["equation.tex"]}
[15:11:13] Manager.filesWatched: ["/Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex"]
[15:11:13] BibWatcher.bibWatcher.getWatched: {}
[15:11:13] BibWatcher.bibsWatched: []
[15:11:13] PdfWatcher.pdfWatcher.getWatched: {}
[15:11:13] PdfWatcher.pdfsWatched: []
[15:11:15] Manager.fileWatcher.getWatched: {"/Users/k-soomro/Documents/Docs/Papers/MDPIPaper":["equation.tex"]}
[15:11:15] Manager.filesWatched: ["/Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex"]
[15:11:15] BibWatcher.bibWatcher.getWatched: {}
[15:11:15] BibWatcher.bibsWatched: []
[15:11:15] PdfWatcher.pdfWatcher.getWatched: {}
[15:11:15] PdfWatcher.pdfsWatched: []
[15:22:54] Current workspace folders: []
[15:22:54] Current workspaceRootDir: 
[15:22:54] Found root file from active editor: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:22:54] Keep using the same root file: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:22:56] Manager.fileWatcher.getWatched: {"/Users/k-soomro/Documents/Docs/Papers/MDPIPaper":["equation.tex"]}
[15:22:56] Manager.filesWatched: ["/Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex"]
[15:22:56] BibWatcher.bibWatcher.getWatched: {}
[15:22:56] BibWatcher.bibsWatched: []
[15:22:56] PdfWatcher.pdfWatcher.getWatched: {}
[15:22:56] PdfWatcher.pdfsWatched: []
[15:23:05] LOG command invoked: default
[15:23:05] Current workspace folders: []
[15:23:05] Current workspaceRootDir: 
[15:23:05] Found root file from active editor: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:23:05] Keep using the same root file: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:23:07] Manager.fileWatcher.getWatched: {"/Users/k-soomro/Documents/Docs/Papers/MDPIPaper":["equation.tex"]}
[15:23:07] Manager.filesWatched: ["/Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex"]
[15:23:07] BibWatcher.bibWatcher.getWatched: {}
[15:23:07] BibWatcher.bibsWatched: []
[15:23:07] PdfWatcher.pdfWatcher.getWatched: {}
[15:23:07] PdfWatcher.pdfsWatched: []
[15:23:10] LOG command invoked: compiler
[15:23:10] Current workspace folders: []
[15:23:10] Current workspaceRootDir: 
[15:23:10] Found root file from active editor: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:23:10] Keep using the same root file: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:23:12] Manager.fileWatcher.getWatched: {"/Users/k-soomro/Documents/Docs/Papers/MDPIPaper":["equation.tex"]}
[15:23:12] Manager.filesWatched: ["/Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex"]
[15:23:12] BibWatcher.bibWatcher.getWatched: {}
[15:23:12] BibWatcher.bibsWatched: []
[15:23:12] PdfWatcher.pdfWatcher.getWatched: {}
[15:23:12] PdfWatcher.pdfsWatched: []
[15:23:20] LOG command invoked: default
[15:23:20] Current workspace folders: []
[15:23:20] Current workspaceRootDir: 
[15:23:20] Found root file from active editor: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:23:20] Keep using the same root file: /Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex
[15:23:22] Manager.fileWatcher.getWatched: {"/Users/k-soomro/Documents/Docs/Papers/MDPIPaper":["equation.tex"]}
[15:23:22] Manager.filesWatched: ["/Users/k-soomro/Documents/Docs/Papers/MDPIPaper/equation.tex"]
[15:23:22] BibWatcher.bibWatcher.getWatched: {}
[15:23:22] BibWatcher.bibsWatched: []
[15:23:22] PdfWatcher.pdfWatcher.getWatched: {}
[15:23:22] PdfWatcher.pdfsWatched: []
```

### Developer Tools Console [Required]

```
ERR Cannot read property 'uri' of undefined: TypeError: Cannot read property 'uri' of undefined
    at /Users/username/.vscode/extensions/james-yu.latex-workshop-8.21.1/out/src/utils/utils.js:188:103
    at Manager.getOutDir (/Users/username/.vscode/extensions/james-yu.latex-workshop-8.21.1/out/src/components/manager.js:111:94)
    at Manager.tex2pdf (/Users/username/.vscode/extensions/james-yu.latex-workshop-8.21.1/out/src/components/manager.js:214:27)
    at Viewer.checkViewer (/Users/username/.vscode/extensions/james-yu.latex-workshop-8.21.1/out/src/components/viewer.js:165:48)
    at Viewer.openTab (/Users/username/.vscode/extensions/james-yu.latex-workshop-8.21.1/out/src/components/viewer.js:210:26)
    at /Users/username/.vscode/extensions/james-yu.latex-workshop-8.21.1/out/src/commander.js:203:50
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Mac OS 11.6.1
 - VS Code version: 1.62.1
 - Extension version: 8.21.1
 - TeX distribution version:  TeX Live 2021

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

**Comment by jlelong** [comment] 2021-11-10 15:28
Duplicate of #2935

Please downgrade to v8.20.2 as a workaround.

https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#install-an-older-version-of-latex-workshop

**Closed by jlelong** 2021-11-10 15:28 UTC

**Comment by jlelong** [comment] 2021-11-10 15:34
Because it is fixed in the `master` branch but it will only be available in the next release.
