### ISSUE TITLE
vscode is giving fatal error on saving document

### ISSUE THREAD

**Issue by thefirstcoders** [James-Yu/LaTeX-Workshop#2140] opened 2020-06-05 05:24 UTC
this is the error: "Recipe terminated with fatal error: spawn latexmk ENOENT."

**Comment by tamuratak** [comment] 2020-06-05 05:38
Duplicate of #1143. See https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#setting-path-environment-variable.

**Closed by tamuratak** 2020-06-05 05:38 UTC
