### ISSUE TITLE
Compilation progress doesn't clear after failure to build

### ISSUE THREAD

**Issue by tecosaur** [James-Yu/LaTeX-Workshop#1383] opened 2019-05-17 05:19 UTC
This is to deal with the progress bar not resetting reset after build failure aspect of #1376.

**Comment by jotagah** [comment] 2019-05-19 15:18
Yes, I have the same issue. On any compilation error from any reciple I choose the LATEX Compilation Live Info shows a still running process and I am not able to terminate the process "by calling Kill LaTeX compiler process from the Command Palette or calling Terminate current compilation from the TeX badge in the Build LaTeX project item" -- both fail to succeed.

I have to close and restar MS Code to proceed.

**Comment by memeplex** [comment] 2019-05-21 06:45
This is a duplicate of my report https://github.com/James-Yu/LaTeX-Workshop/issues/1376 @James-Yu .

**Comment by jlelong** [comment] 2019-05-21 12:28
@jotagah the issue is that the time counter is not stopped when compilation fails but this is not related to having a LaTeX process running or not and the LaTeX is actually really killed.

You do not need to restart VSCode. Everything will work fine the next you compile.

**Comment by memeplex** [comment] 2019-05-21 15:19
To be clear, after an error in compilation:

1. The progress bar won't disappear, sometimes it is empty, sometimes it is full, sometimes it is somewhere in between.
2. Clicking on the progress bar opens the compilation live info. A seconds counter is forever running there.
3. Launching the "Terminate current compilation" task does nothing to stop the progress bar nor the counter.
4. Nothing is being compiled, the latexmk processes are dead for good.
5. I'm able to compile again without restarting vscode.
6. AFAICS it's just an UI problem, as if this "compilation status" stuff lost connection from the underlying building process.

**Comment by tecosaur** [comment] 2019-05-21 17:39
@memeplex I created this issue to deal with what I implemented, and will fix, which is points 1&2 of you're list. Because I do not intend to look at the rest, I thought it was worth separating those out.

**Comment by memeplex** [comment] 2019-05-21 18:07
@tecosaur I understand, I was just trying to point out that there is no "rest" as far as I am concerned, the problem you open a new issue for is the same problem I reported. I see there could have been some confusion because of the subject of my original report (which seemed to imply some continuous compilation was indeed going on), so sorry if that was the case. Also @rahulguptakota comment was a bit confusing regarding this point.

**Comment by tecosaur** [comment] 2019-05-27 11:46
@jlelong I see from the changelog issue I created that you can assign me. I'd be happy if you'd assign me to this issue, as I intend to resolve it sometime in the near future. It's minor I just need to (a) have 5 minutes free, and (b) remember to do it. Assigning me would help with (b).

**Comment by tamuratak** [comment] 2019-06-11 09:17
@tecosaur  If you cannot fix this problem by yourself, please say so.

**Comment by tecosaur** [comment] 2019-06-11 09:26
@tamuratak Sorry, just trying to avoid starting coding over my exam period since it's a trap and I do ***not*** need a distraction right now. I'm freed up from Friday though which is the good news.
If you want to take a look right now then feel free! I just thought since it's mainly an aesthetic issue and I'm 90% sure of what needs to be done to fix it and where the relevant bits in my code are I may as well do it, and didn't think a few weeks would be an issue.

**Closed** 2019-06-16 19:26 UTC
Labels: enhancement
