### ISSUE TITLE
Add a magnifying glass

### ISSUE THREAD

**Issue by phgmacedo** [James-Yu/LaTeX-Workshop#2594] opened 2021-03-21 19:47 UTC
Is your feature request related to a problem? Please describe.
While working on a document, with the .tex file side by side with the pdf file. While the .tex file usually takes most of the space, sometimes it's important to check a detail in the PDF. Resizing the window for the PDF or zooming into the PDF is however annoying.

Describe the solution you'd like
The magnifying glass from other latex editors, like in the screenshot.

![Snipaste_2021-03-21_16-43-47](https://user-images.githubusercontent.com/2473545/111918689-1430bb00-8a65-11eb-9fd5-676b48dc430a.png)

**Comment by tamuratak** [comment] 2021-03-21 20:46
Duplicate of #2076.

**Closed by tamuratak** 2021-03-21 20:46 UTC
Labels: duplicate
