### ISSUE TITLE
Version 1.36 of VScode will lead to a bug of web browser viewer

### ISSUE THREAD

**Issue by xfdywy** [James-Yu/LaTeX-Workshop#1480] opened 2019-07-05 11:53 UTC
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes 

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**
The newest version 1.36:     Web browser viewer cannot auto refresh after change the tex file and recompile it successfully.   Also, the web browser viewer cannot forward and inverse search(synctex). I change nothing config but upgread the vscode. And  everything is normal in the previous version 1.35.  When I uninstall the version1.36 and reinstall the previous version 1.35, everything is ok again. 

**To Reproduce**
1. Install the newest version vscode 1.36.
2. Install the latex-workshop extension and use it to compile a tex file.
3. View the pdf in the web browser viewer.

**Expected behavior**

**Logs [Required]**
Please paste the whole log messages here, not parts of ones. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>

</details>

<details>
<summary>Developer Tools Console [Required]</summary>

</details>

**Screenshots**

**Desktop [Required]:**
 - OS: [e.g. Windows 10]
 - VS Code version: [e.g. 1.20.0]
 - Extension version: [e.g. 5.0.0]

**Additional context**

**Comment by jlelong** [comment] 2019-07-05 11:55
Duplicate of #1477.

**Closed by jlelong** 2019-07-05 11:55 UTC
