### ISSUE TITLE
PDF panel not close with  Ctrl+W

### ISSUE THREAD

**Issue by amirhakh** [James-Yu/LaTeX-Workshop#2346] opened 2020-10-27 05:00 UTC
When I open the PDF panel, I can close it only with the mouse, not with the keyboard shortcut like (Ctrl+w or Ctrl+F4).
Can you fix it?

**Comment by tamuratak** [comment] 2020-10-27 05:01
Duplicate of #2334

**Closed by tamuratak** 2020-10-27 05:01 UTC
