### ISSUE TITLE
Reverse synctex broken on Windows when not using synctexjs

### ISSUE THREAD

**Issue by dasch8** [James-Yu/LaTeX-Workshop#1240] opened 2019-03-20 15:01 UTC
**Describe the bug**
Reverse synctex doesn't work on Windows when using external synctex.

**To Reproduce**
0. Use a Windows machine
1. Disable internal synctex (`"latex-workshop.synctex.synctexjs.enabled": false`)
2. Compile Latex file
3. Open pdf viever
4. Ctrl+click somwhere
5. Nothing happens

**Expected behavior**
Corresponding line in Latex source should be highlighted in VSCode.

**Logs**
Please paste the log messages here. It is very important to identify problems. If you think the logs are unrelated, please say so.

<details>
<summary>LaTeX Workshop Output</summary>

[15:53:43] Executing synctex with args edit,-o,96:206.9180754226268:453.76853055916774:c:\Users\dasch8\latex\main.pdf
</details>

<details>
<summary>Developer Tools Console</summary>

console.ts:134 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, lstat 'c:\Users\dasch8\latex\main.tex
'
t.log @ console.ts:134
console.ts:134 [Extension Host] stack trace: Error: ENOENT: no such file or directory, lstat 'c:\Users\dasch8\latex\main.tex
'
	at Object.realpathSync (fs.js:1744:7)
	at Object.exports.wrapFsWithAsar.fs.realpathSync (ELECTRON_ASAR.js:335:40)
	at module.exports.t.Locator.<anonymous> (C:\Users\dasch8\.vscode\extensions\james-yu.latex-workshop-6.2.2\out\src\main.js:371:335399)
	at Generator.next (<anonymous>)
	at s (C:\Users\dasch8\.vscode\extensions\james-yu.latex-workshop-6.2.2\out\src\main.js:371:330388)
t.log @ console.ts:134
log.ts:173   ERR ENOENT: no such file or directory, lstat 'c:\Users\dasch8\latex\main.tex
': Error: ENOENT: no such file or directory, lstat 'c:\Users\dasch8\latex\main.tex
'
	at Object.realpathSync (fs.js:1744:7)
	at Object.exports.wrapFsWithAsar.fs.realpathSync (ELECTRON_ASAR.js:335:40)
	at module.exports.t.Locator.<anonymous> (C:\Users\dasch8\.vscode\extensions\james-yu.latex-workshop-6.2.2\out\src\main.js:371:335399)
	at Generator.next (<anonymous>)
	at s (C:\Users\dasch8\.vscode\extensions\james-yu.latex-workshop-6.2.2\out\src\main.js:371:330388)
</details>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code version: 1.32.3
 - Extension version: 6.2.2

**Additional context**
I tracked the bug down to here:
https://github.com/James-Yu/LaTeX-Workshop/blob/589a0eb26c088e48ac21990930f803e2b01eb962/src/components/locator.ts#L273-L281

`fs.realpathSync(record.input)` fails because there is a newline character at the end of the file path. If Docker is used for synctex it also fails because the path to the file in the container is not replaced with the path to the file in the host. I'm creating a pull request with my fix.

**Comment by newmrdenis** [comment] 2019-03-20 22:22
The same on Linux. (Yes, I put the magic line into Okular viewer)

**Comment by jlelong** [comment] 2019-03-21 06:53
If I understand well the original post was concerned with the internal pdf viewer, so @newmrdenis your comment is a bit off topic in this issue. If you have trouble with using external viewer and could not find any help in closed issues, open a new one. Note that, when using an external viewer, it is responsible for determining the location in the `.tex` file and firing vscode at this location.

**Comment by dasch8** [comment] 2019-03-21 07:28
Yes it happened with the internal viewer (browser or tab). However the problem is with how the synctex output gets parsed, so it probably also affects external viewers if you get reverse search to work.

**Comment by jlelong** [comment] 2019-03-21 07:36
> However the problem is with how the synctex output gets parsed, so it probably also affects external viewers if you get reverse search to work.

When using an external viewer, the external viewer is responsible for calling `synctex` and determining the location in the .tex file and then it fires the configured editor with `file:line`. So the issue only affects the internal viewer.

However, I cannot reproduce the issue on OS X.

**Comment by dasch8** [comment] 2019-03-21 07:56
> When using an external viewer, the external viewer is responsible for calling synctex and determining the location in the .tex file and then it fires the configured editor with file:line. So the issue only affects the internal viewer.

Oh, I see, I never tried that.

> However, I cannot reproduce the issue on OS X.
It might have to do with how the file system API treats paths. The problem is the line break at the end of the path. So either the API on OS X  (and I'd guess UNIX in general) is more tolerant towards that or the line break is not in the file path on these systems for some reason.

**Comment by newmrdenis** [comment] 2019-03-21 08:54
@jlelong I am sorry(. I became confused about "external".

**Comment by jlelong** [comment] 2019-03-21 09:03
@newmrdenis I was also led astray by "external".

**Comment by jlelong** [comment] 2019-03-22 14:43
Closed by PR #1241

**Closed by jlelong** 2019-03-22 14:43 UTC
