### ISSUE TITLE
can't build tex in iCloud

### ISSUE THREAD

**Issue by AlanKSH** [James-Yu/LaTeX-Workshop#255] opened 2017-09-03 14:46 UTC
### Description

I store the tex file in iCloud, specifically say PDFExpert,  and when I build it, VScode shows 'Toolchain terminated by a fatal error'. But other directories are fine.

### How to reproduce

1. 
2. 
3. 

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

</details>
file: 'file:///Users/username/Library/Mobile%20Documents/3L68KQB4HG~com~readdle~CommonDocuments/Documents/Study/CIS675/Homework1.tex'
severity: 'Error'
message: 'I can't find file `"/Users/username/Library/Mobile Documents/3L68KQB4HG"' <to be read again>                     \protect  <*> ...rs/username/Library/Mobile Documents/3L68KQB4HG~                                                   com~readdle~CommonDocument... (Press Enter to retry, or Control-D to exit) Please type another input file name ! Emergency stop. <to be read again>                     \protect  <*> ...rs/username/Library/Mobile Documents/3L68KQB4HG~                                                   com~readdle~CommonDocument... !  ==> Fatal error occurred, no output PDF file produced! Transcript written on texput.log. Latexmk: Errors, so I did not complete making targets 
'
at: '1,1'
source: 'LaTeX'

<details>
<summary>Developer Tools Console</summary>

</details>

**Comment by James-Yu** [comment] 2017-09-04 01:28
Duplicate of #234 . The error message is generated by LaTeX compiler, which does not support `~` in paths.

**Closed by James-Yu** 2017-09-04 01:28 UTC

**Comment by kaseyzapatka** [comment] 2021-10-12 03:26
@James-Yu, do you know if there is a more recent version of any of the LaTeX compliers to support the `~` in iCloud file paths? I have my a dissertation chapter stored on iCloud and want to compile but it seems like I'm still having this problem. Not sure what the best work-around is other than completely changing where the project is located, which seems cumbersome.

Thanks. Best, 
Kasey
