### ISSUE TITLE
Folding region

### ISSUE THREAD

**Issue by VolodyaRybakov** [James-Yu/LaTeX-Workshop#2406] opened 2020-12-01 07:01 UTC
# Folding region

When I write my code between `%Region` and `%Endregion`, I can't fold it.

## Expected behavior

I would like the code between `%Region` and `%Endregion` to collapse as if it were written between `\begin{...}` and `\end{...}`.

## Alternatives

The *LaTeX language support* from *Long Nhat Nguyen* supports the desired function. It is also possible to add code between curly brackets `{}` in this extension.

![Screenshot_10](https://user-images.githubusercontent.com/28715425/100707687-138fee00-33bc-11eb-8174-d1cc57a8d036.png)

**Comment by tamuratak** [comment] 2020-12-01 07:18
Duplicate of #1716

Use 
```
%\begingroup
...
%\endgroup
```

See https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#code-folding

**Closed by tamuratak** 2020-12-01 07:18 UTC
Labels: feature-request

**Comment by VolodyaRybakov** [comment] 2020-12-01 09:34
I use additional cosmetic extensions, such as highlighting region blocks, and using%\begingroup...%\endgroupdoesn't give you that option -- С уважением,Владимир Рыбаков+7 (977) 400-69-63   01.12.2020, 10:19, "Takashi Tamura" <notifications@github.com>: Duplicate of #1716Use%\begingroup
...
%\endgroup
See https://github.com/James-Yu/LaTeX-Workshop/wiki/Environments#code-folding—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tamuratak** [comment] 2020-12-01 23:25
#2407

**Comment by jlelong** [comment] 2020-12-02 13:29
Implemented in #2409.
