### ISSUE TITLE
Changes in included .tex files (with \include(file)) are not detected

### ISSUE THREAD

**Issue by JungStar** [James-Yu/LaTeX-Workshop#1119] opened 2019-01-17 17:06 UTC
**Description**
Changes in files that are included with \include(file) are not detected even when manually invoking rebuilding.

**To Reproduce**
1. Change the contents of an additional included source file ( \include(another_file))
2. Invoke rebuild
3. Built is triggered, but latex compiler (latexmk) says "All targets (...) are up-to-date", hence the PDF is not updated 

**Expected behavior**
See the changed contents of "another_file"

**Logs**
Latex-Workshop
BUILD command invoked.
Try root file in root directory: f:\main.tex
Found root file in root directory: f:\main.tex
Root file remains unchanged from: f:\main.tex
Building root file: f:\main.tex
Build root file f:\main.tex
Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=./,f:/
File watcher: responding to change in f:\another_file.tex
Parsing f:\another_file.tex
Recipe of length 1 finished.
Successfully built f:\main.tex
Refresh PDF viewer for f:\main.pdf
Preview PDF file: f:\main.pdf

Latex Compiler
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
Latexmk: All targets (./main.pdf) are up-to-date

**Notes**
Modifying main.tex is correctly recognized and rebuilds show updated content from all updated files.

Tested with both TEX Live 2017 and 2018, issue persists.
Downgrade to Latex Workshop 5.19.0 fixes the issue.

**Desktop :**
 - Windows 10
 - VS Code version:  1.30.2
 - Extension version:  5.20.1 and 5.20.0 (from a quick test)

If you need more detailed information let me know. I hope this suffices for now. Thank you very much for keeping up the good work!

**Comment by jlelong** [comment] 2019-01-17 17:22
Duplicate of #1114.

**Closed by jlelong** 2019-01-17 17:22 UTC
