### ISSUE TITLE
"Recipe terminated in error" message should dismiss upon successful compilation

### ISSUE THREAD

**Issue by xsanda** [James-Yu/LaTeX-Workshop#2079] opened 2020-05-12 12:54 UTC
**Is your feature request related to a problem? Please describe.**
When I have a compilation error, and I fix it, the error popovers in the bottom left stay open.

**Describe the solution you'd like**
Upon a successful compilation, any alerts regarding unsuccessful compilations should be dismissed.

**Describe alternatives you've considered**
- Clicking close on the error message manually. This requires the mouse, which most other elements of developing don’t require.
- Leaving it open looks messy, and if I don’t have the bottom panel open then it overlaps with the PDF preview.

**Additional context**
Steps to reproduce:

1. Write invalid LaTeX code.
2. Build LaTeX project (⌥⌘B).
3. Error popup opens in bottom right.
4. Fix LaTeX code.
5. Build LaTeX project (⌥⌘B).
6. Successful compilation.
7. Error popup stays open.
  ![image](https://user-images.githubusercontent.com/8607022/81692945-12ff2c80-9457-11ea-8bd9-e997e35854ad.png)

**Comment by tamuratak** [comment] 2020-05-12 13:25
Duplicate of #898

**Closed by tamuratak** 2020-05-12 13:25 UTC
Labels: feature-request
