### ISSUE TITLE
Problems do not vanish after errors are corrected.

### ISSUE THREAD

**Issue by Lencerf** [James-Yu/LaTeX-Workshop#104] opened 2017-04-10 18:48 UTC
Please see the screenshots. In the first image, I missed a `$` before `\dfrac{...`. In the second image, I added the `$` and latex toolchain succeeded. But the errors are still there. Is this a bug?
![error](https://cloud.githubusercontent.com/assets/6895736/24877030/d42232ca-1dfb-11e7-8122-4f54bca53d75.png)
![correct](https://cloud.githubusercontent.com/assets/6895736/24877029/d421003a-1dfb-11e7-8b4c-61705861e979.png)
(✓ in the status bar indicates that the file has been compiled successfully.)

**Comment by James-Yu** [comment] 2017-04-11 00:51
Can you please attach the log for both tool chain executions? I cannot reproduce the problem on my side, and the log may help identifying the problem.

**Comment by Lencerf** [comment] 2017-04-11 12:35
Hi @James-Yu, I made another simple example:
```tex
\documentclass{article}
\begin{document}
    $a_b$ $d$ a_1
\end{document}
```
Building those codes gives error. Then I change `a_1` to `$a_1$`. success. But the red wave lines are still there.

![su](https://cloud.githubusercontent.com/assets/6895736/24909316/6781b168-1e91-11e7-8840-7a2feb90167d.png)

Below are all the logs. Thank you! 
```
[08:27:45] Initializing LaTeX Workshop.
[08:27:45] Creating LaTeX Workshop http and websocket server.
[08:27:45] LaTeX Workshop initialized.
[08:27:45] Found root file from active editor: /Volumes/HDD/da/test.tex
[08:27:45] Root file changed from: undefined. Find all dependencies.
[08:27:45] Instatiating new file watcher for /Volumes/HDD/da/test.tex
[08:27:45] Parsing /Volumes/HDD/da/test.tex
[08:27:45] Server created on 127.0.0.1:50630
[08:27:45] Default environments loaded
[08:27:45] Default commands loaded
[08:27:45] Default unimathsymbols loaded
[08:27:52] BUILD command invoked.
[08:27:52] Found root file from active editor: /Volumes/HDD/da/test.tex
[08:27:52] Root file remains unchanged from: /Volumes/HDD/da/test.tex.
[08:27:52] Building root file: /Volumes/HDD/da/test.tex
[08:27:52] Build root file /Volumes/HDD/da/test.tex
[08:27:52] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-xelatex,/Volumes/HDD/da/test
[08:27:52] LaTeX log parsed with 2 messages.
[08:27:52] Toolchain returns with error. Latexmk: applying rule 'xelatex'...
This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(/Volumes/HDD/da/test.tex
LaTeX2e <2017/01/01> patch level 3
Babel <3.9r> and hyphenation patterns for 22 language(s) loaded.
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2016basic/texmf-dist/tex/latex/base/size10.clo))
(./test.aux)
/Volumes/HDD/da/test.tex:3: Missing $ inserted.
<inserted text> 
                $
l.3     $a_b$ $d$ a_
                    1
/Volumes/HDD/da/test.tex:4: Missing $ inserted.
<inserted text> 
                $
l.4 \end{document}
                  
[1] (./test.aux) )
(see the transcript file for additional information)
Output written on test.xdv (1 page, 588 bytes).
SyncTeX written on test.synctex.gz.
Transcript written on test.log.
=== TeX engine is 'XeTeX'
Latexmk: Errors, so I did not complete making targets

[08:28:32] File watcher: responding to change in /Volumes/HDD/da/test.tex
[08:28:32] Parsing /Volumes/HDD/da/test.tex
[08:28:33] BUILD command invoked.
[08:28:33] Found root file from active editor: /Volumes/HDD/da/test.tex
[08:28:33] Root file remains unchanged from: /Volumes/HDD/da/test.tex.
[08:28:33] Building root file: /Volumes/HDD/da/test.tex
[08:28:33] Build root file /Volumes/HDD/da/test.tex
[08:28:33] Toolchain step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-xelatex,/Volumes/HDD/da/test
[08:28:33] Toolchain of length 1 finished.
[08:28:33] Successfully built /Volumes/HDD/da/test.tex
[08:28:33] No PDF viewer connected for /Volumes/HDD/da/test.pdf
[08:28:45] Root file remains unchanged from: /Volumes/HDD/da/test.tex.
[08:28:48] Found root file from active editor: /Volumes/HDD/da/test.tex
[08:28:48] Root file remains unchanged from: /Volumes/HDD/da/test.tex.
[08:31:48] Root file remains unchanged from: /Volumes/HDD/da/test.tex.
```

**Comment by Lencerf** [comment] 2017-04-11 12:40
I seem to find the source of this problem. After I have changed my toolchain from `latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-xelatex` to `latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf`, everything works correctly. So LaTeXWorkshop does not support XeLaTeX yet?

**Comment by James-Yu** [comment] 2017-04-11 14:18
Hmm that would be interesting. Will look into it later.

**Comment by James-Yu** [comment] 2017-04-12 02:47
Got the problem. When using `latexmk`, the log parser will only parse the last log segment in the log messages to avoid repeating errors for the same line. This works well for `pdf` toolchain. However, `xelatex` use `xdvipdfmx` as its last executable, which does not provide any significant logs. So the extension consider `latexmk` skipped the compilation, and previous errors are preserved.

Will check for possible solutions.

**Comment by James-Yu** [comment] 2017-04-12 03:06
Will be released to marketplace shortly.

**Closed by James-Yu** 2017-04-12 03:06 UTC

**Comment by Lencerf** [comment] 2017-04-13 13:03
I have tried the new version and it works correctly now. Thank you  very much for this great extension!
