### ISSUE TITLE
Synctex reverse

### ISSUE THREAD

**Issue by atomdistortion** [James-Yu/LaTeX-Workshop#1314] opened 2019-04-15 06:33 UTC
Issue Type: <b>Bug</b>

It is often, when reverse Synctex does not work, especially when I switch it to another LATEX project or other generated file in the same project. And this function often starts work  after removal of synctex files and generating new pdf. But it happens not always. Sometimes this functionality appears suddenly, in other cases I have to restart VSCode once or two times, in hard cases it is necessary to restart system.

Extension version: 6.4.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (9.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by innerlee** [comment] 2019-04-16 04:01
Heisenbug, don't know how to trigger it, but it happens often

**Comment by atomdistortion** [comment] 2019-04-18 06:48
Probably this happens with non-english languages, for ex. I'm writing in russian.

**Comment by tamuratak** [comment] 2019-04-24 23:07
Please notice that LaTeX Workshop does not support multiple projects in one window. See https://github.com/James-Yu/LaTeX-Workshop/issues/12#issuecomment-279634020.

**Comment by lyyc199586** [comment] 2019-04-25 01:07
same issue

**Comment by atomdistortion** [comment] 2019-04-25 06:34
That helps (build LaTeX project, I choose right-mouse menu). I don't have many projects, just several separate files in the same workspace, they use common data. Nevertheless, that is not convenient. I save a project by Ctrl-S (then it build the project), and choose the root file by the left-side browser, so could be it possible to check chosen file and build it or customize that ability.

**Comment by tamuratak** [comment] 2019-04-25 09:10
@atomdistortion, I understand that you are proposing a feature request. Is that right? If so, please close this issue and open a new issue.

**Comment by jlelong** [comment] 2019-04-27 06:53
It is indeed possible to have several LaTeX projects in the same workspace. I do not understand what the issue is exactly. Can you describe a use case?

**Comment by PierreMarchand20** [comment] 2019-04-29 13:16
I have also had this problem for one month or two now. Sometimes it works and sometime it does not. I will try to reproduce it, but not sure it is easy.

**Comment by tamuratak** [comment] 2019-04-30 00:39
@PierreMarchand20 please show us console log when this problem occurs next time. You can refer to [this](https://code.visualstudio.com/api/extension-guides/webview#inspecting-and-debugging-webviews) for debugging webviews.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

**Comment by PierreMarchand20** [comment] 2019-04-30 08:12
I do not know for the window opened when I toggle the developer tools, I will try next time the issue appears. But the output window (the one below where log messages are displayed) is the one where I said nothing happened while I was trying to click on the pdf viewer.

![image](https://user-images.githubusercontent.com/15056323/56948386-43b44280-6b30-11e9-8778-a6fc7ee617fb.png)

**Comment by atomdistortion** [comment] 2019-04-30 08:17
[-1556612133674.log](https://github.com/James-Yu/LaTeX-Workshop/files/3130396/-1556612133674.log)
That is LOG message for the file, which does not support reverse synctex at that current moment

**Comment by jlelong** [comment] 2019-05-09 11:36
Is this fixed with #1350?

**Comment by innerlee** [comment] 2019-05-09 11:43
Close. Still need a ctrl+right click before working

**Comment by jlelong** [comment] 2019-05-09 11:57
`ctrl+click` is the standard way to call `synctex` from the viewer.

**Closed by jlelong** 2019-05-09 11:57 UTC
Labels: can't reproduce, need more info
