### ISSUE TITLE
PDF preview stays blank

### ISSUE THREAD

**Issue by aradarbel10** [James-Yu/LaTeX-Workshop#3670] opened 2023-01-25 21:18 UTC
### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]
You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.
You visited the wiki?: Yes

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.
You can compile a TeX document manually?: Yes

## Describe the bug [Required]

Until recently the PDF preview worked just fine, but today suddenly the preview stays completely blank.
The compilation goes successfuly, and I can view the resulting PDF with any external viewer, only the extension's viewer doesn't show anything.

Moreover when I try `LaTeX Workshop: View LaTeX PDF file in web browser` the browser shows up with "127.0.0.1 refused to connect."

### To Reproduce

1. Open up vscode with `code .`
2. Open any tex file
3. Compile with `LaTeX Workshop: Build LaTeX project`
4. Open preview window with `LaTeX Workshop: View LaTeX PDF file`

### Expected behavior
I expected the PDF preview to show the PDF file, either in a new vscode tab or in a new browser tab.

### LaTeX Workshop Output [Required]
```
[23:05:47][Logger] New log placeholder %WS1% registered for /home/aradarbel10/math/uni-notes/calc2a .
[23:05:47][Config] Configuration for workspace: file://%WS1% .
[23:05:47][Config] editor.acceptSuggestionOnEnter: "on" .
[23:05:47][Config] latex-workshop.bind.enter.key: true .
[23:05:47][Config] latex-workshop.docker.enabled: false .
[23:05:47][Config] latex-workshop.docker.image.latex: "" .
[23:05:47][Config] latex-workshop.hover.preview.mathjax.extensions: [] .
[23:05:47][Config] latex-workshop.intellisense.package.enabled: true .
[23:05:47][Config] latex-workshop.intellisense.update.aggressive.enabled: false .
[23:05:47][Config] latex-workshop.intellisense.update.delay: 1000 .
[23:05:47][Config] latex-workshop.latex.autoBuild.run: "onFileChange" .
[23:05:47][Config] latex-workshop.latex.build.forceRecipeUsage: true .
[23:05:47][Config] latex-workshop.latex.outDir: "%DIR%" .
[23:05:47][Config] latex-workshop.latex.recipes: [
 {
  "name": "latexmk",
  "tools": [
   "latexmk"
  ]
 },
 {
  "name": "latexmk (latexmkrc)",
  "tools": [
   "latexmk_rconly"
  ]
 },
 {
  "name": "latexmk (lualatex)",
  "tools": [
   "lualatexmk"
  ]
 },
 {
  "name": "latexmk (xelatex)",
  "tools": [
   "xelatexmk"
  ]
 },
 {
  "name": "pdflatex -> bibtex -> pdflatex * 2",
  "tools": [
   "pdflatex",
   "bibtex",
   "pdflatex",
   "pdflatex"
  ]
 },
 {
  "name": "Compile Rnw files",
  "tools": [
   "rnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Jnw files",
  "tools": [
   "jnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "Compile Pnw files",
  "tools": [
   "pnw2tex",
   "latexmk"
  ]
 },
 {
  "name": "tectonic",
  "tools": [
   "tectonic"
  ]
 }
] .
[23:05:47][Config] latex-workshop.latex.tools: [
 {
  "name": "latexmk",
  "command": "latexmk",
  "args": [
   "-xelatex",
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "%DOC%"
  ]
 }
] .
[23:05:47][Config] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto" .
[23:05:47][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[23:05:47][Server] Creating LaTeX Workshop http and websocket server.
[23:05:47][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":38679}
[23:05:47][Extension] Initializing LaTeX Workshop.
[23:05:47][Extension] Extension root: /home/aradarbel10/.vscode-server/extensions/james-yu.latex-workshop-9.5.0
[23:05:47][Extension] $PATH: /home/aradarbel10/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/bin/remote-cli:/home/aradarbel10/.opam/4.14.0/bin:/home/aradarbel10/.elan/bin:/home/aradarbel10/.local/bin:/home/aradarbel10/.nvm/versions/node/v18.4.0/bin:/home/aradarbel10/.cargo/bin:/home/aradarbel10/.cabal/bin:/home/aradarbel10/.ghcup/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Azure Data Studio/bin:/mnt/c/Users/arada/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/arada/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/arada/.dotnet/tools:/mnt/c/Users/arada/AppData/Local/Programs/MiKTeX/miktex/bin/x64/:/snap/bin:/home/aradarbel10/.dotnet/tools
[23:05:47][Extension] $SHELL: /bin/bash
[23:05:47][Extension] $LANG: C.UTF-8
[23:05:47][Extension] $LC_ALL: undefined
[23:05:47][Extension] process.platform: linux
[23:05:47][Extension] process.arch: x64
[23:05:47][Extension] vscode.env.appName: Visual Studio Code
[23:05:47][Extension] vscode.env.remoteName: wsl
[23:05:47][Extension] vscode.env.uiKind: 1
[23:05:47][Extension] LaTeX Workshop initialized.
[23:05:47][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[23:05:47][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[23:05:47][Manager] Current workspace folders: ["file://%WS1%"]
[23:05:47][Manager] Found root file from active editor: %WS1%/misc/complete-func-space/complete-func-space.tex
[23:05:47][Manager] Root file changed: from undefined to %WS1%/misc/complete-func-space/complete-func-space.tex
[23:05:47][Manager] Start to find all dependencies.
[23:05:47][Manager] Root file languageId: latex
[23:05:47][Cacher][Watcher] Reset.
[23:05:47][Cacher] Adding %WS1%/misc/complete-func-space/complete-func-space.tex .
[23:05:47][Cacher] Caching %WS1%/misc/complete-func-space/complete-func-space.tex .
[23:05:47][Cacher] Updated inputs of %WS1%/misc/complete-func-space/complete-func-space.tex .
[23:05:47][Server] valdOrigin is http://127.0.0.1:38679
[23:05:47][Cacher][Watcher] Watched %WS1%/misc/complete-func-space/complete-func-space.tex .
[23:05:47][DupLabel] Checking for duplicate labels: %WS1%/misc/complete-func-space/complete-func-space.tex .
[23:05:47][Cacher] Updated elements of %WS1%/misc/complete-func-space/complete-func-space.tex .
[23:05:47][Cacher] Updated bibs of %WS1%/misc/complete-func-space/complete-func-space.tex .
[23:05:47][Cacher] Cached %WS1%/misc/complete-func-space/complete-func-space.tex .
[23:05:47][Cacher] Parsing .fls %WS1%/misc/complete-func-space/complete-func-space.fls .
[23:05:47][Cacher] Found .aux %WS1%/misc/complete-func-space/complete-func-space.tex from .fls %WS1%/misc/complete-func-space/complete-func-space.fls , parsing.
[23:05:47][Cacher] Parsed .aux %WS1%/misc/complete-func-space/complete-func-space.tex .
[23:05:47][Cacher] Parsed .fls %WS1%/misc/complete-func-space/complete-func-space.fls .
[23:05:48][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:38679/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRmhvbWUlMkZhcmFkYXJiZWwxMCUyRm1hdGglMkZ1bmktbm90ZXMlMkZjYWxjMmElMkZtaXNjJTJGY29tcGxldGUtZnVuYy1zcGFjZSUyRmNvbXBsZXRlLWZ1bmMtc3BhY2UucGRm .
[23:05:48][Cacher][PDF] Watched file://%WS1%/misc/complete-func-space/complete-func-space.pdf .
[23:05:48][Viewer] Open PDF tab for file://%WS1%/misc/complete-func-space/complete-func-space.pdf
[23:06:05][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:38679/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRmhvbWUlMkZhcmFkYXJiZWwxMCUyRm1hdGglMkZ1bmktbm90ZXMlMkZjYWxjMmElMkZtaXNjJTJGY29tcGxldGUtZnVuYy1zcGFjZSUyRmNvbXBsZXRlLWZ1bmMtc3BhY2UucGRm .
[23:06:05][Viewer] Open PDF tab for file://%WS1%/misc/complete-func-space/complete-func-space.pdf
[23:06:40][Commander] SHOWLOG command invoked: compiler
[23:06:42][Commander] SHOWLOG command invoked: default
[23:07:15][Commander] SHOWLOG command invoked: default
[23:07:15][Commander] SHOWLOG command invoked: default
```

### Developer Tools Console [Required]
Here are the messages from the console that seem relevant
```
INFO [perf] Render performance baseline is 23ms
DevTools failed to load source map: Could not load content for https://vscode-remote+wsl-002bubuntu-002d20-002e04.vscode-resource.vscode-cdn.net/home/aradarbel10/.vscode-server/extensions/james-yu.latex-workshop-9.5.0/node_modules/pdfjs-dist/build/pdf.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not parse content for vscode-webview://1csp6db1meujds206fssv43d1i6134jvivtr4iqmrcukq3m8vnjh/pdf.worker.js.map: Unexpected end of JSON input
```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: WSL 2 with Ubuntu 20.04 LTS on a windows 11 machine
 - VS Code version: 1.74.3
 - Extension version: 9.5.0
 - TeX distribution version: TeX 3.14159265 (TeX Live 2019/Debian)

### Are you using VSCodium?
Yes
### Are you using the Snap or Flatpack versions of VS Code?
No
### Are you using LaTeX Workshop with VS Code Remote?
Yes
If the answer is Yes, please write which one you are using. Write the versions of the remote extension.
- Remote WSL

### Additional context

Is this possibly a firewall issue? If it is, I'm not sure how to disable it. The logs seem like everything works fine so it's very possibly an issue on my end. But the problem only started today, and I didn't do anything with the machine before it stopped working, not any windows updates at all or anything. I'm uncertain what's the actual cause.

One weird thing that happened was, while trying to debug earlier I removed the extension and re-installed it, reloaded vscode and everything, then the preview seemed to work once but after that went back to how it is now. I cannot reproduce this part.

**Comment by James-Yu** [comment] 2023-01-26 03:35
Do you have the same issue with Remote WSL version 0.72, i.e., don't use the latest two versions?

**Comment by aradarbel10** [comment] 2023-01-26 06:42
I don't think so, that's from powershell
```
> wsl --version
WSL version: 1.1.0.0
Kernel version: 5.15.83.1
WSLg version: 1.0.48
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.25281.1000
```

**Comment by James-Yu** [comment] 2023-01-26 07:12
No, I mean the remote WSL extension.

**Comment by aradarbel10** [comment] 2023-01-26 07:23
Oh my bad. It's on v0.72.0. I just tried with v0.66.2 as well and nothing changed.

**Comment by James-Yu** [comment] 2023-01-26 08:29
I see. Can you also try out previous versions of this extension and see which one caused the bug?

**Comment by aradarbel10** [comment] 2023-01-26 18:29
I tried a bunch of previous versions, all the way to 8.27.0, still won't work on any of them.
BTW, I even tried removing and reinstalling the extension manually, same results.

Maybe it is a firewall problem after all? As I mentioned, following the "internal viewer" in chrome does not connect.
However I'm not sure what would need to be changed, seems that chrome is enabled through it already.

**Comment by James-Yu** [comment] 2023-01-27 01:49
My speculation is that recent updates to WSL (not remotes WSL extension) changed how port forwarding work on particular distro. There were no any reports on this issue for the past a few years but a bunch in the past week. As I cannot reproduce the issue on my WSL with Ubuntu, I am hesitated to provide a tentative solution only based on speculation. There was another issue stating that the problem can be resolved by forcing server to listen to * instead of 127, yet it is widely considered a severe security threat.

**Comment by syvshc** [comment] 2023-01-27 12:11
> ```
> > wsl --version
> WSL version: 1.1.0.0
> Kernel version: 5.15.83.1
> WSLg version: 1.0.48
> MSRDC version: 1.2.3770
> Direct3D version: 1.608.2-61064218
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.25281.1000
> ```

The same issue on Windows version 10.0.22623.1245, and all the other information here is the same.

**Comment by AxiomOfChoices** [comment] 2023-01-27 17:00
> My speculation is that recent updates to WSL (not remotes WSL extension) changed how port forwarding work on particular distro. There were no any reports on this issue for the past a few years but a bunch in the past week. As I cannot reproduce the issue on my WSL with Ubuntu, I am hesitated to provide a tentative solution only based on speculation. There was another issue stating that the problem can be resolved by forcing server to listen to * instead of 127, yet it is widely considered a severe security threat.

I think you are exactly right. Seems to be caused by [this issue](https://github.com/microsoft/WSL/issues/9508), for which a [fix is in testing](https://github.com/microsoft/WSL/issues/9508#issuecomment-1405903487). As a temporary fix for people suffering from this you can downgrade your WSL to 1.0.3 as described [here](https://github.com/microsoft/WSL/issues/9508#issuecomment-1404186768).

PS. @James-Yu I suspect that perhaps your WSL is not at version 1.1.0 (since its prerelease) and that is why you cannot replicate the issue.

**Comment by James-Yu** [comment] 2023-01-27 17:12
> PS. @James-Yu I suspect that perhaps your WSL is not at version 1.1.0 (since its prerelease) and that is why you cannot replicate the issue.

Very likely, as my win is not the main PC. I'll keep an eye on the referenced issues. Thanks @AxiomOfChoices for the detailed report!

**Comment by nidrissi** [comment] 2023-02-02 13:06
The WSL has been fixed: https://github.com/microsoft/WSL/issues/9508#issuecomment-1413430899 However, the bug in the extension remains: I still cannot connect to the PDF viewer from the Windows host.

**Comment by AxiomOfChoices** [comment] 2023-02-02 16:06
@nidrissi I just now updated to WSL version 1.1.2 which fixes the bug and everything works perfectly for me. What you are facing might be a different issue.

I remember when downgrading I had a problem because I tried adding 
```
[wsl2]
kernelCommandLine=ipv6.disable=1
```
to my `.wslconfig` which I then had to remove to make it work, perhaps you have a similar issue.

**Comment by syvshc** [comment] 2023-02-03 03:32
After updating to 1.1.2, the problem remains, and I don't know where the issue is. I didn't edit `.wslconfig` at all.

**Comment by ObT1337** [comment] 2023-02-04 09:45
Had the same problem with the new v9.6.1 for mac. Works fine with v9.6.0.

**Comment by James-Yu** [comment] 2023-02-07 03:48
For those influenced by the WSL hostname issue, you may try out the artifact in https://github.com/James-Yu/LaTeX-Workshop/actions/runs/4101675406 and see if the new hostname change command can help you resolved the issue. Other than that, there is not much can be done from the extension side.

**Closed** 2023-02-11 01:57 UTC
Labels: external issue

**Comment by nidrissi** [comment] 2023-02-13 07:10
@James-Yu How does one go about "trying out the artifact"?

**Comment by titaneric** [comment] 2023-02-13 12:45
Well, you can download the artifact called "latex-workshop.zip" and unzip it.
You can install vscode extension directly by VSIX file.

Unfortunately, I still stay blank after installing this artifact.
