### ISSUE TITLE
Build on save fails when using \input{somefile.tex} and editing that file

### ISSUE THREAD

**Issue by brunottonurb** [James-Yu/LaTeX-Workshop#1608] opened 2019-08-19 08:11 UTC
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue. [Required]**

You still see this issue?: Yes

**Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.**

**Describe the bug [Required]**

Build fails when using /input on v8 latex workshop

**To Reproduce**
Multi file latex project using \input{section/somefile.tex}. Opening pdf in vscode tab. ctrl + click into some area of the document opens that particular .tex file. Editing that file and saving makes the build fail.

**Expected behavior**

Expect build to succeed and pdf in vscode tab to update like in previous versions.

**Logs [Required]**
so.

<details>
<summary>LaTeX Workshop Output [Required]</summary>

</details>

<details>
<summary>Developer Tools Console [Required]</summary>

</details>

**Screenshots**

**Desktop [Required]:**
 - OS: Ubuntu 18.04
 - VS Code version: 1.37.1
 - Extension version: 8.0.2

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Additional context**

**Comment by James-Yu** [comment] 2019-08-19 08:15
Should be a duplicate of #1607 . Looking into it.

**Closed by James-Yu** 2019-08-19 08:15 UTC
