### ISSUE TITLE
Build error when working in path containing symbolic link to a mounted drive

### ISSUE THREAD

**Issue by constantin-huetterer** [James-Yu/LaTeX-Workshop#3045] opened 2022-01-08 14:43 UTC
Thank you for writing this awesome extension! It looks great and I can't wait to use it. :slightly_smiling_face: 

__Edit:__ After some investigation, I am not sure if this is a bug from the extension or a VS Code Bug / security feature. Please close if you find that this bug doesn't belong here. The workaround of just opening the project where it really is works well.

### Disable all the other extensions except for LaTeX Workshop, restart VS Code, and check that you still see this issue. [Required]

You still see this issue?: Yes

### Make sure to visit the [wiki FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) before filling an issue.

You visited the wiki?: Yes, I didn't find anything related to this problem.

### If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.

You can compile a TeX document manually?: Yes, running `latexmk ... %DOC% " manually works

## Describe the bug [Required]

When opening a workspace inside of a folder containing a symbolic link, bibtex reports an error, making the build fail and displaying an error message on each build.

### To Reproduce

Setup:
1. Create symbolic link (in my case it was a mounted drive)
2. Open Tex workspace in a sub-folder through the symbolic link
3. Try to build using latexmk recipe

My setup looks like this:
```
/home/user/docs/ --> symbolic link that points to /mnt/drive/docs
```
- When I open the workspace `/home/user/docs/project/` in VS Code, builds fail
- In contrast to opening `/mnt/drive/docs/project` in VS Code, then builds succeed
- If I run the latexmk command in the VS-Code internal console, however, it succeeds no matter which version of the workspace I had opened.

### Expected behavior

Builds succeed in sub directories of symbolic links as well.

### LaTeX Workshop Output [Required]
<details>
<summary> Workshop Log</summary>

```
[15:19:43] Initializing LaTeX Workshop.
[15:19:43] Extension root: /home/redacted/.vscode/extensions/james-yu.latex-workshop-8.23.0
[15:19:43] $PATH: redacted
[15:19:43] $SHELL: /bin/bash
[15:19:43] vscode.env.appName: Visual Studio Code
[15:19:43] vscode.env.remoteName: undefined
[15:19:43] vscode.env.uiKind: 1
[15:19:43] editor.acceptSuggestionOnEnter: "on"
[15:19:43] latex-workshop.bind.enter.key: true
[15:19:43] latex-workshop.docker.enabled: false
[15:19:43] latex-workshop.docker.image.latex: ""
[15:19:43] latex-workshop.hover.preview.mathjax.extensions: []
[15:19:43] latex-workshop.intellisense.package.enabled: true
[15:19:43] latex-workshop.intellisense.update.aggressive.enabled: false
[15:19:43] latex-workshop.intellisense.update.delay: 1000
[15:19:43] latex-workshop.latex.autoBuild.run: "onFileChange"
[15:19:43] latex-workshop.latex.outDir: "%DIR%"
[15:19:43] latex-workshop.latex.recipes: [
 {
  "name": "latexmk 🔃",
  "tools": [
   "latexmk"
  ]
 },
 {
  "name": "latexmk (latexmkrc)",
  "tools": [
   "latexmk_rconly"
  ]
 },
 {
  "name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
  "tools": [
   "pdflatex",
   "bibtex",
   "pdflatex",
   "pdflatex"
  ]
 }
]
[15:19:43] latex-workshop.latex.tools: [
 {
  "name": "latexmk",
  "command": "latexmk",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "-pdf",
   "-outdir=%OUTDIR%",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "latexmk_rconly",
  "command": "latexmk",
  "args": [
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "pdflatex",
  "command": "pdflatex",
  "args": [
   "-synctex=1",
   "-interaction=nonstopmode",
   "-file-line-error",
   "%DOC%"
  ],
  "env": {}
 },
 {
  "name": "bibtex",
  "command": "bibtex",
  "args": [
   "%DOCFILE%"
  ],
  "env": {}
 }
]
[15:19:43] latex-workshop.viewer.pdf.internal.keyboardEvent: "auto"
[15:19:43] Creating a new file watcher.
[15:19:43] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[15:19:43] Creating PDF file watcher.
[15:19:43] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{}}
[15:19:43] Creating Bib file watcher.
[15:19:43] watcherOptions: {"useFsEvents":false,"usePolling":false,"interval":300,"binaryInterval":1000,"awaitWriteFinish":{"stabilityThreshold":250}}
[15:19:43] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[15:19:43] [Server] Creating LaTeX Workshop http and websocket server.
[15:19:43] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[15:19:43] LaTeX Workshop initialized.
[15:19:43] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[15:19:43] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[15:19:43] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[15:19:43] Current workspace folders: ["file:///home/redacted"]
[15:19:43] Current workspaceRootDir: file:///home/redacted
[15:19:43] [Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":39479}
[15:19:43] Snippet data loaded.
[15:19:43] Fls file found: /home/redacted/document_name.fls
[15:19:43] Found root file from '.fls': /home/redacted/document_name.tex
[15:19:43] Root file changed: from undefined to /home/redacted/document_name.tex
[15:19:43] Start to find all dependencies.
[15:19:43] Root file languageId: latex
[15:19:43] Reset file watcher.
[15:19:43] Parsing a file and its subfiles: /home/redacted/document_name.tex
[15:19:43] Parsing a file and its subfiles: /home/redacted/include/document_header.tex
[15:19:43] Parsing a file and its subfiles: /home/redacted/include/document_settings.tex
[15:19:43] Parsing a file and its subfiles: /home/redacted/include/document_title.tex
[15:19:43] Parsing a file and its subfiles: /home/redacted/include/document_acronym.tex
[15:19:43] Parsing a file and its subfiles: /home/redacted/content/intro.tex
[15:19:43] Parsing a file and its subfiles: /home/redacted/content/basics.tex
[15:19:43] Parsing a file and its subfiles: /home/redacted/content/sota.tex
[15:19:43] Parsing a file and its subfiles: /home/redacted/content/main.tex
[15:19:43] Parsing a file and its subfiles: /home/redacted/content/experiments.tex
[15:19:43] Parsing a file and its subfiles: /home/redacted/content/summary.tex
[15:19:43] Parsing a file and its subfiles: /home/redacted/content/appendix.tex
[15:19:43] Found .bib file: /home/redacted/bibliography.bib
[15:19:43] Added to bib file watcher: /home/redacted/bibliography.bib
[15:19:43] Parsing .bib entries from /home/redacted/bibliography.bib
[15:19:43] Added to file watcher: /home/redacted/document_name.tex
[15:19:43] Added to file watcher: /home/redacted/include/document_header.tex
[15:19:43] Added to file watcher: /home/redacted/include/document_settings.tex
[15:19:43] Added to file watcher: /home/redacted/include/document_title.tex
[15:19:43] Added to file watcher: /home/redacted/include/document_acronym.tex
[15:19:43] Added to file watcher: /home/redacted/content/intro.tex
[15:19:43] Added to file watcher: /home/redacted/content/basics.tex
[15:19:43] Added to file watcher: /home/redacted/content/sota.tex
[15:19:43] Added to file watcher: /home/redacted/content/main.tex
[15:19:43] Added to file watcher: /home/redacted/content/experiments.tex
[15:19:43] Added to file watcher: /home/redacted/content/summary.tex
[15:19:43] Added to file watcher: /home/redacted/content/appendix.tex
[15:19:43] Parsed 9 bib entries from /home/redacted/bibliography.bib.
[15:19:43] Parse fls file.
[15:19:43] Fls file found: /home/redacted/document_name.fls
[15:19:43] Parse aux file: /home/redacted/document_name.aux
[15:19:43] Found .bib file: /home/redacted/bibliography.bib
[15:19:43] Checking for duplicate labels: /home/redacted/document_name.tex.
[15:19:43] Checking for duplicate labels: /home/redacted/include/document_header.tex.
[15:19:43] Checking for duplicate labels: /home/redacted/include/document_settings.tex.
[15:19:43] Checking for duplicate labels: /home/redacted/include/document_title.tex.
[15:19:43] Checking for duplicate labels: /home/redacted/include/document_acronym.tex.
[15:19:43] Checking for duplicate labels: /home/redacted/content/intro.tex.
[15:19:43] Checking for duplicate labels: /home/redacted/content/basics.tex.
[15:19:43] Added to file watcher: /home/redacted/image/logo.pdf
[15:19:43] Added to file watcher: /home/redacted/image/information_overload_de.pdf
[15:19:43] Checking for duplicate labels: /home/redacted/content/sota.tex.
[15:19:43] Checking for duplicate labels: /home/redacted/content/main.tex.
[15:19:43] Checking for duplicate labels: /home/redacted/content/experiments.tex.
[15:19:43] Checking for duplicate labels: /home/redacted/content/summary.tex.
[15:19:43] Checking for duplicate labels: /home/redacted/content/appendix.tex.
[15:19:45] Manager.fileWatcher.getWatched: {"/home/redacted":["document_name.tex"],"/home/redacted/include":["document_acronym.tex","document_header.tex","document_settings.tex","document_title.tex"],"/home/redacted/content":["appendix.tex","intro.tex","experiments.tex","basics.tex","main.tex","sota.tex","summary.tex"],"/home/redacted/image":["information_overload_de.pdf","logo.pdf"]}
[15:19:45] Manager.filesWatched: ["/home/redacted/document_name.tex","/home/redacted/include/document_header.tex","/home/redacted/include/document_settings.tex","/home/redacted/include/document_title.tex","/home/redacted/include/document_acronym.tex","/home/redacted/content/intro.tex","/home/redacted/content/basics.tex","/home/redacted/content/sota.tex","/home/redacted/content/main.tex","/home/redacted/content/experiments.tex","/home/redacted/content/summary.tex","/home/redacted/content/appendix.tex","/home/redacted/image/logo.pdf","/home/redacted/image/information_overload_de.pdf"]
[15:19:45] BibWatcher.bibWatcher.getWatched: {"/home/redacted":["bibliography.bib"]}
[15:19:45] BibWatcher.bibsWatched: ["/home/redacted/bibliography.bib"]
[15:19:45] PdfWatcher.pdfWatcher.getWatched: {}
[15:19:45] PdfWatcher.pdfsWatched: []
[15:19:58] onDidSaveTextDocument triggered: file:///home/redacted/content/intro.tex
[15:19:59] File watcher - file changed: /home/redacted/content/intro.tex
[15:19:59] Parsing a file and its subfiles: /home/redacted/content/intro.tex
[15:19:59] Checking for duplicate labels: /home/redacted/content/intro.tex.
[15:19:59] Auto build started detecting the change of a file: /home/redacted/content/intro.tex
[15:19:59] BUILD command invoked.
[15:19:59] The document of the active editor: file:///home/redacted/content/intro.tex
[15:19:59] The languageId of the document: latex
[15:19:59] Building root file: /home/redacted/document_name.tex
[15:19:59] Build root file /home/redacted/document_name.tex
[15:19:59] outDir: /home/redacted
[15:19:59] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/home/redacted,/home/redacted/document_name
[15:19:59] Recipe step env: {}
[15:19:59] cwd: /home/redacted
[15:19:59] LaTeX build process spawned. PID: 99371.
[15:19:59] Recipe returns with error: 12/null. PID: 99371. message: Rc files read:
  /etc/LatexMk
Latexmk: This is Latexmk, John Collins, 29 September 2020, version: 4.70b.
Rule 'bibtex /home/redacted/document_name': The following rules & subrules became out-of-date:
      'bibtex /home/redacted/document_name'
------------
Run number 1 of rule 'bibtex /home/redacted/document_name'
------------
------------
Running 'bibtex  "/home/redacted/document_name.aux"'
------------

bibtex: Not writing to /home/redacted/document_name.blg (openout_any = p).
Collected error summary (may duplicate other messages):
  bibtex /home/redacted/document_name: Could not open bibtex log file for '/home/redacted/document_name'
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
.
[15:19:59] The environment variable $PATH: redacted
[15:19:59] The environment variable $Path: undefined
[15:19:59] The environment variable $SHELL: /bin/bash
[15:19:59] Cleaning auxiliary files and retrying build after toolchain error.
[15:19:59] Clean glob matched files: {"globs":["*.aux","*.bbl","*.blg","*.idx","*.ind","*.lof","*.lot","*.out","*.toc","*.acn","*.acr","*.alg","*.glg","*.glo","*.gls","*.fls","*.log","*.fdb_latexmk","*.snm","*.synctex(busy)","*.synctex.gz(busy)","*.nav","*.vrb"],"outdir":"/home/redacted"}
[15:19:59] Cleaning file: /home/redacted/document_name.aux
[15:19:59] Cleaning file: /home/redacted/document_name.lof
[15:19:59] Cleaning file: /home/redacted/document_name.lot
[15:19:59] Cleaning file: /home/redacted/document_name.out
[15:19:59] Cleaning file: /home/redacted/document_name.toc
[15:19:59] Cleaning file: /home/redacted/document_name.fls
[15:19:59] Cleaning file: /home/redacted/document_name.log
[15:19:59] Cleaning file: /home/redacted/document_name.fdb_latexmk
[15:19:59] Recipe step 1: latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=/home/redacted,/home/redacted/document_name
[15:19:59] Recipe step env: {}
[15:19:59] cwd: /home/redacted
[15:19:59] LaTeX build process spawned. PID: 99375.
[15:20:01] LaTeX log parsed with 17 messages.
[15:20:01] Recipe returns with error: 12/null. PID: 99375. message: Rc files read:
  /etc/LatexMk
Latexmk: This is Latexmk, John Collins, 29 September 2020, version: 4.70b.
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -file-line-error -recorder -output-directory="/home/redacted"  "/home/redacted/document_name.tex"'
------------
Latexmk: Non-existent bbl file '/home/redacted/document_name.bbl in line'
 No file document_name.bbl.
Latexmk: References changed.
Latexmk: References changed.
Latexmk: Log file says output to '/home/redacted/document_name.pdf'
Latexmk: List of undefined refs and citations:
  Citation `ChewningJr.1990' on page 2 undefined on input line 14
  Citation `Eppler.2004' on page 2 undefined on input line 14
  Citation `Eppler.2004' on page 2 undefined on input line 16
  Citation `Eppler.2004' on page 3 undefined on input line 23
  Citation `Picot.1993' on page 2 undefined on input line 12
  Citation `Picot.1993' on page 4 undefined on input line 54
  Citation `Schroder.1967' on page 3 undefined on input line 23
  Citation `Toffler.1970' on page 2 undefined on input line 16
  Reference `eq:Gy' on page 9 undefined on input line 16
  Reference `fig:information_overload' on page 2 undefined on input line 16
  Reference `footnote:note1' on page 12 undefined on input line 34
Latexmk: Found bibliography file(s) [bibliography.bib]
Rule 'bibtex /home/redacted/document_name': File changes, etc:
   Changed files, or newly in use since previous run(s):
      '/home/redacted/document_name.aux'
------------
Run number 1 of rule 'bibtex /home/redacted/document_name'
------------
------------
Running 'bibtex  "/home/redacted/document_name.aux"'
------------

bibtex: Not writing to /home/redacted/document_name.blg (openout_any = p).
Latexmk: Summary of warnings from last run of *latex:
  Latex failed to resolve 3 reference(s)
  Latex failed to resolve 11 citation(s)
Collected error summary (may duplicate other messages):
  bibtex /home/redacted/document_name: Could not open bibtex log file for '/home/redacted/document_name'
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
.
[15:20:01] The environment variable $PATH: /home/redacted/.meteor:/home/redacted/miniconda3/condabin:/home/redacted/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/lib/jvm/zulu11/bin:/home/redacted/Development/opt/apache-maven-3.6.3/bin:/usr/local/android-sdk/platform-tools:/opt/android-studio/bin:/opt/android-studio/plugins/gradle/lib:/home/redacted/Android/Sdk/tools:/home/redacted/Android/Sdk/platform-tools:/usr/share/code:/usr/lib/jvm/zulu11/bin:/usr/local/texlive/2020/bin/x86_64-linux
[15:20:01] The environment variable $Path: undefined
[15:20:01] The environment variable $SHELL: /bin/bash

```

</details>

### Developer Tools Console [Required]

```
Extension Host] (node:99225) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `code --trace-deprecation ...` to show where the warning was created)
I @ console.ts:137
log.ts:307  WARN [File Watcher (parcel)] correcting a path to watch that seems to be a symbolic link (original: /home/correct/path, real: /correct/path)
notificationsAlerts.ts:42 Recipe terminated with error.
onDidChangeNotification @ notificationsAlerts.ts:42

```

## Desktop [Required]

Please write exact version numbers. Please don't write `latest` instead of exact numbers.

 - OS: Pop!_OS 21.10
 - VS Code version: 1.63.2 899d46d82c4c95423fb7e10e68eba52050e30ba3 x64
 - Extension version: 8.23.0
 - TeX distribution version: TeX Live 2021

### Are you using VSCodium?

No

### Are you using the Snap or Flatpack versions of VS Code?

No

### Are you using LaTeX Workshop with VS Code Remote?

No

If the answer is Yes, please write which one you are using. Write the versions of the remote extension.

- Remote Containers/Remote SSH/Remote WSL
- Remote Extension Version: [e.g. 0.48.0]

**Comment by constantin-huetterer** [comment] 2022-01-08 15:34
I tried to rename the recipes and actions to something else, just to make sure it doesn't use default recipes / actions or something from another settings file. Same result as above. I tried with
<details>
<summary>This settings file</summary>

```
{
	"latex-workshop.latex.recipes": [
		{
			"name": "latexmk _ special name",
			"tools": [
				"latexmk_special"
			]
		},
		{
			"name": "latexmk (latexmkrc)",
			"tools": [
				"latexmk_rconly"
			]
		},
		{
			"name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
			"tools": [
				"pdflatex",
				"bibtex",
				"pdflatex",
				"pdflatex"
			]
		}
	],
	"latex-workshop.latex.tools": [
		{
			"name": "latexmk_special",
			"command": "latexmk",
			"args": [
				"-synctex=1",
				"-interaction=nonstopmode",
				"-file-line-error",
				"-pdf",
				"-outdir=%OUTDIR%",
				"%DOC%"
			],
			"env": {}
		},
		{
			"name": "latexmk_rconly",
			"command": "latexmk",
			"args": [
				"%DOC%"
			],
			"env": {}
		},
		{
			"name": "pdflatex",
			"command": "latexmk",
			"args": [
				"-synctex=1",
				"-interaction=nonstopmode",
				"-file-line-error",
				"-pdf",
				"-outdir=%OUTDIR%",
				"%DOC%"
			],
			"env": {}
		},
		{
			"name": "bibtex",
			"command": "bibtex",
			"args": [
				"%DOCFILE%"
			],
			"env": {}
		}
	],
}
```

</details>

I also tried adding a made up argument to the tool, to see if it would appear in the output and it did. 
<details>
<summary>This settings file</summary>

```
{
	"latex-workshop.latex.recipes": [
		{
			"name": "latexmk _ special name",
			"tools": [
				"latexmk_special"
			]
		},
		{
			"name": "latexmk (latexmkrc)",
			"tools": [
				"latexmk_rconly"
			]
		},
		{
			"name": "pdflatex ➞ bibtex ➞ pdflatex × 2",
			"tools": [
				"pdflatex",
				"bibtex",
				"pdflatex",
				"pdflatex"
			]
		}
	],
	"latex-workshop.latex.tools": [
		{
			"name": "latexmk_special",
			"command": "latexmk",
			"args": [
				"--bogus-argument",
				"-synctex=1",
				"-interaction=nonstopmode",
				"-file-line-error",
				"-pdf",
				"-outdir=%OUTDIR%",
				"%DOC%"
			],
			"env": {}
		},
		{
			"name": "latexmk_rconly",
			"command": "latexmk",
			"args": [
				"%DOC%"
			],
			"env": {}
		},
		{
			"name": "pdflatex",
			"command": "latexmk",
			"args": [
				"-synctex=1",
				"-interaction=nonstopmode",
				"-file-line-error",
				"-pdf",
				"-outdir=%OUTDIR%",
				"%DOC%"
			],
			"env": {}
		},
		{
			"name": "bibtex",
			"command": "bibtex",
			"args": [
				"%DOCFILE%"
			],
			"env": {}
		}
	],
}
```

</details>

resulted in the output `Latexmk: -bogus-argument bad option`.

**Comment by jlelong** [comment] 2022-01-08 18:15
Duplicate of #2303

This is related to `latexmk` not the extension. You are using an old version of `latexmk`. Try to update to `Latexmk, John Collins, 20 November 2021. Version 4.76`?

**Closed by jlelong** 2022-01-08 18:15 UTC
