### ISSUE TITLE
Pdf viewer (CTRL-ALT-V)

### ISSUE THREAD

**Issue by volcompt** [James-Yu/LaTeX-Workshop#1988] opened 2020-03-16 09:46 UTC
Hi, I can open the pdf viwer with Ctrl+alt-v. Is there anyway of closing it with a keyboard shortcut as well?

**Comment by tamuratak** [comment] 2020-03-16 11:09
Duplicate of #1406. It will be available in the next release.

**Closed by tamuratak** 2020-03-16 11:09 UTC
Labels: feature-request
