### ISSUE TITLE
How to use .latexmkrc file in the directory

### ISSUE THREAD

**Issue by gutouyu** [James-Yu/LaTeX-Workshop#1099] opened 2019-01-05 07:23 UTC
# Description
I try to use latexmk with a latexmkrc file. And the engine I want to use is xelatex, But I think latexworkshop just ignore my latexmkrc file , and still use pdflatex.

# Reproduce
You can just use the code from repo  https://github.com/x-magus/ThesisUESTC
and use the recipe `latexmk`

# Question
Does Latexworkshop auto detec latexmkrc file and use it?  What's the build command do in time sequence? So confused about the recipes\tools\latexmkrc .etc.

**Comment by jlelong** [comment] 2019-01-05 08:01
Duplicate of #830.

**Closed by jlelong** 2019-01-05 08:01 UTC
