### ISSUE TITLE
Auto-close "recipe terminated with error" after successful build

### ISSUE THREAD

**Issue by hemker** [James-Yu/LaTeX-Workshop#2587] opened 2021-03-18 10:29 UTC
**Is your feature request related to a problem? Please describe.**
When I have a build error (due to syntax problem), and I run the build recipe, a correct pop-up is shown in the lower right corner stating "Recipe terminated with error." This is of course a good hint.

**Describe the solution you'd like**
When I fix the syntax error and rebuild the project again, the build succeeds (indicated by the checkmark in the lower left area), but the previous "Recipe terminated with error." pop-up is still shown. The pop-up should close itself when the build runs successfully, as it confuses the user.

**Describe alternatives you've considered**
One has to close the pop-up by hand every time a build has failed.

**Additional context**
None

**Comment by jlelong** [comment] 2021-03-18 10:35
Duplicate of #2517 and #898

**Closed by jlelong** 2021-03-18 10:35 UTC
Labels: feature-request

**Comment by tamuratak** [comment] 2021-03-18 11:08
Related to microsoft/vscode/issues/46551
