### ISSUE TITLE
SyncTex menu item not showing up in new VSCode version

### ISSUE THREAD

**Issue by mattecapu** [James-Yu/LaTeX-Workshop#804] opened 2018-09-16 17:27 UTC
### Description

After updating VSCode to version 1.27.2, I no longer see the usual `Sync preview to cursor` in the right-click menu of a editor for .tex files 	

### Log messages

nothing suspicious.

### How to reproduce

1. Update VSCode to 1.27.2
2. Open a .tex file
3. Right click on the editor

### Expected behavior

A menu with LaTeX specific items

### Actual behavior

Usual, LaTeX-unaware menu

**Comment by Gliptal** [comment] 2018-09-16 21:18
Same here.

**Comment by jlelong** [comment] 2018-09-17 04:57
Duplicate of #802.

**Closed by jlelong** 2018-09-17 04:57 UTC
