### ISSUE TITLE
Problem structuring the .tex file

### ISSUE THREAD

**Issue by WeiyeWang** [James-Yu/LaTeX-Workshop#3813] opened 2023-04-01 03:02 UTC
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [ ] The issue has not been reported in this repository.
- [ ] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [ ] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [*] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Windows 10
- Visual Studio Code Version: 1.77.0
- LaTeX Workshop Version: v9.8.2
- TeX Distribution Version: TeXLive 2022

## The Issue*
> _Please briefly describe the issue you come across._
-  it seems to me that there are some problems when it start to stucturing the .tex file
-  it even does not being to build(ctrl-alt-b) anymore 

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. just open the file in vscode, the problem is reproduced

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- 
- 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[10:53:16][Config] latex-workshop.latex.recipes: [{"name":"XeLaTeX","tools":["xelatex"]},{"name":"PDFLaTeX","tools":["pdflatex"]},{"name":"BibTeX","tools":["bibtex"]},{"name":"LaTeXmk","tools":["latexmk"]},{"name":"xelatex -> bibtex -> xelatex*2","tools":["xelatex","bibtex","xelatex","xelatex"]},{"name":"pdflatex -> bibtex -> pdflatex*2","tools":["pdflatex","bibtex","pdflatex","pdflatex"]}] .
[10:53:16][Config] latex-workshop.latex.recipe.default: "lastUsed" .
[10:53:16][Config] latex-workshop.latex.tools: [{"name":"xelatex","command":"xelatex","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","%DOCFILE%"]},{"name":"pdflatex","command":"pdflatex","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","%DOCFILE%"]},{"name":"latexmk","command":"latexmk","args":["-synctex=1","-interaction=nonstopmode","-file-line-error","-pdf","-outdir=%OUTDIR%","%DOCFILE%"]},{"name":"bibtex","command":"bibtex","args":["%DOCFILE%"]}] .
[10:53:16][Config] latex-workshop.latex.autoBuild.run: "never" .
[10:53:16][Config] latex-workshop.latex.autoClean.run: "onFailed" .
[10:53:16][Config] latex-workshop.latex.clean.fileTypes: ["*.aux","*.bbl","*.blg","*.idx","*.ind","*.lof","*.lot","*.out","*.toc","*.acn","*.acr","*.alg","*.glg","*.glo","*.gls","*.ist","*.fls","*.log","*.fdb_latexmk"] .
[10:53:16][Config] latex-workshop.view.pdf.internal.synctex.keybinding: "double-click" .
[10:53:16][Config] latex-workshop.view.pdf.external.viewer.command: "C:\\Users\\weiye\\AppData\\Local\\SumatraPDF\\SumatraPDF.exe" .
[10:53:16][Config] latex-workshop.view.pdf.external.synctex.command: "C:\\Users\\weiye\\AppData\\Local\\SumatraPDF\\SumatraPDF.exe" .
[10:53:16][Config] latex-workshop.view.pdf.external.synctex.args: ["-forward-search","%TEX%","%LINE%","-reuse-instance","-inverse-search","code \"C:\\Users\\Wang Weiye\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\cli.js\" -r -g \"%f:%l\"","%PDF%"] .
[10:53:16][Config] latex-workshop.intellisense.fastparse.enabled: false .
[10:53:16][Config] latex-workshop.message.warning.show: false .
[10:53:16][Config] latex-workshop.message.error.show: false .
[10:53:16][Config] latex-workshop.showContextMenu: true .
[10:53:16][Config] latex-workshop.bind.enter.key: false .
[10:53:16][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[10:53:17][Server] Creating LaTeX Workshop http and websocket server.
[10:53:17][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":8635} .
[10:53:17][Extension] Initializing LaTeX Workshop.
[10:53:17][Extension] Extension root: c:\Users\weiye\.vscode\extensions\james-yu.latex-workshop-9.8.2
[10:53:17][Extension] $PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\libnvvp;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Wolfram Research\WolframScript\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.4.0\;C:\Users\weiye\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;C:\texlive\2021\bin\win32;C:\Users\weiye\AppData\Local\Programs\Microsoft VS Code\bin
[10:53:17][Extension] $SHELL: undefined
[10:53:17][Extension] $LANG: undefined
[10:53:17][Extension] $LC_ALL: undefined
[10:53:17][Extension] process.platform: win32
[10:53:17][Extension] process.arch: x64
[10:53:17][Extension] vscode.env.appName: Visual Studio Code
[10:53:17][Extension] vscode.env.remoteName: undefined
[10:53:17][Extension] vscode.env.uiKind: 1
[10:53:17][Extension] LaTeX Workshop initialized.
[10:53:17][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[10:53:17][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[10:53:17][Manager] Current workspace folders: undefined
[10:53:17][Manager] Found root file from active editor: c:\Users\weiye\Documents\wwy sync\临时工作区\file.tex
[10:53:17][Manager] Root file changed: from undefined to c:\Users\weiye\Documents\wwy sync\临时工作区\file.tex
[10:53:17][Manager] Start to find all dependencies.
[10:53:17][Manager] Root file languageId: latex
[10:53:17][Cacher][Watcher] Reset.
[10:53:17][Cacher] Adding c:\Users\weiye\Documents\wwy sync\临时工作区\file.tex .
[10:53:17][Cacher][Watcher] Watched c:\Users\weiye\Documents\wwy sync\临时工作区\file.tex with a new watcher on c:\Users\weiye\Documents\wwy sync\临时工作区 .
[10:53:17][Cacher] Caching c:\Users\weiye\Documents\wwy sync\临时工作区\file.tex .
[10:53:17][Cacher] Updated inputs of c:\Users\weiye\Documents\wwy sync\临时工作区\file.tex .
[10:53:17][Server] valdOrigin is http://127.0.0.1:8635
```
Normally, it should have a "[stucture]" line like this (opening another file after restarting vscode)
```
[10:57:34][Cacher] Cached c:\Users\weiye\Documents\wwy sync\临时工作区\自拟题目9.tex .
[10:57:34][Cacher][Path] Non-existent .fls for c:\Users\weiye\Documents\wwy sync\临时工作区\自拟题目9.tex .
[10:57:34][Structure] Structure force updated with 1 root sections for c:\Users\weiye\Documents\wwy sync\临时工作区\自拟题目9.tex .
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
workbench.desktop.main.js:620  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:620  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.remote-repositories' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:620  WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:620  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:620   ERR Extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:620   ERR SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at C.$getPassword (workbench.desktop.main.js:1586:49218)
workbench.desktop.main.js:620  INFO [perf] Render performance baseline is 27ms
workbench.desktop.main.js:1904 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///c%3A/Users/weiye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/weiye/.vscode/extensions/james-yu.latex-workshop-9.8.2/syntax/TeX.tmLanguage.json
register @ workbench.desktop.main.js:1904
workbench.desktop.main.js:1904 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///c%3A/Users/weiye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///c%3A/Users/weiye/.vscode/extensions/james-yu.latex-workshop-9.8.2/syntax/LaTeX.tmLanguage.json
register @ workbench.desktop.main.js:1904
workbench.desktop.main.js:1904 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///c%3A/Users/weiye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///c%3A/Users/weiye/.vscode/extensions/james-yu.latex-workshop-9.8.2/syntax/Bibtex.tmLanguage.json
register @ workbench.desktop.main.js:1904
workbench.desktop.main.js:1904 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///c%3A/Users/weiye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///c%3A/Users/weiye/.vscode/extensions/james-yu.latex-workshop-9.8.2/syntax/markdown-latex-combined.tmLanguage.json
register @ workbench.desktop.main.js:1904
workbench.desktop.main.js:1904 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///c%3A/Users/weiye/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///c%3A/Users/weiye/.vscode/extensions/james-yu.latex-workshop-9.8.2/syntax/cpp-grammar-bailout.tmLanguage.json
register @ workbench.desktop.main.js:1904
workbench.desktop.main.js:1690 Extension Host
workbench.desktop.main.js:1690 Debugger attached.
workbench.desktop.main.js:620  INFO UNRESPONSIVE extension host: starting to profile NOW
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
```

## Anything Else?
> _Add any other context about the problem below._
- 
[file.zip](https://github.com/James-Yu/LaTeX-Workshop/files/11128309/file.zip)

**Comment by James-Yu** [comment] 2023-04-02 11:54
I tried to debug on your 7000+ line code but without any luck. I'm afraid you may need to provide a minimal working example showing the problem.

Also before that, can you help confirm the bug with `intellisense.fastparse.enabled` set to `false`?

**Comment by WeiyeWang** [comment] 2023-04-02 14:19
> 

yes i checked that i have let ```intellisense.fastparse.enabled``` set to ```false```.

btw, it seems to me that the problem is not that it won't working out anything. actually it is just toooooo slow. on my laptop (amd r6800, 16g memory), i reduced the number of sections from about 70 to 20, the structuring procedure cost the laptop for about 2 minutes.



i am trying to make a minimal working example.

**Comment by WeiyeWang** [comment] 2023-04-02 15:09
> I tried to debug on your 7000+ line code but without any luck. I'm afraid you may need to provide a minimal working example showing the problem.
> 
> Also before that, can you help confirm the bug with `intellisense.fastparse.enabled` set to `false`?

i think i finally made a weird minimal working(?) example. Though the problem is not the same as metioned in the original issue(perhaps they are relevant?)

when structuring ```problemfile.tex```, the output log show that there is an error as below:
```
[23:03:11][Cacher] Updated elements of c:\Users\weiye\Documents\wwy sync\临时工作区\problemfile.tex .
[23:03:11][Cacher] Updated bibs of c:\Users\weiye\Documents\wwy sync\临时工作区\problemfile.tex .
[23:03:11][Cacher] Cached c:\Users\weiye\Documents\wwy sync\临时工作区\problemfile.tex .
[23:03:11][Structure][LaTeX] Error loading AST during structuring: c:\Users\weiye\Documents\wwy sync\临时工作区\problemfile.tex .
[23:03:11][Structure] Structure force updated with 0 root sections for c:\Users\weiye\Documents\wwy sync\临时工作区\problemfile.tex .
[23:03:11][Structure] Structure updated with 0 root sections for c:\Users\weiye\Documents\wwy sync\临时工作区\problemfile.tex .
```

as for ```common[123].tex```, there is no error at all. the difference between these .tex files are just some ")""{""}" or "\times". 

is it by regex failures?

hope that solving this problem will also close the issue

[files.zip](https://github.com/James-Yu/LaTeX-Workshop/files/11132569/files.zip)

**Comment by jlelong** [comment] 2023-04-03 05:15
The issue is related to https://github.com/tamuratak/latex-utensils, which fails to parse

```{$\times [2,3)$} $[1,2]$```

It seems that the parser wrongly considers `[2,3)$} $[1,2]` as an optional arg of `\times`. This is quite tricky and I am not sure there is a simple way to fix this. is it worth opening an issue at https://github.com/tamuratak/latex-utensils? I am not sure the repo is still maintained

**Comment by James-Yu** [comment] 2023-04-03 05:30
> The issue is related to https://github.com/tamuratak/latex-utensils, which fails to parse
> 
> `{$\times [2,3)$} $[1,2]$`

Exactly. Indeed, LaTeX handles `[` with a very tricky scheme. Instead of setting it to catcode 1 like `{`, `[` is just a non-alphabet code. It is making static analysis quite tricky.

I do think #3817 is a temp fix for this issue. With the PR, the quoted line is stripped into `\times [2,3]`, which can pass `utensils`' analysis. I'm quite pessimistic on the maintenance of utensils though.

**Comment by jlelong** [comment] 2023-04-03 08:25
Making PR to https://github.com/tamuratak/latex-utensils may not be very useful. I opened a PR there once and it did not end well. I am afraid we will have to maintain our own fork and publish it to npm somehow.  Yet, I doubt we can really fix the current parsing issue easily. I will try to investigate this.

**Comment by WeiyeWang** [comment] 2023-04-03 08:43
is it possible to change this structuring feature to an optional one? like set an option to turn this feature on or off?

**Closed** 2023-04-03 09:56 UTC

**Comment by James-Yu** [comment] 2023-04-03 10:01
Finally got it!

In fact, this is not because of a potential slow AST parsing (indeed not quite slow), but instead a problematic regex parsing when no AST is produced. Currently, LW fallbacks to regex-based content parsing if utensils cannot provide a valid AST. When parsing packages used, the regex `/\\usepackage(\[[^[\]{}]*\])?{(.*)}/gs` was used. Note that instead of `(.*?)`, we used a non-lazy group here. This caused a disaster as the parsed "package name" included almost everything in the document. Combined with https://github.com/James-Yu/LaTeX-Workshop/blob/a62a8d8096a4271623740a3da1e090e79b7ae66e/src/providers/completer/package.ts#L126 , thousands of non-existing invalid package names need to be tested on the disk. Extremely slow post-AST actions made the extension irresponsive to any user inputs.

a62a8d8 does not make #3817 invalid: the PR tries to make `utensils` work, a62a8d8 tries to recover when `utensils` decided not.

Congratulate me!

**Comment by jlelong** [comment] 2023-04-03 10:13
That's a hell of a catch @James-Yu !

**Comment by WeiyeWang** [comment] 2023-04-03 10:47
Thank you sooooooooooo much!!!
